### ISSUE TITLE
Document the UI action Prepare Rotation of all Credentials 

### ISSUE THREAD

**Issue by pre** [gardener/gardener#10484]
**How to categorize this issue?**
/area documentation

The [documentation of credential rotation]( https://github.com/gardener/gardener/blob/master/docs/usage/shoot-operations/shoot_credentials_rotation.md) could mention "Prepare Rotation of all Credentials". I was trying to find out what does this UI action actually do but there are no good keyword matches in the documentation.

The user interface has an action "Prepare Rotation of all Credentials", but there are no matches in the documentation for that sentence of for "prepare rotation". 

<img width="1690" alt="image" src="https://github.com/user-attachments/assets/35faa06a-3780-45c4-91ca-76677c7fe427">

**Comment by plkokanov** [comment]
Hello @pre, the `Prepare` phase for the rotation of credentials is already mentioned, however, it is in the subsection describing the rotation for the various credential types, e.g. for CAs: https://github.com/gardener/gardener/blob/05839dfc4c6b53d2bbaa21a014e6d1b5ac6a54ea/docs/usage/shoot_credentials_rotation.md?plain=1#L105-L111

Indeed it might be somewhat misleading when looked from the UI. @n-boshnakov what about editing this [Credential Rotation](https://gardener.cloud/docs/getting-started/features/credential-rotation/) page so that it specifies `Preparing` and `Completing` phases instead of just saying `Phase 1` and `Phase 2`?

**Comment by pre** [comment]
Yes, the search keywords are important. 

When coming from the ui one doesn’t read all the documentation - only the thing which is being searched for (UI action name) is in the focus.

**Comment by n-boshnakov** [comment]
> Hello @pre, the `Prepare` phase for the rotation of credentials is already mentioned, however, it is in the subsection describing the rotation for the various credential types, e.g. for CAs:
> 
> https://github.com/gardener/gardener/blob/05839dfc4c6b53d2bbaa21a014e6d1b5ac6a54ea/docs/usage/shoot_credentials_rotation.md?plain=1#L105-L111
> 
> Indeed it might be somewhat misleading when looked from the UI. @n-boshnakov what about editing this [Credential Rotation](https://gardener.cloud/docs/getting-started/features/credential-rotation/) page so that it specifies `Preparing` and `Completing` phases instead of just saying `Phase 1` and `Phase 2`?

That is a good idea. I will update the documentation and tag you in the PR.

**Comment by n-boshnakov** [comment]
The PR has been opened:
https://github.com/gardener/documentation/pull/533

**Comment by marc1404** [comment]
Additional PRs to address the issue:
- [ ] https://github.com/gardener/gardener/pull/10998
- [ ] https://github.com/gardener/documentation/pull/558
