### ISSUE TITLE
Enhance lastError with timestamp

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#1055]
**What would you like to be added**:
The lastError field currently has a `description` and `codes` fields https://github.com/gardener/gardener/blob/8969ff71e9549a5b2fb4255f408afaad097ab488/pkg/apis/core/types_common.go#L34-L40

A timestamp field similar to the one in `lastOperation` https://github.com/gardener/gardener/blob/8969ff71e9549a5b2fb4255f408afaad097ab488/pkg/apis/core/types_common.go#L76 would be useful for ops purposes.

**Why is this needed**:
When a shoot cluster hit an error during the reconciliation the `lastError` is set in its status. This field is presented till the next successful reconciliation, but a garden cluster operator cannot determine when was the last time the error was observed.

**Comment by rfranzke** [comment]
+1, are you interested in taking this @vpnachev?

**Comment by vpnachev** [comment]
Yes. I could take it.
But firstly before to start to work on it, are you ok with such a change in the API?

**Comment by vpnachev** [comment]
Yes, I will take it.

**Comment by ialidzhikov** [comment]
This will allow also in the [gardener/dashboard](https://github.com/gardener/dashboard) to have 2 different times - one for the time elapsed since the lastError and one for the time elapsed since the lastOperation.
Currently it's a little bit misleading because the dashboard shows the lastOperation time under the Error and for errors that happened 10m ago and now fixed, it could show `a few seconds ago` - and the users still think that the issue persist.

/cc @holgerkoser , @petersutter
