### ISSUE TITLE
Node Provisioning optimization

### ISSUE THREAD

**Issue by minopark7** [gardener/gardener#10637]
**How to categorize this issue?**
/area TODO
/kind enhancement

**What would you like to be added**:
From my analysis, I have found that if there are no nodes to schedule pods on, it takes a long time to provision nodes and schedule pods. Could you please review if there is any way to optimize node creation or bootstrapping time?

**Why is this needed**:
Performance Improvement

**Comment by vlerenc** [comment]
Please reopen and provide your "analysis" in depth, where you believe Gardener can optimise the process of provisioning new nodes. Until then, I will close this ticket, because you provide zero information, but only state that it takes "a long time", which is unspecific. Considering that we receive no complaints otherwise and everybody knows that provisioning nodes with cloud providers (you not even state which one) takes multiple minutes, you may perceive a very special issue or no issue at all.
