### ISSUE TITLE
Specify the control-plane zone for single-zone shoots

### ISSUE THREAD

**Issue by lotharbach** [gardener/gardener#10702]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
The ability to specify the control-plane zone in the shoot spec. We could also think about making that mutable and having some sort of "zone migration" where the etcd volume is re-created from backup in a new volume in a different zone. Maybe even magically move it to wherever the (majority of) workers are during maintenance.

**Why is this needed**:
In a region with multiple zones we run only multi-zonal seeds but still there are many non-HA shoots. Those shoots are not only cheaper but a single az is also simpler to deploy to "correctly" for our users, with deployments that are often not exactly HA-ready.

Shoot owners can specify in which zone(s) their worker nodes are located, but have no control, and also no feedback I think, on where their control-plane ends up. So statistically most shoots end up with their workers and control-plane being in different zones. As a shoot user that chooses to deploy to in a single zone for cost and simplicity, I would not expect to be affected by failures in other zones.

Any opinions? How do you handle that so far in your landscapes?

**Comment by timuthy** [comment]
> The ability to specify the control-plane zone in the shoot spec.

While I understand the motivation of this functionality, there are some challenges and doubts:

1. This feature directly ties the provider of the shoot to the seed's provider, which is not true today. Users don't know which zones are available in the seed. The seed's worker setup is mostly independent.
2. For some providers, we'd need some awkward zone mapping (see comment below).
3. For seeds with multiple zones, this configuration has the potential to exhaust the worker capacity unevenly. Operators usually create their seeds with worker(s) in multiple zones [a, b, c] and pick the autoscaling numbers accordingly [min: 3, max: 3*x] because Gardener divides those numbers internally by the number of zones, also see https://github.com/gardener/gardener/issues/8142.

> So statistically most shoots end up with their workers and control-plane being in different zones. As a shoot user that chooses to deploy to in a single zone for cost and simplicity, I would not expect to be affected by failures in other zones.

Please consider that some providers, e.g. AWS, have a zone mapping per account ([ref](https://docs.aws.amazon.com/ram/latest/userguide/working-with-az-ids.html)). So even if Gardener uses the same zone as their single zone shoot worker group, there is not guarantee they will be in the same physical zone. It would need some additional mapping to achieve this.

**Comment by lotharbach** [comment]
The obviously much better "solution" is to recommend HA controlplanes for customers that actually care, so we are going to shelve this.

**Comment by timuthy** [comment]
Thanks @lotharbach for the update.

I was about to write that after an internal discussion this will not be tackled any time soon by the core maintainers. We are open for contributions but the feature needs to be elaborated, preferably in the form of a GEP, first.
