### ISSUE TITLE
Cannot remove shoot, if the credentials are wrong

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener#1205]
**What happened**:

I created the shoot cluster with the wrong credentials and I want to delete it. Unfortunately I can't.

**What you expected to happen**:

I can delete the shoot cluster with the wrong credentials.

**How to reproduce it (as minimally and precisely as possible)**:

Create shoot cluster with the wrong credentials and try to delete it without fixing the credentials, you'll see in the logs:

```
time="2019-07-11T16:12:31Z" level=error msg="Infrastructure did not get ready yet, lastError is: Error reconciling infrastructure: Terraform execution job 'soil-dev.infra.tf-job' could not be completed. The following issues have been found in the logs:\n\n-> Pod 'soil-dev.infra.tf-pod-94aae' reported:\n* provider.openstack: Authentication failed\n\x1b[0m\n\x1b[0m\x1b[0m\x1b[0m" operation=reconcile shoot=garden/soil-dev
```

**Anything else we need to know?**:

https://github.com/gardener/garden-setup/pull/58

**Comment by rfranzke** [comment]
Does this still happen? If the cluster was initially created with incorrect credentials then the respective extension controller cannot create any infra resources, hence, the TF state configmap should be empty. According to my understanding this should allow the extension controller to finalize the `Infrastructure` object. If the cluster was initially created with correct credentials and resources got created then it's actually desired behaviour to let the cluster deletion fail if not all resources have been cleaned up yet.

Please reopen if you think the problem is not yet solved.
