### ISSUE TITLE
Vendor kubernetes-1.16.0

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1206]
TODOs:
- Vendor `kubernetes-1.15.0` dependencies
- Get rid of https://github.com/gardener/gardener/pull/1185/files#diff-bfba4cfc0724a744471759c72668a271R40

**Comment by rfranzke** [comment]
Let's not do this for now so that we first can get rid of the `gardener-extensions-fixes` branch. In order to do this we have to solve https://github.com/gardener/gardener-extensions/issues/163 so that we can update the Kubernetes version in gardener/gardener-extensions to `kubernetes-1.14` (basically, the same version that gardener/gardener's `master` branch is currently referencing). After that we can hopefully can get rid of the mentioned branch, and then update *both* to `kubernetes-1.15.0`. In the future, we should try to make gardener/gardener-extensions independent of the Kubernetes version referenced by gardener/gardener.

**Comment by ialidzhikov** [comment]
@adracus , @rfranzke should we wait for kubernetes-sigs/controller-runtime#495 or it is not a hard dependency for this issue?

**Comment by rfranzke** [comment]
Most probably we have to wait, otherwise we end-up with the same problems we have seen in the past, I assume.

**Comment by ialidzhikov** [comment]
My plan is first to update to `sigs.k8s.io/controller-runtime@v0.2.2`, then to `sigs.k8s.io/controller-runtime@v0.3.0` and `kubernetes-1.15`.

**Comment by rfranzke** [comment]
Sounds good, thanks

**Comment by ialidzhikov** [comment]
I will rename the issue to be kubernetes-1.16.

**Comment by rfranzke** [comment]
Fixed with #1737
