### ISSUE TITLE
Adopt k/dashboard v2.0.0

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1213]
k/dashboard will soon release v2.0.0 with many improvements/changes:
- Changed image registry - `k8s.gcr.io` -> `kubernetesui/dashboard`.
- Frontend has been completely rewritten to use Angular 8.
- ...

Ref to the beta chagelog - https://github.com/kubernetes/dashboard/releases/tag/v2.0.0-beta1 .

**Comment by zanetworker** [comment]
@ialidzhikov I think that is already being taken care of by @petersutter.

**Comment by ialidzhikov** [comment]
It is about kubernetes/dashboard, not gardener/dashboard.
If it is taken from @petersutter - cool. I just filed the issue and had no intension for now to take it. Btw v2.0.0 is not already released. I suggest to contribute to the addon in k/kubernetes or the official chart in helm/charts first and then to adopt on our side.

**Comment by zanetworker** [comment]
okay, seems like @petersutter was just testing it for https://github.com/kubernetes/dashboard/issues/3680, the issue is still open.

**Comment by rfranzke** [comment]
Do we have to deploy different Kubernetes Dashboard versions for shoots < 1.14? From the release notes I understand that some features might not work for clusters < 1.14.

**Comment by vasu1124** [comment]
> Starting with Google Kubernetes Engine (GKE) version 1.15, the open source Kubernetes Dashboard will [no longer](https://cloud.google.com/kubernetes-engine/docs/concepts/dashboards#kubernetes_dashboard) be natively supported in GKE as a managed add-on.
> We are making this change due to several high-profile attacks that exploited the Kubernetes Dashboard add-on throughout the past year.

Should we follow this example set by GKE and let users install it on their own if they deem that they really need it?

**Comment by ialidzhikov** [comment]
> Do we have to deploy different Kubernetes Dashboard versions for shoots < 1.14? From the release notes I understand that some features might not work for clusters < 1.14.

I just noticed that in k/website they changed k/dashboard version to be the beta one and I opened this issue to have it the backlog. I still haven't played with new v2 branch to see what is supported per k8s version.

> Should we follow this example set by GKE and let users install it on their own if they deem that they really need it?

I have no strong opinion about it. Users can always disable the dashboard add-on and do `helm install stable/kubernetes-dashboard`.
Feel free to close/comment if you think that we should deinvest or change the model with the current in-tree add-on.

**Comment by ThormaehlenFred** [comment]
Google writes in their bulletin: _We are making this change due to several high-profile attacks that exploited the Kubernetes Dashboard add-on throughout the past year._ 
When we stop advertising the k/dashboard in the Gardener cluster creation dialogue we reduce at least the overall risk implied by it. Thus I would vote for _let users install it on their own if they deem that they really need it_

**Comment by rfranzke** [comment]
cc @vlerenc, opinion?

**Comment by vlerenc** [comment]
Well, if that's the new thing, then let's embrace it.

I don't understand the security argument, because I don't know whether version 2 shall be safer than version 1. I assume, it's in general bad to have any dashboard in production systems, because whether or not security was improved, it's an entry vector.

Having no dashboard as an option in Gardener is not acceptable. We must offer one, otherwise newbies and all these Windows people who want to try out Kubernetes are lost. We want to give them a hand finding their way into Kubernetes.

I personally have not used any dashboard for 2 years now, I only remember, that I never liked it. Too bulky/unhandy/clicky and not combinable with other shell tools like grep/awk/sed/xargs, etc. In other words, I am no judge whether version 2 is an improvement over version 1, but I hope so and it's anyways the new thing.

I saw in one of the above links, it's written for 1.14 and will support of course 1.15. We can handle the addon differently depending on the Kubernetes version, so why not switch it out from 1.14 onwards and deploy the latest beta?

I am fine with it, but would have preferred a release. When is the release planned?

**Comment by rfranzke** [comment]
> Having no dashboard as an option in Gardener is not acceptable.
> We can handle the addon differently depending on the Kubernetes version, so why not switch it out from 1.14 onwards and deploy the latest beta?

What is your concrete suggestion now? We keep the kubernetes-dashboard as part of an optional addon in Gardener that can be enabled/disabled in the shoot spec, and we deploy the current version for clusters < 1.14, and the new (not yet released?) `v2.0.0` version for clusters >= 1.14. Did I understand this correctly? Or do you want to not offer it at all anymore for newer clusters? I guess no, right?

**Comment by vlerenc** [comment]
> We keep the kubernetes-dashboard as part of an optional addon in Gardener that can be enabled/disabled in the shoot spec, and we deploy the current version for clusters < 1.14, and the new (not yet released?) v2.0.0 version for clusters >= 1.14. Did I understand this correctly?

Yes, that. From what I understood, that would make sense.
