### ISSUE TITLE
Remove Last Error when Step has been successfully processed

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener#1215]
**What would you like to be added**:
Currently the last error is being displayed until we either hit another error or the cluster has been successfully reconciled. It would be more useful to remove that last error if we passed this with a successful processed step.

**Why is this needed**:
Improves operator productivity.

**Comment by rfranzke** [comment]
@plkokanov you assigned yourself, what are your plans?

**Comment by plkokanov** [comment]
@rfranzke Still coming up with a good way to do it. Checking both the gardener and gardener-extensions code.
If you have anything in mind I'm open to suggestions/help :)

**Comment by rfranzke** [comment]
The only idea I have is: We would need to store in the `LastError` structure at which task of the flow it failed. Then we could reset it after we have passed this task.
For the extensions this is not easily possible because we rarely use the flow there.

**Comment by plkokanov** [comment]
@rfranzke I finally had time to work on this issue.
I think we might have to use an array to list all the LastErrors of each task since flow tasks can run in parallel or extend the LastError structure with an array of TaskErrors.
The reason fir this is that currently:
- At the same time multiple tasks can fail and the error description is a concatenation of all errors-- - This means that If we want to only remove the error caused by a single task we would have to do some string formatting of the description which I don't like as an approach

Another option is to only have an array of failed tasks and then clear the LastError only if all tasks in that array have been completed successfully by the current reconciliation.

**Comment by rfranzke** [comment]
Hi @plkokanov, thank you for the update.

> I think we might have to use an array to list all the LastErrors of each task since flow tasks can run in parallel or extend the LastError structure with an array of TaskErrors.

Yes, this sounds reasonable.

> Another option is to only have an array of failed tasks and then clear the LastError only if all tasks in that array have been completed successfully by the current reconciliation.

Also an option, true, but if we now touch this part anyways and spend time implementing it we can also go the cleaner way which would be the first option you described.
