### ISSUE TITLE
Enable Gardener to use custom ImagePullSecrets

### ISSUE THREAD

**Issue by ccwienk** [gardener/gardener#1380]
**What would you like to be added**:

It should be possible to pass custom ImagePullSecrets to Gardener, thus enabling it to retrieve Container Images from Container Image Registries that require authentication.

Ideally, it should be possible to pass multiple secrets and specify a mapping between secrets and target container image registries.

**Why is this needed**:

In private setups (e.g. in corporate environments), proprietary container images may be used, which are hosted in container image registries requiring authentication. Adding support for custom ImagePullSecrets will help enterprise operators of Gardener Landscapes.

**Comment by vpnachev** [comment]
You could find [1] interesting, at least for Shoot cluster point of view.
For the seed cluster it is not applicable, at least not easy. 

[1] https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

**Comment by vlerenc** [comment]
What is the exact use case? I am asking because with the Hub we have the same issue and so we want to establish a contract that people hosting charts on the Hub have to specify a certain pull secret (by name) with their charts (if they use the Hub's image registry) and we install the/our pull secret prior to installation of the chart.

I haven't thought about integrating that part into Gardener, but it's an idea. However, it may get quickly out of hand (considering that you can do that in many ways/namespaces). Our (Gardener) philosophy was more to leave the contents of the clusters to the end users and other tools and let Gardener only take care of the clusters. Pull secrets are somewhere in between, if Gardener starts to offer registry features like having a mirror/proxy registry in the seed or a BitTorrent-like intra-cluster-nodes registry. It's not yet doing that.

**Comment by ccwienk** [comment]
@vlerenc : can we have a personal follow-up?

**Comment by vlerenc** [comment]
Sure, you invite @cwienk?

**Comment by rfranzke** [comment]
I think there are no concrete plans to pursue this anymore. Generally, even if there's still the necessity for it, I'd vote for implementing this as a separate component that registers a webhook for `Pod`s and injects a configured image pull secret.
Adding it to Gardener core wouldn't be enough as there are many extensions that would require similar functionality, i.e., it's easier to handle it centrally via webhook.
/close
