### ISSUE TITLE
Automated Cluster Updates

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#14]
# Stories
* As user I want the latest version with all security patches and bug fixes, so that my cluster is safe and sound.
* As provider I can update the OS, so that I can deploy important security patches and bug fixes quickly.
* As provider I can update Kubernetes and its components, so that I can deploy important security patches and bug fixes quickly.

# Motivation
See above.

# Acceptance Criteria
- [x] Modification of shoot CRDs with a kubernetesVersion (e.g. v1.5), and an operatorVersion (that was used to create or last update the cluster, e.g. v1.35.0)
- [x] Rolling update when:
  - [x] OS version gets updated
  - [x] Kubelet version (only for new Kubernetes minor versions, otherwise by updating the cloud-config secrets)
- [x] Idempotent cluster update (Terraform & Control Plane) in all other cases (operator changes, Kubernetes patches, image or configuration changes)
- [x] Support multiple shoot cluster Kubernetes versions

# Further Considerations
* Kubernetes version upgrades (e.g. v1.5->v1.6) must be approved and scheduled by the end-user.
* We agreed to postpone CoreOS Container Linux FastPatch updates (#37), because the nodes require a restart also with FastPatch and this isn't worth the effort on an IaaS platform where we can simply run a rolling-update of the nodes.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
### What works today
- API server extension only allows for compatible changes, e.g. name, infrastructure and region cannot be changed, but secret reference, Kubernetes version, worker pools, addons can be changed
- Every 10 minutes the Gardener reconciles the shoot resource with the actual cluster by rerunning all (idempotent) operations, i.e. the entire creation flow is executed including Terraform, control plane and shoot cluster addons deployment
- If the OS changes, new machine classes are created and the existing machine deployments are changed to reference the new machine classes (note: if only the cardinality changes, the machine deployment is updated; if a worker pool is added or removed, a machine deployment is added or removed)
- If the kubelet version or configuration changes (patch version), the new kubelet version/configuration is downloaded and the kubelet is restarted
- If the kubelet version changes (minor version), a rolling update is initiated simply because the rendered Kubernetes version (that only covers major+minor) is changed
- All global settings which would have caused operations in the infrastructure have been moved into the Shoot manifest itself (e.g., the machine image version). This is to prevent a huge wave of updates when a global settings changes.

**Comment by rfranzke** [comment]
Canary updates / auto-halt on issues will be tracked in #87.
