### ISSUE TITLE
Inconsistency between autoUpdate of kubernetesVersion and machineImageVersion

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1419]
Currently we you drop a Kubernetes version from the CloudProfile and a Shoot refers this dropped version, in the next maintenance time window the Shoot `kubernetes.version` will be updated to the next patch version only if `autoUpdate.kubernetesVersion` is true.
On the other hand when you drop a machine image version from the CloudProfile and if a Shoot refers this dropped machine image version, in the next maintenance time window the Shoot will receive the laster machine image version from the CloudProfile - no matter what is the value of `autoUpdate.machineImageVersion`.

**Comment by danielfoehrKn** [comment]
Updating machine images and k8 versions are different use cases.Machine images can be updated to latest whereas Kubernetes version updates to latest might break the cluster.

This was discussed in [1325](https://github.com/gardener/gardener/issues/1325). See: 

@danielfoehrKn I don't think we should forcefully update shoot clusters. Is there a mandatory reason to do that? Even if, we can only update one version at a time. We should never update to the latest, because that is a.) not possible and b.) bears an even greater risk to break the cluster. We should only update to the highest patch version of the oldest permitted minor version.

Still, I am not sure we should update forcefully. Is there a technical necessity to do so? On the other hand, if because of the above, there is no reconciliation code anymore in Gardener for that version, then we have no choice, I guess. The only other option, is to completely cease activities and switch off reconciliation, which is likewise ugly.

So, I guess, we have to update, but to the next = oldest version only (highest patch level of lowest minor version).

_Originally posted by @vlerenc in https://github.com/gardener/gardener/issues/1325#issuecomment-521260196_

**Comment by ialidzhikov** [comment]
By inconsistency I didn't mean that the update is to the latest version.
I mean that currently I can have `autoUpdate.kubernetesVersion: false` and if s.o drops my version from the CloudProfile - I will continue to live with my version and because `autoUpdate.kubernetesVersion: false`.
On the other hand when I have `autoUpdate.machineImageVersion: false` and if s.o drops my version from the CloudProfile - I will get the latest version from the CloudProfile and   `autoUpdate.machineImageVersion: false` won't be respected.

**Comment by ialidzhikov** [comment]
Sorry, my bad. I was not right about `autoUpdate.kubernetesVersion`.
Sorry for taking your time. 😞

**Comment by ialidzhikov** [comment]
Btw @rfranzke this behaviour has changed. 
Previously when you replace version X (for example 1.10.12) with patched Y (1.10.13) in the CloudProfile and the Shoot refers X (1.10.12 in our example) and has `autoUpdate.kubernetesVersion: false` and enters in maintenance time window the version was staying the same - X (1.10.12).
Now when you replace version in the CloudProfile, the Shoot version is updated always to the next patch version (1.10.13 in our example) ignoring  `autoUpdate.kubernetesVersion: false`.
Is this behaviour is the expected one? Do we changed this intentionally?

/cc @vpnachev

**Comment by rfranzke** [comment]
Do you have the commit where this changed?

**Comment by vpnachev** [comment]
This is the code responsible for this  https://github.com/gardener/gardener/blob/61275cccbc28be274e560d975a0b249b5cab7d32/pkg/controllermanager/controller/shoot/shoot_maintenance_control.go#L223-L247


particularly "if it is not in the cloud profile - go get the latest version"
```go
    return !versionExistsInCloudProfile || shoot.Spec.Maintenance.AutoUpdate.KubernetesVersion || ExpirationDateExpired(offeredVersion.ExpirationDate),
```



I think that if `shoot.Spec.Maintenance.AutoUpdate.KubernetesVersion == false` we should not touch the version, independent what is defined in the cloud profile.

**Comment by rfranzke** [comment]
Yes, agreed! @danielfoehrKn can you please fix this asap?

**Comment by vpnachev** [comment]
This one as well ?  https://github.com/gardener/gardener/blob/61275cccbc28be274e560d975a0b249b5cab7d32/pkg/controllermanager/controller/shoot/shoot_maintenance_control.go#L309

**Comment by rfranzke** [comment]
No, machine images are updated by design to the latest version if the current version is not found anymore, right Daniel?

**Comment by vpnachev** [comment]
Even when `*shoot.Spec.Maintenance.AutoUpdate.MachineImageVersion` is `false`?

**Comment by ialidzhikov** [comment]
> Do you have the commit where this changed?

It is changed with gardener/gardener#1363.
It is not a big thing, we just need to make sure that 
`.spec.maintenance.autoUpdate.kubernetesVersion: false` is respected even if `.spec.kubernetes.version` is no longer part of the CloudProfile.
However good to see that we have agreement on it. :)

> No, machine images are updated by design to the latest version if the current version is not found anymore, right Daniel?

Hmm, if that is the case, then I find it a little bit confusing. As Shoot owner you have two identical fields - `autoUpdate.kubernetesVersion` and `autoUpdate.machineImageVersion`. `autoUpdate.kubernetesVersion: false` will make sure that no Kubernetes version update will happen if your current version is missing in the CloudProfile. On the other hand with `autoUpdate.machineImageVersion: false` you will receive the latest machine image version if your Shoot's one is missing in the CloudProfile.
But lets see what @danielfoehrKn will reply.

**Comment by danielfoehrKn** [comment]
@ialidzhikov true, there is a different behaviour implemented even though being two identical fields.

I think the difference originated because we do not treat a kubernetes version update the same way as a machineImage update.

To my understanding: 

**Kubernetes versions** 
- cannot be just updated between minor versions without high risk of breaking the cluster 
- updates between patch versions regarded as "safe" - thats why I implemented the auto update on missing k8 version (even though autoUpdate == false) in CloudProfile this way. But I see that is not desired and thanks for finding that @ialidzhikov
Edit: just saw that I [wrote a test](https://github.com/gardener/gardener/blob/61275cccbc28be274e560d975a0b249b5cab7d32/pkg/controllermanager/controller/shoot/shoot_maintenance_test.go#L292) for that behaviour, I thought it was desired :) 

**MachineImage Versions**
-  used to be forcefully updated to latest version everyday in maintenanceTime Window
- update from older to latest version possible in most cases without breaking the cluster
-  update to latest not regarded as dangerous as k8 updates. 
-  updating to latest when missing in CloudProfile avoids having to support old Os versions (same reasoning why used to update every day). If users really need to test their workload on a certain MachineImage before updating, they can just set the expiration date, then manually update and then remove from CloudProfile.

If that reasoning makes sense and if we should "harmonize" between MachineImage and k8 Version update behaviour of course  should/can be discussed again.

For me the difference in behaviour is fine, as long as we document it somewhere to let the user know. 

What do you think?  @ialidzhikov @vpnachev @rfranzke

**Comment by rfranzke** [comment]
Thanks for the summary @danielfoehrKn.

> If that reasoning makes sense and if we should "harmonize" between MachineImage and k8 Version update behaviour of course should/can be discussed again.

I don't think we should change this. In the past, we always rolled out machine image updates. Now, the user can drop out, but only until the currently used version expires. When the version doesn't exist in the profile anymore an immediate update is happening. This is because we need to be able to roll out security fixes ASAP, and we still control the worker nodes and the machine image versions. If we would let the responsibility to the end-user we might end-up with a lot of clusters whose image is outdated/potentially vulnerable, we can't do that.
With Kubernetes versions it's different, here the responsibility is fully with the cluster owner, even for security patch updates. That's how it was since day 1.

> For me the difference in behaviour is fine, as long as we document it somewhere to let the user know.

Same.

> updates between patch versions regarded as "safe" - thats why I implemented the auto update on missing k8 version (even though autoUpdate == false) in CloudProfile this way. But I see that is not desired and thanks for finding that @ialidzhikov

Yes, please fix that. 👍

**Comment by vpnachev** [comment]
Then do we need the field `shoot.Spec.Maintenance.AutoUpdate.MachineImageVersion` ?

**Comment by rfranzke** [comment]
Yes, we need it, because if operators want to offer expiration dates for machine image versions to allow end-users to "manually" update/migrate to the new image then end-users need to configure this behaviour via this field.
