### ISSUE TITLE
metrics-server on metal not available: FailedDiscoveryCheck

### ISSUE THREAD

**Issue by sjentzsch** [gardener/gardener#1450]
**What happened**:

In our shoot clusters, for our Gardener metal cloud (team here at FI-TS), the metrics-server is being deployed. However, with our infrastructural setup, the metrics server does not seem to work properly anymore, as e.g. the apiservice `v1beta1.metrics.k8s.io` is not available, deletion of namespaces is thus hanging and any auto-scaling (horizontal/vertical) won't work.

However, with the PodSecurityPolicy being deployed and `hostNetwork` enabled (see https://github.com/helm/charts/blob/master/stable/metrics-server/values.yaml) the metrics-server is functional.

We would like to be able to enable/configure such, as it seems like for our Metal Cloud that might be required. How can we go about it and fix the deployment of metrics server?
To me, that would induce a change/extension to the metrics server deployment chart, right?

`kubectl describe apiservice v1beta1.metrics.k8s.io`

```
Status:
    Message:               no response from https://10.244.0.10:8443: Get https://10.244.0.10:8443: dial tcp 10.244.0.10:8443: connect: connection refused
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
```

**What you expected to happen**:

Metrics-server apiservice availability is `True`.

**How to reproduce it (as minimally and precisely as possible)**:

Reproducible within our metal infrastructure (see https://github.com/metal-pod); guess that's not as reproducible on your end as it is on our, however, hopefully we can find the issue together :)

**Anything else we need to know?**:

I am part of the Metal Cloud team here at FI-TS.
Approach also via Slack (see https://kubernetes.slack.com/archives/CB57N0BFG/p1568975926015200)

**Environment**:

- Gardener version: *currently looking up*
- Kubernetes version (use `kubectl version`): v1.14.3 (in shoot cluster), v1.15.3 (client)
- Cloud provider or hardware configuration: see https://github.com/metal-pod

**Comment by rfranzke** [comment]
Hi @sjentzsch, interesting, thanks for filing the issue.
So, I understood that the main problem for you is that you need to run the metrics-server in the host network, right? The PSP is needed in this case as well, right?
I think it makes sense to add the PSP generally directly in Gardener (we already do this for most other components). I'm not so sure whether we should make `hostNetwork=true` the default as well, probably not, but if Gardener would deploy the PSP then you could mutate the PSP + the metrics-server deployment to run in the host network if that's required in your environment.
This way we would a) enhance Gardener (because it should deploy the PSP anyways) and b) get rid of the problem that your webhook would need to create additional resources - instead, it can just mutate the few fields for the host networking. WDYT?

**Comment by sjentzsch** [comment]
Hi @rfranzke Exactly, that makes sense and sounds reasonable.
If you could ensure the PSP for the metrics-server gets deployed via Gardener, we can mutate `hostNetwork=true` on our end.

**Comment by rfranzke** [comment]
Hi @sjentzsch, sounds good. Would you like to file a PR against the metrics-server chart?

**Comment by rfranzke** [comment]
Hey @sjentzsch, any update on this?

**Comment by sjentzsch** [comment]
Hi @rfranzke, we discovered a network issue on our side, which very likely caused such `FailedDiscoveryCheck`. Thus, we might not need the feature anymore. Please feel free to close the issue and we re-open if it turns out we still need some more customization on this end. Thanks a lot so far, nonetheless!

**Comment by rfranzke** [comment]
Okay, thanks for the update!

**Comment by arghya88** [comment]
@sjentzsch what was the network issue?

**Comment by majst01** [comment]
This was a misconfigured network between the seed and the shoot actually.
