### ISSUE TITLE
Container Runtime Options

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1454]
**What would you like to be added**:
Today, Gardener has a hard requirement to Docker, but there are a couple of more container runtimes out there, e.g. `cri-o` or `gvisor`. We should investigate what is necessary to make the container runtime pluggable, and to allow end-users to configure which runtime shall be used on shoot level.

**Why is this needed**:
End-users are interested in using other container runtimes than Docker.

**Comment by majst01** [comment]
Would love to help here

**Comment by liorokman** [comment]
Seems to me that the biggest value would be to make Gardner-managed clusters use Containerd to launch pods by default. Both gVisor and Kata Containers support integrating into Kubernetes using Containerd shims.

Since the latest Docker CE packages come with Containerd, and CoreOS has Containerd preinstalled, the change would mainly require adding the relevant kubelet parameters (`--container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock`). On CoreOS images the correct socket would be `/var/run/docker/libcontainerd/docker-containerd.sock` 

Once kubernetes is configured to use Containerd, actually adding additional runtimes like gvisor or kata containers would require adding the relevant binaries to the nodes (e.g. by providing a [torcx](https://github.com/coreos/torcx) package for CoreOS), configuring containerd correctly, and adding a RuntimeClass object into the Kubernetes control plane.

**Comment by vpnachev** [comment]
Gardener is not working only with CoreOS, it also has support for Ubuntu and SUSE-JEOS. New operating systems might be added in the future, too. A clean contract from the Gardener is required w.r.t. container runtime, so that new operating systems controllers will be implemented without any change in the gardner code.

At the moment, the OS can be configured per worker pool, because of potential issues(missing support for container runtime X in OS Y) maybe the container runtime should be configurable per worker pool, WDYT?

**Comment by majst01** [comment]
Configuration per worker pool is probably the most flexible solution, but probably kinda difficult to manage from a user perspective if there is no default in the cloudprofile.
Regarding container runtime, i would also prefer to add containerd as a second option for the start.

**Comment by vpnachev** [comment]
> Configuration per worker pool is probably the most flexible solution, but probably kinda difficult to manage from a user perspective if there is no default in the cloudprofile.

OS type and version is optional in the shoot manifest, too. If the OS is omitted in the shoot manifest, it is defaulted to the first one available in the respective cloud profile.

https://github.com/gardener/gardener/blob/59a79859b4a6a5428239e5be728716b7ff24b6ca/pkg/apis/core/v1alpha1/types_shoot.go#L804-L805

So, I think that similar approach can be used for the container runtime - have a default in the cloud profile and make it optional in the shoot manifest.

I am only afraid whether all supported OSes will support all container runtimes, so some validation checks might be required, e.g. worker pool with OS `X` supports container runtime `Y` and `Z`, but not `W`. A compatibility matrix might be added to the machine image definitions in the cloud profile as constraints.
https://github.com/gardener/gardener/blob/59a79859b4a6a5428239e5be728716b7ff24b6ca/pkg/apis/core/v1alpha1/types_cloudprofile.go#L85-L91

**Comment by majst01** [comment]
Agreed, so we need to have:

- a default container runtime per CloudProfile, which is available across all possible MachineImages / OSses
- A set of possible/compatible ContainerRuntimes per MachineImage, which will default to that given in the CloudProfile if ommited.

**Comment by liorokman** [comment]
I think this is a little more subtle. The first question is whether Kubernetes is configured to use the Docker API to configure containers, or the CRI API to configure containers. The current default is to use the Docker API, I think we should change that to use the CRI API, by moving the default Kubernetes configuration to use Containerd. This should be done across all worker-nodes, regardless of OS type. 

The advantage of using Containerd is that it is already installed on all of the supported images - it's actually part of the Docker distribution - so it's simply a matter of changing the Kubelet configuration. 

Once Kubernetes has been configured to use the CRI API to configure containers, it becomes possible to make additional changes - adding additional runtime options like GVisor, Kata Containers, and so on - simply by changing the Containerd configuration file and adding a Runtime definition to Kubernetes. This should be a secondary addition to the work done here. Adding these extensions should indeed be done as suggested here - on a worker-group basis.

**Comment by vlerenc** [comment]
Sounds all very reasonable:
- using the containerd shim
- make it configurable per worker pool
- similar defaulting behaviour as we have already for OS
- describe which runtimes are allowed per OS, when we have gaps (maybe RHEL and Docker is already such a gap that may force us to do that, because that combination is officially supported)

In addition, we would get of course another/fourth output qualification dimension (IaaS, K8s Version, OS and Version, and now Runtime and Version?). cc @dguendisch @schrodit @OlegLoewen

**Comment by dguendisch** [comment]
An additional test dimension, uh, I mean if that feature makes sense (and it sounds like), then we'll have to add that dimension. Maybe we can optimize a bit by not creating test shoots with all that dimensions multiplied but combine dimensions into single shoots by using multiple worker pools instead, let's see...

**Comment by deissnerk** [comment]
@dguendisch @vlerenc 
For us (FaaS) this feature would definitely make sense. To my understanding Kata containers can only be used, where nested virtualization is possible (not on ordinary EC2 instances), but gvisor would be very interesting.

**Comment by rfranzke** [comment]
@nimrodoron and colleagues have filed GEP10 (#1735) and started to implement it as of #1971
The implementation happens in three phases (summary of GEP10, see more details there):

1. Allow using `containerd` as CRI for worker pools (requires containerd >= 1.3), see #1971
1. Extend Gardener's `extensions.gardener.cloud` API with a new `ContainerRuntime` resource that is created as part of the shoot reconciliation flow - similar to all our other extension resources, see #2035
1. Develop extension controllers that act on this `ContainerRuntime` resource for gvisor and others, see e.g. https://github.com/gardener/gardener-extension-runtime-gvisor
