### ISSUE TITLE
Kube-proxy and Kube-dns were down during a scalability test 

### ISSUE THREAD

**Issue by nikhilagrawal577** [gardener/gardener#146]
While doing a scalability test in Gardener, we checked  Gardener dashboard.
Kube-dns was down.
Kube-proxy was down.

![image](https://user-images.githubusercontent.com/5903934/39302447-41904cac-4970-11e8-8a9c-5082fd42a044.png)

We are not sure why it is down in the cluster.

**Comment by rfranzke** [comment]
Without further details this will be hard to analyze. Generally, whenever a new machine is spinned up a few system components (like kube-proxy) need to start. When the health check of Gardener is performed in the same moment it will show the message you attached. Hence, I wouldn't be too nervous about that in case you have more detailed information about what exactly and how long it went wrong/did not work.

**Comment by nikhilagrawal577** [comment]
No, we already had enough number of nodes/resources. It didn't spin up any node. 
You can reproduce the problem by creating 35-36 nodes with around 3k pods

**Comment by rfranzke** [comment]
Can you please provide further details? Otherwise, we won't be able to do anything. Logs of the components which don't come up would be helpful.

**Comment by nikhilagrawal577** [comment]
Due to maintenance cost, we deleted the cluster. 
We will be triggering the test again. Will check if we can face the same issue again.

**Comment by vlerenc** [comment]
Valuable feedback, thank you! First I thought, this could be a duplicate of #79, but let's keep it open in case both are two facets of the same "general problem" that our clusters don't scale well enough. The danger that makes this more pressing is that we run seeds as shoots now.

However, the finding is kind of surprising. The proxy scales automatically, because it's a daemon set, so maybe this is indeed a consequence of the unavailability of the API server (#79). The DNS also scales automatically, because we deploy the DNS autoscaler, but maybe that again is a consequence of the unavailability of the API server (#79). If that's the case, we can close this ticket as duplicate. If not, let's find out what's wrong here with the assumptions.

**Comment by vlerenc** [comment]
Closing as we believe this was only a follow-up problem of the unavailable API server (seen also during the latest Garden cluster downtime).
