### ISSUE TITLE
IBM Cloud

### ISSUE THREAD

**Issue by iancrowther** [gardener/gardener#1467]
IBM Cloud Support

Whilst not in the big 3, IBM has k8s

**Comment by vlerenc** [comment]
I guess, that's a feature request to support IBM Cloud. On the other hand, you mention, they also have Kubernetes (yes, we know), but Gardener is no "shell" wrapping around other companies Kubernetes services. It's one of its own with a vanilla Kubernetes distro you can configure. That's how we provision homogenous clusters in private and public clouds. Plus, we can deploy to any region with basic resources like compute, storage, networking, so Gardener runs on even more regions than services like EKS or AKS.

But let's go back to the IBM Cloud. We certainly welcome IBM to contribute Gardener support like Packet Cloud did. We can't really do that, because IBM has not open-sourced their cloud controller managers. It's all proprietary as far as I know. I assume, it would be no problem to adapt Gardener (write a Gardener infrastructure extension) to SoftLayer (which is what I believe they use, but I am no expert here), but because of the closed nature, it should be done by or at least with them.

**Comment by iancrowther** [comment]
hey @vlerenc 

I had, as you correctly identify, completely misunderstood the product offering and indeed thought it was a shell wrapping for managing deployments.  

Thanks for the insight and for your response.
