### ISSUE TITLE
Support multiple DNS providers

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1572]
With the new `core.gardener.cloud/v1alpha1.Shoot` API we are supporting to specify multiple DNS providers: https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L192-L205

However, our current implementation only deploys exactly one provider: https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/dns.go

We should fix our implementation to properly support the API.

**Comment by freegroup** [comment]
If an existing cluster "suddenly" wants to use a custom domain with TLS/certificates, then this is only possible by deleting the cluster completely and entering the domain in the Shoot Manifest and creating the cluster again.

is it possible to use this feature *Custom Domains* with an existing cluster on a migration path (without deleting them at all)?

we have a lot of stakeholder with existing cluster who wants to use this feature.

**Comment by rfranzke** [comment]
I'd consider this request to be independent of this issue.
What you want to do is to change your DNS domain of a running cluster. Theoretically, this should be not too much work. We would need to regenerate the kube-apiserver certificate, and to create/delete new/old records. Can you open a separate issue for this one?

**Comment by timuthy** [comment]
As discussed internally with @rfranzke, we see the necessity to add two new fields to our shoot API in order to make the implementation work in a usable way for the user.

Currently shoots only have a list of DNS providers which comes with certain pitfalls because if we'll have multiple providers in the future we still need to identity the "primary" one that is responsible for the shoot domain. Users might accidentally change this provider by changing the list order which makes DNS management for the shoot domain quite unreliable.

```yaml
dns:
    domain: shoot.example.com
    providers:
    - type: google-clouddns
       secretName: clouddns
    - type: aws-route53
       secretName: route53
```

Instead, we want separate the provider responsible for the shoot domain (`domainProvider`) and other providers which serve  `DNSEntries` inside the shoot (`managedProviders`). The old field `providers` will be **deprecated** in favor of this new structure:

 ```yaml
dns:
    domain: shoot.example.com
    domainProvider:
      type: google-clouddns
      secretName: clouddns
    managedProviders:
    - type: aws-route53
      secretName: route53
``
