### ISSUE TITLE
Offer VPA deployment next to shoot control plane

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1584]
We should optionally offer to deploy and configure the VPA for shoot clusters. We can run the required deployments in the shoot namespace in the seed and wire them accordingly so that the webhooks can seed-internally communicate with the shoot's API server.

End-users could then get a VPA for their clusters out of the box, controlled and managed by Gardener. A new `.spec.kubernetes.verticalPodAutoscaler` flag would be needed in order to control whether it's enabled and to offer potential configuration options.

cc @vasu1124

**Comment by amshuman-kr** [comment]
Why not an add-on?

**Comment by rfranzke** [comment]
What's the benefit in this case?

**Comment by amshuman-kr** [comment]
Hosting on the shoot cluster nodes.

**Comment by rfranzke** [comment]
Okay, no strong opinion, actually. The only benefit of running it in the seed is that it can talk cluster-internally to the kube-apiserver. But that’s not a very strong benefit. There is no real reason to run it in the seed, so I‘d be okay running it in the shoot.

**Comment by amshuman-kr** [comment]
> Okay, no strong opinion, actually. 

Me neither :-) Just thought hosting optional components in the seed would add to the cost of hosting the control planes.

**Comment by vlerenc** [comment]
Personally, I tend to keep it rather with our control plane. It's critical to the auto-scaling, too. In general, all the things that can be either on the shoot or on the seed, I would prefer to have on the seed, because that means less network traffic, friction, stability issues. In the end, we are responsible to keep these components running, on seed or shoot. If on the seed, it's easier for us to fulfil that promise.

As for costs, Gardener hosters can charge back for the control plane, if they want. So, the compute+memory costs are there, this way or the other, but the network costs are lowered in the seed (in addition to keeping the component in a safe spot and not on the cluster). Then again, significant cost factors would "look better" if not charged back in commercial models, but VPA doesn't seem to be one.

As for how to get it out, let's make it optional (to not collide with already deployed VPAs) as @rfranzke suggested, but if someone needs a truly auto-scaling cluster, she can only get it if this option is ticked. Large clusters won't be available without VPA deployed by us then.
