### ISSUE TITLE
Gardener differentiation

### ISSUE THREAD

**Issue by ghost** [gardener/gardener#1595]
How does gardener different from Google's Anthos and Azure Arc ?

Like to understand when would i would gardener when compared to others ?

**Comment by vlerenc** [comment]
There is not much to be compared here. Anthos is GKE (Google Cloud) and GKE-on-prem (VMware), but while the first is well-known and regarded, the latter is not of the same qualities (no Borg anywhere outside of Google), see also https://cloud.google.com/gke-on-prem/quotas, which are quite restricting. It's all very, very early.

Arc is even fresher, Azure and private DC hardware only, and mostly rebranded stuff and marketing, see https://www.zdnet.com/article/microsofts-hybrid-2-0-strategy-azure-arc-azure-stack-hub-azure-stack-edge-explained and this summary here:
> „Azure Arc seems to be Microsoft's attempt to answer Amazon with Outposts and Google with Anthos, said Sid Nair, a Gartner Research Vice President. Beyond that, at this point at least, it seems to be mostly a bunch of industry buzzwords, Nag said."

Gardener is plain Kubernetes, running in production for years and supports clusters on Alicloud, AWS, Azure, GCP, OpenStack, Packet Cloud (no experience here, contribution by Packet Cloud itself), a metal-as-a-service implementation that wanted Gardener Kubernetes clusters on-prem and maybe more (because it's open source, we know of the infrastructures only when the users share that with us).

We run it ourselves, thousands of clusters, so this is real cluster management and a comparison would make more sense with ACK, EKS, AKS, GKE and such, but they are all specific to one infrastructure only, while we didn't want the lock-in and looked for a solution to support **homogenous clusters** at scale with minimal TCO. That's Gardener in a nutshell.

**Comment by ghost** [comment]
@vlerenc  Thanks for the response. What i understand, Gardener is more of a homogenous K8S for multiple clouds  managed from single pane of glass.
