### ISSUE TITLE
Getting started. 

### ISSUE THREAD

**Issue by ghost** [gardener/gardener#1618]
Hello Team.

I would like to install gardener, install UI and also create GKE and EKS using gardener. 

Can you help point me to right links to get started ?

**Comment by vlerenc** [comment]
Gardener is no shell around other managed Kubernetes services/offerings. Gardener comes with a configurable vanilla Kubernetes distro. To achieve that, it needs to control the control plane, which no managed service allows (for obvious reasons). Gardener comes with minimal TCO and manages everything including the nodes. Again, services like EKS don't support that.

Gardener's mission goal is to provide homogeneous clusters at scale with minimal TCO. That's why we can't use managed services. If you want to do that, check out the cluster API SIG. Progress is slow and the features are limited, but that's in the nature of the managed services (not blaming the SIG here). You can't get the same Kubernetes version, operating system, control plane configuration, feature gates, runtime configurations, node management, network settings, etc. from them. It's simply not possible - they all differ. Not even speaking of lifecycle management operations themselves - they all differ. However, we needed a Kubernetes distro that looks and feels on all infrastructures the same (as far as possible), which is why Gardener uses low level resources such as compute, network, storage and deploys its own control plane and nodes. It keeps track of the cluster health and manages all lifecycle management operations like updates 24x7 on auto-pilot (you can also opt-out and manually trigger operations if you like). So, our provisioning, deprovisioning, update flow looks and feels the same on all infrastructures, because it is. Monitoring, logging, cluster access is the same. You get the same Kubernetes version, the same OS, the same cluster and control plane auto-scaling, the same settings left and right for all regions of all supported infrastructures. That's Gardener. Not a wrapper around vastly divergent other managed services.

That not only allows us to offer homogeneous clusters, but also to go into all regions (e.g. EKS/AKS aren't available in all regions), offer full control, go even into less popular infrastructures, and even support bare metal (we were adopted by companies with bare metal hardware and proprietary management stacks).

That is the goal of Gardener, because hyperscalers will never do that. Their interest is to differentiate and lock-in end users and that's OK/to be expected (no criticism). Our interest was to have a uniform Kubernetes with minimal TCO everywhere.

**Comment by ghost** [comment]
Thanks for the detailed explanation @vlerenc 

Can you point me to steps for installing gardener ?

**Comment by ialidzhikov** [comment]
@kkbrat9 , you can check the community installer - https://github.com/gardener/garden-setup/ and the related [docs](https://github.com/gardener/garden-setup/tree/1.16.2/docs/extended).
