### ISSUE TITLE
CloudRouter conversion is missing for Shoot APIs

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#1645]
**What happened**:
https://github.com/gardener/gardener-extensions/pull/417 added a new field `cloudRouter` to the `VPC` of the provider GCP API.

Since `cloudRouter` hasn't been added to `garden.sapcloud.io/v1beta1` but Gardener still offers both shoot API versions, a proper conversion logic is required: `cloudRouter` should be saved as an annotation (`migration.shoot.gardener.cloud/infrastructureConfig`) in `v1beta1` shoots.

**What you expected to happen**:
Roundtripability between `core.gardener.cloud/v1alpha1` and `garden.sapcloud.io/v1beta1` shoots w/o data loss.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot in `core.gardener.cloud/v1alpha1` with `cloudRouter` information.
2. Edit the shoot from 1.) in version `garden.sapcloud.io/v1beta1`.
3. Get shoot from 1.) in `core.gardener.cloud/v1alpha1` and see that the `cloudRouter` info is gone.

- Gardener version: 0.31.2

/cc @zanetworker

**Comment by rfranzke** [comment]
Can we simply add the new fields to the spec.cloud.gcp object in the old garden.sapcloud.io/v1beta1 API instead of inventing another mechanism that stores parts of the infrastructure config inside an annotation? This makes the implementation way easier, and as we plan to remove the old API soon anyways, we should only invest the minimal effort to keep the API backwards compatible.

**Comment by rfranzke** [comment]
According to @timuthy it's possible to use the `cloudRouter` fields with the new `core.gardener.cloud` API group. The old `garden.sapcloud.io` API group will be removed in a few weeks, so let's not invest anything anymore.
