### ISSUE TITLE
Use AKS or EKS for the gardener cluster.

### ISSUE THREAD

**Issue by luisdavim** [gardener/gardener#180]
Hi,
Is it possible to use a managed kubernetes cluster for the (top level) gardener cluster?

**Comment by vlerenc** [comment]
Depends on... the native service. The Gardener itself might run on any Kubernetes cluster that passes the conformance tests, I guess. The Dashboard, in its standard configuration, depends on OpenID Connect to be configured at the API server.

We have [Kubify](https://github.com/gardener/kubify) (Terraform-based bring-up on different infrastructures), too.

**Comment by luisdavim** [comment]
thanks for the answer @vlerenc

**Comment by jicowan** [comment]
@vlerenc the documentation says the seed base cluster must support basic authentication.  The only types of authN that EKS supports is IAM and bearer tokens.

**Comment by rfranzke** [comment]
@jicowan where do you see this documentation on our side? It's actually wrong - the only contract for registering a seed cluster in gardener is a kubeconfig with no provider specific authentication method (because gardener does not vendor any provider specific plugins that would be needed).
So, if you provide a kubeconfig for your EKS seed containing a bearer token it should work fine.

**Comment by jicowan** [comment]
@rfranzke thanks for clarifying.  I found it here, step 6, https://github.com/gardener/garden-setup.  "If you created the base cluster using GKE convert your kubeconfig file to one that uses **basic authentication** with Google-specific configuration parameters:"  I tried installing on a KOPS clusters with `sow` but kept failing at the **seeds** step with this error: 
```
*****************************
*** sowing species gardencontent/seeds
using local action script
2019/07/21 21:20:54 error generating manifest: unresolved nodes:
	(( sum[landscape.iaas|[]|s,v|->v.mode == "seed" ? s utilities.kubectl.generate(__ctx.DIR "/manifests/manifest.yaml", imports.kube_apiserver.export.kubeconfig, *(providerconfig)) : s] ))	in /mounted/Users/jicowan/GitProjects/landscape/crop/components/gardencontent/seeds/deployment.yaml	kubectl	()	*evaluation of lambda expression failed: lambda|s,v|->v.mode == "seed" ? s utilities.kubectl.generate(__ctx.DIR "/manifests/manifest.yaml", imports.kube_apiserver.export.kubeconfig, *(providerconfig)) : s: {s: [], v: {crede ... 1b, us-east-1c]}}
		... evaluation of lambda expression failed: lambda|file,config,settings|->*(_.templates.kubectl): {config: {apiVers ... 100.64.0.0/10}}}}
		... resolution of template 'utilities.kubectl.templates.kubectl' failed
			(( sum[values.config.credentials|{ }|s,k,v|->s { k = base64(v) }] ))	in /mounted/Users/jicowan/GitProjects/landscape/crop/components/gardencontent/seeds/manifests/manifest.yaml	manifests.[0].data.<<	()*evaluation of lambda expression failed: {config: {apiVers ... 1b, us-east-1c]}}lambda|s,k,v|->s { k = base64(v) }: {config: {apiVers ... rname: admin}}]}}
					... first argument for base64 must be a string
error classification:
 *: error in local dynaml expression
 @: dependent of or involved in a cycle
 -: depending on a node with an error
Error: processing deployment.yaml
```

When I tried the YAML generated by the Gardener Installer page, it failed at an earlier step with an error about the ClusterIP not in range [100.64.0.0/13]. Happy to open a separate issue for tracking purposes.

**Comment by rfranzke** [comment]
@Diaphteiros @mandelsoft can you assist here with this sow error?

**Comment by Diaphteiros** [comment]
@jicowan Based on your error message, the structure of the credentials in one of the entries of `landscape.iaas` seems to be wrong. You can find information about the correct structure for the credentials here: https://github.com/gardener/garden-setup/blob/master/README.md#landscapeiaas

If you can't figure out what is wrong, post the `landscape.iaas` node of your acre.yaml (obfuscate sensitive information, but leave the structure as it is)

**Comment by jicowan** [comment]
Thanks @Diaphteiros.  The documentation left me a little confused.  I thought the `iaas.cluster` section was referring to the CIDR ranges of the base cluster.  It says: 

```
The first entry of the landscape.iaas list is special:
It has to exist - the list needs at least one entry.
Don't specify the cluster node for it - it will configure your base cluster as seed.
Its type should match the one of your base cluster.
```

Does this mean I should leave the cluster node blank?  I assume it still needs a reference to the kubeconfig. What IP ranges are valid?  On EKS, you can't configure the Service CIDR and the pod CIDR is the same CIDR as the nodes.  Do you have an example of an `acre.yaml` for EKS?

My `acre.yaml` looks like this: 

```
...
cluster:                                         
    kubeconfig: ./kubeconfig          
    networks:                                       
      nodes: 172.20.0.0/16
      pods: 100.96.0.0/16
      services: 100.64.0.0/10

  iaas:
    - name: aws                          
      type: aws            
      region: us-east-1      
      zones:                                     
        - us-east-1a   
        - us-east-1b   
        - us-east-1c  
...
```

**Comment by Diaphteiros** [comment]
The part of the README you are quoting refers to the first entry of `landscape.iaas`. As opposed to (optional) further entries in `landscape.iaas`, the first one doesn't need the `cluster` node - it will use the values from your base cluster (the ones from `landscape.cluster`). 
Regarding the CIDRs: Unfortunately, I did never use the garden setup on EKS and don't have a working configuration at hand. The Gardener uses the CIDRs specified in the seed to make sure that the CIDRs of shoots running on that seed don't overlap with the one of the seed's base cluster. This means that the CIDRs you specify in the acre.yaml don't have to match the ones of your base cluster exactly, but your base cluster's CIDRs should be completely within the ones specified here.

**Comment by jicowan** [comment]
Thanks @Diaphteiros.  So you're saying I don't need the `iaas.cluster` node?  The comment that appears in the acre.yaml template/example says "information about your **base** cluster" and "CIDR IP ranges of **base** cluster". If you omit those from acre.yaml, will it still work?  I feel like I've completely  misinterpreted the documentation.  I get that the shoots are virtual Kubernetes clusters that run on seed clusters.  I'm struggling with getting the base Gardener cluster running along with the first seed. 

Here the acre.yaml I'm using: 
```
landscape:
  name: garden                       # general Gardener landscape identifier, for example, `my-gardener`
  domain: jicomusic.com       # unique basis domain for DNS entries

  cluster:                                          # information about your base cluster
    kubeconfig: ./kubeconfig          # path to your `kubeconfig` file, rel. to directory `landscape` (defaults to `./kubeconfig`)
    networks:                                       # CIDR IP ranges of base cluster
      nodes: 172.20.0.0/16
      pods: 100.96.0.0/16
      services: 100.64.0.0/10

  iaas:
    - name: aws                           # name of the seed
      type: aws            # iaas provider
      region: us-east-1      # region for initial seed
      zones:                                     # remove zones block for Azure
        - us-east-1a   # example: europe-west1-b
        - us-east-1b   # example: europe-west1-c
        - us-east-1c   # example: europe-west1-d
      credentials: 
        accessKeyID: A...
        secretAccessKey: N...                            # provide access to IaaS layer used for creating resources for shoot clusters
        kubeconfig:                              # kubeconfig for seed cluster
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: ...
              server: https://api.k8s.jicomusic.com
            name: k8s.jicomusic.com
          contexts:
          - context:
              cluster: k8s.jicomusic.com
              user: k8s.jicomusic.com
            name: k8s.jicomusic.com
          current-context: k8s.jicomusic.com
          kind: Config
          preferences: {}
          users:
          - name: k8s.jicomusic.com
            user:
              client-certificate-data: ...
              client-key-data: ...
              password: ...
              username: ...
          - name: ...
            user:
              password: ...
              username: ...

  etcd:                                       # optional, default values based on `landscape.iaas`
    backup:
      type: s3               # type of blob storage
      resourceGroup:                          # Azure resource group you would like to use for your backup
      region: us-east-1              # region of blob storage (default: same as above)
      credentials:
        accessKeyID: A...
        secretAccessKey: N...     # credentials for the blob storage's IaaS provider (default: same as above)

  dns:                                    # optional, default values based on `landscape.iaas`
    type: aws-route53   # dns provider
    credentials: 
      accessKeyID: A...
      secretAccessKey: N...   # credentials for the dns provider

  identity:
    users:
      - email: jsmith@acme.com                               # email (used for Gardener dashboard login)
        username: jsmith                             # username (displayed in Gardener dashboard)
        password: ...                           # clear-text password (used for Gardener dashboard login)
      
  cert-manager:
    email: jsmith@acme.com                                   # email for acme registration
    server: self-signed    # which kind of certificates to use for the dashboard/identity ingress (defaults to `self-signed`)
```

**Comment by Diaphteiros** [comment]
I'll try to explain what happens here:
You need to provide the base cluster. In theory, that can be any kubernetes cluster - GKE, kops, even a shoot if you already have access to running Gardener somehow.
In the `landscape.cluster` node, you need to provide the path to the kubeconfig for your base cluster and specify the CIDRs of that cluster (or at least some CIDRs that completely contain those of your base cluster, as described above).
Each entry of `landscape.iaas` will create a seed. That's not completely true, as there are some advanced configuration options, but for the sake of simplicity, let's assume you only have one entry here. The first entry of `landscape.iaas` is special, because it will always create a seed *on your base cluster*. Therefore it doesn't need a `cluster` entry containing kubeconfig and CIDRs, because you already specified them for your base cluster in `landscape.cluster`. All following entries in `landscape.iaas` will need these values though, as they do not refer to your base cluster.

Creating a seed for a cluster / configuring a cluster as seed (not sure what is the fitting terminology here) basically means telling the Gardener that it can host control planes of shoots on that cluster. So in this case, you have a base cluster, deploy a Gardener to that cluster and then configure it so the Gardener can also use it to host control planes.

**Comment by jicowan** [comment]
@Diaphteiros Ok, that makes sense, however, I don't have a `landscape.iaas.cluster` node in my `acre.yaml`.  Gardener seems to have an issue with the CIDR ranges that my base cluster is using.  Are there certain ranges that are invalid.  The ranges that I've listed in my `acre.yaml` are the ranges that my base KOPS cluster is using.

**Comment by Diaphteiros** [comment]
@jicowan There shouldn't be any 'invalid' ranges. However, the default CIDRs kops uses clash with the dashboard defaults:
```
nodes: 10.250.0.0/19
pods: 100.96.0.0/11        <- overlaps with kops defaults
services: 100.64.0.0/13    <- overlaps with kops defaults
```

But you should notice that only when trying to create a shoot via the dashboard, not before.

What exactly is the error message you get and when do you get it?

**Comment by jicowan** [comment]
https://github.com/gardener/gardener/issues/180#issuecomment-513772304

**Comment by jicowan** [comment]
@Diaphteiros it happens during the seeds stage.  I have not tried creating a shoot via the dashboard.

**Comment by Diaphteiros** [comment]
@jicowan Ah, it's still that error. The error message is comparatively precise - there is a function that base64-encodes your credentials to put them into a secret and that function fails because it gets a non-string argument. 
Ah, I found it: You have put the kubeconfig in the `credentials` node! That is not correct, the kubeconfig belongs in the `cluster` node (however, since that is the first entry of `landscape.iaas`, it uses your base cluster for which you already provided the kubeconfig in `landscape.cluster.kubeconfig`, therefore you don't need it at all). Just remove the `kubeconfig` entry from your credentials and try again. 
Sorry, I didn't notice that earlier.

**Comment by jicowan** [comment]
@Diaphteiros sorry for the delay.  I removed that section from my acre.yaml and managed to get a little further.  Now I'm getting the following error: 

```
*** sowing species gardencontent/seeds
using local action script
Plugin: cleanup[deploy] (cleanup)
Plugin: kubectl[deploy] (/sow/plugins/kubectl/plugin)
manifest for Secret(v1): garden/aws-seed
secret/aws-seed created
manifest for Seed(garden.sapcloud.io/v1beta1): aws
The Seed "aws" is invalid: spec.networks.pods: Invalid value: "100.96.0.0/16": must not be a subset of "spec.networks.services" ("100.64.0.0/10")
```

I am trying to install this onto a KOPS cluster with the default settings.  In an earlier comment, https://github.com/gardener/gardener/issues/180#issuecomment-515477710, you mentioned that the ranges overlap with the gardener dashboard.  What should I change the CIDRs to or do I need to re-install KOPS with different defaults?

In an EKS cluster, the IPs of the workers and the pods will almost always overlap because the AWS VPC CNI assigns pods IPs from the VPC.  It does not use an overlay network.

**Comment by Diaphteiros** [comment]
@jicowan I think you will have to re-install kops with modified CIDRs to avoid conflicts with the dashboard defaults (they can't be changed at the moment, unfortunately).

However, the error you are seeing right now has a different reason - it's because your pod and service CIDR overlap, which shouldn't be the case.
