### ISSUE TITLE
Support for restricted environment

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/gardener#1813]
**What would you like to be added**:
When running a Gardener landscape in a restricted environment e.g. on AWS GovCloud the cluster admin kubeconfig.yaml files contain a domain which can only be resolved by a DNS from within this restricted environment.

**Why is this needed**:
The default generated kubeconfig.yaml files cannot be used neither in an automation nor with gardenctl. To be able to operate this Gardener landscape from outside, currently requires an adaptation of all generated kubeconfig.yaml files.

**Comment by danielfoehrKn** [comment]
By "A restricted environment" in this context  I suppose you mean the usage of a DNS domain that cannot be resoled from public internet such as with Route53 private hosted zones.

The shoot kubeconfig per default then contains a DNS entry that resides in the private hosted zone and cannot be used from the outside.

How to make kubeconfig usable from public internet in this case: 
- configure the Shoot to use a custom 'default domain' with a custom dns provider -> this is already configurable in the Shoot

This requires
- publicly reachable LoadBalancers  for the kube-apiserver
- **stakeholder bring their own (public) dns provider** !

 Currently the Gardener creates an external and an internal DNS domain. The shoot internal communication uses the internal domain, the shoot admin kubeconfig uses the external domain. The external domain points to the internal domain.

What we would need to change is, that the external domain also points to the LB of the api-server instead of the internal domain. 
This way the stakeholder can configure their own DNS domain that points directly to the public LB (instead as previously to the internal dns domain that is not reachable in this case).

I will prototype that change in the coming days.

**Comment by danielfoehrKn** [comment]
Adressed in PR #1994

**Comment by rfranzke** [comment]
Closing as it was fixed with #1994
