### ISSUE TITLE
Rapid changes to shoot yaml take a long time to get reconciled

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/gardener#184]
Pre-condition:

The cluster was healthy at 100 nodes.
Steps:

1. Try scaling the cluster from 100 to 150. This froze the machinedeployment because the AWS quota limits were exceeded.

1. Try to scale it down to 130. This froze the machinedeployment again because the AWS quota limits were still exceeded.

1. Try to scale it down to 100 which was within the quota limits.

Observed behaviour:

-The shoot controller loop seems to be struck at the previous reconciliation loop waiting for the machinedeployment to scale to 130.
Logs....
time="XXXXX" level=info msg="Waiting until all machines are healthy/ready (109/130 OK)..." opid=UDMppSxF shoot=XXXX

Desired behaviour:

- The previous reconciliation is aborted and a fresh reconciliation is started as the new values are already updated in the shoot yaml.

**Comment by amshuman-kr** [comment]
This is an enhancement/productivity issue. But I am not able add the labels.

**Comment by rfranzke** [comment]
Yeah, this is basically because we have a maximum wait time of 30 minutes for all machines to become ready.
So far, there is no way for the Gardener to identify that it will never succeed. https://github.com/gardener/machine-controller-manager/pull/89 will help with this, but what do you suggest to do? Gardener can only abort and restart a new reconciliation flow if the created `MachineDeployment` object exposes the needed information.

**Comment by amshuman-kr** [comment]
Agreed. This can be only addressed after MachineDeployment starts conveying the required information.

I just recorded it here. We can either close and re-open this after [PR#89](https://github.com/gardener/machine-controller-manager/pull/89) is merged or keep it open.

**Comment by rfranzke** [comment]
Sure, let's keep it open.

**Comment by amshuman-kr** [comment]
BTW, freeze label and freeze condition is already updated on the MachineDeployment. Can this be used as an indication to abort the current reconciliation if there is a new update in the queue?
