### ISSUE TITLE
Seed bootstrapping fails

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#1939]
**What happened**:
#1863 introduced a bug which causes the Seed bootstrapping to fail for a new Seed.

Bootstrapping fails on apllying the newly introduced VPA `kube-state-metrics-vpa` (see [here](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/kube-state-metrics/templates/kube-state-metrics.yaml#L47-L58)):
```
time="2020-02-14T11:10:05+01:00" level=error msg="no matches for kind \"VerticalPodAutoscaler\" in version \"autoscaling.k8s.io/v1beta2\"" seed=local-seed
```
It looks like the issue here is the order in which we apply the rendered resources (VPA created before VPA CRD is created).

**What you expected to happen**:
Seed bootstrapping to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Spin up a cluster somewhere.
2. Register it as a seed.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Duplicate of https://github.com/gardener/gardener/issues/1871?

**Comment by ialidzhikov** [comment]
Wasn't this error message present only until the vpa components are started?

**Comment by timebertt** [comment]
> Duplicate of #1871?

No, this is the actual Seed Bootstrapping that fails, not the installation of the ControllerInstallation's MR.


> Wasn't this error message present only until the vpa components are started?

The vpa components won't come up, because they are part of the same chart and the chart applier fails and returns before it can apply the vpa components...

**Comment by rfranzke** [comment]
> The vpa components won't come up, because they are part of the same chart and the chart applier fails and returns before it can apply the vpa components...

In the next reconciliation the VPA CRD is installed and then also the VPA CRs should be able to get created.

The root cause is the same like in #1871, so I suggest closing one issue.

**Comment by rfranzke** [comment]
After a deeper look it turns out that the root cause here is indeed completely different: Our Kubernetes applier returns an error if it cannot create/update a resource, causing the subsequent resources to not be considered at all. Hence, it will never succeed because the VPA CRD is coming after the VPA CR for the kube-state-metrics.

Eventually, we should switch to using the gardener-resource-manager for the seed bootstrapping (which will also allow an easy implementation for cleaning up the created resources when the seed shall be deleted/disconnected). Though, we should still fix the applier the continue with the other resources and return a combined error at the end.

**Comment by timebertt** [comment]
/assign
I will take care of the fix for the chart applier to return a combined error.
