### ISSUE TITLE
☂️-Issue for network cost optimizations across Gardener components

### ISSUE THREAD

**Issue by zanetworker** [gardener/gardener#1953]
Network cost contribute a large portion of our total costs, therefore, it makes sense to monitor and optimize networking to reflect lower costs.

The optimizations should cover a large umbrella including but not limited to:

**Seeds**
- [x] Gardenlet (https://github.com/gardener/gardener/pull/1928)
- [x] Resource Manager  (https://github.com/gardener/gardener/pull/1931, https://github.com/gardener/gardener-resource-manager/pull/40, https://github.com/gardener/gardener-resource-manager/pull/47)
- [x] Dependency Watchdog - talks to the shoots loadbalancers (https://github.com/gardener/gardener/pull/1954)
- [x] Gardener Extensions (health checks) – library imported by every extension and uses the loadbalancer for to access the shoot APIs (https://github.com/gardener/gardener-extensions/pull/602)
- [x] Shoot controlplanes
   - [x] Cloud-controller-manager?
- [x] Monitoring @wyb1
   - [x] Seed Prometheus (#1976)
   - [x] Aggregate Prometheus (#1976)
   - [x] Grafana (access to dashboard repositiories - raw.github.usercontent.com and grafana.com) (#1977)
- [x] OS Processes
   - [x] GCP  (google_accounts_daemon, google_clock_skew_daemon, google_network_daemon)
   - [x] Azure (waagent daemon) -> `/usr/share/oem/bin/waagent`
   - [x] Other providers (needs more investigation)
- [x] Image Pulls (utilize caching or p2p registeries?)

**Garden**:
- [x] Seed Kube-apiservers -> Catalog + Metrics server
- [x] Auditlog pods -> api.auditlog.sap.hana.ondemand.com (@vpnachev)
- [x] Prometheus + Garden Promentheus (@wyb1)
- [x] Seed Kube-controller-managers
- [x] Seed Cloud-controller-managers

**Possible fixes:** 

- Fix the health-checks to access the API-servers of the shoots in-cluster instead of going through the load-balancer.
- Reduce Prometheus scrape intervals, especially non-availability alert metrics.
- Grafana (can we use an offline dashboard library, do we really need access to the internet, should we block by network policies).
- Kube-proxy + other system components + cloud-controller-managers (we probably won’t be able to influence much here, can we really?).
- Processes (some can be stopped I guess, others seems to be important such as the waagent and the google_accounts_damons)

If there are other components that you think are making egress connections, please add them to the list. 

/cc @vlerenc @rfranzke @timuthy @tim-ebert @danielfoehrKn @DockToFuture @vpnachev @amshuman-kr @georgekuruvillak @wyb1 @dkistner @mliepold

**Comment by timebertt** [comment]
Would it make sense to also add some dashboards/charts on network usage by different components in addition to the proposed optimizations to gain some more observability on the topic?

@wyb1

**Comment by amshuman-kr** [comment]
> Dependency Watchdog - talks to the shoots loadbalancers) - > can we reduce the frequency?

#1954 

I am not able to update the checklist. Could someone with access do it for me?

**Comment by zanetworker** [comment]
@tim-ebert 

> Would it make sense to also add some dashboards/charts on network usage by different components in addition to the proposed optimizations to gain some more observability on the topic?

It is possible, but would require some time, so these are the quick fixes. That said, we could definitely create another issue for that.

**Comment by wyb1** [comment]
The grafana in each shoot namespace is not able to access the internet due to network policies, but the grafana in the garden namespace is able to access the internet since no networkpolicies act on it.

**Comment by vpnachev** [comment]
Regarding OS Processes, they are installed and configured by the image vendor. These daemons are recommended by the respective cloud providers for better integration. For example execution of custom-data, users sync, ssh keys sync and others. 

They should be talking only with the internal metadata service, so I believe their traffic is not charged, or at least the data volume should be relatively small.

**Comment by rfranzke** [comment]
@zanetworker can you explain more what is still open?

I guess "Image Pulls (utilize caching or p2p registeries?)" is covered by #1013 already.

What does """
 Seed Kube-apiservers -> Catalog + Metrics server
 Seed Kube-controller-managers
 Seed Cloud-controller-managers
"""

mean? What should be done?

**Comment by zanetworker** [comment]
@rfranzke These three components are more questions than they are conclusions, a better way to read them is: 
- Can something be optimised in Seed Kube-apiservers -> Catalog + Metrics server communication?
- Can something be optimised  in Seed Kube-controller-managers -> cloud-providers communication for example (volume controller?)
- Can something be optimised  in Seed Cloud-controller-managers -> cloud provider communication?

I had no ideas, so if you think the answer is no to all three then this issue can be closed since the p2p registery is already covered by another issue.

**Comment by rfranzke** [comment]
OK, understood now, thanks.

> Can something be optimised in Seed Kube-apiservers -> Catalog + Metrics server communication?

You mention this because the communication happens over VPN (= internet, in case the seed is a shooted seed)? I don't think this can be prevented/optimized, there simply is the air gap and that's the price. Is it really that much?

> Can something be optimised in Seed Kube-controller-managers -> cloud-providers communication for example (volume controller?)
> Can something be optimised in Seed Cloud-controller-managers -> cloud provider communication?

This depends on the infrastructure itself (e.g., AWS offers private links), but I don't think it's something that can be handled generally. It's more up to a specific landscape and concrete installation, or?

> I had no ideas, so if you think the answer is no to all three then this issue can be closed since the p2p registery is already covered by another issue.

OK - what do the others think? cc @vlerenc @amshuman-kr @ggaurav10 @ialidzhikov @vpnachev @timuthy @tim-ebert @wyb1

**Comment by vlerenc** [comment]
Well, do we already know what the traffic is about? I believe we don't, but finding out is probably a very difficult task, right @zanetworker?

So, is the question whether we stop here - at least for now, because we lack information what to optimise @rfranzke? Then OK, I understand. In the networking area, we have the problem with the failing probes which tear holes into our monitoring and the tunnel feature for seeds behind firewalls, which are both even more pressing.

As for the image registry @rfranzke, #1013 is about pre-loading, not an image registry like https://github.com/dragonflyoss/Dragonfly, i.e. it is only about making sure all nodes have the critical images (like ETCD) ready at all times before the nodes themselves go ready, so that after the pod is scheduled to that node, the pod can start as early as possible/without wasting even more time on image downloads (especially critical for our 1-replica ETCDs). That would, by itself, not lower, but increase network traffic. I don't think we already have somewhere a BLI on a seed-local image registry resp. P2P solution such as https://github.com/dragonflyoss/Dragonfly, do we? I can't recall anymore, if so, but I didn't see one in gardener or kube-backlog.

**Comment by timebertt** [comment]
> This depends on the infrastructure itself (e.g., AWS offers private links), but I don't think it's something that can be handled generally. It's more up to a specific landscape and concrete installation, or?

We had a discussion about whether we could use [AWS VPC interface endpoints / PrivateLinks](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html) for reducing outgoing traffic to the AWS APIs. What's the status here? cc @mliepold 
I assume, other providers offer similar techniques we could leverage.
Though, I think this would belong more in the respective provider extension repos.

**Comment by timebertt** [comment]
> > Would it make sense to also add some dashboards/charts on network usage by different components in addition to the proposed optimizations to gain some more observability on the topic?
> 
> It is possible, but would require some time, so these are the quick fixes. That said, we could definitely create another issue for that.

I think, we don't have an issue for that, yet.
I understand, that this issue is probably more about actually reducing the costs and this has rather low/no priority. But I still think it would be good to have some more network observability for sustainably improving here.
Should we open another issue for that?

**Comment by vpnachev** [comment]
> Can something be optimised in Seed Kube-apiservers -> Catalog + Metrics server communication?

For the service catalog there is some room for improvements:
1. make the service catalog controller manager to talk directly to apiserver extension instead of going through the k8s apiserver
1. upgrade the service catalog to a version that is using migrated to CRDs
1. remove the service catalog - it seems it is not required and we can do our job even better without it.

For the metrics server - we can try to move deployment from the shoot to the seed, but it might lead to even worse results, because the metrics server still needs to collect metrics from the kubelet.


> Can something be optimised in Seed Cloud-controller-managers -> cloud provider communication?

Here we can try to move the cloud-controller-manager to run inside the shoot cluster.

**Comment by rfranzke** [comment]
About the service catalog - we don't have it in the open-source project, so I guess the discussion should be moved somewhere else?

> Here we can try to move the cloud-controller-manager to run inside the shoot cluster.

I don't think we want to do this - the control plane runs in the seed by design, and CCM is part of the control plane.

**Comment by zanetworker** [comment]
> You mention this because the communication happens over VPN (= internet, in case the seed is a shooted seed)? I don't think this can be prevented/optimized, there simply is the air gap and that's the price. Is it really that much?

I guess here communication  will be improved, since we will not be initiating egress traffic if we implement the reverse tunnel approach.  Also what I meant is the service catalog talking egress to the API servers, what @vpnachev already shed light about. 

> This depends on the infrastructure itself (e.g., AWS offers private links), but I don't think it's something that can be handled generally. It's more up to a specific landscape and concrete installation, or?

True, but I guess there many things that are not handled generally, and a good place for such optimisations would be the provider extensions, the question should we expose the knobs required to configure these options or implement it as a rule of thumb for every shoot?

What we can do out of these three items, is fork them into separate issues to provide more clarity if you that would be better.

**Comment by mliepold** [comment]
> We had a discussion about whether we could use AWS VPC interface endpoints / PrivateLinks for reducing outgoing traffic to the AWS APIs. What's the status here?

In order to know if we can use these, we first need to analyse the traffic going through the NAT Gateway. For this we could activate the VPC Flow logs for dedicated NATs. The data would then be available on CloudWatch and could then be analysed together with our Network experts.

**Comment by vlerenc** [comment]
Thank you @zanetworker. Would you be OK to move the remaining tasks into the wider umbrella issue https://github.wdf.sap.corp/kubernetes/kube-backlog/issues/39 if not already listed there. Then we can close this one and keep track only in one issue. WDYT?

/cc @rfranzke

**Comment by zanetworker** [comment]
I guess since we now know the root cause of what's causing the networking costs, I can close this one and create an additional open point on your referenced issue, namely "Optimize leader-election retry-periods for extension controllers / make leader election configurable." The only concern I have is that this issue acts as a good rendezvous point for all related PRs.

**Comment by vlerenc** [comment]
OK @zanetworker, then let's close this one and if you need something else as umbrella ticket, please use the above mentioned umbrella ticket.
