### ISSUE TITLE
Seed cluster ingresses needs domain records

### ISSUE THREAD

**Issue by fsniper** [gardener/gardener#201]
When deploying shoot clusters, gardener deploys monitoring applications and creates ingresses for them:
```
$ gardener > kubectl get ing -n shoot-seed-msa-1
NAME           HOSTS                                           ADDRESS   PORTS     AGE
alertmanager   a.msa-1.seed.garden-1.az.dub.rd2.thingworx.io             80, 443   1h
grafana            g.msa-1.seed.garden-1.az.dub.rd2.thingworx.io             80, 443   1h
prometheus     p.msa-1.seed.garden-1.az.dub.rd2.thingworx.io             80, 443   1h
```

But these domains are not created, or there is no wildchar record is available.

I tried to use external-dns to create these records to no avail, because external-dns requires services, or ingresses to have external-dns.alpha.kubernetes.io/hostname= annotations, which are not available.

**Comment by rfranzke** [comment]
Thanks @fsniper for mentioning that. Currently, Gardener expects the Seed clusters to run the nginx-ingress-controller and to have a wildcard DNS record pointing to the exposed load balancer already created (https://github.com/gardener/gardener/blob/master/example/seed-azure.yaml#L14).

Your proposal is to drop that assumption, however, that would require Gardener to install the ingress controller as well as to register the wildcard DNS itself.

I agree that this would make the setup much easier and more "self-contained", but to do that we have to consider a few facts:

- The Seed cluster could have already running a nginx-controller, hence, we'd have to deploy our own with another [ingress class](https://github.com/kubernetes/ingress-nginx/blob/master/cmd/nginx/flags.go#L53).
- Do we want to create a dedicated DNS record per Ingress? I guess not, creating a record takes ~1min on AWS. We probably want to continue with a wildcard record, but then we'd have to find a domain which we can use. We could have a similar/the same `dns` section like in the [Shoot resource](https://github.com/gardener/gardener/blob/master/example/shoot-azure.yaml#L30-L32), e.g.:

```yaml
spec:
  ...
  dns:
    provider: aws-route53
    hostedZoneID: 1234
    secretName: secret-containing-credentials
    ingressDomain: *.ingress.my-seed.example.com
  ...
```

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/1284/files#r311564192 should also be considered.

**Comment by rfranzke** [comment]
/remove lifecycle/rotten

FYI: See also https://github.com/gardener/gardener/blob/master/docs/deployment/kubernetes.md, that's the current situation/requirement/contract:
> ⚠️ A current prerequisite of Kubernetes clusters that are used as seeds is to have a pre-deployed nginx-ingress-controller to make the Gardener work properly. Moreover, there should exist a DNS record *.ingress.<SEED-CLUSTER-DOMAIN> where <SEED-CLUSTER-DOMAIN> is the value of the .dns.ingressDomain field of a Seed cluster resource (or the respective Gardenlet configuration).

---

I suggest to introduce `.spec.settings.nginxIngress` to the `Seed`, similar to https://github.com/gardener/gardener/blob/master/example/50-seed.yaml#L48-L49, but disabled by default (because it requires further configuration, see below).

If enabled, the seed controller deploys the nginx-ingress controller plus our default backend (https://github.com/gardener/gardener/tree/master/charts/shoot-addons/charts/nginx-ingress) into the `garden` namespace of the seed. We should probably configure a dedicated ingress class, e.g. `nginx-gardener` [here](https://github.com/gardener/gardener/blob/master/charts/shoot-addons/charts/nginx-ingress/values.yaml#L42) to not interfere with potentially deployed other nginx ingress controller that listen for the default class `nginx`.

Also, we would need DNS configuration to automatically create a wildcard record for this nginx-ingress controller. Concretely, we require the domain name, the DNS provider, and the corresponding secret. We can design this similar to the `dns` section of the `Shoot`. Concretely the structure could look as follows:

```yaml
kind: Seed
...
spec:
  settings:
    ...
    nginxIngress:
      enabled: true
      domain: ingress.foo.example.com # out of this, a DNS record "*.ingress.foo.example.com" will be created
      provider: aws-route53
      secretName: my-aws-route53-secret
```

Similar like for shoots we can create `DNSProvider` and `DNSEntry` in the `garden` namespace for the nginx-ingress.

Please note that https://github.com/gardener/gardener/blob/master/example/50-seed.yaml#L27-L28 should not be allowed    to be used when `.spec.settings.nginxIngress.enabled=true` and vice versa. This is to not break existing cluster that run a manually deployed nginx-ingress controller. Though, one of these two options must be enabled (either `.spec.dns.ingressDomain` is provided or `.spec.settings.nginxIngress` is enabled).

In the shoot controller we simply have to switch the ingress class from `nginx` to `nginx-gardener`, e.g. [here](https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/grafana/templates/grafana-ingress.yaml#L5).
