### ISSUE TITLE
PodSecurityPolicy order is not guaranteed

### ISSUE THREAD

**Issue by zanetworker** [gardener/gardener#2052]
**What would you like to be added**:
A naming convention for PSPs that follows a lexicographic order for PSPs. 

**Why is this needed**:
As of today, we apply default PSPs (namely `gardener.priveleged` and `gardener.unprivileged`) in addition to custom PSPs for every system-component. In some cases the policy order does not apply and  `gardener.privileged` might be chosen over the custom-defined PSP for the system-component (e.g., deployed by extensions), which can produce undesired results.

**Comment by rfranzke** [comment]
cc @mvladev as you were involved in analyzing an issue last week - WDYT?

**Comment by mvladev** [comment]
> In some cases the policy order does not apply and gardener.privileged might be chosen over the custom-defined PSP for the system-component (e.g., deployed by extensions), which can produce undesired results.

This happens because the PSP for that system component doesn't match the Pod without mutation and therefore the `gardener.privileged` is chosen as it does not mutate the Pod.

Ordering for PSP (with 1 having more priority than 2):

1. no mutation happens. 
   - if multiple chosen -> lexicographic ordering
1. mutation happens. 
   - if multiple chosen -> lexicographic ordering

**Comment by zanetworker** [comment]
@mvladev AFIK mutation only happens if annotations are defined, or?  there could be a case where  other custom policies are applied that do not require pod mutation, which will result in `gardener.privelged` being chosen.

**Comment by mvladev** [comment]
> AFIK mutation only happens if annotations are defined, or?

Mutation happens always (because PSP is both mutating and validating admission controller there is a `specMutationAllowed` which is set to `true` on the mutating and `false` on the validating step). See https://github.com/kubernetes/kubernetes/blob/92ea33efc509052b208e094390a363c5dbd21b7c/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L258-L292

Here are all the fields which can be mutated in the Pod: https://github.com/kubernetes/kubernetes/blob/af0e1319c35fa143ef6dcb891d753099b6ac1e4b/pkg/security/podsecuritypolicy/provider.go#L64-L123

Also mutation to individual container securityContext https://github.com/kubernetes/kubernetes/blob/af0e1319c35fa143ef6dcb891d753099b6ac1e4b/pkg/security/podsecuritypolicy/provider.go#L125-L202

**Comment by zanetworker** [comment]
still if a custom-policy that requires no mutation is behind `gardener.privileged` in lexicographical order, `garderner.privileged` will be chosen still, and thus is not guaranteed, correct?

**Comment by mvladev** [comment]
Yes, this is correct. Custom policies should be before that.

**Comment by rfranzke** [comment]
How do we proceed here? What can we do?

**Comment by rfranzke** [comment]
ping, any ideas/concrete plans?

**Comment by mvladev** [comment]
The PSP API is [deprecated in 1.21](https://github.com/kubernetes/kubernetes/pull/97171) and scheduled for removal in v1.24.

Should we keep this issue opened?

**Comment by rfranzke** [comment]
Let's
/close
it for now as there is anyways no concrete planned follow-up action, and if they are being deprecated and removed anyways, there's probably little point in investing now.
