### ISSUE TITLE
Control plane migration: shoot specific owner ids for DNS entries

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener#2054]
**What would you like to be added**:
Gardener and dns-shoot-service should add shoot specific owner ids for their managed DNS entries and corresponding DNS owner objects to allow a smooth control plane migration.

**Why is this needed**:
Both Gardener and the dns-shoot-service manage DNS entries in the control plane of the shoot. If the control plane is moved to another seed, it must not happen, that DNS entries (or more important the corresponding DNS records in the DNS backend) are deleted during intermediate states. Even if they will be recreated later, this would result in unavailable services in the shoot.
There are two controllers generating DNS entries for the shoot: the gardenlet responsible for the API server and INGRESS DNS entries, and the dns shoot service managing entry objects for services and ingresses in the shoot.
There are several aspects to be considered:
- Only one DNS controller must be responsible for managing DNS entries for a shoot. This should already be handled by some hand-over mechanism of Gardener (see issue #1631)
- The DNS controller taking over responsibility must reconcile all DNS entries of the shoot, before it takes ownership of them. Otherwise it can happen, that it starts deleting DNS records of still unreconciled and therefor unknown DNS entry objects. As there are two controllers managing shoot related DNS entries, each needs an own owner ID.

** Suggested owner ids **
The owner id must be globally unique for each shoot and managing controller. Therefore it must contain
- the Garden ID
- the project name
- the shoot name
- the managing controller
The managing controller is needed, as the creation of the DNS owner is used as sync point after all DNS entries which must be migrated are written.

There is already a shoot id used as label key in the shoot-dns-service, which can be reused as a basis.
It has the form: `<garden-id>.gardener.cloud/<shoot-namespace>` 

It is suggested to append `/core` for Gardener and `/dns-shoot` for dns-shoot-service respectively.

**Comment by rfranzke** [comment]
Hm, I'm confused. If you would use `<garden-id>.gardener.cloud/<shoot-namespace>/<some-suffix>` as owner ID, how can you then move the responsibility for the DNS entries to a new seed? I don't see any seed identifier encoded in the owner ID.

(Just for reference, looking at what we have today, the `TXT` record with the owner ID is `seed.gardener.cloud/<garden-id>/<shoot-name>`.)

If I understand correctly, this issue is about the following things:

1. Define what the garden ID is (today, we are using the `uid` of  the `garden` namespace in the garden cluster, see https://github.com/gardener/gardener/blob/master/pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go#L226-L228)
1. Define what the seed ID is (today, we are using the `name` of the `Seed` resource)
1. Enhance the gardenlet to write the `DNSOwner` resource as part of shoot reconciliation/deletion flows
1. (Enhance the shoot-dns-service to write the `DNSOwner` resource as part of its reconciliation [though, out-of-scope of this issue, please open a separate one at https://github.com/gardener/gardener-extension-shoot-dns-service once clarified how the ID should look like])

Is this summary correct?

**Comment by mandelsoft** [comment]
It can be migrated *because* there is no seed identifier in the owner id. Therefore the actually used ids (with the seed) have to be migrated in a first step towards the new ones. But we should generally align on the various ids, otherwise it gets even more confusing. If we would have a defined shoot-id (may be including somehow project and shoot name to be meaningful for human beings) this id could also be the basis for the owner ids. Just use this id and extend the identity of the managing controller (as proposed above)

**Comment by mandelsoft** [comment]
@MartinWeindel do you know whether there is a relevant length limit for text record entries?

**Comment by MartinWeindel** [comment]
> Strings in SPF and TXT records should be no longer than 255 characters. However to get around this limitation, per RFC 4408 a TXT or SPF record is allowed to contain multiple strings, which should be concatenated together by the reading application.

**Comment by rfranzke** [comment]
> It can be migrated because there is no seed identifier in the owner id.

Can you explain more? Doesn't not encoding a seed identifier in it lead to the risk that multiple DNS providers act on the same DNS records simultaneously?

>  If we would have a defined shoot-id (may be including somehow project and shoot name to be meaningful for human beings) this id could also be the basis for the owner ids.

Do you have concrete suggestions? We have `.status.uid` and `.status.technicalID` in the `ShootStatus` at this point in time.

**Comment by mandelsoft** [comment]
If the owner id would be seed specific , then changing the seed responsibility would result in dangling DNS records, because the DNS controller on the new seed is not responsible. Even worse, if the old controller is still responsible for the owner id , the DNS record would be deleted and then later on recreated by the new controller. 
To avoid this the DNS entries need a stable owner id that is bound to the shoot, not to the seed implementing the control plane of the shoot. This allows for a seamless migration of the responsibility.

To avoid a parallel responsibility, the owner object for the shoot on the old seed must be deleted before it is created on the new seed. In case of a regular migration this is ensured by the migration mechanism. In case of a fail-over scenario, we discussed (in Sofia), a lease mechanism with a dedicated timeout can solve the problem. So, if the lease is not renewed, the controller keeps its fingers off those entries.
This mechanism still has to be implemented, but you mentioned, that the fail-over is not in the scope yet.

**Comment by rfranzke** [comment]
OK, thanks for clarifying, makes perfect sense.
Let's go back to the concrete problem solution: You suggested `<garden-id>.gardener.cloud/<shoot-namespace>` as ID - the easiest would be to simply keep what we have today: `<garden-id>=<uid-of-garden-namespace>`. Or do you suggest something else? You also mentioned that the garden ID should be added to the `extensions.gardener.cloud/v1alpha1.Cluster` resource. How would that look like?

**Comment by mandelsoft** [comment]
For the garden identity we've used so far the UID of the garden namespace in the virtual garden cluster. This seems to be ok. The seed identity is not handled uniformly today. may be the seed name plus the UID of the seed object plus the garden id should be incorporated. To avoid long names, it could be calculated, for example the hash over the string `<gardenid>-<seed object UID>` prefixed bay the seed name.

The same is valid for the shoot, it should incorporate the gardenid and the UID of the shoot object. This assures that new shoots with the same name get a new id. Again the hash over the string `<gardenid>-<shoot object id>` prefixed by the shoot name and project can be used.

The prefix is always optional, because it is just for human readability, if the id is too long for a dedicated purpose.

These ids should always be properties in the cluster info object on the seed.

In general it would be very helpful if we could generally offer an info object in the `kube-system` namespace, that provides the identity of a cluster. For shoot clusters that could always be the shoot id. For soils we could fake this object by choosing a unique id based on the `kube-system` namespace object. It could always be provisioned by the seed controller, it there is not yet an info object (form the shoot creation).

This object could just be a config map `cluster-identity`, that hosts a mandatory and other optional properties:
| Property|Realm|Meaning|
|:---|:---:|:---|
|`cluster-id`|always|Id of the cluster. For shoot clusters this is the shoot id, for others it could be an id based on the UID of the `kube-system`namespace|
|`shoot-id` or `shoot.gardener.cloud`|shoot|the shoot id|
|`shoot-seed-id` or `seed.shoot.gardener.cloud` |shoot|the id of the managing seed|
| `shoot-garden-id` or `garden.shoot.gardener.cloud`|shoot|the id of the garden the shoot is maintained by|
|`seed-id-<gardenid>` or `seed.<gardenid>.gardener.cloud`|seed|the id of the seed for a dedicated garden if the cluster is used as seed for this garden|

Controller just requiring a cluster id always only read the `cluster-id` property. This feature is independent of the gardener environment. So the DNS/Cert controller environment could fall back for its multi cluster support to read these ids instead of requiring manual consistent settings on the command line. 
Gardener-aware controller could also evaluate the gardener-specific properties.

This cluster id can then be the basis for the owner ids for the DNS environment. For example: `shoot.gardener.cloud/<shoot-id>` or better refined for the two managament realms `core.gardener.cloud/<shoot-id>` and  `shoot.gardener.cloud/<shoot-id>`.

/cc @timuthy

**Comment by rfranzke** [comment]
Okay, what do you think about proceeding concretely as follows:

1. Garden ID = `garden-hash(uid of garden namespace in garden cluster)[:10]`, e.g. `garden-a1b2c3d4e5`
1. Seed ID = `seed-hash(gardenID + uid of seed object)[:10]`, e.g. `seed-u7i8o3j765a`
1. Shoot ID = `shoot-hash(gardenID + uid of shoot object)[:10]`, e.g. `shoot-j8nbf7a4e2`
1. Enhancing the `extensions.gardener.cloud/v1alpha1.Cluster` resource as follows:
```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
spec:
  shoot: ..
  seed: ..
  cloudProfile:
  project:
    <project-spec-without-members/owners>
  identities:
    garden: <gardenID>
    seed: <seedID>
    shoot: <shootID>
```
5. Ideally, the `Seed` and the `Shoot` object get to know about their IDs in the status as well:
  a. `core.gardener.cloud/v1beta1.Seed.Status.ID=<seedID>`
  b. `core.gardener.cloud/v1beta1.Shoot.Status.ID=<shootID>` (today, we have also `uid` (should be deprecated, probably), and `technicalID` (which is the shoot namespace, maybe it should be renamed to `namespace`?)

> In general it would be very helpful if we could generally offer an info object in the kube-system namespace, that provides the identity of a cluster. 

We already have a `shoot-info` configmap in the `kube-system` namespace of every shoot, e.g.:

```yaml
apiVersion: v1
data:
  domain: my-domain.com
  extensions: shoot-cert-service,shoot-dns-service
  kubernetesVersion: 1.12.10
  maintenanceBegin: 000000+0100
  maintenanceEnd: 010000+0100
  nodeNetwork: 10.222.0.0/16
  podNetwork: 10.223.128.0/17
  projectName: my-project
  provider: aws
  region: eu-west-1
  serviceNetwork: 10.223.0.0/17
  shootName: my-shoot
kind: ConfigMap
metadata:
  name: shoot-info
  namespace: kube-system
```

It could be enhanced with `gardenID`, `seedID`, and `shootID` fields as well.

> cluster-id ,always , Id of the cluster. For shoot clusters this is the shoot id, for others it could be an id based on the UID of the kube-system namespace
> Controller just requiring a cluster id always only read the cluster-id property. This feature is independent of the gardener environment. So the DNS/Cert controller environment could fall back for its multi cluster support to read these ids instead of requiring manual consistent settings on the command line.
> seed-id-<gardenid> , seed , the id of the seed for a dedicated garden if the cluster is used as seed for this garden

This means, that you are proposing a `seed-info` configmap in the `kube-system` namespace in every seed as well, correct? However, can't these two be combined? And, instead of using the `uid` of the `kube-system` namespace, can't we use the `uid` of the `Seed` object again as cluster ID?

```yaml
apiVersion: v1
data:
  gardenID: <gardenID>
  seedID: <shootID (if the seed is a shoot as well), or uid of `Seed` object>  
kind: ConfigMap
metadata:
  name: seed-info
  namespace: kube-system
```

WDYT?

**Comment by timuthy** [comment]
> Garden ID = garden-hash(uid of garden namespace in garden cluster)[:10], e.g. garden-a1b2c3d4e5
Seed ID = seed-hash(gardenID + uid of seed object)[:10], e.g. seed-u7i8o3j765a
Shoot ID = shoot-hash(gardenID + uid of shoot object)[:10], e.g. shoot-j8nbf7a4e2

Can we also just take the UID of the object we refer to in each ID, i.e. `Shoot ID = shoot-<uid of shoot object>`?
Kubernetes follows the `ISO/IEC 9834-8` which says:
> ISO/IEC 9834-8:2008 specifies the format and generation rules that enable users to produce128-bit identifiers that are either guaranteed to be globally unique, or are globally unique with a high probability.

**Comment by mandelsoft** [comment]
I would prefer to not tightly bind the DNS eco-system to the gardener infrastructure. Therefore I proposed a more general config. map not necessarily bound to a shoot  or seed. Therefore the name `cluster-identities`. It should always contain a cluster id and can be enriched by any other kind of id as described above.

It also allows to handle combined shoot/seed clusters or even seeds for multiple gardens (if we want to support this some day). Fixed names like `shoot-info` or `seed-info` are not really suitable here.

Fore sure, additionally there may be any other kinds of info objects, that are specific to dedicated environments.

@timuthy Rafael mentioned a potential length limitation in various consuming environments. May be this is the reason for the shortened form.

**Comment by MartinWeindel** [comment]
Is it really a good idea to introduce a new gardenID? It would also be helpful to provide readable  IDs for seeds and shoots, e.g seed-aws-u7i8o3j765a and shoot--core--foobar--j8nbf7a4e2.

BTW, what do you think about introducing a singleton garden object which has a name (the landscape name) and maybe some other global attributes?
For existing landscapes, the id of the garden namespace will be used. For new gardens, we
can switch to the scheme garden-name-<random()[:10]>, e.g. garden-dev-r5i3t3j265h
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Garden
metadata:
  name: mylandscape
spec:
  id: <uuid>
```

**Comment by rfranzke** [comment]
> Can we also just take the UID of the object we refer to in each ID, i.e. Shoot ID = shoot-<uid of shoot object>?

Hm, yes, we should simply put the UID there. If users think it's too long they can cut themselves/hash again.

> I would prefer to not tightly bind the DNS eco-system to the gardener infrastructure. 

I don't see any connection between DNS and Gardener. This issue is about introducing IDs for the various layers, Garden, Seed, Shoot. Whether DNS controller use it or not is not related (yes, this was the trigger for this discussion, though, the solution is general).

> Therefore the name cluster-identities. It should always contain a cluster id and can be enriched by any other kind of id as described above.

Your proposal from above also contains `seed`, `shoot` etc. I'm confused now... :( Maybe you can write down your concrete proposal how the IDs would look like in their config maps?

----

@MartinWeindel 

> Is it really a good idea to introduce a new gardenID? It would also be helpful to provide readable IDs for seeds and shoots, e.g seed-aws-u7i8o3j765a and shoot--core--foobar--j8nbf7a4e2.

Yes, makes sense, it's definitely helpful for operators and end-users if the Garden has a human readable name. Maybe a combination of both, the operator-provided name plus the UID of the `garden` namespace in the garden cluster?

> BTW, what do you think about introducing a singleton garden object which has a name (the landscape name) and maybe some other global attributes?

IMO a `Garden` object is the wrong way to model this. This purports the possibility that it is possible to create multiple `Garden` resources in the  same garden landscape which definitely is not possible. Instead, it should be similar to the internal domain: If you provide it it's immutable unless you delete everything (only then you can change the domain). Similarly, the Garden ID can be provided and then never be changed unless all seeds/shoots are deleted. Today, the internal domain is stored in a configmap, no need for a dedicated object.

**Comment by mandelsoft** [comment]
> Your proposal from above also contains seed, shoot etc. I'm confused now... :( Maybe you can write down your concrete proposal how the IDs would look like in their config maps?

As I already explained twice, it is a general object that has mandatory and scenario based identity fields. it *always* has (independently of the gardener) a `cluster-id` field. It basically can be provided in any way and scenario. For gardener clusters it is maintained by the gardener, it uses the shoot id, if the cluster is a shoot. It can only be a shoot of one garden, therefore it is uniquely defined, even for seeds that are shoots (as described it always uses the shoot id). For non-shooted clusters in the gardener ecosystem (soils), the gardener (seed reconciler/gardenlet) defines the cluster-id (as explained it could be based on the uid of the kube-system namespace).
This general field can be consumed by any party just requiring a unique cluster identity.

*Additionally* scenario specific fields could be added, best in a qualified manner, for example `shoot.gardener.cloud` instead of just `shoot-id` and `seed.shoot.gardener.cloud` and `seed.<gardenid>.gardener.cloud`. This file is therefore modified by multiple controllers, but different properties.

This is independend of the way we decide to generate ids in the garden scenario.
TBO, I would also prefer more human readable ids, but I see the problem with the length.

**Comment by rfranzke** [comment]
> For non-shooted clusters in the gardener ecosystem (soils)

There is no such terminology in the Gardener API. We have `Seed` and `Shoot` resources, that's it. So let's stick to those, please. What you mean is a cluster that will end-up as a `Seed` object as well. It doesn't/shouldn't matter where it is coming from (whether it was created as shoot or is coming from somewhere else).
Why should we take the UID of the `kube-system` namespace instead of the UID of the corresponding `Seed` object?

> TBO, I would also prefer more human readable ids, but I see the problem with the length.

The IDs generated by Gardener should be human-readable, I guess. What a controller concretely does with them is up to it. If it uses the IDs in an environment with length restrictions then it has to cut them accordingly. We shouldn't care.

Still, I don't understand how you envision this should look like in the system. Can you please outline a **concrete** configmap example for both `Seed` and `Shoot` clusters? What shall Gardener generate?

**Comment by mandelsoft** [comment]
> There is no such terminology in the Gardener API. We have Seed and Shoot resources, that's it.

Sure we have soil clusters, that are no shoots, they do not have a cluster Id defined by their shoot identity. Therefore the cluster identity must be something else. We have two possibilities:
- use the seed identity (taken from the garden cluster), but this would be inconsistent with the shooted seeds, here the shoot-id will be used as cluster id. Another problem would be the potential possibility to use a cluster as seed for multiple gardens. Therefore the seed id would be not a good idea.
- use something else, like the uid of the cluster's kube-system namespace. Because the soil (per definition) is used as seed, the controller installing the cluster as seed, should set this cluster-id, if it is not yet set (for example: manually, or by the usage of the cluster by another garden). If it is used by another garden, also, the rule to create the cluster-id is the same, or, because the uid of the kube-system namespace is used, it is always guaranteed to be unique.

The example for such a `cluster-id` config map in `kube-system` is in the [table above]( https://github.com/gardener/gardener/issues/2054#issuecomment-600200704), I've just added qualified names that are better than just flat names.

**Comment by timuthy** [comment]
Meeting with @mandelsoft @MartinWeindel  and @rfranzke with the following result:

1. Garden Cluster:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-identity
  namespace: kube-system
data:
  cluster-identity: <landscape-name>-<uid-garden-namespace> # landscape-name is an immutable name for the garden landscape that is assigned by the garden operator
```
2. Seed Cluster:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-identity
  namespace: kube-system
data:
  cluster-identity: <uid-kube-system-namespace>
```
3. Shoot Cluster:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-identity
  namespace: kube-system
data:
  cluster-identity: <shoot.namespace>-<shoot-uid>-<garden-cluster-identity> # garden-cluster-id from 1. Garden Cluster
```

Each `ConfigMap` is created by Gardener. If a seed is a shoot at the same time, the cluster already has a `cluster-identity` and thus won't get another id during the seed registration.

Todo:
- [ ] Implement possibility to configure a <landscape-name> (see 1.)
- [ ] Implement ConfigMap creation through Gardener
- [ ] Add shoot cluster-id (see 3.) to the shoot status

**Comment by mvladev** [comment]
In gardener there is no concept for `landscape-name` or landscape at all.
I'll would like to have those references removed.

**Comment by swilen-iwanow** [comment]
We decided to remove the `landscape-name` and leave this to the Gardener operator/admin to decide what unique identifier to use.
