### ISSUE TITLE
Enable ScheduleDaemonSetPods feature gate for 1.11 shoots

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2076]
**What happened**:
For < 1.12 shoot clusters the daemon set pods are not scheduled by the kube-scheduler but by the kube-controller-manager. This can lead to situations where pods with a high priority cannot be started properly.

**What you expected to happen**:
(Daemon set) Pods with high priority can be properly scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a 1.11 cluster
1. Deploy pods into it that request almost all resources
1. Try to deploy a daemon set with `system-cluster-critical` priority class

**How fix it**:
Since 1.11, Kubernetes has introduced a `ScheduleDaemonSetPods` feature gate that makes the kube-scheduler schedule the pods instead of the KCM. This fixes the above mentioned problem.
The feature gate is enabled by default beginning with Kubernetes v1.12.
Let's add the feature gate to both the kube-controller-manager and kube-scheduler configuration by default for 1.11 clusters.

**Environment**:

- Gardener version: v1.1.5
- Kubernetes version (use `kubectl version`): v1.11.10
- Cloud provider or hardware configuration: AWS

**Comment by zanetworker** [comment]
For 1.10 and 1.11 clusters enabling this feature-gate won't help much as the kube-scheduler takes node readiness into consideration and fails to schedule Networking pods (e.g., Calico) which will result in a broken setup due to FailedPlacement. As a result, **we recommend upgrading to higher versions of kubernetes (> v1.11) for clusters with these issues where the feature-gate is enabled by default.**
