### ISSUE TITLE
Gardener Controller Manager should not delete ControllerInstallation right away

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2218]
**What happened**:

When removing the Containerruntime support for a Shoot, the GCM determined that the gVisor extension is not required any more (only Shoot using ContainerRuntimes).
The gVisor extension is removed immediately.

The reconcile of the Shoot fails, because the ContainerRuntime will never be reconciled/ deleted.
**What you expected to happen**:
The GCM waits for the Shoot to be reconciled successfully before removing the ControllerInstallation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with gVisor as a Container Runtime
2. Make sure it is the only Shoot having gVisor enabled.
3. Delete gVisor for the worker pool.
4. Observe the ControllerInstallation for extension-gvisor is deleted right away
5. Observe that the Shoot reconcile does not complete
![image](https://user-images.githubusercontent.com/33809186/80002283-b9db5300-84bf-11ea-9214-efe20eed8d0d.png)

**Anything else we need to know?**:
Even though I first encountered that behaviour using the gVisor ControllerRegistration, it is not specific to it.  A general solution is needed.

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
Yes, that's a good finding... thanks for opening the issue. As the computation which extensions are required are done by the GCM that does not necessarily have access to the seed clusters (otherwise, it could simply look into them to see which extension resource kind/types are still pending), one solution would be to store the list of required extensions in the shoot status after a successful reconciliation operation. The `computeRequiredExtensions` function would not only take the `spec` of shoots into account but also this list in the status. I don't like it too much, but I don't have a better idea right now.

**Comment by timebertt** [comment]
Nice catch, @danielfoehrKn!

I also don't like the Shoot status field with the required extensions too much.
What if we rather let the gardenlet write a new condition to the `ControllerInstallation`s status, stating if there are still any resources of the respective kind/types in the Seed and take this condition into account when gcm computes the required extensions?

**Comment by rfranzke** [comment]
Nice idea, sounds promising.
