### ISSUE TITLE
Healthcheck controller stops tracking CR after hibernation

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2241]
**What happened**:
With the improvement gardenlet to detect outdated healthcheck conditions (ref #2197) we noticed that after hibernation the healthcheck actuator do no longer requeue the extension CR.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot

2. Hibernate the Shoot.

3. Wake up the Shoot.

4. Ensure that the extension CR conditions will be outdated. For example the Worker CR:
```
$ k -n shoot--foo--bar get worker baz -o yaml

  status:
    conditions:
    - lastTransitionTime: "2020-04-28T00:29:03Z"
      lastUpdateTime: "2020-04-28T00:29:03Z"
      message: Shoot is hibernated
      reason: HealthCheckSuccessful
      status: "True"
      type: SystemComponentsHealthy
    - lastTransitionTime: "2020-04-28T00:29:02Z"
      lastUpdateTime: "2020-04-28T00:29:02Z"
      message: Shoot is hibernated
      reason: HealthCheckSuccessful
      status: "True"
      type: EveryNodeReady
    - lastTransitionTime: "2020-04-28T00:29:02Z"
      lastUpdateTime: "2020-04-28T00:29:02Z"
      message: Shoot is hibernated
      reason: HealthCheckSuccessful
      status: "True"
      type: ControlPlaneHealthy
    lastOperation:
      description: Successfully reconciled worker
      lastUpdateTime: "2020-04-28T06:15:37Z"
      progress: 100
      state: Succeeded
      type: Reconcile
```
**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by danielfoehrKn** [comment]
Tracking [this discussion](https://github.com/gardener/gardener/pull/2249#discussion_r417142588).

The Healthcheck library should start with health checks as soon as the Shoot has fully woken up (shoot.Status.isHibernated == false) from hibernation. 
However the gardenlet does not yet update the Cluster resource in the Seed after each reconciliation (see this [PR](https://github.com/gardener/gardener/pull/2217)) - so the extension controllers might not observe that status change and do not start the health checks again.
In order to prevent that / be backwards compatible, the health checks start as soon as the Shoot.Spec.Hibernation.enabled == false.

TODO / in the future, this code could be added [here in the code](https://github.com/gardener/gardener/blob/f994d6e816e015ff66e59165009a60ba77bc2cbd/extensions/pkg/controller/healthcheck/reconciler.go#L134-L133)
```
if cluster.Shoot.Status.IsHibernated {
		r.logger.Info("Do not perform HealthCheck for extension resource. Shoot is waking up.", "name", acc.GetName(), "namespace", acc.GetNamespace(), "kind", acc.GetObjectKind().GroupVersionKind().Kind)
		return reconcile.Result{}, nil
	}
```

@rfranzke  when could we get rid of the backwards compatibility?  When the Gardener + Extensions using the new gardener version are released?

**Comment by rfranzke** [comment]
Hm, probably we have to wait a little longer as this is not a code-wise dependency but a deployment dependency. I guess a few weeks/months we have to keep it.
