### ISSUE TITLE
Increase kube-apiserver replicas and add anti-affinity

### ISSUE THREAD

**Issue by dansible** [gardener/gardener#2294]
**What would you like to be added**:
Increase the default number of replicas for the API server deployment to 3 and add anti-affinity rules for the apiserver pods such that they are each running on a different node

**Why is this needed**:
If the node where the apiserver is running is not working, this causes access to the apiserver for the shoot to go down

**Comment by rfranzke** [comment]
As we only have one etcd replica it doesn't help too much to scale the kube-apiserver for availability reasons. There was #423 where the same was discussed, but it was closed: https://github.com/gardener/gardener/issues/423#issuecomment-614095899

/cc @vlerenc

**Comment by dansible** [comment]
Cool! Was there a reason why the other issue was closed? 

This issue came up this morning where a seed had 2 nodes down and those two nodes were hosting the API servers for 8 shoots, which all started alerting that the API was down. In this case the node issues resolved after 15-20 minutes and the API servers came back up. 

It seems like this issue could easily be resolved by increasing the replica count for the API server (and the ETCD) and adding anti-affinity rules to ensure each replica is running on a different node. A PDB would also be great!

**Comment by rfranzke** [comment]
Well, before we decide for the latter (which will definitely increase resource consumption, costs) it would be more interesting to get to know why it took 15-20 minutes to resolve. Shouldn't this be way faster? Can you explain more about the "2 nodes down" situation? What was happening exactly and why was it resolving after some time, and especially, why weren't the API server moved to healthy nodes in the meantime?

**Comment by timebertt** [comment]
While I further investigated, I discovered, that both the nodes were rebooted due to a OS update:
```
/ # last -x
reboot   system boot  4.19.106-coreos  Wed May  6 07:33   still running
reboot   system boot  4.19.86-coreos   Wed Apr  1 11:51   still running
wtmp begins Wed Apr  1 11:51:30 2020
```

I assume, this was triggered by the CoreOS auto-update and is probably fixed by https://github.com/gardener/gardener-extension-os-coreos/pull/10

**Comment by rfranzke** [comment]
... 🤨 do you have logs of the update-engine unit? It should have been disabled and not running at all.

**Comment by timebertt** [comment]
The Shoot API downtime was probably caused by downtime of `etcd` which was running on one of the Nodes that got rebooted. I can confirm so for one of the instances:
<img width="925" alt="Screen Shot 2020-05-07 at 07 54 10" src="https://user-images.githubusercontent.com/46341950/81259456-477a7f00-9038-11ea-91f7-fb1eaf3c4760.png">

Looking at the StatefulSet dashboard, it shows me, that `etcd-main` took about 12min to get healthy again.

**Comment by timebertt** [comment]
> ... 🤨 do you have logs of the update-engine unit? It should have been disabled and not running at all.

Hmm, interesting. The logs don't show any output. 🤔 
What could have triggered the OS update then if not the `update-engine`?

```
/ # last -x
reboot   system boot  4.19.106-coreos  Wed May  6 07:33   still running
reboot   system boot  4.19.86-coreos   Wed Apr  1 11:51   still running

wtmp begins Wed Apr  1 11:51:30 2020
/ # systemctl status update-engine
● update-engine.service
   Loaded: masked (Reason: Unit update-engine.service is masked.)
   Active: inactive (dead)
/ # journalctl -u update-engine
-- Logs begin at Fri 2020-04-24 01:59:48 UTC, end at Thu 2020-05-07 06:02:09 UTC. --
-- No entries --
```

**Comment by rfranzke** [comment]
Hm, what about the kubelet-Monitor unit?

**Comment by timebertt** [comment]
```
/ # journalctl -u kubelet-monitor --since "2020-05-03"
-- Logs begin at Fri 2020-04-24 01:59:48 UTC, end at Thu 2020-05-07 06:56:04 UTC. --
May 06 07:34:36 systemd[1]: Starting Kubelet-monitor daemon...
May 06 07:34:39 systemd[1]: Started Kubelet-monitor daemon.
May 06 07:34:39 health-monitor[3166]: Start kubernetes health monitoring for kubelet
May 06 07:34:39 health-monitor[3166]: Wait for 2 minutes for kubelet to be functional
```

**Comment by vlerenc** [comment]
> Increase the default number of replicas for the API server deployment to 3

This was an early design decision @dansible right from the start (3y). Rational was that since pods restart fast, we don't run many replicas (unless necessary for load balancing).

The far larger "problem" is, as @rfranzke pointed out, the single-replica ETCD. 2y ago we had the CoreOS ETCD controller, but it was rubbish, so we had to take it out and since a.) ETCD is anyways a singleton incapable of load-balancing and b.) ETCD replication is wasteful and causes a lot of trouble, we don't have it anymore. Since we use pods, also ETCD starts "relatively" fast and since we have PVs and continuous backups for disaster recovery which is even stronger, we run with this since then.

That said, we do work on a controller for ETCD, called ETCD druid, our own. It will enable clustered ETCDs (and more, specific to Gardener), but it will take a few more months. It was never high on the priority list, since it's rarely a practical issue. I know that it may appear "wrong", but believe me that we made this decision on the grounds of practical experience and in the context of our setup with seeds and continuous backups. We also had a similar conversation with Google 1.5y ago. They too have a similar setup and had only that for the first years: zonal clusters (before regional ones were introduced) with 1 API server and 1 ETCD. They too complained about ETCD's replication. In the end they added regional clusters, as you request as well, but mostly to comply with checkbox lists, not because it was really all that necessary. It drives costs and since regional clusters are so easily accessible nowadays and people have learned the difference (the default is always zonal), I guess they are more heavily used and that will have been part of the pricing decision for GKE as of lately. If we run 3 replicas with the massive cache demand of an API server, our costs would increase, too. However, we plan to change the minReplicas for productive labeled clusters to 2. That's something we do plan to do (cc @amshuman-kr  @ggaurav10).

> Add anti-affinity rules for the apiserver pods such that they are each running on a different node

Yes, that is something we have said years ago, but not yet done. 😉

> If the node where the apiserver is running is not working, this causes access to the apiserver for the shoot to go down

As said, the downtime should be seconds. Since you have noticed a problem and have opened a ticket, I must assume, more was wrong here. If the node is "broken", it should be taken out and the pods should be rescheduled. However, even if the kubelet fails to call back home, liveliness/readiness will get stale, but that will only trigger restarts (that may or may not fail), but no rescheduling, so that may be the problem and we should get better.

> This issue came up this morning where a seed had 2 nodes down and those two nodes were hosting the API servers for 8 shoots, which all started alerting that the API was down. In this case the node issues resolved after 15-20 minutes and the API servers came back up.

Yes, that's the default timeout, 20m I believe (cc @prashanth26 @hardikdr). So there is something to be improved, maybe based on or similar to the dependency-watchdog (cc @amshuman-kr @georgekuruvillak). Thanks!

> A PDB would also be great!

Yes, I agree. When we have >1 replicas, we should have a PDB=1. That was discussed, but never implemented together with the anti-affinity topic. Thanks for reminding us so painfully. 😉

**Comment by rfranzke** [comment]
@tim-ebert Then I have no idea what might have restarted the node, unfortunately. :( Anybody else maybe?

> Yes, I agree. When we have >1 replicas, we should have a PDB=1. That was discussed, but never implemented together with the anti-affinity topic. Thanks for reminding us so painfully. 😉

Gardener cannot create this PDB. Probably it needs to be done by HVPA because only it knows when the kube-apiserver is scaled.

**Comment by vlerenc** [comment]
It can always be 1 even with one API server, because that's anyways the outcome without. No need for complexity. ;-)

**Comment by rfranzke** [comment]
Do you suggest `maxUnavailable=1`? Isn't this exactly the problem like with the istio default configuration that is blocking our node draining processes because MCM cannot evict it due to this PDB (as it runs as singleton)?

**Comment by vlerenc** [comment]
No, Istio has `maxUnavailable=0`. I suggest 1.

**Comment by rfranzke** [comment]
Thanks 👍

**Comment by vlerenc** [comment]
Great, then let's summarise the plan:
- Gardener instructs HPVA to use 2 min replicas for `productive` clusters, otherwise 1 min replica
- Node-level Anti-Affinity
- PDB=1

We still need to think about the case where the API server sits on a dead node or continuously fails to start. If we consider a dead node a node that is `NotReady`, it may be premature to relocate the pod, but then again, why not? Was the node `NotReady` @dansible? `NotReady` has a grace period, so if it's not ready, then it's bad and the KCM will have deregistered the node already from the LB, so its broken anyways. Of course, if it heals in the next seconds, all is good again. That sounds unlikely, though. If it fails in our (highly automated) case, it's usually broken. The whole `NotReady` stuff is predominantly in for manual clusters where people break and repair stuff. That is not the case with us, so it would only help with temporary flaky networking/infrastructure and that's unlikely, so I think it's best to reschedule the pod proactively than letting it rot for 20m.

The other topic is the restart. Do you have ideas what happened @tim-ebert?

**Comment by wyb1** [comment]
>Was the node NotReady?

I checked the seed during the outage and all nodes were `Ready`. To make sure I checked the monitoring data and all nodes were `Ready` during that time.

**Comment by timebertt** [comment]
> The other topic is the restart. Do you have ideas what happened @tim-ebert @vpnachev @marwinski?

No, I have run out of ideas, what triggered the reboot/OS update.

**Comment by vlerenc** [comment]
OK, thanks @wyb1. Does someone know or have an idea why ETCD took 12m? The reattach of the volume? Any particular issue here? Are volume operations "as fast as usual"?

**Comment by rfranzke** [comment]
@wyb1 we just looked into the node with @tim-ebert and saw that the kubelet was down for ~5min. Hence, the node must have been `NotReady`, right? As for the recovery time, though, it's unclear why it took so long to get all the pods up and running again.

**Comment by timebertt** [comment]
The kubelet logs indicate, that the kubelet at least was not running for about 6m:
```
May 06 07:27:38 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w kubelet[16203]: I0506 07:27:38.852497   16203 container_manager_linux.go:457] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker.service
-- Reboot --
May 06 07:33:47 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w systemd[1]: Starting kubelet daemon...
May 06 07:33:48 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w systemd[1]: kubelet.service: Current command vanished from the unit file, execution of the command list won't be resumed.
May 06 07:34:36 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w systemd[1]: Started kubelet daemon.
May 06 07:34:36 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w kubelet[2821]: I0506 07:34:36.507453    2821 flags.go:33] FLAG: --address="0.0.0.0"
```

It sent the `NodeReady` event pretty fast after that:
```
May 06 07:35:12 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w kubelet[2821]: I0506 07:35:12.477142    2821 kubelet.go:1933] SyncLoop (PLEG): "dependency-watchdog-endpoint-65f99687f6-b4k8c_garden(9216ca43-8242-47c1-b115-5f76dbe8044d)",May 06 07:34:37 shoot--garden--az-eu1-cpu-worker-77f954f956-x486w kubelet[2821]: I0506 07:34:37.332402    2821 kubelet_node_status.go:471] Recording NodeReady event message for node shoot--garden--az-eu1-cpu-worker-77f954f956-x486w
```

Then it had some trouble verifying the attached etcd volume (a lot of error messages like this):
```
Volume has not been added to the list of VolumesInUse in the node's volume status for volume
```

**Comment by wyb1** [comment]
The `NotReady` condition must have never reached Prometheus. I just checked again and the only thing I see is that one of the nodes' conditions was `unknown`.
<img width="735" alt="Screen Shot 2020-05-07 at 11 56 41" src="https://user-images.githubusercontent.com/8710621/81281212-d350d300-9059-11ea-867f-37baaa67b40e.png">

How long was kubelet posting its `NotReady` condition? Perhaps due to the scrape interval it was missed by Prometheus.

**Comment by rfranzke** [comment]
`Unknown` makes sense - the kubelet was down and the KCM set it to `Unknown`.

**Comment by kayrus** [comment]
This may be related to https://github.com/gardener/gardener-extension-os-coreos/pull/10. I wonder in which cgroup context the https://github.com/gardener/gardener/blob/master/charts/shoot-cloud-config/templates/scripts/_cloud-config-script.sh#L93 script is executed. If it is executed inside the container, then systemd dbus is not available and unit "stop" commands cannot be executed.
