### ISSUE TITLE
Add management for DNSOwners and DNSEntries during Shoot reconciliation, migration and restoration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#2335]
**What would you like to be added**:
The normal shoot reconciliation flow should deploy `DNSOwner` objects together with `DNSEntries` and `DNSProviders` and set the `DNSEntry.spec.ownerId` to the `ownerID` field of the `DNSOwner`. The `ownerID` is specific for the shoot cluster and should not depend on the name of the `Seed`.
`DNSOwners`, `DNSEntries` and `DNSPRoviders` are CRs managed by the dns extension controller.

The shoot migration step of the Control Plane Migration should delete these resources in the following order:
1. `DNSOwner`
2. `DNSProvider`
3. `DNSEntries`

The shoot restoration phase of the Control Plane Migration should create these resources in the following order:
1. `DNSEntries`
2. `DNSProvider`
3. `DNSOwner`

**Why is this needed**:
Today `gardenlet` manages and creates the `DNSEntries` and `DNSProvider` required for the `Shoot`'s APIServer. Once the `DNSEntries` are reconciled a dns record is created which will have the `Seed`'s name as its owner id. Once a Shoot is migrated to a new seed, the dns extension controller will try to reconcile the `DNSEntries` on the new seed which will fail since it will try to overwrite the record's owner id to the name of the new `Seed`.  To avoid this error and having to recreate the dns records we need to make use of additional `DNSOwner` objects

**How to categorize this issue?**

/area control-plane-migration
/kind enhancement
/priority normal

**Comment by rfranzke** [comment]
cc @vlerenc - can we allow members of the `core` team to use this command?

**Comment by vlerenc** [comment]
Hmm... we can do whatever we want @rfranzke. It's our code, but I would like to avoid certain hard-coded behaviour, like hard-coding the `core` team anywhere.

Let's take a look at https://github.tools.sap/kubernetes/kube-docs/wiki/GitHub-Bots#commands:
* add/remove label: some white-listed labels all, the rest of the labels only maintainers 
* set/unset milestones: only maintainers
* close/reopen: author (???) and maintainers
* hold/unhold: only maintainers
* assign/unassign: commenter for him-/herself (???) and otherwise only maintainers for anybody
* cc/uncc: only maintainers

Should I allow the ??? ?

**Comment by rfranzke** [comment]
Yes, that would be great, thank you! :)
