### ISSUE TITLE
out-source secret creation to prevent unpredictable cpu spikes in gardenlet

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#2368]
**How to categorize this issue?**
/area robustness
/area monitoring
/area operations
/kind bug
/priority normal

**What happened**:
We see alerts that the gardenlet condition flaps, caused by the gardenlet losing leader election.

**Comment by vlerenc** [comment]
It seems, VPA is too sluggish, but since VPA has many global knobs, we have difficulties configuring it properly for this use case. Here what @vpnachev reported:

> The leader election is an issue on staging because most of the time there is no shoots, thus gardenlet is idling and vpa reduce the limits to minimum. When the landscape is released or some other tests are started, this creates a lot of clusters all of a sudden. Unfortunately, secret generation is a costly operation and multiplied by the number of shoots is almost a disaster. The gardenlet pod is throthelled on cpu thus it fails to renew the leader election leading to a failure.
This morning we had ~120 aws shoots that were waiting their secrets to be generated, but gardenlet was in crashloopbackoff so VPA was seeing no resource usage and kept its requests and limits low. This was a dead lock. I've manually bumped the limits and the actual usage was full 14 cpus for a while, later when secrets were generated the usage was reduced 100m cpu.
However, most of the alerts here are from seeds that are not officially part of any landscape and most of us even do not know what clusters actually are they, where are running, what kind of quality is the infrastructure that they are using, who is responsible for them and so on. Thus I asked the alerts to be enabled only for seeds that are officially in some landscape.yaml.
Azure seeds are also sporadically failing, but usually they self heal in the next 10 minutes.

**Comment by timebertt** [comment]
We might want to think about outsourcing the secret generation out of the gardenlet.

While discussing the topic with @timuthy @ialidzhikov @vpnachev @danielfoehrKn some ideas were:

**1. Secret generation in separate goroutine worker pool**
If we use some kind of pool of gorountines generating the secrets, we could rate limit the amount of secrets generated in parallel to control the resource consumption. This can maybe be implemented as a new controller in the gardenlet, which only generates secrets, or a completely different mechanism to allocate generator goroutines in a rate limited fashion. 
Though, this approach would not offload the resource usage off the gardenlet binary/container, so VPA might still scale the gardenlet quite unfortunately, because spiky usage can still happen, but we can hopefully limit the magnitude of the spikes with this.

**2. Outsource secret generation to Pods**
We could create a new binary which is responsible only for generating secrets and storing them in Kubernetes secrets, which can be started by the gardenlet on demand as a Pod (similar to terraform).
The advantage of this approach would be, that the gardenlet will have a relatively stable resource usage and can therefore be scaled by the VPA more fittingly.
Such Pods can probably run with Burstable QoS, so they can use left-over capacity on Seed worker nodes to run this resource-heavy task.

**3. Outsource secret generation to custom controller with CRDs**
Similar to approach 2 we could introduce a new binary running a secret generation controller listening on secret CRs, that the gardenlet would create. The controller could then either generate the secrets in-place (in the same container) or start new Pods for each task (like in approach 2). This approach is obviously more effort to implement, but could also be extended by making use of a message queue for enqueueing secret generation requests and auto-scaling a worker deployment, which would then in turn be even more over-engineered 😉 

WDYT?

**Comment by rfranzke** [comment]
My personal preference would be the second approach as it sounds most promising wrt scalability (we can have "as many" secret generation pods as we need in parallel).

**Comment by vpnachev** [comment]
I would like just to mention that the `ShootState` resource was introduced with the idea for secret generation outsourcing, so for the third option the "CRD" is already available.

**Comment by rfranzke** [comment]
Hm, no, I don't think the `ShootState` is related in any way here. It holds arbitrary data, generated data, but what we need is a CRD that takes a desired configuration (e.g., certificate common name, SANs, lifetime, etc.) and then generates the cert (that might later be put into the `ShootState`, but again, unrelated, so let's not mix it up).

**Comment by rfranzke** [comment]
/title Out-source secret creation to prevent unpredictable CPU spikes in gardenlet
/remove area/ops-productivity area/monitoring kind/bug
/area auto-scaling 
/kind enhancement
/exp intermediate
/platform all
/topology garden seed

**Comment by BeckerMax** [comment]
In a discussion with @rfranzke @vpnachev @timebertt @timuthy we decided to go for option 2):
Differing from the original proposal we want to utilize the Job resource to perform the secret generation. The flow would therefore be:
During reconciliation the Gardenlet checks if there are secrets missing (it can rely on its cache). If secrets are missing it creates a Job object and passes the secrets to generate. The Job will spawn Pods which generate the missing secrets and sends them to the API-server. As no secrets are actually stored within the pod it is resistent to node crashes. If the pod would crash during secret generation a new one would automatically be scheduled picking up the work where it was left.

**Comment by timuthy** [comment]
/assign
I started to create APIs (extracted already available internal ones) for CP secret generation. This is a first step to make the functionality available from the outside, see [here](https://github.com/timuthy/gardener/tree/feature.cp-secrets-api/pkg/secretsmanager/apis/v1alpha1). Following this, we can start to craft a separate component which will be called by Gardener.

**Comment by timuthy** [comment]
@rfranzke what is your impression on this issue today? My thought is that especially with https://github.com/gardener/gardener/issues/4661 this issues becomes less relevant and I wonder if we will still need to out-source the secrets generation.

**Comment by BeckerMax** [comment]
@timuthy I think this issue loses relevance.
With #4661 the gardenlet will no longer generate secrets for components in the Seed (MCM, KCM,...) to authenticate with the Shoot KAPI. Instead a new component other than the gardenlet will request short-lived tokens instead.

**Comment by timuthy** [comment]
Thanks for confirming my statement @BeckerMax. The question is rather if it's then fine to keep the remaining secret generation in Gardenlet (I assume we will still have some, e.g. CAs, server certs, probably some client certs like [this](https://github.com/gardener/gardener/blob/ff0d90cc18811314f1b3640f4f33c40f902bf332/pkg/operation/botanist/wanted_secrets.go#L185)?!) and don't see the necessity to out-source it. Can you already give a ratio of how much the secrets generation will be reduced by implememting #4661?

**Comment by rfranzke** [comment]
I would agree with the assumption that #4661 will relieve us significantly from the concerns we had earlier. Given that it is implemented and we haven't encountered the CPU spikes anymore since a longer time, I would also vote for
/close
ing the issue now. We can reopen/revisit if it becomes relevant again, but I don't expect it from today's point of view.
