### ISSUE TITLE
Kubelet as Pod

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#25]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/43_

----

# Acceptance Criteria
- [ ] Bootstrap/deploy the kubelet as pod if possible, so that it can be conveniently updated

(!) Beware if kubelet is run in a docker container: Volume attachment does not work/needs a lot of time (works with --containerized)

:information_source: Migrated from Jira issue [KUBE-159](https://jtrack.removed/browse/KUBE-159)

**Comment by vlerenc** [comment]
We decided against the kubelet in a pod, because of its increasing complexity. We would have preserved a local kubelet still, potentially deviating in version from the one in the pod and that was actually the main use case (to update the kubelet). Now that we can update it via the machine controller and can update its configuration even easier via a seed resource that gets downloaded when changed, we dropped kubelet-in-a-pod.
