### ISSUE TITLE
Preferred Scheduling for Shoot K8s Control Plane

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#250]
For HA anti-affinity is key, but for components that depend on each other, we should rather use affinity and `preferredDuringSchedulingIgnoredDuringExecution` scheduling to reduce the failure domain. While without affinity a OS image roll-out may break the control plane multiple times, affinity could help to break it only once while the node is down (and the pods get rescheduled) or drained (and the pods get rescheduled).

In general we should better understand, why our control planes under update are offline for so long.

**Comment by rfranzke** [comment]
Assigning @hardikdr and @prashanth26 as it requires machine-controller-manager in the first place.

**Comment by prashanth26** [comment]
We have opened up an [issue](https://github.com/gardener/machine-controller-manager/issues/174) to track the same. We shall prioritize this.

Regards,
Prashanth

**Comment by prashanth26** [comment]
Hi @rfranzke ,

I went back to thinking on this issue and realized that this feature is already supported by the machine-controller-manager/gardener shoots. The only requirement it has is the topologyKey for which we can use the [built-in-node-labels](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#interlude-built-in-node-labels) such as this `topologyKey: kubernetes.io/hostname`. I tried the same with a running shoot and it seems to be working fine. Am I missing anything?

Furthermore, to support the [PreferNoSchedule taint](https://github.com/gardener/machine-controller-manager/issues/120) we would require support from MCM to support the tainting which we are working on with the following issues -  https://github.com/gardener/machine-controller-manager/issues/174 & https://github.com/gardener/machine-controller-manager/issues/120. 

Regards,
Prashanth

**Comment by rfranzke** [comment]
Hi, thanks @prashanth26. What MCM should do is the following:

1. During a rolling update of the MachineSet it should label all the new machines/nodes with some specific label, let's say `newmachine=true`.
2. After the rolling update of the MachineSet is done the label can be completely removed from all machines.

With that we can add the `preferredDuringSchedulingIgnoredDuringExecution` affinity configuration to the control plane components to avoid that they are re-scheduled to old nodes (which will get drained later on) when the machines are getting drained during the rolling update. We want them to preferably get scheduled to the new machines so that we can avoid more than one re-schedule operation.

Please come back in case you have any questions/doubts.

**Comment by prashanth26** [comment]
Thanks for the detailed explanation @rfranzke. I understand your concern now. If I understand it correctly there are two parts to what we are both thinking here,

1. Pods to be placed in new machines when a rolling update is going on (as you have described above)

- We planned to apply the following taints to all the old nodes/machines - [`PreferNoSchedule`](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration) before a rolling update occurs.
- This would have the same effect as using `preferredDuringSchedulingIgnoredDuringExecution` with NodeAffinity as you mentioned above. 
- The issue to track this can be found here - https://github.com/gardener/machine-controller-manager/issues/120

2. Colocation of API server and ETCD pods 

- This preferred as it would reduce API server and ETCD going up and down one after the other and would be re-scheduled simultaneously during rolling updates, thereby reducing service downtime
- For this, we can use preferredDuringSchedulingIgnoredDuringExecution with [PodAffinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity) between the two pods/deployments.
- This would schedule both these pods on the same node.
- We still need to think about how multiple replicas of API server and ETCD would be affected in this case. 
- I am not sure if the same issue is enough to track this issue as well?

The confusion was because the two problems mentioned above could be solved with `preferredDuringSchedulingIgnoredDuringExecution` but with node and pod affinities respectively. :sweat_smile:

**Comment by vlerenc** [comment]
Right, these are two different issues:
1. One is about not scheduling control planes components on old nodes and reschedule them again and again when doing a rolling update (gardener/machine-controller-manager#120)
2. The other is about scheduling the critical two components (etcd + api server) on the same node, so that when a rolling update happens, both go down together/are rescheduled together

However, now with HPA for the API servers, my ticket makes no sense anymore, respectively gets more complicated:
* If we have multiple API servers, they should be rather scheduled with anti-affinity among themselves in regards to the hostname; reason being that affinity with etcd would otherwise prefer scheduling of all API servers on the same node, which is neither good from HA perspective (something we didn't have prior to HPA, but that we don't wanna lose if we now have it), nor will it practically work anyways as there is not enough space on a node
* If we have only one API server, because the load is not large enough, we would like affinity with etcd for the originally stated reasons, but that's not possible to achieve with HPA alone
* We may want to change the HPA minimum to 2 while doing the rolling update, but that may be pointless, because if the load is minimal, the second API server will be dropped again and the users will see connection termination
* We may want to always run at least 2 API servers, but that may be expensive and limits the dynamic range for auto-scaling
* We may want to compensate the above by static vertical scaling (based on core/memory of max workers in the worker pools), but that may not work for small clusters with huge load and be expensive for large clusters with minimal load
* We may want to ignore the same and always have at least 2 large enough API servers for `productive` flagged clusters and ignore the issues in not `productive` flagged clusters, which seems totally fine as well and would mean we can go for anti-affinity among the API servers in regards to the hostname

Side note: Maybe the best solution would be to take scaling into our own hands. The best solution would be not to depend on metrics alone, but replace the API server/ETCD when they really start failing or fail, because then it's necessary. I wonder how Google is handling this. We see a brief API server unavailability when we bombard them with requests, so they must reschedule the master VM (I believe we know, they only run a single master), so that's certainly not HPA, but something home-grown. I am not sure, we can get as far with HPA alone. Then again, such an approach would bring back the single API server, would take into consideration API server + ETCD as one group of critical components that must be sized together and appropriately and then we could have affinity again between themselves.

I guess we need to put more thinking and testing into the subject matter? Or we go with the `productive` hint and anti-affinity among the API servers in regards to the hostname if we stick with HPA.

What are you thinking @rfranzke @Adracus @prashanth26 @hardikdr @ggaurav10 @amshuman-kr.

**Comment by rfranzke** [comment]
@vlerenc is this ticket still relevant/up-to-date (especially after #2310) or can we close it?
If still relevant, could you update it with what is still missing/should be done?

**Comment by ghost** [comment]
@gardener-botmanager Only code owners and the author are allowed to close a ticket or PR.

**Comment by rfranzke** [comment]
The botmanager became alive... 😨
