### ISSUE TITLE
Reconcile in Maintenance Time Window Only

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#251]
People complain that they see shoot cluster control plane outages during the day (when we roll out a new Gardener), which is true. When we, e.g. change the control plane settings (CPU/memory limits) the control plane becomes shortly unavailable. Also, we have a load issue with the reconciler and it generates too many events. So why not run the reconciler once a day? We already had to change the interval for the latter reason and would most likely continue to do that anyway and make the interval longer and longer. Since we already have the maintenance time window, why not restrict reconciliation to that time of the day?

There is an automation (controller) to apply OS (and Kubernetes) patches to the shoot resource. We could drop that and modify the shoot resource right away, expecting it to be reconciled later, but that's not how it works (it would be picked up immediately). Also, when a user changes e.g. the worker pools, this change would then accidentally also install a new OS (and Kubernetes) patch, which would be unintended. So let's not change this mechanic and only defer the reconciliation until into the maintenance time window.

That's still not perfect, because if the user really changes e.g. the worker pools, the Gardener would have no "old" reconciler code anymore and could indeed e.g. change the control plane settings and thereby cause a small outage, but it would be much more stable than before. To "fix" that we could either version and "have" the old reconciler code (entire flow), but that's unrealistic. Or we could keep track and inform the user what is going to happen when the cluster (shoot resource) is changed. Or we could limit the reconciliation to only the changed part of the spec (when the worker pool is changed, only the worker pool gets reconciled), which isn't simple either, but maybe the best solution?

**Comment by rfranzke** [comment]
I'm not sure if this is really a good idea, mainly for the reasons you already mentioned in the last paragraph. If we introduce any of these behaviours we break basic principles of Kubernetes controllers.

One thing we definitely should not change is that Gardener reconciles all Shoots when it starts. We could make it configurable for the user to define that Gardener shall only reconcile in the maintenance time window, however, as we cannot/should not change the "reconciliation on startup" this would not be of much help.

Considering the plans regarding automatic vertical scaling of etcd we cannot avoid this situation anyway: If etcd restarts, then the control plane is very shortly (a few seconds) unavailable.

**Comment by vlerenc** [comment]
Yes, when the user changes the spec, e.g. the workers, we can easily argue, that things may temporarily be restarted/become unavailable briefly for the changes to be applied.

What I am actually more "unhappy" about is that I have no good answer for the "unexpected downtimes":
1. We roll out a new OS to the seed and all control planes are hit - here we could at least improve the situation with affinity a little bit (place API server and ETCD on the same seed worker, so that these components fail only once jointly). But it's still an unplanned downtime that we can't move it into the maintenance time window of the respective clusters, because one worker holds multiple control planes (and aligning their update with the hosted control planes is too complicated anyhow). Luckily, this happens very rarely. Next with Spectre-NG, once Core OS Container Linux has the patch ready.
2. We roll out a new Gardener and all control planes could potentially be hit because of the startup behaviour - while I immediately get the advantages of "reconciliation on startup" (quick detection of issues, quick fix of said issues, bring the clusters to a state where Gardener knows how to deal with them), I also see that this may cause downtimes right away, far outside the maintenance time window.

Do you agree? Is there some solution to the problem? What are your reasons for "reconciliation on startup"? The same as above or more/others?

**Comment by rfranzke** [comment]
Regarding 1. and 2.:

True, but those changes to the Seeds are updated in their respective maintenance time windows as well (in the night). Anyway, the "problem" (it also saves us from many other issues) is that we only have one etcd replica, and when it needs to be moved to another node, then the volume must be re-attached and the backup-restore sidecar must do its validation - both takes some time.

If we give up the "reconciliation on startup" we have to implement a lot of custom logic complicating the controller and violating the concepts. Moreover, we will never know in which state the clusters are. We would have to implement checks for specific sections (e.g., only changes to the worker pool) and only do those (just as an example). In the end, the clusters may up in individual states where things may not work together anymore because they may be dependent on a previous step which we haven't executed because we only wanted it to be in the maintenance window.

> What are your reasons for "reconciliation on startup"? The same as above or more/others?

Mainly those mentioned by you in your last paragraph and my thoughts above.

**Comment by vlerenc** [comment]
Night is a relative term (for the single Gardener instance) in this global world. ;-)

As for the new point you brought up: that was not what I meant. The complexity you mention is something we should definitely avoid, i.e. if someone, by touching/modifying the shoot resource (e.g. worker pools), really triggers an update, a full reconciliation should run, nothing less. There should never be a "mixed" state of affairs.

The question is rather, what will happen if we drop the "reconciliation on startup" and move the normal reconciliation into the maintenance time window. Also today, a cluster may be late to be reconciled if there are too many clusters for the finite number of Gardener workers (it could take hours to reconcile them all).

So, I am coming from the position: we can't guarantee that a cluster is reconciled soon after Gardener deployment anyhow, so why not defer it then completely into the maintenance time window  to at least run (maybe availability-critical) operations only then.

So, in summary, you say:
* we break the basic controller principle of reconcile (resync) at startup, which is true, but I am not sure how much this hurts, because of the missing guarantee when a cluster is reconciled anyhow
* late feedback about changes after Gardener deployment, which is certainly true, but then again, that we accidentally break all clusters at the same time is also not a virtue and then there is still the thought of #87
* late fixes in case we need to force something through quickly, which, if we go that path, can and must be compensated with an "expedited" process, but this causes additional implementation effort

I am pretty sure, the moment we break something for the first time with an accidental change (has never really happened in the past year, which is testament to the high quality, but remains a possibility), we will implement #87 and then we are not that far away anymore from the question raised here.

**Comment by rfranzke** [comment]
> So, I am coming from the position: we can't guarantee that a cluster is reconciled soon after Gardener deployment anyhow

True, that's how it might be at the moment, but that's not "unchangeable". With our extensibility story and moving responsibilities to other controllers we can and we have to reduce the time Gardener needs to reconcile a cluster. This will give us more capabilities to scale, managing more Shoots.

> so why not defer it then completely into the maintenance time window to at least run (maybe availability-critical) operations only then.

That's exactly the point complicating the logic, because subsequent steps may depend on these availability-critical operations, and we would always have to take care about that whenever we implement something.

I've also not the best feelings regarding #87 because, as you said, it goes in the same direction like this ticket and comes with similar problems. We would have to do the reconciliation in steps (10 at a time, if more than 5 succeed, continue with the next 10, otherwise stop doing anything). Anyway, I agree that we need these kind of "safety features" to protect our clusters, but maybe we haven't found the best solution yet?!

**Comment by vlerenc** [comment]
> subsequent steps may depend on these availability-critical operations

What do you mean? Is there a "startup phase" in the Gardener, i.e. does it first reconcile all clusters *before* it starts going over into "normal" operation mode?

**Comment by rfranzke** [comment]
No, I was talking about the steps executed in the usual reconciliation flow. If we pick certain steps and declare them as "availability critical" and only execute them within the maintenance time window then we might also have to defer the execution of subsequent steps which are dependent on those "availability critical" operations. This will complicate the whole reconciliation logic, and in the end it's implementation-wise better to completely move the whole reconciliation into the maintenance time window, leading to the problems we already discussed.

**Comment by vlerenc** [comment]
No, I never meant to "pick certain steps" and defer only them. It's all or nothing. I do not expect the Gardener to know what is an "availability critical" operation, either. That would be far too complex. That's why I asked, whether we can defer everything into the maintenance window, exactly because it's hard to know what is "availability critical" and certainly not to rip the reconciliation into two parts.

OK, so with "problems we already discussed" we settle on:
* we break the basic controller principle of reconcile (resync) at startup, which is true, but I am not sure how much this hurts, because of the missing guarantee when a cluster is reconciled anyhow
* late feedback about changes after Gardener deployment, which is certainly true, but then again, that we accidentally break all clusters at the same time is also not a virtue and then there is still the thought of #87
* late fixes in case we need to force something through quickly, which, if we go that path, can and must be compensated with an "expedited" process, but this causes additional implementation effort

**Comment by rfranzke** [comment]
I wanted to start working on this one, but I figured out that there is something that blocks us from doing it: We are still in the situation that Gardener creates the bootstrap tokens for the worker pools with an expiration duration of `90m`. Hence, if a shoot would only be reconciled in its maintenance time window  and a machine breaks so that a new one gets created then it most likely can't join the cluster (as no up-to-date/valid bootstrap token will exist).

Consequently, we first have to solve this problem before we can start working on this item here. I pinged @prashanth26 and @hardikdr and they agreed to start the discussion.

Now, assuming we would be rid of this problem the implementation for ensuring reconciliation only in maintenance time windows could be as follows:
1. We introduce a new field in the Shoot spec: `.spec.maintenance.reconcileOnlyInTimeWindow={true,false}` (better name?) that defaults to `false`. We should not enforce that for all shoots but make it configurable per shoot.
1. We would allow immediate reconciliation by annotation the shoot with `shoot.garden.sapcloud.io/operation=reconcile` (similar to how we allow immediate maintenance by annotating it with `shoot.garden.sapcloud.io/operation=maintain`).
1. If a shoot sets `.spec.maintenance.reconcileOnlyInTimeWindow=true` then the shoot controller will only queue it if it was annotated with `shoot.garden.sapcloud.io/operation=reconcile`. No automated requeueing happens.
1. The shoot maintenance controller will annotate the shoot with `shoot.garden.sapcloud.io/operation=reconcile` when maintaining it. This will trigger the shoot controller to reconcile.

**Comment by vlerenc** [comment]
More people complain about out-of-maintenance-time-window maintenance. Some want to implement HA scenarios where they have multiple shoot clusters with disjunct maintenance time windows, but if the update happens already with the reconciliation, they can't protect against (temporary) parallel updates (failures) as we reconcile how we see fit, ignoring any maintenance time window.
