### ISSUE TITLE
Update Garden clients at runtime

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2546]
**How to categorize this issue?**

/area quality
/ area robustness
/kind enhancement
/priority normal

**What would you like to be added**:

Make it possible to transparently update the Garden Cluster clients at runtime. 

With the introduction of the client map concept, it is possible to [refresh clients](https://github.com/gardener/gardener/pull/2544) when the underlying kubeconfig stored in a secret changes. 
This is implemented for Seed and Shoot clusters only.

What we need is to 
- refresh the garden clients in the garden client map (similar to how it is implemented for the seed and shoot client map) 
- a solution to exchange the clients used by the [SharedInformers throughout the project](https://github.com/gardener/gardener/blob/4fb79950b64f99bd43ae9236ee1c7f2d41601581/pkg/client/core/informers/externalversions/factory.go#L79-L78). Possibly replace the direct usage of SharedInformers with e.g the [ControllerRuntime](https://github.com/kubernetes-sigs/controller-runtime).

I understand that the latter is a bigger task, but I wanted to raise the issue already to collect thoughts and ideas.

**Why is this needed**:

The garden cluster client credentials are not guaranteed to be stable. For instance due to
1) [Certificate rotation performed by the  Gardenlet](https://github.com/gardener/gardener/pull/2542)
   - After certificate  rotation, the Gardenlet needs to self terminate in order to get the new credentials when the new pod comes up 
2) Operator wants the Gardenlet to act on another Garden cluster - updates the Garden kubeconfig
   - The Gardenlet currently does not detect changed credentials for the Garden cluster nor updates the clients & Informers. The Gardenlet still targets the "old" cluster.

Regarding Certificate Rotation: Currently this is an event happening once a year, but I envision offering functionality like the kubelet's  `-experimental-cluster-signing-duration`  to control the client certificates lifetime.

**Comment by rfranzke** [comment]
@tim-ebert can explain it in detail, but what I understood from a discussion with him is that it's very complex/not even clear from the current design's perspective to achieve a dynamic refreshment of the garden client.
IIUC the certificate rotation of the gardenlet is the only real use-case (I don't understand the second point, sounds artificial to me, can you explain more about it).
Even if we lower its client certificate validity duration I don't think that restart of the gardenlet is problematic given that we omit additional code/complexity.

So, my take on this would be: If there is an easy, straight-forward way to achieve this behaviour then sure, let's do it, but if not, then let's not do/postpone it in favor of tasks with a higher priority.

**Comment by timebertt** [comment]
> @tim-ebert can explain it in detail, but what I understood from a discussion with him is that it's very complex/not even clear from the current design's perspective to achieve a dynamic refreshment of the garden client.

Indeed, I don't see any way how the configuration of client-go style ClientSets, Informers or Listers can be changed at runtime. Maybe I miss something here, if you see such possibilities, I would be very interested to look into them.
As we rather heavily rely on Informers and so on in our controllers and don't have any way of refreshing them, we need to shutdown the gardenlet in order to recreate them, when its certificate is changed.

BTW: the same also applies to the Informers obtained from a runtime cache from a ClientMap. So if you change a Seed Secret for example and you obtained some Informers from a runtime cache from the ClientMap, they will be stopped by the ClientMap, so they will receive no more watch events. That in turn means, that controllers relying on such informers will have to get a new client again and start watching with new Informers. Fortunately, we currently only rely on generated Informers, that are statically initialized, but that will change with #2516. So we will have to somehow refresh the Informers we use there in order to receive further watch events (cc @timuthy).

**Comment by danielfoehrKn** [comment]
> If there is an easy, straight-forward way to achieve this behaviour then sure, let's do it, but if not, then let's not do/postpone it in favor of tasks with a higher priority

Agree. I am not advocating to tackle the issue right now but to keep in mind that we have some technical debt here in my opinion.
I think it makes sense to leave this issue open and revisit it when we see more reasons to switch to the controller runtime clients. 

> Indeed, I don't see any way how the configuration of client-go style ClientSets, Informers or Listers can be changed at runtime. Maybe I miss something here, if you see such possibilities, I would be very interested to look into them.

No I do not. I see that as a reason to harmonize the client usage in the GCM, Gardenlet and extensions to all use the controller runtime clients. 

> That in turn means, that controllers relying on such informers will have to get a new client again and start watching with new Informers.

That would be possible at runtime, right?

**Comment by timebertt** [comment]
> Agree. I am not advocating to tackle the issue right now but to keep in mind that we have some technical debt here in my opinion.

TBO, I don't really get, why this would be a technical debt. Can you elaborate, why you think so?
We have a lot of other components that are simply restarted if their configuration changes (see the Pod checksum annotations in many of our deployments). And I guess, this is also the "cloud-native" way to do things. Rather kill your workload to see it get restarted cleanly with the correct configuration instead of reloading configuration. And I think, doing so is a well-established mechanism in the kubernetes space and I don't see any problem with it. The only place, where such mechanisms are not desired is for stateful workload, that might take some time for being restarted (e.g. prometheus) and for such workload, there are other means to reload configuration (e.g. the prometheus-config-reloader sidecar).
But as the gardenlet is not a stateful component and can start up quite fast, it doesn't hurt if it shuts down itself ~once a year for rotating its certificate. In between it might have been killed/restarted hundreds of times by the VPA or version upgrades or whatever...

I was also thinking about how other controllers for custom resources in kubernetes do such things.
I guess most of the time they a running as a Pod and using in-cluster config/ServiceAccounts to talk to the API server and start their watches. So probably none of them is doing a dynamic reload of their client configuration, or am I mistaken?
And that's probably why there are no mechanisms in the kubernetes libraries to accomplish such things.

BTW: how does the kubelet deal with rotated certificates? Does it dynamically refresh the underlying configuration of its watches? And if so, how?

> I think it makes sense to leave this issue open and revisit it when we see more reasons to switch to the controller runtime clients.

What do you mean by that? I don't understand how this is related to controller-runtime clients...

> > Indeed, I don't see any way how the configuration of client-go style ClientSets, Informers or Listers can be changed at runtime. Maybe I miss something here, if you see such possibilities, I would be very interested to look into them.
> 
> No I do not. I see that as a reason to harmonize the client usage in the GCM, Gardenlet and extensions to all use the controller runtime clients.

Why? The controller-runtime clients also use client-go under the hood, so I'm not aware of any mechanisms to refresh the rest config of their Informers at runtime as it is just the same client-go stuff.

> > That in turn means, that controllers relying on such informers will have to get a new client again and start watching with new Informers.
> 
> That would be possible at runtime, right?

Of course, that would be possible at runtime. But we don't have any mechanism for that at the moment. I was thinking about such a way to do so, but I now tend more and more to not implement such things, as they will be highly gardener specific and probably won't work if we use our clientmaps for constructing controller-runtime managers unless this mechanism is highly over-engineered.

**Comment by danielfoehrKn** [comment]
We agreed upon that it does not make sense to update the Garden and Seed clients at runtime due to increased complexity.
Gardener is build in a stateless fashion - so killing the Gardenlet pod will do not harm (does not reconcile any Shoots again etc.).
The only thing that possibly happens is that an ongoing reconciliation will be started again.

Thanks for your guys input!
Closing this.
