### ISSUE TITLE
unable to delete shoot when shoot failed to create

### ISSUE THREAD

**Issue by knightXun** [gardener/gardener#2565]
When shoot cluster failed to create, I cannot delete ths shoot cluster mannually.Please notice this.

**Comment by timuthy** [comment]
This is a very generic statement and since a lot of steps are involved to create a shoot cluster which are also infrastructure/cloud provider dependent, the reasons for an unsuccessful deletion can be versatile.

> I cannot delete ths shoot cluster mannually

Did you really try to clean-up the shoot and dependent resources manually yourself or did you instruct Gardener to delete the shoot again. What's the concrete issue?

I kindly ask you to provide **more details** about this issue, **so that we can reproduce it**.

For example:
- At which step did the creation fail
- At which step does the deletion fail
- Infrastructure type
- Versions of Gardener and involved extensions
- Any details about your Gardener and Shoot like enabled feature gates, OS, K8s versions, ...
