### ISSUE TITLE
add the --admission-controller=Initializers to the kube-apiserver

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#257]
I try to use a kubernetes feature named **Kubernetes Initializer** which is well explained in
a tutorial from Kelsey Hightower

https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/docs/initializing-deployments.md

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-initializers

Unfortunately I'm unable to use this feature because a required flag isn't set at the kube-apiserver
```YAML
--admission-controller=Initializers
```
I can't change the settings by my own - the reconcile reset it always to the defaults.

**Comment by vlerenc** [comment]
That is indeed an open question: Shall we allow configuration of admission controller plugins or not. And if yes, what can happen worst case? A few must be always on, because we depend on them. See also #254 that requires the PriorityAdmissionPlugin.

**Comment by freegroup** [comment]
yes - you should allow it   👍

**Comment by bergerx** [comment]
When I was first looking at the gardener design, having control over
admission plugins was one of my first expectations.

We were using AKS and had no control over most cluster level configs (authn
fields, admission plugins, feature gates, etc.) when we found Gardener I
immediately thought it would allow us more control over such configs. Which
turned out to be not true for admission plugins.

I think Gardener should allow more control over admission plugins.

**Comment by freegroup** [comment]
maybe the configuration can be part of the shoot.yaml?
see https://github.com/gardener/gardener/issues/259

**Comment by vlerenc** [comment]
All related: #254 (priority), #257 (Initializers), #258 (PodNodeSelector , PodTolerationRestriction), #259 (PersistentVolumeClaimResize).

BLI for configurable admission controllers/plugins is now #263.
