### ISSUE TITLE
split operation and developer kubeconfig.yaml into two

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#260]
at the moment the `kubeconfig.yaml`, downloadable from the gardener dashboard, is the very
same as this one which is required of the gardener to operates the cluster.

For this reason, it is not possible to revoke the kubeconfig.yaml if this has been leaked.

May it is a good idea to create a new admin group, used by the dev-kubeconfig.yaml which is downloadable from the dashboard.

**Comment by vlerenc** [comment]
That's a duplicate of #105, right?

**Comment by freegroup** [comment]
partly duplicate

 - add the feature to reset/revoke kubeconfig.yaml // **dublicate**
 - kubeconfig for reconcile and operation (done by the gardener) must be a different one than the kubeconfig.yaml for developers // **new**

**Comment by rfranzke** [comment]
> add the feature to reset/revoke kubeconfig.yaml // dublicate

This is not possible at the moment as the kubeconfig contains a client certificate which cannot be revoked on demand. The only way to revoke is would be to change the CA of the cluster. However, this isn't something we do in the next time.

> kubeconfig for reconcile and operation (done by the gardener) must be a different one than the kubeconfig.yaml for developers // new

This is already a different one and always was since day one.
