### ISSUE TITLE
Adding prometheus-operator as an addon

### ISSUE THREAD

**Issue by cihangirbesiktas** [gardener/gardener#272]
We need `prometheus-operator` to be deployed on a specified namespace of our shoot clusters. Currently, we are deploying it using this [helm chart](https://github.com/coreos/prometheus-operator/tree/master/helm). To automate the installation, I am planning to add the helm chart as a shoot addon. 
Implementation details:
- Adding the `prometheus-operator` helm chart to `charts/shoot-addons/charts/prometheus-operator` directory
- Creating `GeneratePrometheusOperatorConfig` function in `pkg/operation/botanist/addons.go`
- Creating `PrometheusOperatorEnabled` function in `pkg/operation/shoot/shoot.go`
- Creating `PrometheusOperator` type in `pkg/apis/garden/v1beta1/types.go`
- Updating some of yaml and tpl files to have prometheus operator related config
- Creating validation and its test for prometheus operator

Any ideas?

**Comment by vlerenc** [comment]
We would rather not like to extend the add-on concept in-tree. See also @bergerx request #246. This would not be sustainable (which is why we didn't add any other add-ons anymore) and we need another approach here, if anything at all. Meaning, most cluster installers focus on the cluster installation itself - content can be added independently and the field is moving fast.

An extension concept could also be realised via an independent controller, e.g. deployed into the garden (or seed) cluster watching shoot resources (or namespaces) and acting upon them. This way we would decouple the logic and not turn the Gardener into an unmanageable beast that does too much.
