### ISSUE TITLE
Logs missing in loki

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2758]
**How to categorize this issue?**

/area logging
/kind bug
/priority normal

**What happened**:
Unable to find logs of extension controllers in the seed loki (the one in the garden ns).

**What you expected to happen**:
To be able to find the logs.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open the grafana ingress of some large seed.

2. Navigate the the explore UI.

3. Try to find provider-aws logs

Currently the existing pods are

```
$ k -n extension-provider-aws-dmdjz get po -l app.kubernetes.io/instance=provider-aws
NAME                                               READY   STATUS    RESTARTS   AGE
gardener-extension-provider-aws-64868b6d8d-8rbc8   1/1     Running   0          4h4m
gardener-extension-provider-aws-64868b6d8d-s5m6q   1/1     Running   0          39m
gardener-extension-provider-aws-64868b6d8d-wkskk   1/1     Running   0          149m
```

Trying the following queries returns nothing

```
{pod_name="gardener-extension-provider-aws-64868b6d8d-8rbc8"}
{pod_name="gardener-extension-provider-aws-64868b6d8d-s5m6q"}
{pod_name="gardener-extension-provider-aws-64868b6d8d-wkskk"}
```

or 

```
{pod_name="gardener-extension-provider-aws-64868b6d8d-8rbc8", namespace_name="extension-provider-aws-dmdjz"}
{pod_name="gardener-extension-provider-aws-64868b6d8d-s5m6q", namespace_name="extension-provider-aws-dmdjz"}
{pod_name="gardener-extension-provider-aws-64868b6d8d-wkskk", namespace_name="extension-provider-aws-dmdjz"}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.8.0 and master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
@vlvasilev @Kristian-ZH recently the logging has received a lot of improvements and most of the logs are now successfully ingested in the correct Loki instance, am I right?

**Comment by rfranzke** [comment]
Shall we close this in favor/merge this into #2677?

**Comment by Kristian-ZH** [comment]
Yes :) we can close this issue

**Comment by ialidzhikov** [comment]
And how exactly this issue is fixed?

**Comment by rfranzke** [comment]
Even if it's not fixed yet let's track it in the general improvement issue #2677

**Comment by Kristian-ZH** [comment]
The issue was caused because Loki was not able to handle the logs rate. 
When the buffer was overflowing, the output plugin was receiving `pause` command. The normal behaviour after a `pause` command is to receive a `resume` command, when some capacity of the buffer is released. Unfortunatelly once our plugin was `paused`, it was not resumed anymore.

The improvement we did there was to use `rwmutex` instead of basic mutex in the place where the output plugin was getting Client to the correct Loki: https://github.com/gardener/logging/pull/64

In the before version the critical section was blocking always when a goroutine enters into it.
Now it splits the routines on readers/writers and Multiple readers can access it  simultaneously.

After this change we are getting `pause` again but after that we are getting also `resume` which is the expected behaviour.

Future improvement will be to send into Loki a bulk of logs, because it is slow operation and currently we are sending logs across the network one by one
