### ISSUE TITLE
Mutating webhook doesn't abide by the failurePolicy of Ignore and blocks further pod creation

### ISSUE THREAD

**Issue by ashwani2k** [gardener/gardener#2779]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority normal

**What happened**:
The issue happened during upgrade of Gardener, which had enhancement to move VPA to shoot control plane in the shoot namespace. During the upgrade there is a short period of time when there is no VPA pod backing the mutating webhook which results in error. Although the failurePolicy for the mutating webhook vpa-webhook-config  is set to “Ignore” but during the upgrade each restart of the vpa-admission pod resets this timeout value for mutating webhook back to 30 seconds which doesn’t honor the failurePolicy “Ignore” (a limitation from upstream Kubernetes
) and hence blocks any further pod creation. 

**What you expected to happen**:
The mutating webhookconfiguration of failurePolicy: Ignore should be respected and a failure should not block further pod creation. 

**How to reproduce it (as minimally and precisely as possible)**:
Sequence of events  per my understanding, but the actual flow during upgrade might be different so please correct. 
Edit the mutating webhookconfiguration vpa-webhook-config  in the seed  to 10s. 
Restart the vpa-admission pod 
Check the timeout it should be set back to 30s which doesn't follow the failurePolicy of Ignore. 

**Anything else we need to know?**:
A possible  mitigation discussed could be to disable the self registration of the mutating webhook and let Gardener deploy it.. In this way we will have full control of the timeout and it can be properly set to something different to 30 seconds.

**Environment**:

- Gardener version: 0.85.0
- Kubernetes version (use `kubectl version`): Kubernetes 1.16 
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
By the way, the issue can happen at any time, it is more likely to happen during upgrades because of possible node eviction and so on, but is not limited only to this occasions. A general recommendation is to not use 30 seconds for the webhook timeouts and this was considered for the `v1` version of `admissionregistration.k8s.io` when the default was changed from 30 to 10 seconds(ref: https://github.com/kubernetes/kubernetes/pull/79549).

More details for the issue with `FailurePolicy: Ignore` and `timeout: 30s` can be found here https://github.com/kubernetes/kubernetes/issues/71508#issuecomment-470126655.

The described solution is to use this feature https://github.com/kubernetes/autoscaler/pull/2949 of VPA and let Gardener own and manage the webhook configuration, e.g. set the timeout to 10 seconds.


/assign @ggaurav10 @amshuman-kr
