### ISSUE TITLE
Node details dashboard has missing metrics with containerd

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#2800]
**How to categorize this issue?**

/area monitoring
/kind bug
/priority normal

**What happened**:
The node details dashboard has missing metrics when the shoot is configured to use containerd.
Network I/O pressure is missing and the system service usage is also missing.
![image](https://user-images.githubusercontent.com/8710621/91731535-3507f080-eba7-11ea-94a6-bdd8613b40d7.png)

**What you expected to happen**:
The dashboard should contain the data. Example with docker:
![image](https://user-images.githubusercontent.com/8710621/91731602-523cbf00-eba7-11ea-9ae2-b94871155d77.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with 
```yaml
cri: 
  name: containerd
```
check the node details dashboard and see the missing data.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): 1.18.5
- Cloud provider or hardware configuration: aws

**Comment by danielfoehrKn** [comment]
Containerd exposes a configurable prometheus compatible metrics endpoint (not part of the default config.toml) that we do not set yet.
Other than that it should expose the default metrics via CRI for each container & per pod [ContainerStats](https://github.com/kubernetes/cri-api/blob/5862c637c0946a29efea6eb7954d229e44fe1daf/pkg/apis/runtime/v1alpha2/api.proto#L1276-L1275)

   > CpuUsage cpu = 2;
    // Memory usage gathered from the container.
    MemoryUsage memory = 3;
    // Usage of the writable layer.
    FilesystemUsage writable_layer = 4;

Not sure if containerd even exposes Network IO - would need some more investigation.
I can take a look at it when focusing on the [Container Runtime topic in the future](https://github.com/gardener/gardener/issues/2719) - though blocked with quality focus atm.

**Comment by rfranzke** [comment]
Any plans to mitigate this issue @wyb1 @danielfoehrKn ?

**Comment by danielfoehrKn** [comment]
Still working on other issues - but I intend to pick it up when picking up ContainerRuntimes again. Otherwise @wyb1 might take a look

**Comment by istvanballok** [comment]
My latest info is that the cadvisor component is (currently) not exposing some metrics if the container runtime is containerd. This is the reason why the panels are empty on the screenshot above. cc @voelzmo

**Comment by istvanballok** [comment]
/reopen

Looking into this issue I found that actually the network related metrics are exposed by the cadvisor.
The reason why we drop them is this rule:
https://github.com/gardener/gardener/blob/21ac4306b7b4a80fedfe2349616e87cde50fa2e1/charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml#L168-L170
If the container label is empty, the series is dropped. This heuristic was probably introduced to keep only relevant metrics.
With docker as container runtime, the container label was "POD". With containerd, it is empty.
Note that for network related metrics, the container label doesn't make sense (and hence the empty value is correct), because the containers of a pod share the same network namespace and hence the network related metrics can not distinguish between containers.
