### ISSUE TITLE
Support HTTPS for /healthz, /readyz, /metrics and /debug endpoints

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2829]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
[Similar to Gardenlet](https://github.com/gardener/gardener/blob/74fbee9bb67270899b0afd8d9cc1bd806bdf80c1/cmd/gardenlet/app/gardenlet.go#L440-L448), controller-manager, admission-controller, resource-manager, scheduler and seed-admission-controller should serve `/healthz`, `/readyz` and `/metrics` endpoints via HTTPS instead of HTTP. 
Additionally, `/debug` should also be served via HTTPS if enabled (ref https://github.com/gardener/gardener/issues/4567).

**Comment by rfranzke** [comment]
Should we close this in favor of #4251? cc @timebertt

**Comment by timuthy** [comment]
Hm, I don't think that one comes with the other. The scheduler for instance was changed to use the Controller-Runtime but the endpoints are still served via http only. Even on the contrary, with the Controller-Runtime serving these endpoints with https is not supported yet (https://github.com/kubernetes-sigs/controller-runtime/issues/979). Hence, we should only close it if we decide that this is not too relevant.

**Comment by timebertt** [comment]
Once we refactor gardenlet to a native controller-runtime component (https://github.com/gardener/gardener/issues/4251), i.e. use a c-r manager to expose metrics and health endpoints, we will also be back to plain http for `/healthz`, `/readyz`, `/metrics` and `/debug` there as well.

Do we consider this to be important?
If so, we could
- a) tackle https://github.com/kubernetes-sigs/controller-runtime/issues/1007 and contribute the required mechanisms to c-r
  - in that case, we probably would want to allow reusing the same listener (port, certs, etc.) for webhook server, health and metrics endpoints as our components currently use one port for everything
- b) use [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) as a sidecar container for our components like described in https://github.com/kubernetes-sigs/controller-runtime/pull/993#issuecomment-645045329
  - in addition to TLS, this would allow configuring RBAC for the endpoints (e.g. like it is the case for API servers)

If not and we want to go with HTTP for the endpoints, we need to
- c) adapt seed-prometheus scrape config to allow scraping with `http` scheme:  https://github.com/gardener/gardener/pull/4706#discussion_r713648371

If we should decide for a), it might make sense to start with this in parallel to the other steps in https://github.com/gardener/gardener/issues/4251, so that we don't need to add configuration knobs for different ports and so on that will be replaced shortly afterwards again.

Looking for more opinions here!

**Comment by timuthy** [comment]
Thanks a lot @timebertt for outlining the options. I personally prefer **b)** because it additionally delivers RBAC capabilities. The disadvantage I see is yet another vertically scaled side-car and I hope that if we decide for option **b)**, we don't see this as the #1 reason for Pod evictions.

**Comment by timebertt** [comment]
Thanks @timuthy for adding your opinion here. I like b) as well.

I recently learned, that kubebuilder actually uses kube-rbac-proxy for securing the metrics endpoints etc. by default: https://book.kubebuilder.io/reference/metrics.html#protecting-the-metrics
So I think, b) should be a safe bet :)

**Comment by timebertt** [comment]
https://github.com/gardener/gardener/issues/4605

**Comment by rfranzke** [comment]
I vote for closing this one and simply relying on what the controller-runtime library provides. If it's HTTP for the metrics and health endpoints, then it's HTTP and good enough (I don't see any security risk whatsoever with this).

**Comment by timuthy** [comment]
I kind of agree here, even though I'm a bit more concerned that we don't have authorization for `/debug` which is however disabled by default. Any strong concerns from your side @timebertt?
IIRC, the main reason for opening this issue was to mimic what K8s did with their components and to make it consistent with Gardenlet when we didn't use CR.

**Comment by rfranzke** [comment]
Any feedback @timebertt?

**Comment by timebertt** [comment]
I still vote for implementing option b) (adding kube-rbac-proxy) which is very little effort.
This plays nicely with what the community does (kubebuilder, etc.) and follows best practices. I would consider this to be "what controller-runtime/kubebuilder provides" even though it is a sidecar component rather than a go library feature.

I even have some running examples in one of my projects, which can be used as a template.

**Comment by rfranzke** [comment]
In an internal chat we figured that we won't be able to use the `kube-rbac-proxy` approach for the `/healthz` and `/readyz` endpoints since we otherwise would need to write JWT tokens into the `{live,ready}nessProbe`s of the various `Deployment`s (which isn't a great idea).

Since `/debug` is disabled by default and typically only used for dev purposes, `/metrics` is the only endpoint left that would "benefit" from using `kube-rbac-proxy`.

However, `/metrics` doesn't expose sensitive data and is in addition only reachable cluster-internally (this is different for the comparable endpoints in `kube-apiserver`).

In this light, we agreed to not invest here since the additional complexity/effort is not worth it.

/close
