### ISSUE TITLE
Local Gardener setup - creation of a Shoot cluster not working

### ISSUE THREAD

**Issue by fableh** [gardener/gardener#290]
Hi all,

i´am just starting with the gardener local setup on my mac.
All steps working fine, but if i want to create the "Shoot Cluster" by executing this:

`kubectl apply -f dev/shoot-local.yaml`

I got the following response:

**error: the path "dev/shoot-local.yaml" does not exist**

By checking  the "dev" folder, iam have the following files in place:

_20-componentconfig-gardener-controller-manager.yaml
minikube-seed-kubeconfig
90-shoot-local.yaml					
shoot-kubeconfig_

As u can see in the screenshoot, the Gardener API server, the Gardener controller manager and the Gardener Local Provider is up an running:

![image](https://user-images.githubusercontent.com/13249857/43184784-110a5580-8fea-11e8-9600-d80bcbf440f6.png)

Any tips what iam doing wrong here?

thx and br,
fabian

**Comment by plkokanov** [comment]
@fableh you should use `kubectl apply -f dev/90-shoot-local.yaml`
@mvladev maybe we should update the local setup documentation?

**Comment by mvladev** [comment]
@plkokanov yes this should be updated to `kubectl apply -f dev/90-shoot-local.yaml`

**Comment by fableh** [comment]
@mvladev ok i tried this also but i got the following response:


`The Shoot "local" is invalid: spec: Invalid value: garden.ShootSpec{Addons:(*garden.Addons)(0xc4209f3dc0), Backup:(*garden.Backup)(0xc420f1fee0), Cloud:garden.Cloud{Profile:"local", Region:"local", SecretBindingRef:v1.LocalObjectReference{Name:"core-local"}, Seed:(*string)(0xc420bb2f20), AWS:(*garden.AWSCloud)(nil), Azure:(*garden.AzureCloud)(nil), GCP:(*garden.GCPCloud)(nil), OpenStack:(*garden.OpenStackCloud)(nil), Local:(*garden.Local)(0xc4209f3e40)}, DNS:garden.DNS{Provider:"unmanaged", HostedZoneID:(*string)(nil), Domain:(*string)(0xc420bb2f80), SecretName:(*string)(nil)}, Kubernetes:garden.Kubernetes{AllowPrivilegedContainers:(*bool)(0xc4208ffb9e), KubeAPIServer:(*garden.KubeAPIServerConfig)(nil), KubeControllerManager:(*garden.KubeControllerManagerConfig)(nil), KubeScheduler:(*garden.KubeSchedulerConfig)(nil), KubeProxy:(*garden.KubeProxyConfig)(nil), Kubelet:(*garden.KubeletConfig)(nil), Version:"1.11.0"}, Maintenance:(*garden.Maintenance)(0xc420bb2f90)}: field is immutable`

And this one "The Shoot "local" is invalid: spec: Invalid value" looks not like a success message?
If i go ahead by exectuing the following command:

`kubectl --namespace shoot-dev-local get secret kubecfg -o jsonpath="{.data.kubeconfig}" | base64 --decode > dev/shoot-kubeconfig`

I got this resp.:

`Error from server (NotFound): namespaces "shoot-dev-local" not found`

Any tip?

**Comment by plkokanov** [comment]
@fableh we should also update the name of the shoots to reflect recent namespace changes. Instead of `shoot-dev-local` you should use `shoot--dev--local`

In the controller-manager screenshot I see that there was a [SHOOT RECONCILE] log so I'm guessing you already tried starting a shoot. 

You can list all of the namespaces in your cluster (so you can see your shoot's namespace)
`kubectl get namespaces`

And then check the pods of your shoot's controlplane with 
`kubectl -n <shoot-namespace> get pods`
to get an idea if everything is working properly

Or alternatively just use `kubectl get pods --all-namespaces` to get all available pods

**Comment by mvladev** [comment]
Fixed in #291

**Comment by fableh** [comment]
@plkokanov one (hopefully) last question....

If i execute now this one:
`kubectl --kubeconfig dev/shoot-kubeconfig get nodes`

i got this error:

`The connection to the server 192.168.64.2.nip.io:31443 was refused - did you specify the right host or port?`

The following pods available:

(https://user-images.githubusercontent.com/13249857/43197936-16b6197e-900d-11e8-977b-8cb1862213f8.png)
![image](https://user-images.githubusercontent.com/13249857/43197945-233de30c-900d-11e8-9237-8e4e5ce1afcd.png)

Any hint here what iam doing wrong here?

thx and br,
fabian

**Comment by plkokanov** [comment]
@fableh can I contact you via slack or mail since the initial issue was resolved?
In the meantime:
The problem might be that 192.168.64.2.nip.io is not getting resolved properly (to 192.168.64.2) or your minikube has changed its IP address.
Could you please check the output of 
`dig 192.168.64.2.nip.io`
and
`nslookup 192.168.64.2.nip.io` 

Then also check
`minikube ip`

**Comment by fableh** [comment]
@plkokanov ok sounds great i just signed in to the gardener slack channel.
username: fabian
