### ISSUE TITLE
Guestbook test on openstack leak volumes from redis StatefulSet

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#2958]
**How to categorize this issue?**

/area testing
/kind bug
/priority normal

**What happened**:
In regular tests I noticed that a lot of volumes leak in our openstack landscape. Most of the leaked volumes are 8GB in size and contain some redis data, so I assume they are from the guestbook test with deploys a redis `sts`.

**What you expected to happen**:
No leaking.

**How to reproduce it (as minimally and precisely as possible)**:
Currently I only observe it after the fact (after the resp. test cluster was already deleted). Haven't tried to reproduce yet.

**Anything else we need to know?**:
We are currently testing k8s 1.19.2 and 1.18.9 clusters, unfortunately from the leaked volumes I cannot tell which clusters the volumes originated from.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`): 1.19.2 and 1.18.9
- Cloud provider or hardware configuration: openstack
- Others:

**Comment by ialidzhikov** [comment]
This issue is actually caused by the `Testing if Shoot can be hibernated successfully` against v1.19 cluster. See https://github.com/gardener/gardener-extension-provider-gcp/issues/172 (issue is opened under gardener/gardener-extension-provider-gcp but it is applicable also for all providers using CSI, there is also the same issue under g/g - https://github.com/gardener/gardener/issues/2545).

You can read the full analysis in https://github.com/gardener/gardener-extension-provider-gcp/issues/172#issuecomment-692791115. Long story short - currently there is no garbage collection for of `volumeattachments.storage.k8s.io` (resource which is used with CSI) in kube-controller-manager (ref kubernetes/kubernetes#77324). When Shoot is hibernated, the Nodes are forcefully deleted (without waiting running Pods to detach volumes) -> this leaks volumeattachments. On wake up new volumeattachment is created for the PV and the new Node and the old volumeattachment is orphaned. This orphaned volumeattachment then blocks the PV deletion.

Basically this can be easily reproducible with with the `Testing if Shoot can be hibernated successfully` test.

1. Run the test

```
$ go test -timeout=0 -mod=vendor ./test/suites/shoot \
      --v -ginkgo.v -ginkgo.progress -ginkgo.noColor \
      --report-file=/tmp/report.json \
      -kubecfg=$KUBECONFIG \
      -shoot-name=$SHOOT_NAME \
      -project-namespace=$PROJECT_NAME \
      -ginkgo.focus="Testing if Shoot can be hibernated successfully"
```

2. Ensure that the test succeeds but leaves a PV

```
# Ensure that the test ns is deleted
$ k get ns
NAME              STATUS   AGE
default           Active   97m
kube-node-lease   Active   97m
kube-public       Active   97m
kube-system       Active   97m

$ k get volumeattachments.storage.k8s.io
NAME                                                                   ATTACHER                   PV                                                               NODE                                                     ATTACHED   AGE
csi-62dfe186e1e1498955ff92d07d3ea7bc6bb30531547b73527bd0fc0bd214f2e2   cinder.csi.openstack.org   pv-shoot--baaaaar--tm-foo-1a9ced3c-9750-4ebe-90bc-7b7ea1edaaaa   shoot--baaaaar--tm-foo-worker-uoq0s-z1-ddcdf9db8-8khsn   true       35m


$ k get pv
NAME                                                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                          STORAGECLASS   REASON   AGE
pv-shoot--baaaaar--tm-foo-1a9ced3c-9750-4ebe-90bc-7b7ea1edaaaa   8Gi        RWO            Delete           Released   gardener-e2e-269qt/redis-data-redis-master-0   default                 36m

$ k describe pv

Events:
  Type     Reason              Age                   From                                                                                                  Message
  ----     ------              ----                  ----                                                                                                  -------
  Warning  VolumeFailedDelete  3m11s (x13 over 26m)  cinder.csi.openstack.org_csi-driver-controller-69fb7c6f55-rhp74_2788f50c-fd59-4d66-817a-5c9463b6c6d1  persistentvolume pv-shoot--baaaaar--tm-foo-1a9ced3c-9750-4ebe-90bc-7b7ea1edb3ea is still attached to node shoot--baaaaar--tm-foo-worker-uoq0s-z1-ddcdf9db8-8khsn
```

This issue should also occur for the other providers.

/status accepted

**Comment by ialidzhikov** [comment]
Note also that the Shoot deletion flow does only delete and wait for PVCs, but not PVs.

**Comment by ialidzhikov** [comment]
> This issue should also occur for the other providers.

I tested on AWS now and the PV deletion hanged again in Terminating but the underlying EBS volume was successfully deleted. I now see that there was a change in the external-provisioner starting v2.0.0 (ref https://github.com/kubernetes-csi/external-provisioner/pull/438/) that now checks whether the PV has volumeattachments and if yes, it fails early and does not call the CSI driver for volume deletion. Currently only provider-openstack extension is using external-provisioner@v2.0.0. That explains why we see the volume leak issue only on openstack (for now).

**Comment by dguendisch** [comment]
Nice finding! Thanks so much for digging into this!
