### ISSUE TITLE
Mid-air updates lead to shoot deletion failures

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2960]
**How to categorize this issue?**

/area robustness
/kind bug
/priority normal

**What happened**:
A cluster which had been woken up from hibernation was deleted and but stuck in the deletion flow at the `Initializing connection to Shoot` step.

**What you expected to happen**:
The cluster to be deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Hibernate existing or new cluster
2. Change `.spec` of shoot, e.g. a worker group
3. Wait for the reconciliation to beginn
4. Change `.spec.hibernation.enabled  = false` **during reconciliation**
5. Immediately delete shoot

After the first reconciliation you should notice that the shoot has `.status.hibernated: "false"` even though it's never woken up. As consequence, the deletion fails because Gardener never tries to wake up the control plane.

- Gardener version: v1.11.1

/cc @MartinWeindel

**Comment by ialidzhikov** [comment]
That explains the issue I was looking for yesterday. Thank you for creating this issue!

**Comment by rfranzke** [comment]
Is my understanding correct that the issue is the wrongly reported `.status.hibernated` field? Or is there more that needs to be adapted?

**Comment by timuthy** [comment]
> Is my understanding correct that the issue is the wrongly reported `.status.hibernated` field? Or is there more that needs to be adapted?

Yes, `.status.hibernated` is `true` even though the CP/Workers haven't been scaled down.

**Comment by danielfoehrKn** [comment]
The problem is, that we [here](https://github.com/gardener/gardener/blob/8d8680551021d79b28727e5fe186870abc26ef23/pkg/gardenlet/controller/shoot/shoot_control.go#L566) set the hibernation status based on the current spec.
We will have the same problem for the Seed name: if during a reconciliation someone changes the Seed name, after the first reconciliation, the seed is set incorrectly in the status. So a control plane migration will not happen.

I think we have two options here
1) After successful reconciliation, introduce  checks
      -  for the Seed name: does the Shoot exist on the Seed specified in `spec.seedName` ? E.g check shoot namespace exists. 
      -  hibernation status: is the control plane really hibernated?. E.g check if there are any running pods in the shoot ns in the Seed.
2) Do not allow updating those two fields during an active reconciliation e.g via admission plugin.

I tend towards 1) due to usability concerns, WDYT?

@rfranzke @timuthy 

EDIT: The same problem does not seems to exist for the SeedName as the Seed Object in the reconciliation flow is not updated during the flow. (@plkokanov @swilen-iwanow @vlvasilev)

**Comment by timuthy** [comment]
Thanks @danielfoehrKn for the analysis. Since option 2 really contradicts with the Kubernetes design principles that we follow, I also **vote for option 1**. We also can't expect Gardener clients to handle blocking spec updates and it'd be an incompatible change of a wide extent.

Another option besides checking the seed or the control plane, is to consult the cluster resource. It is written to the seed at the beginning of every reconciliation and we can be sure that the `.spec` there hasn't changed in the meantime. It sounds like a trick, but we already make use of it for health checks and the confine spec rollout feature [here](https://github.com/gardener/gardener/commit/e2f1e84288cc8ef9f209318a548aa1e60e7becd8).

**Comment by rfranzke** [comment]
Agreed to @timuthy, thanks. 
@danielfoehrKn, please keep the `.spec.seedName` logic untouched for now and focus on the hibernation problem. The colleagues implemented #1631 (@plkokanov @swilen-iwanow @vlvasilev) will handle this if necessary.

**Comment by danielfoehrKn** [comment]
> @danielfoehrKn, please keep the .spec.seedName logic untouched for now and focus on the hibernation problem. The colleagues implemented #1631 (@plkokanov @swilen-iwanow @vlvasilev) will handle this if necessary

Sure, just mentioned it so that we are aware of the problem.
