### ISSUE TITLE
need to monitor real time pod numbers

### ISSUE THREAD

**Issue by latituder** [gardener/gardener#2988]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/priority normal

**What would you like to be added**:
in Grafana dashboard `Node/Worker Pool Overview`, need to have a pod number count for each workgrop. please do not average it;
better, we can select a k8s namespace in this dashboard, so we can only shows the pod count in the namespace.

**Why is this needed**:
currently there is a `Average # of Pods on each Node in Worker Group(s) All`, it always shows flat cruve, even there was a high workload in seveal hours.
we run Jenkins Agents in the kubernetes cluster, would need to understand how many workloads does jenkins bring to this k8s cluster in certain time slot.

**Comment by timebertt** [comment]
Thanks for the enhancement request.

This sounds like a great first PR 😉 
The dashboard in question is located here: https://github.com/gardener/gardener/blob/60e30c8c077970a5f3d0e2871c70f9d65adedd55/charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Would you like to contribute this enhancement?

**Comment by timebertt** [comment]
One thing to note, though: the monitoring stack provided by gardener is supposed to give a good overview over the cluster status and it's system components for operators and shoot owners.
Though I think it makes sense to enable some common scenarios which might help many users and operators, it is not meant to serve as a general-purpose monitoring solution and doesn't relieve the shoot owners for deploying their own fully-fledged prometheus and so on for monitoring their workload.

/cc @wyb1 @istvanballok

**Comment by wyb1** [comment]
Hi @latituder the reason that you don't see an increase in the number of the pods is because we only track pods in the kube-system namespace. This should be made prominent and perhaps this panel is not very useful then and we can consider removing it. Like @timebertt said the monitoring stack provided by gardener is a not general purpose solution and recommend you deploy your own monitoring that fits your needs.

Edit: monitoring stack provided by gardener is a **not** general purpose solution
