### ISSUE TITLE
Shoot reconciliation failed with an error when attempting to update the worker status

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3119]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority normal

**What happened**:
During DoD activities, we noticed multiple errors where shoot reconciliation failed with an error when attempting to update the worker status. This is a transient error that disappears during one of the next retries. However, it may cause multiple clusters in all landscape to fail during a single day, spamming the "clusters with issues" view in the dashboard.

**What you expected to happen**:
No such errors.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, we don't know how to reliably reproduce the issue yet.

**Anything else we need to know?**:
* The dashboard error is similar to: `task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--hc-ci--577cd3-haas/577cd3-haas to become ready: extension encountered error during reconciliation: Error reconciling worker: failed to update the machine image status: timed out waiting for the condition`
* From the above error, it can be seen that the attempt to update the status of the worker resource with the machine images fails with "timed out waiting for the condition".
* The corresponding code in the generic actuator calls the function `UpdateMachineImagesStatus` (https://github.com/gardener/gardener-extension-provider-aws/blob/a21ad05e12c54de9385bf2eafbd138487e7e3808/pkg/controller/worker/machine_images.go#L29-L44), which fails with the above error.
* Unfortunately, the errors returned by this function are not wrapped and so it's hard to tell precisely which of the many calls fails. However, the most likely culprit is the update of the status of the resource itself (there are not too many other operations that could time out).
* We could not find any issues in `kube-apiserver` logs related to updating the worker status.

**Environment**:

- Gardener version: v1.12.3
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by timebertt** [comment]
> Perhaps a meaningful next step would be to wrap the relevant errors in the AWS provider extension (or even all extensions) in order to gain more information when such an error occurs again?

Yes, improving the logs is always a good idea. If you find a way to improve the error handling, so that the stack trace is more helpful, please do so :)

Also, I think it would be necessary to analyze the issue a bit deeper to find the root cause. I can think of the following points to start the investigation:
1. was the provider controller restarted at the time / leader election changed, the issue occurred? This might have caused a long wait for the cache sync, which might have timed out or something similar (just guessing, but needs to be checked)
2. was the API server available during the time of the issue?

At the end it might also be related to what you have observed in https://github.com/gardener/gardener/issues/3118 or https://github.com/gardener/gardener/issues/3108, which again we don't have any observability for...

**Comment by rfranzke** [comment]
Any objections closing this for now with the option to reopen if necessary/relevant again?

**Comment by timebertt** [comment]
Nope

**Comment by stoyanr** [comment]
@rfranzke Should we close this issue? It seems it was not observed any more and it has effectively become stale as well.
