### ISSUE TITLE
Validation of the configured feature gates of a shoot cluster and its k8s version

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#3140]
**How to categorize this issue?**

/area control-plane ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:
There should be a validation checking that the kubernetes version of a shoot cluster is compliant with the configured feature gates of the kubernetes API server, kubernetes controller manager, kubelet, kubernetes scheduler, kube-proxy. The cloud controller manager also supports custom feature gates but this validation should be executed by each provider extension, however the gardener extensions library can be enhanced with such generalized feature.

**Why is this needed**:
To avoid control plane components crashing with unknown feature gates. See this kube-apiserver logs for example:

```
Error: invalid argument "CustomResourceWebhookConversion=true,CSIMigration=true,CSIMigrationAWS=true" for "--feature-gates" flag: unrecognized feature gate: CustomResourceWebhookConversion
```

**Comment by rfranzke** [comment]
ℹ️ We have never done this on purpose (prevent the maintenance effort of duplicating all possible feature gates in our code base).

**Comment by timuthy** [comment]
This seems to become problematic with forceful K8s [version upgrades](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_versions.md#forceful-migration-of-expired-versions).

**Comment by rfranzke** [comment]
In a discussion round with @gardener/gardener-maintainers we decided to not introduce this validation with the main argument of @timuthy in https://github.com/gardener/gardener/issues/3140#issuecomment-724161061.

When a user configures invalid/non-existent feature gate then the logging stack can help him identify why his kube-apiserver is not starting up. All of this is only getting problematic when such a shoot is deleted because the `spec` is immutable after the shoot has a deletion timestamp, i.e., invalid feature gate configuration cannot be self-corrected by the end-user, hence, this results in ops effort.

We talked about options to not respect the feature gate configuration of the end-user (or, more general, any custom configuration at all) during shoot deletion, but this should probably be a conscious decision as feature gate (or other custom configuration) might change the cluster behaviour and could theoretically lead to orphaned resources. Still, there should probably be such an option, but we leave it to #3110 to tackle such scenarios and won't implement any custom logic for the feature gates now.

/close
