### ISSUE TITLE
Consider migrating from github.com/gobuffalo/packr/v2 to github.com/markbates/pkger

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3171]
When I was recently checking https://github.com/gobuffalo/packr/tree/master/v2, I saw the following statement in their README.md:

```
NOTICE: Please consider migrating your projects to github.com/markbates/pkger. It has an idiomatic API, minimal dependencies, a stronger test suite (tested directly against the std lib counterparts), transparent tooling, and more.

https://blog.gobuffalo.io/introducing-pkger-static-file-embedding-in-go-1ce76dc79c65
```

/kind cleanup
/priority normal

**Comment by rfranzke** [comment]
FYI: As part of the `OperatingSystemConfig` refactoring (#2754) I'm introducing https://github.com/go-bindata/go-bindata because packr was not used in gardener/gardener yet and, as it recommends to another tool anyways I considered `go-bindata` as best fit for my use-case for now. I'm planning to get rid of it again with Golang 1.16 and the new `//go:embed` feature.

Shall we generally close this issue in favor of the `//go:embed` coming with Golang 1.16?

**Comment by majst01** [comment]
I would also consider waiting for go 1.16 and use `//go:embed` instead, we at metal-stack will do the same.
