### ISSUE TITLE
Remediate broken shoot webhooks in care controller

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#3244]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:

@mandelsoft proposed to add a new controller (sitting in a dedicated component next to the Shoot's control plane), that will reconcile webhooks in the shoot, that will be problematic for different shoot operations (e.g. maintenance, hibernation, scale-up, ...). (ref https://github.com/gardener/gardener/issues/3122, https://github.com/gardener/gardener/pull/1642 and similar)

It should check all webhooks in the shoot, check [if they are problematic](https://github.com/gardener/gardener/blob/e4b9da08a17183d49197ffdd7759498f408451a6/pkg/operation/botanist/constraints_check.go#L102) and then either add
- a `namespaceSelector` excluding the `kube-system` namespace
```yaml
namespaceSelector:
  matchExpressions:
  - key: gardener.cloud/purpose
    operator: NotIn
    values:
    - kube-system
```
- or an `objectSelector` excluding objects managed by gardener (labelled with `origin=gardener`) (only supported by k8s v1.16+, I think)

Endusers should be able to opt out of this behaviour, if they have setup their webhooks properly (multiple backing replicas, PDBs and so on), for example by adding a special label to the webhook.
The controller should also annotate the webhooks it touches and explain what was changed / how to opt out.

We might think about adding more controllers to this new component in the future, so we should keep this in mind (e.g. also for naming...).

**Why is this needed**:

We often see endusers configuring problematic webhooks, which lead to issues for the mentioned shoot operations causing a lot of ops effort. The gardener operator shouldn't be concerned with such problematic user behaviour, so we should invest into some kind of automation to workaround those problems.

**Comment by timuthy** [comment]
I still believe that a shoot problem detector, analogue to the [node problem detector](https://github.com/kubernetes/node-problem-detector), is a real and a more independent alternative to add such checks.

**Comment by timebertt** [comment]
So, are you saying, that we shouldn't automatically add selectors to the problematic webhooks and just detect such webhooks and only put some additional conditions on the shoot?
Or is this only about the naming?

**Comment by rfranzke** [comment]
Yes, agreed, it makes sense to do it in a separate project and untangle it from the Gardener lifecycle. Again, already the naming (NPD and SPD) suggests that the approach proposed by @timuthy is right.

**Comment by timuthy** [comment]
> So, are you saying, that we shouldn't automatically add selectors to the problematic webhooks and just detect such webhooks and only put some additional conditions on the shoot?

Yes, only conditions, mainly because:
- We wouldn't need to touch the shoot owner's setup
- We wouldn't need another exception / opt-out mechanism ("The controller should also annotate the webhooks it touches and explain what was changed / how to opt out.")
- Components are free to decide how the condition is evaluated

**Comment by timebertt** [comment]
In another chat including @rfranzke and @timuthy, we found that we are not sure, what would be the best approach for this. Both approaches have their pros and cons:

Option a:
We detect problematic webhooks and set special conditions (or constraints) in the Shoot's status (similar to what we have already in place with the current constraints) but don't act on the problematic webhooks, which is similar to the node-problem-detector.
* \+ We wouldn't need to touch the shoot owner's setup
* \+ We wouldn't need another exception / opt-out mechanism ("The controller should also annotate the webhooks it touches and explain what was changed / how to opt out.")
* \+ Components are free to decide how the condition is evaluated (e.g. Dashboard can show warning to the Shoot owners)
* \- Dashboard is an optional component and users might not get aware of the configuration problems in case the dashboard is not available to them

Option b:
We do a) and additionally "fix" the problematic webhook configurations by adding label selectors as proposed above.
* \+ problematic configs can be automatically resolved, leading to less ops effort
* o can just act upon the condition/constraint from a) and thus be placed in a separate component/project/...

Notes regarding both options:
* unclear, how to detect webhooks that are configured to include system-components on purpose: maybe the backing webhook server is setup properly and the webhook isn't actually problematic


Happy to hear some additional opinions!
@vlerenc @ialidzhikov @vpnachev @mandelsoft

**Comment by rfranzke** [comment]
In more syncs we decided to go for option b) and allow the users to opt-out of this automatism of they need it. The whole feature should be optional and it should also be possible to disable it entirely for a shoot or maybe even a project.

**Comment by vlerenc** [comment]
Considering how much this problem is a nuisance to Gardener (see topic of VPN reversal where not even a proper web hook setup with PDBs and such would have helped...; then again, one could argue, that we could do the VPN reversal in two phases instead of one, which would be backward-compatible), and that all despite even Kubernetes' clear statement in https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace, I would also welcome option b), though I see @timuthy 's point clearly.

Some thoughts:
- Both topics, informing (a) and remediating, let's call it (b'), should be separated, so that we can switch on the former and later the latter.
- To not break anything accidentally, we can put down into the "breaking changes" section that activating (b') must be done with care. On our landscapes we can use the information from (a) to proactively approach all offenders before switching on (b') on already rolled out clusters or... with a new Kubernetes version (let's say 1.22 at the time of this writing), we can switch it on by default/regardless, because then users will notice when they validate their workload with a new Kubernetes version, which they must, that we have defined new rules for this game (safe moment to do such a thing).
- Then there is the topic of fighting controllers, ours vs. possibly an end user controller that both change the web hook configuration back and forth: here I would suggest to store a `spec` hash of the original web hook configuration somewhere (a resource) and not patch it again, if it was already seen with that hash in the past. In addition, we should flip a condition in the status to highlight to the end user and our ops (SRE/dev) that we couldn't apply a remediation and the cluster is potentially not stable (which is motivating to change said controller as end users prefer to have only healthy conditions). It's not perfect, but we cannot rewrite the code of the fighting controller either to end this vicious cycle that would otherwise keep the API server busy, which we do not want.

Hope that makes sense or WDYT?

Two more things:
- The cheapest solution in terms of "informing (a)" is to improve the already existing bot probe/self-diagnosis. But the real kicker is if Gardener/we implement (a) here, of course.
- We are talking here a lot about kube-system exclusion, but we may not always foresee ways to negatively impact us and it may come from a different angle altogether, e.g. some non-discriminatory daemonset or whatever that breaks the node. The more general means to detect that is to implement detectors that actually probe what may not fail to work, e.g. a network problem detector (like a node problem detector) that probes network connectivity (node to node, pod to pod, pod to service, etc.) and reports it as conditions at the node and (eventually) shoot state.

**Comment by vpnachev** [comment]
It looks like the community is working on a feature allowing some webhooks to work on other webhooks. 
Then we can add a validating webhook for validating and mutating webhooks that will reject create/update requests if they are affecting resources in the kube-system namespace. Our validating webhook might have an object selector so that users can skip this validation if they put a well-known label.
The webhook itself can be a sidecar container to the kube-apiserver deployment similar to the current `apiserver-proxy-pod-mutator`

We can even implement a mutating webhook  injecting a rule in the namespace selector of each webhook not matching the kube-system namespace.

Ref:
- https://github.com/kubernetes/kubernetes/issues/101794 
- https://github.com/kubernetes/kubernetes/pull/101815

**Comment by vlerenc** [comment]
@rfranzke Since this is an issue that is constantly causing trouble, what is the plan to help here? Gardener is sensitive to "wrong" web hooks, so what are we doing? Improving the UI https://github.com/gardener/dashboard/issues/1144 is then all we do or are there other tickets/plans?

**Comment by rfranzke** [comment]
The ticket is open since very long and nobody is currently working on it. Given this, the fact that there are doubts, and that I recently heard you saying (or writing) that "we don't want racy controllers", I decided to close the issue for now. Do you suggest to reopen it and implement such controller?
I think that the "webhook intercepting webhooks" feature linked by @vpnachev above would be a sustainable solution for our scenario, but unfortunately it seems the community closed the work on this topic (due to inactivity).

**Comment by vpnachev** [comment]
second attempt, `reopen` should be the right [command](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener#reopen) 
/reopen
