### ISSUE TITLE
enable vpa by default for newly created shoots (configurable)

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#3304]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/priority normal

**What would you like to be added**:

The `node-exporter` should be under VPA.

**Why is this needed**:

Static requests and limits do not make sense for the node exporter. The resource consumption of the node exporter greatly depends on the size/activity of the node. If the nodes are too large the node exporter will have issues. Increasing the requests and limits across the board for all node exporters will mean wasted resources for smaller nodes. 

**Potential Issues**:

VPA is not active in all shoots by default so we cannot have VPA for the node exporter unless it is configured in the shoot.

**Comment by rfranzke** [comment]
Hm, I'm confused, what is this issue about? What shall be implemented? VPA is an optional feature in shoots, and end-users can enable it if they want (also the system components) to vertically scale. For backwards-compatibility reasons we cannot enable it by default, but if it's enabled then the node-exporter gets put under VPA, see https://github.com/gardener/gardener/blob/master/charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/vpa.yaml

**Comment by wyb1** [comment]
I could have been more clear in the issue description. The question would be what can we do for shoots that do not have VPA enabled?

**Comment by rfranzke** [comment]
We could compute the resource requests/limits for node-exporter based on the used machine type, however, generally, we should rather motivate the users to enable the VPA for the shoot if they see scalability issues in the system components.

**Comment by hardikdr** [comment]
We faced this issue while testing the high-CPU workload on the MemoryOne machines. It seems the issue is 2-fold.
First, node-exporter gets short of resources for large machines, we saw CPU-spikes and in-general high-CPU utilization of the node-exporter pod during tests. This is solvable by simply enabling VPA for the shoot.

Second, the current live-ness probes of `5s` for the node-exporter is too small for large machines. We observed a delay-time of around `10s` sometimes for it to respond(feedback from user). 
- This leads to probe-failure and some burden on the dockerd at last.
- We could increase the live-ness probe of the node-exporter to a larger value ~15s in general or set it according to the machine-size.

@wyb1  Only out of curiosity is it already known that node-exporter is expected to consume more resources for larger machine-sizes, may be due to it's nature?

**Comment by wyb1** [comment]
> Only out of curiosity is it already known that node-exporter is expected to consume more resources for larger machine-sizes, may be due to it's nature?

It is tracking many different aspects of the node so it is not surprising that large nodes with more activity would require more resources. You can see the active collectors [here](https://github.com/prometheus/node_exporter/blob/master/README.md#collectors). Some collectors might be consuming might be causing a bottleneck so those would also be worth looking into

**Comment by rfranzke** [comment]
@hardikdr @wyb1 What's your proposed follow-up action here? We have VPA already if the user enables it. Do you still want to compute proportional resource requests/limits based on the machine type? The down-side of this would be that we probably would need one `DaemonSet` per worker pool.

**Comment by rfranzke** [comment]
ping @hardikdr @wyb1

**Comment by hardikdr** [comment]
Sorry, missed it earlier.
No concrete proposal from me, I'd say we can hold on to this until we have a clear requirement from the user, as I remember the user also suspected certain configuration in kubelet could be a reason for the behavior they saw.

**Comment by wyb1** [comment]
I think we can close this issue. We can add a dashboard for CPU throttling. This way a user can help themselves by seeing if the node exporter is getting throttled and add their own VPA or use ours for the node-exporter.

**Comment by vlerenc** [comment]
Hmm... doesn't it make sense to do this @wyb1 (like we did in the early days without proper auto-scaling)?

> We could compute the resource requests/limits for node-exporter based on the used machine type

---

> The down-side of this would be that we probably would need one DaemonSet per worker pool.

@rfranzke Why is that?

**Comment by rfranzke** [comment]
@vlerenc because a shoot can have multiple worker pools with different machine types, so one DaemonSet with some statically computed resource requests/limits wouldn't work in all cases.

Still, I'm wondering why we want/have to do this in the first place. We offer VPA and it should do all all of this for us. Is there a reason why the user cannot enable it? Should we start enabling it by default for new clusters with a future Gardener version?

**Comment by vlerenc** [comment]
> @vlerenc because a shoot can have multiple worker pools with different machine types, so one DaemonSet with some statically computed resource requests/limits wouldn't work in all cases.

🤦  Sure, yes.

> Still, I'm wondering why we want/have to do this in the first place.

How are the others doing it? Not all hyperscalers ship with VPA and also not by default. But then again, via dedicated daemon sets possibly.

> We offer VPA and it should do all all of this for us. Is there a reason why the user cannot enable it?

Tell me. :-) Back then we thought, because the user may already have one deployed on his own, right? What's our take on this, because...

> Should we start enabling it by default for new clusters with a future Gardener version?

...otherwise I would also be for default enablement.

**Comment by rfranzke** [comment]
Yes, this was the only reason why we did not enable it by default, i.e., to be "backwards compatible" in case somebody already deploys his own PR. However, as it improves the general quality of the cluster and also releases the burden of running the VPA from end-users, it should be a good step to enable it by  default for new clusters. We can make this behaviour configurable in the gardenlet so that operators can announce early and allow enough time for end-users to adapt. OK?

**Comment by vlerenc** [comment]
Yes, very reasonable, thank you @rfranzke @wyb1.

**Comment by rfranzke** [comment]
/title Enable VPA by default for newly created shoots (configurable)
/assign

**Comment by timebertt** [comment]
After a quick chat with @rfranzke about this, I will take over and implement this via an admission plugin as proposed in #3461.
/assign
