### ISSUE TITLE
New Gardener project role for accessing, downloading and rotating the super admin kubeconfig/secret

### ISSUE THREAD

**Issue by donistz** [gardener/gardener#3419]
**How to categorize this issue?**
/area security
/kind enhancement
/priority critical

**What would you like to be added**:
A new Gardener role that will segregate the permissions to access, download and rotate the kubeconfig/secret of the super admin user of the shoot cluster
**Why is this needed**:
There are two APIs that can be used to manage shoot cluster resources: The Gardener API and Kubernetes API.
When a shoot cluster is created all users with Gardener project role "Admin" get access to see, download and rotate the super admin kubeconfig and all other admin activities for the cluster.
To improve the default security for Kubernetes clusters management via Gardener, it is necessary to segregate in a separate role the access to the super admin kubeconfig/secret that grants full anonymous access to the shoot cluster. This way there could be gardener project members with admin access who can perform admin activities via the Gardener API but will have to be explicitly granted access to the Kubernetes API for the shoot clusters. At the moment every project admin has access to the super admin secret. The alternative to the admin role is a role called "viewer" and grants only display access via the Gardener API. At the moment the project owners cannot regulate easily the access to the super admin secret without implementing custom permissions in their project namespace and assigning them manually via the Gardener API to individual project members.
When a new project is created, this new role must be assigned always only to the Owner of the project. The Owner or a user with UAM permissions will be able to assign the new role to other members of the project. For backwards compatibility the role should be assigned also to all project members and service accounts who will have "admin" role at the moment of the implementation of this improvement. The project owner will have to decide if the role has to be remove from some of the members/service accounts later.

**Comment by timuthy** [comment]
Did I get it correctly that you suggest to split the `admin` role into the following two roles?
- Admin (e.g. `ProjectOperator`) who only manages assets in the project namespace of the Garden cluster
- Admin (e.g. `ShootAdmin`) who has full access to the shoot cluster

**Comment by donistz** [comment]
> Did I get it correctly that you suggest to split the `admin` role into the following two roles?
> 
> * Admin (e.g. `ProjectOperator`) who only manages assets in the project namespace of the Garden cluster
> * Admin (e.g. `ShootAdmin`) who has full access to the shoot cluster

Yes, this is absolutely what I mean.

**Comment by vlerenc** [comment]
Link to current roles: https://github.com/gardener/gardener/blob/master/docs/usage/projects.md

If that is the main driver, won't #999 help solving the problem? Because, once we have that, we would have no `*.monitoring` secret anymore and could use RBAC to limit access. The two other secrets, `*.kubeconfig` and `*.ssh-keypair` would then be available only to admins. Viewers (according to https://github.com/gardener/gardener/blob/master/docs/usage/projects.md) could then access Grafana/Prometheus.

**Comment by vlerenc** [comment]
@donistz Isn't the main driver, that some teams want to enable their ops colleagues to access Grafana/Prometheus without being able to download the admin kubeconfig for the cluster with full permissions?

If that is the main driver, won't #999 help solving the problem? Because, once we have that, we would have no `*.monitoring` secret anymore and could use RBAC to limit access. The two other secrets, `*.kubeconfig` and `*.ssh-keypair` would then be available only to admins. Viewers (according to https://github.com/gardener/gardener/blob/master/docs/usage/projects.md) could then be allowed to access Grafana/Prometheus.

**Comment by donistz** [comment]
> @donistz Isn't the main driver, that some teams want to enable their ops colleagues to access Grafana/Prometheus without being able to download the admin kubeconfig for the cluster with full permissions?
> 
> If that is the main driver, won't #999 help solving the problem? Because, once we have that, we would have no `*.monitoring` secret anymore and could use RBAC to limit access. The two other secrets, `*.kubeconfig` and `*.ssh-keypair` would then be available only to admins. Viewers (according to https://github.com/gardener/gardener/blob/master/docs/usage/projects.md) could then be allowed to access Grafana/Prometheus.

No, Here the main driver is to limit the access to a super admin secret and to be able to control the full admin access to the shoot cluster easier. The actual requirement was some admins to be able to change the shoot yaml but to not be able to access the nodes via a terminal and create privileged pod on a node.
The SSO for Grafana will not resolve such problem. Here it is necessary to segregate the access to manage the control plane from the access to administer the workload.

**Comment by rfranzke** [comment]
Cross-ref: #3138

**Comment by vlerenc** [comment]
OK, got it @donistz . But it's still confusing... and I want to avoid a proliferation of roles. P.S.: The `admin` role with the current UAM restriction is already confusing (an admin that cannot administer other members).

@rfranzke cross-referenced #3138. Why is `viewer` not OK? But actually, that's not even the real ask. They seem to be fine with the `admin` role in general, but they want rotation and what they cannot rotate is the Gardener generated admin kubeconfig. Only therefore they don't want to see it anymore. What we actually need to support is rotation and maybe we have to do that eventually anyhow.

Because otherwise, I would find it super confusing to have another role, let's say `demoted-admin`, that can do what the `admin` can, but cannot download the kubeconfig, because:
- Such admins can still create technical users with full access, right?
- Even worse, they can change the shoot spec, which can break everything, but it can also be used to gain access by manipulation of `oidcConfig` and making sure to hide the audit trail by manipulation of `auditConfig` and then they can also manipulate the networking including DNS to do all kind of nasty things.

So, I am wondering wether that really is what the end users want. We cannot create individual roles for each and every permission/field/bit of information that people want to access, can we? And if it's open like a Swiss cheese it's only superficial security we create. Maybe sufficient for an audit and these checkbox checkers, but no hinderance for an attacker.

**Comment by rfranzke** [comment]
What about this issue? Is there still something concrete to be done or can we close it?
