### ISSUE TITLE
Cloud Credentials on the Nodes are not Updated During Deletion Flow

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#3420]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority normal

**What happened**:
The cloud credentials for an (openstack) cluster has expired, its was set for deletion and later the valid credentials were provided. 
All secrets using the cloud credentials on the seed were properly updated, however the OperatingSystemConfig are not reconciled during the deletion, thus the credentials on the Nodes used by kubelet are not updated. 

Due to the usage of invalid credentials, the cloud provider starts rate limiting the serviceaccount/technical user which results in kube or cloud controller managers not able to start up. Also, the MCM is failing to send the deletion request. 

**What you expected to happen**:
The cloudprovider credentials to be updated on the nodes during the deletion flow.
My understanding is that the following steps needs to be executed during the deletion
1. reconcile the OperatingSystemConfig resources
1. re-deploy the ManagedResources
1. re-deploy the resource manager (probably already ensured by some other step).

These steps should ensure that the `kube-system/cloud-config-<worker-pool-name>-*` secrets in the shoot cluster contains the latest cloud provider credentials.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The above was observed on several openstack clusters sharing the same credentials. Their versions was <=1.18, i.e. they were not running with CSI but with the built-in cinder volume provider. 

**Environment**:

- Gardener version: 1.14.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
  - provider-openstack:  v1.14.1
  - shoot's k8s: v1.16

**Comment by rfranzke** [comment]
This issue is open since quite a long time without anyone picking it up or any attention at all. @dkistner @kon-angelo @MartinWeindel any opinion?
IIUC, this is only relevant for OpenStack shoots < 1.19 since higher versions use CSI and wouldn't run into this issue, correct? If so, given that we have dropped support for shoots < 1.17 with #5272 while 1.17/1.18 are already rarely used/out-of-maintenance and this issue didn't have any activity since a year, it seems to not make too much sense to invest into this now?
