### ISSUE TITLE
BackupBucket Controller Enhancements

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#3491]
**How to categorize this issue?**

/area scalability
/area robustness
/kind enhancement
/priority normal

**What would you like to be added**:

- [ ] Seed Control BackupBucket in Gardener Controller Manager
    - On Seed creation: Create new BackupBucket for new Seed (move out logic from [here](https://github.com/gardener/gardener/blob/437ab664ce84ea6ff63f48abfeba7e1006f59a5f/pkg/gardenlet/controller/seed/seed_control.go#L366))
    - On Seed deletion: Check if BackupBucket is still being referenced by BackupEntries
        - At least one BackupEntry w/o `DeletionTimestamp`:  🗣️ TBD, BackupBucket must be moved to another seed (see #1428). We don't want to block Seed deletion until all Entries are gone. With control plane migration (#1631), entries might [refer to a "remote" bucket](https://github.com/gardener/gardener/blob/437ab664ce84ea6ff63f48abfeba7e1006f59a5f/pkg/operation/operation.go#L517:21) as long as they exist. Thus, buckets cannot simply be deleted like done today ([ref](https://github.com/gardener/gardener/blob/437ab664ce84ea6ff63f48abfeba7e1006f59a5f/pkg/gardenlet/controller/seed/seed_control.go#L225)) /cc @plkokanov @kris94 @stoyanr.
        - All BackupEntries w/ `DeletionTimestamp`: Retain BackupBucket until all entries are deleted
        - No BackupEntries: Delete BackupBucket
- [ ] Secret -> BackupBucket mapper for BackupBucket controller
    - Enables that if a BackupBucket related secret is changes, the BackupBucket is enqueued and reconciled asap. Required for properly rolling credentials.
- [x] Seed BackupBucket Conditions (https://github.com/gardener/gardener/pull/3531)
   - Introduce a new "secondary" controller in the pkg/gardenlet/controller/seed package which watches BackupBuckets and enqueues the referenced Seed when an event is triggered. Then, this Seed is reconciled (via a new, smaller reconciliation function (not the big one which also bootstraps)) in the sense that all BackupBuckets referenced it are checked for readiness. It then maintains the `BackupBucketReady` condition for the seed (/cc @rfranzke)

**Why is this needed**:

The listed implementations are needed to overcome current shortcomings in the `BackupBucket` handling and to enable proper seed management in the future when we expect shoots being migrated and seeds being added and removed more regularly.

**Comment by vlerenc** [comment]
I'd like to mix in a (new?) requirement @timuthy: all seeds shall have their own backup bucket to which only they have access to (individual credentials with access only to "their" shoot backups/data), so that no seed can read the shoot backups from another seed and attackers can traverse laterally through all shoots.

That will have impact on control plane migration, I guess, as it was implemented under the assumption, that the new seed can read the backup from the old seed's backup bucket. Is that right @plkokanov? If so, we need a concept to overcome that. Obviously, central components like GCM cannot help, because the seeds and their backup buckets may be behind a firewall. So, we need either to issue temporary credentials with locked down permissions, but that's maybe not even possible (a.) we may/should not have IAM access to issue new credentials and b.) I don't know whether path-based ACLs are supported everywhere) or the keys to the old backup bucket are handed out by GCM to the new seed only temporarily, i.e. they never get stored in the seed and remain in memory until the copy operation from one backup bucket to another is completed.

WDYT?

**Comment by timuthy** [comment]
That's a good point @vlerenc, although I think that the BackupBucket (BB) is not the main problem here but rather the BackupEntry (BE). In the end, the BE holds a reference to a copied secret of the BB from the Garden cluster.

What if we migrated BEs from bucket A -> B? Actually, we don't need to move any data between the buckets but keeping the entry in bucket A long enough to ensure that another full backup has already been saved to bucket B.

**Comment by vlerenc** [comment]
Yes, as you say, that the credentials are stuffed into the BE comes on top. My main point was that no seed shall be able to read backups of shoots hosted by another seed. So, when we improve what you described, which is anyway reasonable (we don't want to have backups left and right of the actual seed that hosts some shoots), e.g. so that we can safely delete a seed eventually, then we should also incorporate the security question in the concept. The new seed should only temporarily have access to the old backup and "copy it over" before it executes/finishes the migration flow. After the migration, there should be no left-overs/residual data (especially no credentials) to anything of the old seed. Seeds have to be treated as isolated security domains.

@plkokanov @kris94 @stoyanr WDYT? How can this be done (see above) as securely as possible?

**Comment by plkokanov** [comment]
Also for the "Bad Case Scenario" the etcd `backup-restore` in the new seed needs to have access to the backup directories of the shoot cluster in order to write which is the current 'master' seed so that the `backup-restore` in the old seed can read them (if we completely move the backups from the old to the new seed then we could use the fact that the backup is missing to inform the old seed that it is no longer the master)
These credentials, to get the backups from the old seed, would only be required once during the start of the etcd and its `backup-restore` sidecar and can be removed afterwards. Then we could let the `backup-restore` create new backups in the new seed's backup bucket instead of moving them by some other mechanism.

**Comment by amshuman-kr** [comment]
> (if we completely move the backups from the old to the new seed then we could use the fact that the backup is missing to inform the old seed that it is no longer the master)

The way things are, this would be indistinguishable to the old `etcd-backup-restore` (if it is still running) from a new etcd starting up. So, we will still some kind of handshake to inform the old instance that this is the migration scenario.

**Comment by plkokanov** [comment]
Oh yeah, it would try to create a backup first, and that would succeed. For some reason I was thinking only about fetching backups :/

**Comment by vlerenc** [comment]
> then we could use the fact that the backup is missing to inform the old seed that it is no longer the master)

@plkokanov Yes, I would think so.

> The way things are, this would be indistinguishable to the old etcd-backup-restore (if it is still running) from a new etcd starting up. So, we will still some kind of handshake to inform the old instance that this is the migration scenario.

@amshuman-kr Right, the handshake can be fairly simple like a file in the backup folder marking it accordingly and after the backup was transferred, it can be removed, so that we don't leave traces. When the seed comes only again (if ever), it can auto-clean the "hollow" backup.

> Oh yeah, it would try to create a backup first, and that would succeed. For some reason I was thinking only about fetching backups :/

Hmm... what do you mean? When we migrate a control plane, we have to have the backup first to reinitialise ETCD from it. I somehow would think, it's safer and easier, if a central component (in the garden namespace or wherever) in the seed does the "backup content migration" and when the new shoot control plane starts up, it finds the backup already in the right spot (and has at no point in time access to the credentials of the old seed's backup bucket).

**Comment by plkokanov** [comment]
> Hmm... what do you mean? When we migrate a control plane, we have to have the backup first to reinitialise ETCD from it. I somehow would think, it's safer and easier, if a central component (in the garden namespace or wherever) in the seed does the "backup content migration" and when the new shoot control plane starts up, it finds the backup already in the right spot (and has at no point in time access to the credentials of the old seed's backup bucket).

I was talking about the backups for the __Source Seed__. But let me see if I actually understood @amshuman-kr correctly: 

After the backup has been transferred and the backup directory for the __Source Seed__ is empty (or non existant), if there is nothing else indicating that the __Source Seed__ is no longer the master (due to any network problem, for instance), the etcd `backup-restore` in the __Source Seed__ (if it still exists) would just create a new backup file.

**Comment by vlerenc** [comment]
Yes, I speak of both, source and destination @plkokanov .

> After the backup has been transferred and the backup directory for the Source Seed is empty (or non existant), if there is nothing else indicating that the Source Seed is no longer the master (due to any network problem, for instance), the etcd backup-restore in the Source Seed (if it still exists) would just create a new backup file.

See my previous reply: If we leave the old backup there or delete the folder, the backup sidecar would continue. That's why Amshu and I suggest a little "handshake", which could be a file with a certain name or whatever. Then again, it doesn't actually matter too much, because eventually this seed will be fully terminated or will get back online again and will then deschedule the shoot anyway. So, maybe there is also no harm in continuing the backups, but I think this little handshake is no big deal.

**Comment by plkokanov** [comment]
I think we're all saying the same thing here but just to be complete: my point was that if the backups in the source seed continue, the etcd `backup-restore` wouldn't terminate and that would mean that MCM and other controllers would continue working so there's a possibility we could run into a split brain scenario.
As far as I understand that's why we would need the "handshake" (I wasn't arguing against it :) )

**Comment by amshuman-kr** [comment]
Sorry for the delay. I agree we are talking about pretty much the same thing. Making sure that source backup-restore goes down as early as possible/workable seems to be a good thing to avoid other downstream issues of keeping it potentially running until the source seed heals and deletes the source shoot control plane.

In my review comments in https://github.com/gardener/gardener/pull/3066#pullrequestreview-524994890, I had proposed changes to address this (including changes to druid and backup-restore components). Can you please see if it still make sense?

**Comment by amshuman-kr** [comment]
To be clear, https://github.com/gardener/gardener/pull/3066#pullrequestreview-524994890 had re-use of the same backup storage across seeds (after migration). So, we can make suitable changes considering that we no longer want to re-use the backup storage across seeds.

**Comment by timuthy** [comment]
> So, we can make suitable changes considering that we no longer want to re-use the backup storage across seeds.

+1

That was also the consideration I had in a discussion with @vlerenc and will simplify the architecture a lot.

@plkokanov in the scope of migration, would you be willing to take over implementing the "Seed Control BackupBucket in Gardener Controller Manager" mentioned in the issue?

**Comment by plkokanov** [comment]
@timuthy yep I think I can take care of that. I could later on cover any changes in the BackupEntry migration to migrate the etcd data as securely as possible.

**Comment by timuthy** [comment]
Awesome, thank you!!
/assign @plkokanov

**Comment by rfranzke** [comment]
@plkokanov can you provide the current status here?
