### ISSUE TITLE
Kubernetes Version Configurability per Worker Pool

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#3501]
**What would you like to be added**:
Today, end users can define the OS version per worker pool, but not the Kubernetes version. I.e., while they can create themselves a new worker pool with a new OS and orchestrate a careful migration of workload (brownfield/legacy apps that have individual "planned maintenance time window" where the cluster-global maintenance time window won't help), they cannot do that for a Kubernetes minor version update (patch updates are executed in-place, but due to effort/risk this is not supported for minor versions, yet).

Therefore, it would be great to support "pinning" the Kubernetes version also per worker pool:
- A skew of 2 versions is permitted (see https://kubernetes.io/docs/setup/release/version-skew-policy)
- We want to flag this feature, as also others do, as supported only during upgrades and not in general (which would speak for a skew of only one minor version for a limited amount of time)
- We should validate the shoot spec and allow a skew only if there is a specific `kubelet` configuration for that worker pool or none at all for the cluster in general (otherwise end users may forget to copy it to the old worker pool when they adapt the global `kubelet` configuration to the new Kubernetes version that wouldn't fit the old Kubernetes version anymore)

**Why is this needed**:
To allow end users to execute "gentle" Kubernetes version minor version upgrades where they can much better control the transition of workload from old to new worker nodes.

/cc @amshuman-kr @rfranzke @vpnachev @dguendisch

**Comment by timebertt** [comment]
Should kube-proxy (and maybe other system components that run per node like `csi-driver-node`) be on the same version like the kubelet?
If that's the case, it will be a bit tricky to orchestrate that for components managed by extensions.

**Comment by rfranzke** [comment]
From https://kubernetes.io/docs/setup/release/version-skew-policy/:

> kube-proxy must be the same minor version as kubelet on the node.

We knew it would come some day, so it seems that we have to split the today single kube-proxy `DaemonSet` into a dedicated `DaemonSet` per worker pool. 👀

**Comment by vlerenc** [comment]
P.S.: Only briefly touched in the ticket description and not strongly related, but from out-of-band communication, it seems possible to offer in-place upgrades of minor versions as well, right? I don't think a ticket exists yet for that, right?

**Comment by rfranzke** [comment]
From https://kubernetes.io/releases/version-skew-policy/#kubelet-1:

> Note: Before performing a minor version kubelet upgrade, drain pods from that node. In-place minor version kubelet upgrades are not supported.

**Comment by majst01** [comment]
> P.S.: Only briefly touched in the ticket description and not strongly related, but from out-of-band communication, it seems possible to offer in-place upgrades of minor versions as well, right? I don't think a ticket exists yet for that, right?

This is an issue our customers also often raise, but i am currently strong against such a possibility because:
- as @rfranzke already pointed its not supported
- even if technically possible, beside being supported, will end in a cat like k8s cluster usage which i strongly discourage

**Comment by vlerenc** [comment]
Ha, I never noticed. Thanks for sharing @rfranzke. That's an excellent argument and I agree of course @majst01. Some kind of chaos engineering, at least every 4 months, certainly helps the apps to not get too lazy/complacent.

Also, it helps to get a clean slate now and then and fight drift, which is also from security perspective helpful (at least every 4 months a potential attacker has to vacate her home/machine, if the cluster owner let them in accidentally).

**Comment by rfranzke** [comment]
/reopen

During the review of #4971, @danielfoehrKn [pointed out](https://github.com/gardener/gardener/pull/4971#issuecomment-965356076) that the provider extensions need to be adapted to support this feature in all cases. Especially those with CSI migration logic need "special care".

When looking at https://github.com/gardener/gardener/pull/4971#issuecomment-965356076, there are multiple ways to tackle the problems:

### Approach 1

1. Adapt `csimigration` extensions library package to only
    1. start CSI migration only if all Kubernetes versions have reached minimum.
    2. complete CSI migration as usual.
    3. enable CSI and claiming it as complete only if all versions are higher.

   ℹ️ _This is to prevent splitting the `csi-driver` `DaemonSet` into a dedicated `DaemonSet` per worker pool (similar to what was done for `kube-proxy` with #4969) since it is (a) unclear whether this works in the first place, and (b) makes the entire scenario even more complex and error-prone._
2. Revendor above change in all provider extensions with CSI migration
3. Consider correct kubelet version (of this pool) when computing feature gates for CSI migration.

### Approach 2

1. Add some validation, i.e., only allow having separate versions per worker pool if control plane version is larger than CSI migration version+1 (for example, for AWS the CSI migration version is 1.18, so only allow separate worker pools when the control plane version is 1.20 or higher).
2. Consider correct kubelet version (of this pool) when computing feature gates for CSI migration.

### Approach 3

1. Add some even more restrictive validation, i.e., only allow having separate versions per worker pool if control plane version is equal or larger than the highest version which has impact on the CSI migration version (for example, for AWS the highest version with impact on CSI migration version is 1.21, so only allow separate worker pools when the control plane version is 1.21 or higher).

### Decision

Both approaches 1 and 2 have the downside that the webhook mutating the kubelet configuration only operates on `OperatingSystemConfig` resources, i.e., it is not aware of the Kubernetes version (of this pool). Consequently, approach 3 has the least implementation effort (though, it has the highest restrictions).

For approach 3, however, the downside is that extensions might need information about the Kubernetes version of the kubelet (of this pool) anyways to take educated decisions (not only for CSI migration purposes, but maybe also when setting flags or feature gates).

Due to this, following approach 1 seems favourable since changes in the extensions library are anyways required (hence, revendoring of the extensions is inevitable; thus, "prolonging" the rollout/usability of this feature is unavoidable). Approach 2 is discarded since it just imposes artificial limitations whilst not "speeding up" the rollout.

### Plan

- [x] https://github.com/gardener/gardener/pull/5437
- [x] Extend `kubelet` service unit in original `OperatingSystemConfig` with information of the Kubernetes version (gardenlet).
- [x] Adapt the `controlplane` extensions webhook mutator to pass this Kubelet version to the ensurer. (https://github.com/gardener/gardener/pull/5256)
- ~Adapt the `csimigration` extensions controller package to only~
    ~1. start CSI migration only if all Kubernetes versions have reached minimum.~
    ~2. complete CSI migration as usual.~
    ~3. enable CSI and claiming it as complete only if all versions are higher.~
- [x] Add documentation explaining that extensions should validate that worker pool Kubernetes versions may only differ from control plane Kubernetes version when CSI migration version is reached.
- Revendor this change
   - [x] `provider-alicloud` (https://github.com/gardener/gardener-extension-provider-alicloud/pull/422)
   - [x] `provider-aws` (https://github.com/gardener/gardener-extension-provider-aws/pull/478)
   - [x] `provider-azure` (https://github.com/gardener/gardener-extension-provider-azure/pull/428
   - [x] `provider-gcp` (https://github.com/gardener/gardener-extension-provider-gcp/pull/381
   - [x] `provider-openstack` (https://github.com/gardener/gardener-extension-provider-openstack/pull/383)
   - [x] `provider-equinix-metal` (https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/188)
   - [x] `provider-vsphere` (https://github.com/gardener/gardener-extension-provider-vsphere/pull/200)
- Adapt the `controlplane` webhooks for all provider extensions to consider the “correct” version in conditions and document support.
   - [x] `provider-alicloud` (https://github.com/gardener/gardener-extension-provider-alicloud/pull/424)
   - [x] `provider-aws` (https://github.com/gardener/gardener-extension-provider-aws/pull/479)
   - [x] `provider-azure` (https://github.com/gardener/gardener-extension-provider-azure/pull/429)
   - [x] `provider-gcp` (https://github.com/gardener/gardener-extension-provider-gcp/pull/382)
   - [x] `provider-openstack` (https://github.com/gardener/gardener-extension-provider-openstack/pull/384)
   - [x] `provider-equinix-metal` (https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/191)
   - [x] `provider-vsphere` (https://github.com/gardener/gardener-extension-provider-vsphere/pull/202)
- Adapt the validation of all provider extensions performing CSI migration to prevent different worker pool Kubernetes versions (compared to control plane version) when CSI migration version is not reached.
   - [x] `provider-aws` (https://github.com/gardener/gardener-extension-provider-aws/pull/479)
   - [x] `provider-azure` (https://github.com/gardener/gardener-extension-provider-azure/pull/429)
   - [x] `provider-gcp` (https://github.com/gardener/gardener-extension-provider-gcp/pull/382)
   - [x] `provider-openstack` (https://github.com/gardener/gardener-extension-provider-openstack/pull/384)

**Comment by rfranzke** [comment]
While looking into the adaptation of the `csimigration` controller I figured that above approach would not work since the entire CSI migration process leverages the fact that we perform a rolling update of all (!) nodes during the migration. If we'd only start the CSI migration when all Kubernetes versions have reached minimum then there might still be pools whose version hasn't changed, i.e., pools whose nodes wouldn't be rolled out.

I guess it's safer to simply add some validation in the extension admission components with CSI migration to only allow having worker pool Kubernetes versions lower than the control plane version if the worker pool version is at least the CSI migration version.
For example, for AWS the CSI migration version is `1.18`, so we'd only allow to have pools with `1.18` or higher while the control plane version must be at least `1.18` or higher as well, e.g. `control plane=1.20, pool1=1.19, pool2=1.18` but not `control plane=1.19, pool1=1.18, pool2=1.17`.
This ensures that the CSI migration process and roll out is triggered like today when the shoot cluster is updated to the CSI migration version (in AWS case from `1.17` to `1.18`). After this is completed, the user is free to pin/have different versions for the pools for the Kubernetes versions to come.

The above plan is adapted accordingly.

**Comment by majst01** [comment]
Luckily our metal-stack csi provider was always out-of-tree.

**Comment by rfranzke** [comment]
Yes :-) For you, only the first part of #5256 could be relevant
