### ISSUE TITLE
Seed unbootstrap fails with "could not find image gardener-resource-manager"

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3513]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority critical

**What happened**:
Seed unbootstrap fails with:
```
Failed to unbootstrap Seed Cluster (could not find image "gardener-resource-manager" opts runtime version v1.18.14 target version v1.18.14).
```

**What you expected to happen**:
Seed unbootstrap succeeds.

**How to reproduce it (as minimally and precisely as possible)**:
Register a seed, allow it to bootstrap successfully, then delete it to trigger the unbootstrap.

**Anything else we need to know?**:
Caused by #3445 that was merged recently. The code at https://github.com/gardener/gardener/blob/0557bd7414facc5627b0f97e3175abb72ac3a11b/pkg/operation/seed/seed.go#L861-L864 tries to find the "gardener-resource-manager" image in the image vector. This is ok during bootstrap, but during unbootstrap the passed image vector is `nil` (see https://github.com/gardener/gardener/blob/0557bd7414facc5627b0f97e3175abb72ac3a11b/pkg/operation/seed/seed.go#L835), which causes the above error.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by BeckerMax** [comment]
The initial issue would be fixed with: https://github.com/gardener/gardener/pull/3518

But we discovered a more fundamental issue that needs to be addressed:
By refactoring the gardener resource manager into component form we now require to define dependencies in the deletion flow. Specifically, the grm needs to be deleted *after* all components that rely on the grm got deleted. The current Seed deletion flow does not support dependencies.
After a discussion with @timuthy we decided to implement a flow graph similiar to shoot_control.go and shoot_control_delete.go for Seed (de-)bootstrapping. This issue will stay open until that is merged.

**Comment by rfranzke** [comment]
Yes, the GRM is (hopefully the only?) special component in the seed reconciliation: It needs to be deployed first and deleted last, obviously without the means of a `ManagedResource` but via the normal Kubernetes Go client applier. All other components can then be created/deleted in parallel by leveraging `ManagedResource`s.
