### ISSUE TITLE
Pinning of system components

### ISSUE THREAD

**Issue by cbarbian-sap** [gardener/gardener#3537]
Today, Gardener deploys a bunch of workloads (let's call them 'system components') into kube-system namespace.

While most or all of them run with a high priority class (which is good) it would be in addition desirable to pin these workloads to certain worker groups. It seems that this was already (partially) addressed when the worker spec field `systemComponents.allowed` was introduced (which is defaulted as true). However in the current logic (https://github.com/gardener/gardener/blob/efb517ac8e2b4efc464c95c049c770367df1b058/pkg/apis/core/validation/shoot.go#L1169), when electing nodes for system components, Gardener considers only worker pools for which this flag is true *and* which have no strict taints. 

But naturally, if one would pin system components to a particular 'system' worker group, this group would be probably (heavily) tainted, to prevent regular workloads from going there. Which makes the `systemComponents.allowed` flag kind of useless.

The requirement is to specify certain (even strict) taints as tolerable for Gardener's system components, to allow them to run on a worker group with `systemComponents.allowed == true` even if it carries strict taints.

**Comment by vpnachev** [comment]
There are some system components that must run on each node and they cannot be isolated to a specific worker pool.
Could you name the components that you do not want to run the special worker pool?

**Comment by cbarbian-sap** [comment]
Of course, daemon sets excluded. But for all others ...

**Comment by vpnachev** [comment]
> Could you name the components that you do not want to run the special worker pool?

**Comment by cbarbian-sap** [comment]
All current (and yet unknown future) non-daemonset workloads that Gardener deploys ...

**Comment by vpnachev** [comment]
This does not help. 
You can check https://github.com/gardener/gardener/issues/2462 and the related PRs to see which components and why were considered as node critical and hence runs everywhere. 

/close

**Comment by rfranzke** [comment]
> The requirement is to specify certain (even strict) taints as tolerable for Gardener's system components, to allow them to run on a worker group with systemComponents.allowed == true even if it carries strict taints.

Hm, wouldn't it be good enough if Gardener would simply add [the taints which are specified on the "system" worker pool](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L64-L67) as tolerations to the deployments? All of them? Then there is no need to explicitly configure the tolerations via a separate field. This would also be backwards-compatible with the current behaviour and should allow for all use-cases (the current and the one envision by @cbarbian-sap)?

**Comment by vpnachev** [comment]
Isn't it getting a bit complicated for the extensions then? They also have to find this system worker pool and add the respective tolerations. Code wise this can be implemented by a utility function, but for some versions the Gardener and the extensions will not be fully compatible.

If there are multiple worker pools allowing system components and each of them have some taints, then the system components must tolerate all of the taints which can potentially brake somebody's else scenario that is also trying to isolate the system components but via the taints. Of course, these users can use
```yaml
    systemComponents:
      allow: false
```
instead of the taints, but this is then not backward compatible for them.


> But naturally, if one would pin system components to a particular 'system' worker group, this group would be probably (heavily) tainted, to prevent regular workloads from going there. Which makes the systemComponents.allowed flag kind of useless.

I think I might be starting to get what you are asking - do you want the system worker pool to be available only for the gardener's system components and nothing else? If yes, you can achieve this even now by adding labels to the system worker poll and use [node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) to select only other nodes for your apps. This is a bit cumbersome and error prone because each application needs to add this node label selector, I agree.

> Then there is no need to explicitly configure the tolerations via a separate field.

What about adding these taints via an additional optional empty by default field named `taints` in the `systemComponents` https://github.com/gardener/gardener/blob/efb517ac8e2b4efc464c95c049c770367df1b058/pkg/apis/core/v1beta1/types_shoot.go#L1030-L1033

A worker pool can have either the `pool.taints` or the `pool.systemComponents.taints` set, but not both. This way it will be clear from the API that these taints will be always tolerated by the gardener's system components.
