### ISSUE TITLE
Allow any Machine Type when using Bring-Your-Own-Accont

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#365]
# Story

As a Gardener user I want to be able to use all the machine types that the cloud provider offers when I provide account details of my own infrastructure account, not just the ones provided by Gardener. 

# Motivation

In a completely managed environment we mainly would like to offer the machine types that are cost efficient for us, for which we have special discounts. When somebody brings their own resources (e.g. their own IaaS account) we really should not care and limit the user by the machine types he can use.

**Comment by vlerenc** [comment]
Well, we would have done that since long, would we have seen a reasonable way, but we don't. How would we do that? How should Gardener or the Dashboard even know? We are not the infrastructure provider, so we have a hard time getting to that information. Or do you imagine some "free-text" field that we then can't validate?

**Comment by marwinski** [comment]
I can think of a way. Ultimately the one who brings the secret should determine the machine types; so there is an association between the secret and the machine types. How about this: the list of all possible machine types and the list of default machine types (more or less the list we do have today) shall be part of the cloud profile. When the list of machines is not specified when entering the secret then the default list of machine types is taken keeping compatibility to the current approach. When entering a secret the stakeholder could additionally select from the list of all types which is present in the cloud profile (or for UI simplicity) all machine types could be taken.

**Comment by vlerenc** [comment]
Sure Dirk, there are means. I meant (and wrote) "reasonable" means. That is a lot of stuff you are packing up here for a tiny requirement, i.e. this will never be implemented, because there will never be time, because there will always be lower hanging fruits and more important requirements.

What do we need for the above:
- Somebody constantly maintaining the "full list" (more likely we will handle that on request basis, but ideally it should come from the botanist, later IaaS extension)
- Preferred machine types (that is easy, but we have the `deprecated` mitigation right now)
- Placing desired machine types into the secret binding (that is not only new functionality, but also and actually kind of ugly, at least incomplete; by that logic you would start putting more than just machines there, e.g. allowed storage classes or max disk sizes, etc. so it can't be interpreted easily, which will become important below when considering the Dashboard)
- Admission controllers checking these secret bindings, admission controllers checking the shoot specs
- Dashboard support for this, which always is the bottleneck and a lot of work (UI always is, which is why we only implement the straight-forward cases there, limit it to ops and enable users via the Gardener API server for everything that is more complex), so most likely we wouldn't do that at all; it would be difficult anyhow, if we would allow to tweak more constraints here, potentially IaaS-specific ones, which is a lot of effort as it means the Dashboard must get extensible
- ...

I don't see us winning anything, wouldn't you agree? Today, if someone wants a new machine type, we add it. That's the equivalent of the first task in the list above, but without the others tasks.

And if the users wants to limit the machine types, why should we do that for him? Actually, I don't even like the misuse of the `deprecated` feature. Everything should be visible and `deprecated` should be used for what it is meant to be used, e.g. `m5` over `m4`. Everything else, and here it is futile to chase the infrastructures and their powerful model, can be done by IaaS quotas/limits, so if someone doesn't want `m4` or `m5`, just change the quota/limit. That is none of our business, but IaaS business. We can make it our business, but it is not valuable enough to burn our time. Let's stick to the Gardener core features, because that's something only we can build.

If you agree, let's please close this ticket. Let's agree to grow the machine types list, let's agree that later the botanists/extensions shall bring the that list per IaaS and delegate the rest to the IaaS and their quota/limit management. It's not as ideal, but good enough.

**Comment by marwinski** [comment]
@vlerenc  please be careful with absolute statements like "this will never be implemented". 

Not important, well my inbox is full of those kind of questions and requirements so I do not agree that this is not important. In case we want to offer this as a service we are in the driver seat and offer the machine types that we find appropriate and that suit us and our business needs. Others who pay the bill themselves are of course free to use whatever they need and want and for what they might have a special deal. Yes we can do that with different shoots and restrict projects on shoots but that sounds really awkward and wrong - at least for this use case. 

Well I don't think that we need all of the above and that there is a reasonable way with reasonable effort to get this done. Here is a take:

- the full list can be handled on demand, no need to write code to sync that with the cloud provider or keep looking every week. 
- I don't see an immediate need to maintain the data in the dashboard - if you bring your own secret you can just get everything, if not you get the default list. 
- I did not suggest put the machines into the secret but a config map beside (which is created based on the above rule 
- I don't see the need for an admission controller. Further to the above, if you have a secret (which means your brought it) the config map with the machine types is considered. If you have a secret-binding this one is ignored 

I might be wrong but this does not sound like a huge project.

**Comment by vlerenc** [comment]
@marwinski: I said why... "this will never be implemented, because there will never be time, because there will always be lower hanging fruits and more important requirements"

I didn't write "not important". I wrote "more important".

> In case we want to offer this as a service we are in the driver seat

We are in the driver seat, therefore let's add the machine types and be done with it. That's what I suggested. Nothing complicated, just add what is requested. Later, let the botanists/extensions bring the full list. After all, the user cannot do that as a self-service - they can only pick what the IaaS offers.

> Yes we can do that with different shoots and restrict projects on shoots but that sounds really awkward and wrong - at least for this use case.

Not sure what you mean. Nothing I suggested.

> I did not suggest put the machines into the secret but a config map beside (which is created based on the above rule

Doesn't matter where, but it must be somewhere.

> I don't see the need for an admission controller. Further to the above, if you have a secret (which means your brought it) the config map with the machine types is considered. If you have a secret-binding this one is ignored

That is the admission controller. You want to limit it, so if the shoot specifies something outside the secret/cm, it must be rejected.

Again, let's not overcomplicate this. Let's close this ticket and get your list of requirements "my inbox is full of those kind of questions and requirements" into the current cloud profiles and be done with it. I cannot explain this requirement and why we need configurability to the team.

**Comment by marwinski** [comment]
Lets discuss this with the team and decide, maybe I will be able to explain it. If not I will dump it.

**Comment by vlerenc** [comment]
In any case, can you please share your "inbox full of those kind of questions and requirements" with us, maybe we should get them in right away with https://github.wdf.sap.corp/kubernetes/landscape-setup/issues/172? In any case, we need to add them in order to become available and it would be a waste if we block our users.

**Comment by vlerenc** [comment]
What will happen with this ticket? There is always the manual way to add all/many more machine types. Are you interested to file a PR @hummelo?
