### ISSUE TITLE
Hibernated cluster with custom CSI drivers could not be deleted

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#3766]
**How to categorize this issue?**

/area ops
/kind bug
/priority 3

**What happened**:

A *hibernated* cluster (on Alicoud, but irrelevant) with a custom CSI drivers could not be deleted

**What you expected to happen**:

Cluster to be deleted successfully

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy custom CSI driver e.g. rook for ceph
1. Create some volumesnapshots e.g:

   ```console
   kubectl get volumesnapshots.snapshot.storage.k8s.io -A
   NAMESPACE         NAME                                 READYTOUSE   SOURCEPVC                  SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAP SHOTCLASS     SNAPSHOTCONTENT                                    CREATIONTIME   AGE
   composed-earwig   foooooooooooo-p8mlx-20210221120007   true         foooooooooooo-p8mlx-data                           8Gi           some-snapshot-class   snapcontent-123445-dd97-4810-8506-30c296691e27   30d            30d
   fun-sparrow       foooooooooooo-65g8n-20210221120007   true         foooooooooooo-65g8n-data                           8Gi           some-snapshot-class   snapcontent-123445-d069-4124-83ac-4541375237aa   30d            30d
   ```

   ```console
   kubectl get volumesnapshotcontents.snapshot.storage.k8s.io
   NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                       VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                       AGE
   snapcontent-1a84b2f5-d360-4803-987c-97902d22efec   true         8589934592    Delete           rook-ceph.rbd.csi.ceph.com   rook-ceph-block       foooooooooooo-qsxhh-20210221200005   30d
   snapcontent-2fecce74-e0cf-46f2-9359-a65628b474f6   true         8589934592    Delete           rook-ceph.rbd.csi.ceph.com   rook-ceph-block       foooooooooooo-7fwsw-20210221080011   30d
   ```

1. Hibernate the cluster
1. Attempt to delete it
1. The cluster is now stuck in deletion and it could not remove the CSI managed resources

As there are no csi drivers running that responsible for rook, the `volumesnapshotcontents` and `volumesnapshots` resources would not be removed.

Even worse - now the `VolumeSnapshotClass` was removed and the CSI driver in the seed cluster was reporting the following error:

```log
E0324 02:00:45.632407       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

Ideally what needs to happen is we prevent the deletion of a *hibernated* Shoot if there are CSI drivers installed that are not managed by Gardener.

**Anything else we need to know?**:

**Environment**:

- Gardener version: latest
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: alicloud with CSI enabled
- Others:

**Comment by stoyanr** [comment]
We discussed this issue and agreed that we should detect custom CSI drivers and `VolumeSnapshots` managed by such drivers and add an appropriate constraint to the shoot. For now, this constraint should be used to make users aware about potential issues with the deletion of such shoots, e.g. in the dashboard, since such issues could arise also with non-hibernated shoots.

In addition, we will forbid the deletion of hibernated shoots in general, to avoid further surprises and simplify the deletion logic that is now different for hibernated vs. non-hibernated shoots.

**Comment by vlerenc** [comment]
> In addition, we will forbid the deletion of hibernated shoots in general, to avoid further surprises and simplify the deletion logic that is now different for hibernated vs. non-hibernated shoots.

+1

I would also hope we can map the deletion of hibernated clusters to their wake-up + deletion, so that we don't have to treat it as special case.

Also, it's another case where https://github.com/gardener/gardener/issues/3110#issuecomment-734647043 would have helped us. End-user problems like this should not become Gardener problems. All kind of things may be wrong with a cluster, not only hibernated + custom CSI drivers...

> We discussed this issue and agreed that we should detect custom CSI drivers and VolumeSnapshots managed by such drivers and add an appropriate constraint to the shoot. For now, this constraint should be used to make users aware about potential issues with the deletion of such shoots, e.g. in the dashboard, since such issues could arise also with non-hibernated shoots.

That's additional effort on our end. I would rather go for https://github.com/gardener/gardener/issues/3110#issuecomment-734647043 and the flow simplification. Catching another special case is no long-term strategy, I would think.

**Comment by stoyanr** [comment]
> I would also hope we can map the deletion of hibernated clusters to their wake-up + deletion, so that we don't have to treat it as special case.

For now we intended to simply forbid it via an admission plugin. I think this is good enough as a start, while mapping as you suggest would be much harder to do. We could consider that later if we are dissatisfied with the simpler approach.

> That's additional effort on our end. [...]

We will probably not work on this right away, since we are not sure how often this could affect us, so this issue is likely to remain open for some time, until we are hit by it at least one more time. 

I think we all agree about [#3110 (comment)](https://github.com/gardener/gardener/issues/3110#issuecomment-734647043), but the discussion was in the context of short term quality improvements, so sweeping changes like the ones proposed were not considered.

**Comment by dguendisch** [comment]
> In addition, we will forbid the deletion of hibernated shoots in general

Are we sure that no one is doing this automatically today (deleting hibernated shoots), otherwise it could be considered an API change if it's suddenly forbidden?

**Comment by stoyanr** [comment]
@dguendisch Even if someone is doing that, I don't think we ever had a "contract" or something similar to prevent us from doing such a change.

In general, hibernation is considered to be a "developer cost saving" feature, this is why it's frustrating to us that we need special logic to handle deletion of hibernated cluster.

@rfranzke Any considerations from your side?

**Comment by rfranzke** [comment]
I think I mentioned this as well: There might be end-users which might need to adapt their automation accordingly. I think it needs to be somehow configurable so that operators can give end-users enough time to adapt before they enable this behaviour. We can also have a chat to think about ways how to best and most easily achieve this.

**Comment by vpnachev** [comment]
I vote for 

> I would also hope we can map the deletion of hibernated clusters to their wake-up + deletion, so that we don't have to treat it as special case.

This would mean the regular reconciliation should happen if the shoot is not already awaken and just at the end, the deletion loop is triggered if the the deletion timestamp is set.

**Comment by stoyanr** [comment]
> This would mean the regular reconciliation should happen if the shoot is not already awaken and just at the end, the deletion loop is triggered if the the deletion timestamp is set.

As said above, I don't think this is easy to do, and so from my perspective is yet another rather complex thing we introduce for the deletion of hibernated shoots. I could be missing something of course. @rfranzke Do you think we should invest in further researching this? From our discussion in the meeting I had the impression we are aiming at a "simple" solution to get rid of the current complexity, not replace it with complexity of a different kind.

**Comment by rfranzke** [comment]
> This would mean the regular reconciliation should happen if the shoot is not already awaken and just at the end, the deletion loop is triggered if the the deletion timestamp is set.

Actually, I like the idea because we would not change the API validation and don't need to mentioned configurability, etc. Is it really that complex/why do think so? Generally, I agree that we are striving for something simple, but such changes to the API are always rather the opposite, so if we can solve the issues internally we can hopefully avoid some of the struggles.

**Comment by stoyanr** [comment]
@rfranzke OK, I will look into this further, although it doesn't seem too promising to me in terms of complexity. It also has its own drawbacks in terms of "compatibility". Now, if I delete a shoot, suddenly it's reconciled at first instead of being deleted. Or, if the shoot is not hibernated but also not fully awaken, nothing happens for a while until it's fully awaken. And if this fails for some reason, again nothing happens, the shoot just sits there without being deleted. 

Wouldn't all that surprise some users, and in some cases lead to exactly the types of hard to resolve situations we wanted to avoid? If a deletion is rejected then at least it's very explicit and leaves no room for confusion or doubt.

**Comment by rfranzke** [comment]
Thanks @stoyanr for bringing up your thoughts, I can partly understand your reservations with respect to the complexity concerns, but I'm not sure if it's really that complicated. Why I mainly like @vlerenc's/@vpnachev's idea is because we wouldn't break today's API (even if we don't know of use-case or consider them "minor", in reality, there might be end-users relying on this). 

> It also has its own drawbacks in terms of "compatibility". Now, if I delete a shoot, suddenly it's reconciled at first instead of being deleted. Or, if the shoot is not hibernated but also not fully awaken, nothing happens for a while until it's fully awaken.

I would rather argue that this is an implementation detail and not related to compatibility at all. The end-user can still work with the API like before, and whether we now first wake up the cluster or not is completely up to us and entirely out of scope for the end-user, isn't it?

> And if this fails for some reason, again nothing happens, the shoot just sits there without being deleted.

Yes, but this isn't different to the other proposal (forbidding deletion and asking the user to first wake it up) - it can fail similarly and end-up in the same state. Especially, this is partly also what is implemented today (if the control plane wake-up in the deletion flow fails, the state is the same).

> Wouldn't all that surprise some users, and in some cases lead to exactly the types of hard to resolve situations we wanted to avoid? If a deletion is rejected then at least it's very explicit and leaves no room for confusion or doubt.

Hm, which situations do you have in mind here, especially compared to the other proposal? The only difference is that the `.status.lastOperation` might show `Delete Processing` while we first try to wake it up, but this is to some extent already what happens today in the deletion flow (we wake up the control plane already). Are there more differences?

Let's see what your investigations reveal, but my impression is that this idea is achieving the same goals that we initially had (less complexity in the code (especially in the flows), better coverage for graceful deletions with custom-installed controllers, ...) while keeping the API stable.
If it turns out to be too complex then we can reiterate and try to discover other options, of course.

**Comment by stoyanr** [comment]
@rfranzke Let's look at the code together, perhaps we can come up with a simple idea how to do it, so far the few things I tried aren't working and other approaches I can think of aren't simple.

**Comment by stoyanr** [comment]
Update: In a short meeting with @rfranzke and @timebertt we decided to do nothing for the moment. We will not forbid the deletion of hibernated shoots because of the objectons mentioned above. We will also not try to execute the wake-up of hibernated shoots as part of the deletion because it's not really simple, especially if all the cases that should be tested are taken into account. Also, both approaches suffer from the drawback that we would require the shoot to successfully wake-up before it could be deleted, which might not be possible in some cases, so the shoot will sit there wasting resources.

We also took a closer look at [#3110 (comment)](https://github.com/gardener/gardener/issues/3110#issuecomment-734647043) and think that perhaps the so-called "drop cluster" functionality might be a low-hanging fruit. I will look deeper into this if I have time this week.
