### ISSUE TITLE
Rate limit exceeded errors are wrongly detected as non-retriable

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#3775]
**What happened**:
Currently rate limit issues are detected as non-retriable errors. It means that if a cloud provider rate limit exceeded error occurs, the Shoot will be set to Failed and will be no longer retried.

**What you expected to happen**:
Rate limit exceeded errors should be retied.

**Comment by vpnachev** [comment]
ref: https://github.com/gardener/gardener/pull/3662#issuecomment-791295281

Thanks @ialidzhikov for pointing this out.

**Comment by rfranzke** [comment]
@ialidzhikov From the description, this issue is about the DNS controller not adhering to the extension contracts. It was moved to the external-dns-management repo. Can you please close this issue again and open a separate one for tracking the "rate limit error code" topic?

(Actually, I'm confused about your title - didn't we agree that it's NOT wrong to detect them as non-retryable?)

**Comment by ialidzhikov** [comment]
> Can you please close this issue again and open a separate one for tracking the "rate limit error code" topic?

I updated the description of the current issue. No "DNS" in it now, pure "rate limit exceeded".

> (Actually, I'm confused about your title - didn't we agree that it's NOT wrong to detect them as non-retryable?)

I am tired of this discussion. These errors were retriable since the beginning for probably almost more than 3 years. I cannot understand what changed now. Is it normal to you that we set the Shoot to Failed and stop retrying when a rate limit error occurs? It is not the expected behaviour to me. In most of the cases rate limit exceeded errors are transient ones. Cloud providers have request throttling mechanisms where the allowed request quota is likely to recover in seconds/minutes - for example [token bucket algorithm](https://en.wikipedia.org/wiki/Token_bucket) for AWS.
