### ISSUE TITLE
[Flaky Test] `ControllerManager Shoot Controller Suite` fails with data race

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4036]
/area testing
/kind flake
/priority 3

**Which test(s)/suite(s) are flaking**:
`ControllerManager Shoot Controller Suite` and `Gardener Envtest Suite` fail with data race

**CI link**:
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-head-update-job/builds/234
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-head-update-job/builds/233
- https://concourse.ci.gardener.cloud/builds/11207009

**Reason for failure**:

**Anything else we need to know**:

**Comment by timebertt** [comment]
Yep, also saw this one...
It seems like it wasn't the best idea to start `g-api` in-process and we should probably reconsider building a binary and executing that one instead.
Ref https://github.com/gardener/gardener/issues/3765

**Comment by timebertt** [comment]
Should we disable the test for now until we have sorted things out in the `envtest` package?

**Comment by timebertt** [comment]
> It seems like it wasn't the best idea to start `g-api` in-process and we should probably reconsider building a binary and executing that one instead.

I decided to not build a binary beforehand and keep running g-api in-process because
- we don't have to think about test result caching for envtest suites
- we don't have to think about building binaries in `make {verify,test,...}`
- test packages can still be executed easily with `go test` / `ginkgo` without building binaries in `pkg/envtest`
- k/k uses the same approach in its [integration tests](https://github.com/kubernetes/kubernetes/tree/master/test/integration)

To fix the data race in the API server described in this issue, I rather isolated the integration tests (again just like k/k does) and just disabled the race detector for them: https://github.com/gardener/gardener/pull/4265.
