### ISSUE TITLE
aggregate-prometheus-0 is OOMKilled on almost all Seeds after gardenlet@v1.22.2 rollout

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4048]
**How to categorize this issue?**
/area auto-scaling
/kind bug
/priority 3

**What happened**:

We observe `aggregate-prometheus-0` that is OOMKilled on multiple Seed after gardenlet@v1.22.2 rollout

```
$ k -n garden get po aggregate-prometheus-0
NAME                     READY   STATUS             RESTARTS   AGE
aggregate-prometheus-0   1/2     CrashLoopBackOff   30         151m

$ k -n garden describe po aggregate-prometheus-0

    Args:
      --config.file=/etc/prometheus/config/prometheus.yaml
      --storage.tsdb.path=/var/prometheus/data
      --storage.tsdb.no-lockfile
      --storage.tsdb.retention.time=2w
      --web.enable-admin-api
      --web.listen-address=0.0.0.0:9090
      --web.enable-lifecycle
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 12 May 2021 14:40:00 +0300
      Finished:     Wed, 12 May 2021 14:40:31 +0300
    Ready:          False
    Restart Count:  30
    Limits:
      cpu:     500m
      memory:  2000Mi
    Requests:
      cpu:      30m
      memory:   500Mi
```

**What you expected to happen**:

No OOMKilled events.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: gardenlet@v1.22.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by amshuman-kr** [comment]
Even though HVPA is applying the VPA recommendations to the `aggregate-prometheus` `StatefulSet`, the [long-standing issue](https://github.com/kubernetes/kubernetes/issues/67250) of `StatefulSet` controller not doing the rolling updates if pods are unhealth/crashing is preventing the pods to get the recommendation.

In one seed at least, I can see that the memory usage jumped from `~1Gi` to `~3.2Gi`. I suspect the same to be true in the other seeds too.

![image (3)](https://user-images.githubusercontent.com/32157254/117970815-be7edd80-b346-11eb-8a05-fb12b9a5ae55.png)

The [current configuration](https://github.com/gardener/gardener/blob/c6bd6586ae7194d5e248740a66903157e356ca03/charts/seed-bootstrap/values.yaml#L102-L108) of `limitsRequestsGapScaleParams` is not sufficient to handle such spikes in usage. I suggest to modify these values to something like below at least.
```
    limitsRequestsGapScaleParams:
      cpu:
        percentage: 60
        value: 400m
      memory:
        percentage: 80
        value: 2Gi
```

**Comment by rfranzke** [comment]
> Even though HVPA is applying the VPA recommendations to the aggregate-prometheus StatefulSet, the long-standing issue of StatefulSet controller not doing the rolling updates if pods are unhealth/crashing is preventing the pods to get the recommendation.

Side note: If there will ever be a v2 of HVPA, I really recommend to not touch the higher-level resources but only the `Pod`s directly (like VPA). Apart from this concrete issue (StatefulSet not updating crash-looping pods), we have a lot of avoidable code complexities in g/g that would not be necessary. cc @timebertt

**Comment by amshuman-kr** [comment]
>  Side note: If there will ever be a v2 of HVPA, I really recommend to not touch the higher-level resources but only the Pods directly (like VPA)

FWIW, I disagree. This would be a a work-around on top of a work-around. Besides, HVPA is not the only component that has this problem. Anyone deploying/managing statefulsets via controllers technically has this problem which potentially requires a manual intervention to recover.

May I suggest a controller that watches `statefulsets` (suitably annotated) and their pods. If it sees the pods crashing (or crashlooping to be sure) and the podspec is different from the pod template, then shoots the pod.

The reluctance in upstream Kubernetes to do this automatically is assuming the worst case where stateful workload always requires manual intervention on crashing. But all of the statefulsets that we use in gardener can and do handle restarts gracefully (and we can mark this fact in an annotation on the statefulset).

This would solve not just this issue here but also other cases it might manifest generally.

**Comment by amshuman-kr** [comment]
> we have a lot of avoidable code complexities in g/g that would not be necessary.

The fact that VPA enables to avoid the complexity in gardener does not mean it should ideally be avoided. In principle, who ever deploys a resource should ideally be responsible for it mutating between reconciliation, especially if another component is also deployed which is expected to mutate it.

AFAIK, even with HPA, the replicas will get overwritten if the reconciler is not careful.

**Comment by amshuman-kr** [comment]
VPA using webhook to mutate pods is really just a work around and messes with rolling update strategy among other things. It breaks layers.

What is really required is a `Scale` subresource equivalent to scale resources. A `Resources` subresource, if you will. But even that won't eliminate the need for g/g to be careful not to overwrite. Which is as it should be, IMHO.

**Comment by amshuman-kr** [comment]
To complete my thoughts on the topic of mutating resources (at the risk of dragging the discussion on a side-note), a more viable way to dynamically mutate resources while also reducing the complexity in gardener of having to take care not to overwrite would be to use a separate CRD (for resources) coupled with a mutating webhook to mutate higher order resources instead of mutating the pods underneath. Something like what is done by `PodPreset` and kupid.

This would let gardener not worry about overwriting anything while also not breaking layers and the problems thereof.

Nothing like this exists yet, of course.
