### ISSUE TITLE
Add option to enable / disable anonymous authentication of the kube-apiserver

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#4063]
**How to categorize this issue?**

/area control-plane
/area security
/kind enhancement
/priority 3

**What would you like to be added**:

The `anonymousAuthentication` field should be added to [apiserver configuration](https://github.com/gardener/gardener/blob/41cfe1d32cafc7ea3ded555bde01a2a657e7aa3f/pkg/apis/core/v1beta1/types_shoot.go#L454). It should be optional `*bool` and defaulted to `false`.

The value should control the `--anonymous-auth` flag of `kube-apiserver`.

**Why is this needed**:

Since [Service Account Issuer Discovery](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) feature is enabled, access to `https://{kube-apiserver-hostname}/.well-known/openid-configuration` is only allowed for authenticated users. Most of the OIDC metadata discovery clients do not support authentication as they expect unprotected access to the endpoint.

This relevant to #4023

**Comment by timebertt** [comment]
@mvladev I don't fully understand this request.

`--anonymous-auth` defaults to `true` in 1.15 - 1.21, [ref](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). So why is it necessary to explicitly enable it via the `ShootSpec`?

[Service Account Issuer Discovery](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) states:

> Clusters include a default RBAC ClusterRole called `system:service-account-issuer-discovery`. No role bindings are provided by default. Administrators may, for example, choose whether to bind the role to `system:authenticated` or `system:unauthenticated` depending on their security requirements and which external systems they intend to federate with.

So I conclude, that in order to reach the goal of the issue description (to make `https://{kube-apiserver-hostname}/.well-known/openid-configuration` publicly accessible), you probably rather want to create a new `ClusterRoleBinding`, binding `system:service-account-issuer-discovery` to `system:{authenticated,unauthenticated}`, am I right?

**Comment by vpnachev** [comment]
> @mvladev I don't fully understand this request.
> 
> `--anonymous-auth` defaults to `true` in 1.15 - 1.21, [ref](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). So why is it necessary to explicitly enable it via the `ShootSpec`?

Because of https://github.com/gardener/gardener/blob/cb2c544fcf074699db2102080509bbe28dda054e/charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml#L105

**Comment by mvladev** [comment]
> So why is it necessary to explicitly enable it via the ShootSpec?

From a strict security point - it's better to disable anonymous authentication. The idea is to give option to have it disabled by default and cluster admins can enable it.

> So I conclude, that in order to reach the goal of the issue description (to make https://{kube-apiserver-hostname}/.well-known/openid-configuration publicly accessible), you probably rather want to create a new ClusterRoleBinding, binding system:service-account-issuer-discovery to system:{authenticated,unauthenticated}, am I right?

Yes, this is what cluster admins need to do. However if `--anonymous-auth` is set to `false` then the API request won't even hit the RBAC authorizer. It'll be denied at the authentication step (see https://github.com/kubernetes/apiserver/blob/781f4a410756dad30f33da3c4de585c69bc0e67e/pkg/authentication/authenticatorfactory/delegating.go#L119-L121)
