### ISSUE TITLE
Drop ability of gardenlet to control multiple seeds

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4078]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:
Today, the gardenlet can either control exactly one seed (`.seedConfig`) or multiple seeds by providing a label selector (`.seedSelector`).
We would like to drop the latter entirely.

**Why is this needed**:

There are several concerns with the functionality of controlling multiple seeds:

- Security-related checks cannot be performed properly (#1723) 
- Scalability concerns (a single gardenlet can only control limited number of seeds and shoots)
- Complexity in the code (it's more difficult to establish watches against the seed cluster)

Generally, for above reasons, we don't recommend to use this feature in production but only for development scenarios.

⚠️ One consequence of dropping it would be that the local dev setup would also only be able to control exactly one seed.

**Comment by vpnachev** [comment]
> :warning:  One consequence of dropping it would be that the local dev setup would also only be able to control exactly one seed.

I usually have only one seed in my local setup, but sometimes have to add temporary second one. 
We can improve the local setup tools to easily switch between seeds or to run multiple gardenlet instances in parallel. The latter would mean to support easy overwrite of the `--config=` flag and use different network [port](https://github.com/gardener/gardener/blob/92bffce756bd797fd35084a0f00058979ac13968/example/20-componentconfig-gardenlet.yaml#L83) for the local server.

So generally, I am fine with proposal.

**Comment by timebertt** [comment]
+100, very much in favor of this 💯👍

**Comment by mandelsoft** [comment]
In general I would urgently avoid to restrict the usecases a controller can be used for without very severe reasons.
Be happy that we already have a general solution and do not try to mutilate such a solution.

Basically I cannot see those reasons here.

There are three points mentioned above:
- Just reading  (#1723) if couldn't find any real problem, but may be I missed something.
  The only problem should be to formally identify the seeds a gardenlet is responsible for. Then restricting the access for the gardenlet should not make a big difference, if this list has one or multiplle entries.
- Fore sure the number of shoots maintainable by a gardenlet is limited, but this is not new and no reason not to
  use a central gardenlet (for example running in the garden cluster) to handle a small number of shoots. We run the gardener several years this way.  For dedicated environments it might be a useful option. (For sure not for our large environments)
- Yes, you require multiple watches. But with appropriate code this concerns only a thin watch layer and does not affect the majority of the functional code that is evolved frequently. For this code it should not matter for which seed it is called.

So, the technical reasons to drop this feature seem to be relatively weak.

Leaving just the general view on the overall design, where is might look more like the kubelet approach. But be aware, for this scenario there are technical reasons for the kubelet to run on the node it manages. But for the gardenlet there are no such reasons to run on the seed it manages. Exactly this is the strength of the kubernetes controller architecture, it does not require specialized implementations for different deployment/management scenarios, if the controllers are written correctly. This gives the flexibility to dynamically switch scenarios according to new upcoming needs without requiring a (partial) rewrite of the code. ( See our initial problems with dedicated k8s controllers, which, without technical need, had to run in the cluster they are responsible for). The complete gardener approach (including our virtual data plane solution) only works because those constraints are explicitly not required for most of the controllers used for a k8s cluster. 

By the way I hope we still have the possibility to run the gardenlet somewhere else than in the seed cluster.

So, I would try to avoid to introduce this limitation.

**Comment by rfranzke** [comment]
Thanks for your PoV @mandelsoft!

> The only problem should be to formally identify the seeds a gardenlet is responsible for. Then restricting the access for the gardenlet should not make a big difference, if this list has one or multiplle entries.

> Yes, you require multiple watches. But with appropriate code this concerns only a thin watch layer and does not affect the majority of the functional code that is evolved frequently. For this code it should not matter for which seed it is called.

Yes, you're right, we might be able to solve this in one way or the other, still, it'd mean more effort/extra code.

> Fore sure the number of shoots maintainable by a gardenlet is limited, but this is not new and no reason not to
use a central gardenlet (for example running in the garden cluster) to handle a small number of shoots. We run the gardener several years this way. For dedicated environments it might be a useful option. (For sure not for our large environments)

If you only have a small number of shoots then you most likely only have one seed cluster. Even if not, there is enough automatism in place (`ManagedSeed`, landscaper component for gardenlet) that makes managing the lifecycle of gardenlets too simple. OTOH, Gardener was built for managing many hundreds/thousands of clusters, and a landscape with only one gardenlet can not scale.

> By the way I hope we still have the possibility to run the gardenlet somewhere else than in the seed cluster.

Sure, it's still possible.

Overall, you have not mentioned a scenario that **required** the gardenlet's ability to control multiple seeds. Even if the presented technical motivation for removing the feature seems "weak" or could be overcome, IMO it doesn't make sense to maintain code that makes many other areas unnecessary complex/special if there is no good reason for having it.
IIUC, your main argument is "flexibility", but still, I would be interested in a scenario for which the recommended approach (one gardenlet per seed) does not work and if it exists (which I doubt) then why.
Personally, I also like today's flexibility, though, the price of maintaining it is continuously increasing and it seems that there is no strong reason for such investments.

**Comment by rfranzke** [comment]
In a meeting about the subject matter with @stoyanr @timebertt @timuthy @vpnachev, we discussed potential ways to address the apparently sole meaningful reason for still having the ability for gardenlet to control multiple seeds in the first place:

> ⚠️ One consequence of dropping it would be that the local dev setup would also only be able to control exactly one seed.

We figured, that in 95% of the development cases it is sufficient to have a gardenlet only targeting exactly one seed. The rest is accounted to the efforts

- when a new Kubernetes version is released, integrated and validated on multiple infrastructures in parallel (happens only once every `4m`)
- when the control plane migration feature is developed locally.

For both cases, there were no strong reasons why running two or multiple gardenlet processes locally wouldn't be equally good enough (obviously, this is not as convenient as today, but still okay).

We also discussed how the `make dev-setup` experience can be kept. Dropping the `seedSelector` field in the gardenlet config meant that the developer would have to specify `seedConfig` in the gardenlet config in the `dev` folder. Today, `make dev-setup` copies the example gardenlet config into the `dev` folder, i.e., all manually configured settings in `seedConfig` would be overwritten.
To make it simple for developers to switch the targeted seeds for their locally running gardenlet processes, we propose to allow specifying the `name` of an existing `Seed` resource in the garden cluster via an environment variable read on gardenlet start-up. It can then compute the `seedConfig` for its config internally based on the `spec` of the respective `Seed` resource. This allows developers to keep their today's workflows and easily switch between seeds.

Additionally, we figured that it might be possible to also drop some code in the `ManagedSeed` controller. The `seedmanagement.gardener.cloud/v1alpha1.ManagedSeed.spec.seedTemplate` field does not bring any value anymore now that `seedSelector` is dropped. The main argument in the discussions was - again - a simplified dev setup.
We didn't take a final decision about it yet, so for now this GitHub issue is focusing on the `seedSelector` field in the gardenlet config, however, as a follow-up we might even want to remove the `seedmanagement.gardener.cloud/v1alpha1.ManagedSeed.spec.seedTemplate` field.

/needs help
