### ISSUE TITLE
BL: Persistent Volume Autoscaling

### ISSUE THREAD

**Issue by vasu1124** [gardener/gardener#4173]
**What would you like to be added**:
With [allowVolumeExpansion](https://kubernetes.io/docs/concepts/storage/storage-classes/#allow-volume-expansion) in beta since 1.11 and supported by many CSI controllers, and [ExpandInUsePersistentVolumes](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) also in beta since 1.15, we could offer a PV autoscaling controller similar to [dynamic-pv-scaler](https://github.com/opstree/dynamic-pv-scaler), capable of online expanding an in-use PV (without restart).

Also see https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Why is this needed**:
HPA, VPA help withh autoscaling compute (pods). A similar mechanism for storage (PVs), offered as an in-built service of the Gardener provided control plane, will improve the value proposition. A user can start with a ample sized PV claim, set a sizing treshold and increment (shrinking is not possible), and can save effort (manual maintenance) and costs.

/area control-plane
/area auto-scaling
/area storage
/priority 4
/kind enhancement

**Comment by MartinKolbAtWork** [comment]
Automatically scaling up volumes is essential for many workloads. Since the finalization of “Volume Expansion” in K8s, the foundation for volume autoscaling is available.
In the "SIG Storage" of K8s, there are no plans to provide volume autoscaling directly in K8s. Some open-source projects have tried to offer autoscaling capabilities, but none of them do this in a production-grade manner.
Therefore, an offering for volume autoscaling within Gardener would be an important value-add for Gardener and would avoid the need for a plethora of individual solutions.

/reopen
/remove-lifecycle rotten

**Comment by vasu1124** [comment]
/reopen

for @MartinKolbAtWork

**Comment by dnaeon** [comment]
pvc-autoscaler implementation is now in the following repo: https://github.com/gardener/pvc-autoscaler
