### ISSUE TITLE
CPM Is failing on step "Deleting all extension CRs from the Shoot namespace"

### ISSUE THREAD

**Issue by krgostev** [gardener/gardener#4180]
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
Control Plane Migration fails with the following error:
```
Flow "Shoot's control plane preparation for migration" encountered task errors: [task "Deleting all extension CRs from the Shoot namespace" failed: 5 errors occurred:
	* resource name may not be empty
	* resource name may not be empty
	* resource name may not be empty
	* resource name may not be empty
	* resource name may not be empty
] Operation will be retried.
```

With the current changes on the master branch the object that is passed to the [DeleteExtensionObject()](https://github.com/gardener/gardener/blob/080adaec429c75d7525b45b6d48d6f8d774355f4/pkg/extensions/customresources.go#L158) function contains almost no data. Example:
```
&{{ } {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[confirmation.gardener.cloud/deletion:true gardener.cloud/timestamp:2021-06-07 14:01:18.207702 +0000 UTC] [] []  []} {{ nil}  { } []} {{nil [] nil nil 0 nil []} <nil>}
```
This cause the function [ConfirmDeletion()](https://github.com/gardener/gardener/blob/080adaec429c75d7525b45b6d48d6f8d774355f4/pkg/utils/gardener/deletion_confirmation.go#L58) to return error `resource name may not be empty`

This happens in the following components when the `Destory()` function is called:
```
1. /gardener/gardener/pkg/operation/botanist/component/extensions/infrastructure/infrastructure.go:181
1. /gardener/gardener/pkg/operation/botanist/component/extensions/worker/worker.go:269
1. /gardener/gardener/pkg/operation/botanist/component/extensions/network/network.go:140
1. /gardener/gardener/pkg/operation/botanist/component/extensions/controlplane/controlplane.go:177
```
**What you expected to happen**:
The control plane migration should finish successfully. 
**How to reproduce it (as minimally and precisely as possible)**:
Run CPM as described [here](https://github.com/gardener/gardener/blob/080adaec429c75d7525b45b6d48d6f8d774355f4/docs/usage/control_plane_migration.md) The issue is reproducible every time.
**Anything else we need to know?**:

**Environment**:

- Gardener version: tested with 1.25.0-dev, but should be reproducible with 1.24.0 as well
- Kubernetes version (use `kubectl version`): tested with 1.19.2 and 1.20.6 but should be irrelevant
- Cloud provider or hardware configuration: tested with GCP and AWS
- Others:

**Comment by timebertt** [comment]
This is probably caused by https://github.com/gardener/gardener/pull/4027, right?

**Comment by krgostev** [comment]
Yep, this could be, however I am not completely sure.

**Comment by timebertt** [comment]
Ok, I was able to reproduce this locally. It is indeed introduced by #4027.
If for some reason, the migrate flow is executed a second time immediately after the first run, the extension resources are already gone which leads to the failure described here.

What happens is the following:
1. `Migrate` is called on component (e.g. [`infrastructure.Migrate`](https://github.com/gardener/gardener/blob/2e0ba2a8efba0ce61c67fe09155bf41b04f2f0e7/pkg/operation/botanist/component/extensions/infrastructure/infrastructure.go#L171)). This will go through, as it ignores the `NotFoundError` and the in-memory object in the extension component (e.g. [`infrastructure.infrastructure`](https://github.com/gardener/gardener/blob/2e0ba2a8efba0ce61c67fe09155bf41b04f2f0e7/pkg/operation/botanist/component/extensions/infrastructure/infrastructure.go#L116)) is untouched, so it will still contain `Name` and `Namespace`.
2. `WaitMigrate` is called on component, which calls [`extensions.WaitUntilExtensionObjectMigrated`](https://github.com/gardener/gardener/blob/1179b760b691c1734f9527239ab7c7e241a01424/pkg/extensions/customresources.go#L395). Before reading the object, it always resets the in-memory object to an empty object [here](https://github.com/gardener/gardener/blob/1179b760b691c1734f9527239ab7c7e241a01424/pkg/extensions/customresources.go#L413), which thereby also removes `Name` and `Namespace`. The `Get` call will again get a `NotFoundError`, which is ignored, and now `infrastructure.infrastructure` is completely empty.
3. `Destroy` is called on component, which calls [`extensions.DeleteExtensionObject`](https://github.com/gardener/gardener/blob/1179b760b691c1734f9527239ab7c7e241a01424/pkg/extensions/customresources.go#L155) but passes an empty object because of the previous step. Thus it fails with `resource name may not be empty`.

These steps should be idempotent of course and succeed, if the extension resources are already gone, as it's a no-op.
Fix is incoming :)
/accepted
/assign

**Comment by timebertt** [comment]
Besides the bug introduced by my refactoring, we should probably look into why the migrate flow is executed twice.
Is this by design? Have you observed this behavior before?

**Comment by krgostev** [comment]
Thanks a lot for checking this!
Yes we have observed this and a PR is already on its way to fix this issue. #4189 
It appears that it was doing it for a while, but we have missed this since the migration flow was running successfully. With the latest changes in the gardener this issue became more visible.

**Comment by timebertt** [comment]
Ok, great!
Then both issues touched here will be fixed :)
