### ISSUE TITLE
Condense Backups

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#43]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Tuesday Oct 24, 2017 at 00:29 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/160_

----

Right now we take only backups for the past 7 days (once a day), but it would be better to have a more flexible backup plan and condense older backups:
* Run backups hourly
* Keep only the last 24 hourly backups and of all other backups only the last backup in a day
* Keep only the last 7 daily backups and of all other backups only the last backup in a week
* Keep only the last 4 weekly backups

**Comment by vlerenc** [comment]
Remark: These backups would not be used for customer-initiated restore or PiTR (because most likely the infrastructure resources would no longer fit/match and the backup would not be usable anymore without manual processing), but as a safeguard against unnoticed backup corruption. In these cases these backups would be the last hope to extract valuable data and process the data manually to restore as much as possible of a lost cluster workload.

**Comment by vlerenc** [comment]
Moved to https://github.com/gardener/etcd-backup-restore/issues/3.
