### ISSUE TITLE
Deploying the Gardener into a Kubernetes cluster

### ISSUE THREAD

**Issue by phongvu0403** [gardener/gardener#4360]
I can't find `controlplane-values.yaml` and `gardener-values.yaml` in directory `charts/gardener/controlplane`. So I can't deploy the gardener control plane. Can you help me fix this problem?
Thanks advanced!

**Comment by vpnachev** [comment]
You should be looking for https://github.com/gardener/gardener/blob/master/charts/gardener/controlplane/values.yaml and https://github.com/gardener/gardener/blob/master/charts/gardener/gardenlet/values.yaml.

**Comment by phongvu0403** [comment]
Firstly, thanks your reply!

Sorry, I had a mistakes. I tried to deploy the Gardener in to a Kubernetes cluster following the [link](https://github.com/gardener/gardener/blob/master/docs/deployment/setup_gardener.md)

In the command 
```
helm install charts/gardener/controlplane \
  --namespace garden \
  --name gardener-controlplane \
  -f gardener-values.yaml \
  --wait
```
I think file `gardener-values.yaml` is in folder `gardener` when I cloned Gardener Project because of relative path `charts/gardener/controlplane`.

I think [https://github.com/gardener/gardener/blob/master/charts/gardener/controlplane/values.yaml](https://github.com/gardener/gardener/blob/master/charts/gardener/controlplane/values.yaml) is installed by helm default because I install all of `controlplane` directory.

Can you help me find `gardener-values.yaml` and its content?

Thank u very much!!!

**Comment by vpnachev** [comment]
Reading https://github.com/gardener/gardener/blob/master/docs/deployment/setup_gardener.md my understanding is that you are responsible to create own `controlplane-values.yaml` file, as https://github.com/gardener/gardener/blob/master/charts/gardener/controlplane/values.yaml can be used as starting point.

The only problem with the guide that I see is that in the helm command `controlplane-values.yaml` should be used instead of `gardener-values.yaml`.
