### ISSUE TITLE
Make Backup Status Available

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#44]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Tuesday Oct 24, 2017 at 00:35 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/161_

----

Right now, the user (nor operator for that matter) has access to the status (success or failure) of the backups, their full list with date/time (taken, took) or the size. As a first step towards on-demand restore, this would be helpful.

It is not clear, whether this should be handled within the operator (as additional status information) or put into additional CRD "backup" resources that are then read from the seed cluster/shoot namespace. Other implementation proposals are welcome.

**Comment by vlerenc** [comment]
This ticket makes no sense anymore after we have learned that there is no infrastructure reconciler, i.e. we could end up with backups that shows infrastructure resources that do no longer exist (e.g. an LB service was deleted after the backup was taken) or vice versa, that lacks infrastructure resources that exist, but the cluster has forgotten about (e.g. an LB service was created after the backup was taken). Furthermore, after being made aware of this shortcoming, it becomes apparent that all kinds of other scenarios are also broken with old backups as long as the restore is no intrinsic part Kubernetes, e.g. CRDs could carry any meaning and reflect any state in the physical world outside the Kubernetes cluster itself (e.g. something similar like infrastructure resources). As long as Kubernetes becomes not fully aware of a restore and can inform all involved parties, there is no point in restoring old backups or PiTR. It is simply not possible without rock-solid reconcilers and even then it would be dangerous and potentially stupid to reconcile data loss. ;-)

Therefore we discussed in our cross-location syncs to drop this idea and instead follow up on continuous etcd backups, so that we can shorten the timespan between backups respectively always have up-to-date backups to reduce the likelihood of restoring an outdated backup that could bring the above problems.
