### ISSUE TITLE
Nodes which are removed in a rolling update still apply new cloud-config

### ISSUE THREAD

**Issue by voelzmo** [gardener/gardener#4415]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority 3

**What happened**:

When a rolling node update is triggered, a new worker pool is created and the nodes in the old worker pool are marked as `preferNoSchedule` by the MCM, then drained and in the end removed, once the new nodes are ready. In this process, any changes in the cloud-config are still applied to the old nodes.
This isn't really what we want, because this interferes with draining the node. If the downloader script finds any delta in the hypercube images or the cloud-config, it will reload `systemd` and restart all of our systemd units (kubelet, container runtime, watchers, etc).
Note this does not apply to changes in the k8s `major.minor` version, [as this creates a cloud-config secret with a different name](https://github.com/gardener/gardener/blob/da556e69b265796e7b31f07b58f0b77ef66553c4/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L625)

**What you expected to happen**:

Nodes which are about to be removed should not apply the new cloud-config – unless we have specific reason for this?

**How to reproduce it (as minimally and precisely as possible)**:
* Create a cluster with a single worker pool
* Change the worker pool configuration, such that a node rollout is triggered
* Observe the old worker download and apply the new configuration

**Anything else we need to know?**:

Discovered in the context of #4254. Just changing the logic on how the cloud config secret name is computed isn't really feasible, as we saw in #4390. If this would be the direction we're going for, we would need some logic to have two secrets (one with the old name, one with the new name) for some period of time, such that we don't break existing clusters, which have the secret-to-be-downloaded in their downloader script on disk. While this script kind of updates itself, we would still need the old secret for at least one successful cloud-config update cycle for each node. 

**Environment**:
- Gardener version: 1.27
- Kubernetes version (use `kubectl version`): 1.20.6
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
> Discovered in the context of #4254.

Actually, my understanding for the bug was always exactly what is now described in this ticket and I would say it is duplicate of #4254. Or maybe #4254 is about something different?

**Comment by voelzmo** [comment]
While #4254 is caused by this issue, they're still talking about different things. For example, we tried to fix #4254 without fixing this issue. I think we agreed that #4254 is acceptable to have (because it goes away when there are no clusters with k8s version <1.22 anymore), while this issue here is probably something we should think about how to solve. Does this make sense?

**Comment by voelzmo** [comment]
Approaches we tried unsuccessfully
* give the osc a new name when CRI changes: #4289 
  * We reverted this later with #4408 because of #4390
* Finding out if the node is about to be deleted by looking at the taints set by MCM:
```
pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh:

+NODE_TAINTED=$({{ .pathBinaries }}/kubectl --kubeconfig="{{ .pathKubeletKubeconfigReal }}" get node "$NODENAME" -o jsonpath={'.spec.taints[?(@.key == "deployment.machine.sapcloud.io/prefer-no-schedule")].value'})
+if [[ "$NODE_TAINTED" != "True" ]]; then
+  echo "Will apply changes as node is not tainted to noSchedule"
+else
+  echo "No changes as node is  tainted with noSchedule"
+fi
+
+if [[ "$NODE_TAINTED" != "True" ]]; then
+  # Apply most recent cloud-config user-data, reload the systemd daemon and restart the units to make the changes
+  # effective.
+  if ! diff "$PATH_CLOUDCONFIG" "$PATH_CLOUDCONFIG_OLD" >/dev/null || \
+     ! diff "$PATH_CCD_SCRIPT_CHECKSUM" "$PATH_CCD_SCRIPT_CHECKSUM_OLD" >/dev/null || \
+     [[ "$HYPERKUBE_IMAGE_USED_FOR_LAST_COPY_KUBELET" != "$LAST_DOWNLOADED_HYPERKUBE_IMAGE" ]] ||
+     [[ "$HYPERKUBE_IMAGE_USED_FOR_LAST_COPY_KUBECTL" != "$LAST_DOWNLOADED_HYPERKUBE_IMAGE" ]]; then
+
+    echo "Seen newer cloud config or cloud config downloader version or hyperkube image"
+    if {{ .reloadConfigCommand }}; then
+      echo "Successfully applied new cloud config version"
+      systemctl daemon-reload
+  {{- range $name := .units }}
+  {{- if and (ne $name $.unitNameDocker) (ne $name $.unitNameVarLibMount) (ne $name $.unitNameCloudConfigDownloader) }}
+      systemctl enable {{ $name }} && systemctl restart --no-block {{ $name }}
+  {{- end }}
+  {{- end }}
+      echo "Successfully restarted all units referenced in the cloud config."
+      cp "$PATH_CLOUDCONFIG" "$PATH_CLOUDCONFIG_OLD"
+      md5sum ${PATH_CCD_SCRIPT} > "$PATH_CCD_SCRIPT_CHECKSUM_OLD" # As the file can be updated above, get fresh checksum.
+    fi
```

But this doesn't work consistently as there's no guarantee that the taint will be visible before the OSC content is updated and seen by the script.

**Comment by voelzmo** [comment]
After talking to @vpnachev about this some more, we agreed to try the following approach to avoid this scenario
* compute the WorkerPoolHash also during content creation for the OSC and include it in the OSC contents
* in the OSC executor, read the hash, and either write it to disk (if no hash there yet) or compare it to a hash that is already written to disk
* if hashes differ, don't execute cloud-config, regardless of content

This work, because a changed worker pool hash is our mechanism to roll nodes for an otherwise unchanged worker pool. All other mechanism (like the ones described above) don't work, because they run into race conditions.

**Comment by rfranzke** [comment]
I started looking into this issue and would like to summarize my line of thought here. In order to stop the `cloud-config-executor` from applying the most recent cloud config to nodes which are about to be terminated, I could think of two approaches:

#### Approach 1

1. `cloud-config-executor` reads its `Node` object and checks for a new `scheduled-for-termination` annotation:
    1. If it exists then it exits early.
    2. Otherwise, it executes the script (also if the annotation is not present).
2. Now the `Worker` controllers are responsible for annotating the `Node`s with `scheduled-for-termination=true` in case they plan to terminate a `Node`.
3. Since 99% of the Gardener systems use `machine-controller-manager`:
    1. `cloud-config-executor` considers the taint `deployment.machine.sapcloud.io/prefer-no-schedule:True: PreferNoSchedule` equal to the `scheduled-for-termination=true` annotation. This way, the extensions don't need adaptation, however the contract is still generic enough for `Worker` controllers which decide to NOT manage the `Node`s with `machine-controller-manager`.
    2. Alternatively (i.e., without considering this taint), we would need to add another reconciler in the `Worker` controller (extensions library) watching `Node`s in the shoots and then reconciling the `scheduled-for-termination` annotation according to the taint. This would be a lot of effort/cost without almost no value given that MCM is a “first-class citizen” anyways.

Still, this approach has the conceptual problem that `Nodes` could still get updated with the most recent cloud-config in case MCM is down or does not add the taint/annotation fast enough. Hence, it's no option.

#### Approach 2

This approach is similar to what I suggested earlier in https://github.com/gardener/gardener/pull/5273#discussion_r789772957:

1. `gardenlet` publishes checksum of cloud-config to a new field in the `extensionsv1alpha1.Worker` resource.
2. `cloud-config-executor` reads `Node` and checks for the `checksum-to-apply` annotation
    1. If the downloaded cloud-config checksum matches the value of the `checksum-to-apply` annotation then it executes it.
    2. For backwards-compatibility, if there is no such annotation, it also executes it.
    3. If the value does not match then it exits early.
3. Now the `Worker` controllers are responsible for annotating the `Node`s NOT scheduled for termination with the `checksum-to-apply` value read from the `extensionsv1alpha1.Worker` resources.

It doesn't seem to be straight-forward to implement 3. One approach could be to let the generic `Worker` actuator loop over all `Node`s, check for the `deployment.machine.sapcloud.io/prefer-no-schedule:True: PreferNoSchedule` taint and then maintain the `checksum-to-apply` annotation accordingly.
However, this still has the problem that MCM might be down while the `Worker` controller loops over the `Node`s, so it does not know “when” is the right time to maintain the annotation (when did MCM mark the respective nodes for termination?). Also, it doesn't play well together with operations outside of the reconciliation (i.e. if `cluster-autoscaler` decides to shut down a `Node`).

<hr>

In summary, I don't think that we can find a solution for the problem that justifies the effort/implementation costs required to make it work. Also, the entire node bootstrapping and update procedure with the `cloud-config-{downloader,executor}` is already complicated enough, and any such mechanism would just exacerbate this "problem".

So, I decided to go back one step and re-assessed the goal that we actually try to achieve here, which is: When updating the CRI for worker pools then we'd like to perform a rolling update of the nodes and only use the new CRI on the new nodes while keeping the old as before.
This is exactly the same that we already achieve today when updating minor Kubernetes versions (we don't want old nodes to restart kubelet with the new minor version). For changes to CRI, this actually is the same (in-place updates don't seem to be a realistic/workable use-case).

1. Now, we already use a function for the secret name (https://github.com/gardener/gardener/blob/da556e69b265796e7b31f07b58f0b77ef66553c4/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L618-L626) which computes a key based on the Kubernetes version. Those secrets contain the cloud-config which is later downloaded to the nodes. The mentioned function is used to compute distinct secrets when the minor Kubernetes version is changed. This way, old nodes are not updated while new nodes get the new secret (with new cloud-config). Can't we do the same for the CRI?
2. Then I saw that there was already an attempt to implement exactly this: https://github.com/gardener/gardener/pull/4289 which got reverted again with https://github.com/gardener/gardener/pull/4408 due to https://github.com/gardener/gardener/issues/4390 
3. However, I actually think that this is the way to go, so we should find a way to make this backwards-compatible.

**Comment by vpnachev** [comment]
> gardenlet publishes checksum of cloud-config to a new field in the extensionsv1alpha1.Worker resource.

Single `extensionsv1alpha1.Worker` is responsible for all pools (machinedeployments), each pool should have different checksum. And the extension should somehow distinguish which nodes are to-be-deleted from the pool. Without going into further details, I cannot follow how this idea could resolve the issue.


> However, I actually think that this is the way to go, so we should find a way to make this backwards-compatible.

It indeed looks the same as minor k8s version update, but it was implemented since day one or back in the time when sporadic replacement of all nodes was not a problem. So, if it is done in a backward-compatible way, i.e. deploy the `cloud-config-` secret twice
1. once without any CRI to be considered into checksum calculation (just like it is today)
2. once for the configured CRI

This could be temporary code that will be removed after 1-2 minor releases. The problem is that the node is instructed to download the secret `cloud-config-foo-no-cri`, when Gardener consider the CRI when calculating the hash, the secret will be named `cloud-config-foo-with-cri` and `cloud-config-foo-no-cri` will be garbage collected. But due to the nature how `cloud-config-downloader` works on the node, it will keep trying to download `cloud-config-foo-no-cri` and will fail here. So, the idea is that both secrets exist for long enough time and both of them are configuring `cloud-config-downloader` to use `cloud-config-foo-with-cri`

**Comment by rfranzke** [comment]
> The problem is that the node is instructed to download the secret `cloud-config-foo-no-cri`, when Gardener consider the CRI when calculating the hash, the secret will be named `cloud-config-foo-with-cri` and `cloud-config-foo-no-cri` will be garbage collected. But due to the nature how `cloud-config-downloader` works on the node, it will keep trying to download `cloud-config-foo-no-cri` and will fail here. So, the idea is that both secrets exist for long enough time and both of them are configuring `cloud-config-downloader` to use `cloud-config-foo-with-cri`

Right, this is what I have in mind @vpnachev. After the `cloud-config-downloader`s on the old nodes download the `cloud-config` from `cloud-config-foo-no-cri` for the first time, their scripts will be updated to point to the `cloud-config-foo-with-cri` in the future. After some releases, we can delete this temporary code then again. I will experiment with this.
