### ISSUE TITLE
Control plane not suspended or stopped when cluster is hibernated

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#444]
When we hibernate a cluster the control plane is not shut down. This produces many errors (in fact I have been hunting them until I realised that the cluster was hibernated) and consumes resources. Can we please scale the deployments to 0 or delete the pods in the control plane when the cluster is hibernated.

**Comment by vlerenc** [comment]
Can you be more specific? The control plane is shut down to some extent (e.g. monitoring stack), but not completely for technical reasons. Maybe we can improve hibernation further, but what are those errors?

**Comment by marwinski** [comment]
@rfranzke mentioned that the control plane is not shut down. Anyway, we see several megabytes (I guess to the extend of the log rotation) of garbage logs from the vpn pods (number of api servers plus 1). It appears that the api server pods and prometheus pods remain up.

**Comment by rfranzke** [comment]
etcd, kube-apiserver, kube-controller-manager, kube-scheduler(, aws-lb-readvertiser), and machine-controller-manager are not shut down. The rest including the entire monitoring stack and autoscaler is shut down.
I can't remember anymore why we kept the above mentioned pods. I guess it should be also fine to shut them down as well. @vlerenc, do you maybe remember the reason?

**Comment by vlerenc** [comment]
No @rfranzke, that's why I wrote "Maybe we can improve hibernation further". I can't recall any good reason anymore. Gardener has control and can resurrect at will, so let's try. Will reduce costs even more and of course get rid of the seed VPNs/logging that their shoot counterpart is long gone.

**Comment by rfranzke** [comment]
I wanted to implement it, but then I remembered why we might have decided to not scale down everything entirely: If a shoot is hibernated and shall be deleted then no etcd,apiserver,controller-manager will be running. However, the deletion flow needs to talk to the apiserver to ensure a proper cleanup.

We have three options:
1. We disallow shoot deletion when a cluster is hibernated: A user would have to wake up the cluster in a first step, and then delete it in another one. The overall deletion process will take much longer as the cluster needs to be woken up first.
1. We redeploy the needed components for the deletion process in the shoot deletion flow: Drastic code change, probably very ugly, and I'm not even sure if it can be done without complicating the whole code tremendously.
1. We scale down everything other than etcd, apiserver, kube-controller-manager, cloud-controller-managers: No special handling needed, but aws-lb-readvertiser, kube-scheduler, and machine-controller-manager are scaled down (which are currently not).

I heavily vote for option 3 as it can be achieved very fast, and does neither complicate/uglify the deletion process for the user nor for us (implementation-wise).
Would you agree?

**Comment by rfranzke** [comment]
Just had a chat with @dguendisch: When talking about the second approach I was assuming that the deployments have already been deleted, however, in fact they would have been only scaled down to zero. There might be an easy way to wake them up again when deleting a shoot. I will explore it and come back.

**Comment by rfranzke** [comment]
I explored this path a little bit. It is too complicated to really shut down everything entirely without modifying the codes in too many places. Lots of steps are depending on a running/available Shoot API server. We need at least
* etcd-events
* etcd-main
* kube-apiserver

Theoretically, we could scale down the remaining deployments and wake them up in the deletion flow.
I have done the implementation for this behaviour, however, the machine-controller-manager seems to delete `Machine` objects although the VMs are not yet gone:

```
$ kubectl -n shoot--dev--aws get mach                                                                                                            
No resources found.
```

```
$ kubectl get no
NAME                                          STATUS                     ROLES   AGE     VERSION
ip-10-250-18-145.eu-west-1.compute.internal   Ready,SchedulingDisabled   node    8m31s   v1.9.10
ip-10-250-25-166.eu-west-1.compute.internal   Ready,SchedulingDisabled   node    8m3s    v1.9.10
ip-10-250-3-226.eu-west-1.compute.internal    Ready,SchedulingDisabled   node    8m43s   v1.9.10
```

I informated @prashanth26 and @hardikdr to further investigate. I paused this one now as the implementation depends on a correct behaviour when scaling down the machine deployment to 0.

**Comment by prashanth26** [comment]
AWS takes a while (up to a few minutes) to terminate VMs. During this phase, the node object is stuck in   `Ready,SchedulingDisabled`. Eventually, these objects get deleted.

**Comment by rfranzke** [comment]
I checked again with @hardikdr and @prashanth26: Seems like the behaviour reported in the previous comment was a "false positive": The actual VMs have been correctly deleted on AWS, hence, it was correct  to also delete the `Machine` objects. However, as we have scaled down KCM the node-lifecycle-controller inside was not running anymore. This controller is responsible for deleting the `Node` objects. So, we also need the
* kube-controller-manager

to prevent modifying the code in too many places.
We would end up with running etcd, apiserver, controller-manager pods during shoot hibernation, effectively saving resources/costs for the unneeded machine-controller-manager, cloud-controller-manager, aws-lb-readvertiser.

**Comment by amshuman-kr** [comment]
@rfranzke Perhaps we can shutdown kube-controller-manager after it has deleted the nodes? Is that a possibility?

**Comment by rfranzke** [comment]
We could shut it down in a later reconciliation, but not in the same reconciliation that hibernates a cluster (too complicated code-wise).

**Comment by rfranzke** [comment]
Opened PR #477. As described before we will end up with etcd and the kube-apiserver (and the kube-controller-manager if there are still nodes, however, it would be scaled down in a further reconciliation step).

@marwinski As we keep the kube-apiserver for now we will also keep the vpn-seed (same pod). If you want to get rid of the error messages produced by VPN you add a check whether nodes exist (or better, whether a vpn-shoot pod exists and runs), and only try establishing the connection if this succeeds (call against apiserver similar to https://github.com/gardener/vpn/blob/master/seed/network-connection.sh#L46-L53).

**Comment by vlerenc** [comment]
I had no chance to read through the stream of messages yesterday, but my take would have been clearly #1, but the following comments shed some more light on the matter: internal dependencies to a running API server. What exactly are these dependencies, e.g. care controller?

Reasoning: #1 or rather a total shutdown of the control plane is the right thing to do, because:
1. It basically relieves the seed of all responsibility and will later fit nicely into relocating shoots to other seeds (hibernation is the time window the customer gives us to rebalance the seeds without having to pay for it with a lower availability).
2. All our efforts to reduce costs, e.g. cron-based hibernation, pay off more if the control plane is gone.
3. We plan to have a large number of hibernated clusters with our output qualification process (pool of hibernated seeds, hibernated shoots after PR testing), so every core we do not burn/memory we release, saves money. 
4. In summary, costs, costs, costs. Especially ETCD will consume a lot of resources in larger clusters (vertically scaled with the number of max nodes and who would scale it down, if not we again in additional code) and I am not sure how the API servers will react/when they will scale-down (in productive clusters not below 2 anyways and the vertical scaling is static in relation to the number of max nodes also here, but of course we can change that behaviour in the case of hibernation, but that's even more code).
5. VPN issues (another motivation, though I agree, that hopefully there is also another solution)
6. All in all, the issues with MCM above already indicate dangerous complexity (not even sure I would have scaled it down, if the rest of the control plane still runs anyway), maybe we will have more issues with total shutdown, maybe less/some things will become easier (e.g. scale-in/down mentioned in the lines above).

OK, we will do whatever you decide for practical reasons, but my goal is clearly total shutdown and nothing else. Only then we will have peace with this topic and really save money for our community.

**Comment by rfranzke** [comment]
Fully agreed, my goal is the same - I just don't want to spend this time right now implementing it because it is not straight-forward.

I have opened a PR that only keeps etcd+apiserver which should be fine for time being (at least it improves a lot in contrast to how it was before (all controllers still running). We will certainly address the topic again after the extensibility epic.
