### ISSUE TITLE
Cloud config downloader script does not catch cloud config reload error

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#4556]
**How to categorize this issue?**

/area quality
/kind bug
/priority 3

**What happened**:

Observed an outdated cloud config

![image](https://user-images.githubusercontent.com/33809186/130809705-53f764bc-6a1d-4724-b392-83e09af4ffec.png)

The kubelet binary version was the old 1.18.16.

However, the checksum on the Node was already updated indicating that the cloud config was successfully applied.

```
Annotations:        checksum/cloud-config-data: d93f7f2ea278ac7d3e18e88176cda0f76d4e2e1b8a6b021b497c433878e28cb3
```

You can also see it in the logs for the cloud-config-downloader
- the cloud init failed
- the node was updated nonetheless

![image](https://user-images.githubusercontent.com/33809186/130810233-cded446b-80ba-4cd2-82ed-f7c62a14e6bf.png)

**What you expected to happen**:

That the checksum `checksum/cloud-config-data` on the node is not updated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
This duplicated mac is something which I was constantly observing since several months and it was always failing because of the calico interfaces. This was the main driver os-ubuntu extension to be migrated from cloud-init to bash scripts, therefore I would like to ask you to also check the os extension running in this landscape, what is the version of os-ubuntu?

Ref: https://github.com/gardener/gardener-extension-os-ubuntu/issues/31#issuecomment-842094560

**Comment by danielfoehrKn** [comment]
It was the version v1.10.0 of the ubuntu extensions.
Now with v1.13.0 it seems to. have been resolved.
