### ISSUE TITLE
`Progressing` condition status for seed conditions

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4722]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority 3

**What would you like to be added**:
Similar to the `Shoot` condition statuses (https://github.com/gardener/gardener/blob/6cb966488b2801f1e2875d359f8a52b9d699341b/docs/usage/shoot_status.md#conditions), the `Seed` conditions should also support the `Progressing` status. Today, failing checks are immediately resulting in the `False` status.

**Why is this needed**:
To not disturb operators with short-time failing health checks due to progressing seed reconciliations.

**Comment by timebertt** [comment]
https://github.com/gardener/gardener/pull/5274 already tackles part of this. Once its merged, this issue can be tackled for the other parts as well.

**Comment by timebertt** [comment]
What is the status here? What's missing for completing this issue?
@plkokanov @kris94

**Comment by plkokanov** [comment]
Currently only the `Bootstrapped` and `SeedSystemComponentsHealthy` are set to `Progressing` during reconciliations. 
`BackupBucketsReady`, `ExtensionsReady` and `GardenletReady` are still only set to `Unknown`, `True` or `False`. 

Should we add support for `Progressing` status to them as well?

**Comment by rfranzke** [comment]
Yes

**Comment by plkokanov** [comment]
I plan to finish this next week. Nearly done with the first part.

- [x] Add a new `conditionThreshold` for the `ExtensionsReady` condition that is managed by the [seed_extension_control](https://github.com/gardener/gardener/blob/master/pkg/gardenlet/controller/seed/seed_extension_control.go). The `ExtensionsReady` condition will be set to progressing if any of the `ControllerInstallation`s'  `Installed` `Healthy` or `Valid`  conditions are not true. Eventually the `ExtensionsReady` will be either set to `False`, if the conditions do not become true within the `conditionThreshold`, or it will be set to `True` if they do. -> https://github.com/gardener/gardener/pull/6551
- [x] extend the [controllerinstallation_care_control]() to also check for the `ResourcesProgressing` condition of the `ManagedResources` that are deployed for `ControllerInstallations` and reflect that in a new `Progressing` condition in the `ControllerInstallation` (similar to `Healthy` and `Installed`). Make the `ExtensionsReady` condition also consider that `Progressing` condition. -> https://github.com/gardener/gardener/pull/6590
- [x] Add a new `conditionThreshold` for the `BackupBucketsReady` condition that is managed by [seed_backup_bucket_reconcile](https://github.com/gardener/gardener/blob/master/pkg/controllermanager/controller/seed/seed_backup_bucket_reconcile.go) and make it so that the condition is set to Progressing initially if there are any errored `BackupBuckets`. -> https://github.com/gardener/gardener/pull/6587

I feel like the `GardenletReady` condition does not need a `Progressing` status as it already relies on a timeout before it is set to false.

**Comment by rfranzke** [comment]
All items are done

/close
