### ISSUE TITLE
Replace deprecated kubelet flags with recommended configuration

### ISSUE THREAD

**Issue by voelzmo** [gardener/gardener#4739]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:
Remove all deprecated kubelet flags and replace them with the new, recommended way. At the point of writing these are:

| flag | removed in | replacement |
|------|------------|-------------|
| `--cloud-provider` | k8s 1.23  | cloud-provider specific configuration |
| `--provider-id`| ? | kubelet config file |
| `--enable-controller-attach-detach` | ? | kubelet config file |

**Why is this needed**:
Some of these will be removed with k8s 1.23 and require cloud-provider specific configuration, so we should probably look at the necessary work well ahead of supporting 1.23.

**Related issues**
* AliCloud provider extension: https://github.com/gardener/gardener-extension-provider-alicloud/issues/202
* `<add other extensions here>`

**Comment by rfranzke** [comment]
/close as this was done as part https://github.com/gardener/gardener/issues/5102

https://github.com/gardener/gardener-extension-provider-alicloud/issues/202 remains open since there is a follow-up task w.r.t. the elimination of the `--provider-id` flag (see [details](https://github.com/gardener/gardener-extension-provider-alicloud/issues/202#issuecomment-1022443917)).
