### ISSUE TITLE
Health checks of extension resource to use dedicated `Lease` resource for heart beats.

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4798]
**How to categorize this issue?**

/area quality
/kind enhancement
/priority 3

**What would you like to be added**:
A new optional field `LastHeartbeatTime` to be introduced in the conditions. This field should be used only for heartbeats.
Currently `LastUpdateTime` is mused for this purpose.

**Why is this needed**:
Currently, the `LastUpdateTime` field is used for heartbeats by the extension's health check https://github.com/gardener/gardener/blob/13249899a9632e64ecd990098cbb66251927dddf/extensions/pkg/controller/healthcheck/reconciler.go#L277-L278

This timestamp is used here https://github.com/gardener/gardener/blob/13249899a9632e64ecd990098cbb66251927dddf/pkg/operation/care/checker.go#L524 to check when the last health check was done.

But this contradicts with the fact that the `LastUpdateTime` should be updated only when there is change in the reason, message or codes of a condition https://github.com/gardener/gardener/blob/13249899a9632e64ecd990098cbb66251927dddf/pkg/apis/core/v1beta1/helper/condition_builder.go#L103

**Comment by timebertt** [comment]
I don't have much more in my head other than what is described in https://github.com/gardener/gardener/pull/5394#pullrequestreview-876002608 already.
I think, this outlines the next steps pretty well and I'm unsure what to propose without picking up the topic on my own.
/unassign

**Comment by plkokanov** [comment]
After taking a look @timebertt's proposal in https://github.com/gardener/gardener/pull/5394#pullrequestreview-876002608 and experimenting a bit here's how I plan to proceed with this:

-  Extensions stop updating the lastUpdateTime in the extension status if no changes to the condition occurred (as previously suggested)
- `gardenlet` reuses the leader election `lease` resources of extension controllers to check if the extensions are still operational. I feel like it's not necessary to add a second `lease` resource that will be dedicated just for heart beats because `gardenlet` runs in the same cluster where the leader election `lease`s are and adding a dedicated resource would require a new `lease` controller that takes care of updating it at regular intervals.
- Add a way for `gardenlet` to find the `lease` resource of the correct extension controller depending on the extension resource whose conditions are currently being checked. One way to do that is to get the corresponding `ControllerRegistration` from the garden cluster (depending on the extension resource's kind and type), then use its name to find the namespace of the extension controller's `lease` via a label selector (the namespaces where extension controllers and their `lease`s are have the following labels: `gardener.cloud/role=extension` and `controllerregistration.core.gardener.cloud/name=<controller registration name>`). The extension `kind/providerType` to `ControllerRegistration` name can be saved in a map so that the retrieval of `ControllerRegistration` doesn't happen on each health check reconciliation.

@timebertt @shafeeqes wdyt?

**Comment by timebertt** [comment]
Instead of retrieving all `ControllerRegistrations` and then listing namespaces that might match, gardenlet should retrieve all `ControllerInstallations` for its seed and map these to the corresponding extension objects via `ControllerRegistrations`.
`ControllerInstallations` have a 1:1 relation to their installation namespace.
However, there is no contract about the lease name currently.
What's your plan to enforce this?

**Comment by plkokanov** [comment]
Initially I assumed that there was only one lease per namespace (since we currently have one controller per namespace). However, I guess this is not necessarily true? 
There's also a function that the extension controllers use when generating the leader election name - `cmd.LeaderElectionNameID(<extension-name>)`, at least for the provider extensions. Currently we only perform the health checks for extension resources that are reconciled by the provider extension controllers, but this might change in the future.
And one more problem would be that the leader election is not necessarily handled by `Lease` resources, as the resource kind can be specified in a value from the controller-registration helm charts.

I plan to focus more on this issue on Tuesday and Wednesday next week. If I cannot come up with a more strict way to find out the names and kinds of lease resources for extension controllers, then we might have to use dedicated heartbeat resources (as was also suggested initially). However, in that case `gardenlet` might have to first check if it can find the heartbeat resource, and if it cannot find it, try to check the update time of the extension resource's conditions. This would be needed to cover cases where the extension controllers still do not support a dedicated heartbeat resource.

**Comment by plkokanov** [comment]
/reopen as the new heartbeat controller has to be enabled in the extension controllers when `gardener/gardener`>=`v1.58.0` is revendored

---
### Provider Extensions
- [x] Revendor g/g in [extension-provider-openstack](https://github.com/gardener/gardener-extension-provider-openstack) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-openstack/pull/512
- [x] Revendor g/g in [extension-provider-equinix-metal](https://github.com/gardener/gardener-extension-provider-equinix-metal) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/236
- [x] Revendor g/g in [extension-provider-vsphere](https://github.com/gardener/gardener-extension-provider-vsphere) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-vsphere/pull/319
- [x] Revendor g/g in [extension-provider-aws](https://github.com/gardener/gardener-extension-provider-aws) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-aws/pull/642
- [x] Revendor g/g in [extension-provider-gcp](https://github.com/gardener/gardener-extension-provider-gcp) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-gcp/pull/516
- [x] Revendor g/g in [extension-provider-azure](https://github.com/gardener/gardener-extension-provider-azure) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-azure/pull/594
- [x] Revendor g/g in [extension-provider-alicloud](https://github.com/gardener/gardener-extension-provider-alicloud) and enable heartbeat controller. https://github.com/gardener/gardener-extension-provider-alicloud/pull/544
---
### Networking Extensions
- [x] Revendor g/g in [extension-networking-cilium](https://github.com/gardener/gardener-extension-networking-cilium) and enable heartbeat controller. https://github.com/gardener/gardener-extension-networking-cilium/pull/133
- [x] Revendor g/g in [extension-networking-calico](https://github.com/gardener/gardener-extension-networking-calico) and enable heartbeat controller. https://github.com/gardener/gardener-extension-networking-calico/pull/220
- [x] Revendor g/g in [extension-shoot-networking-filter](https://github.com/gardener/gardener-extension-shoot-networking-filter) and enable heartbeat controller. https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/39
- [x] Revendor g/g in [extension-shoot-networking-problem-detector](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector) and enable heartbeat controller. https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/35
---
### OS Extensions
- [x] Enable controller in the common app package for os extensions: https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/operatingsystemconfig/oscommon/app/app.go https://github.com/gardener/gardener/pull/6968
- [x] Revendor g/g in [extension-os-ubuntu](https://github.com/gardener/gardener-extension-os-ubuntu) and enable heartbeat controller. https://github.com/gardener/gardener-extension-os-ubuntu/pull/73
- [x] Revendor g/g in [extension-os-gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux) and enable heartbeat controller. https://github.com/gardener/gardener-extension-os-gardenlinux/pull/71
- [x] Revendor g/g in [extension-os-suse-chost](https://github.com/gardener/gardener-extension-os-suse-chost) and enable heartbeat controller. https://github.com/gardener/gardener-extension-os-suse-chost/pull/77
- [x] Revendor g/g in [extension-os-coreos](https://github.com/gardener/gardener-extension-os-coreos) and enable heartbeat controller. https://github.com/gardener/gardener-extension-os-coreos/pull/53
---
### Others
- [x] Revendor g/g in [extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service) and enable heartbeat controller. https://github.com/gardener/gardener-extension-shoot-dns-service/pull/168
- [x] Revendor g/g in [extension-shoot-cert-service](https://github.com/gardener/gardener-extension-shoot-cert-service) and enable heartbeat controller. https://github.com/gardener/gardener-extension-shoot-cert-service/pull/135
- [x] Revendor g/g in [extension-shoot-oidc-service](https://github.com/gardener/gardener-extension-shoot-oidc-service) and enable heartbeat controller. https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/70
- [x] Revendor g/g in [extension-runtime-gvisor](https://github.com/gardener/gardener-extension-runtime-gvisor) and enable heartbeat controller. https://github.com/gardener/gardener-extension-runtime-gvisor/pull/65
- [x] Revendor g/g in [extension-registry-cache](https://github.com/gardener/gardener-extension-registry-cache) and enable heartbeat controller. https://github.com/gardener/gardener-extension-registry-cache/pull/4

---
When enabling the heartbeat controller the following changes are required (the provider-local extension controller is used as an example here):

- Define, add and validate the heartbeat controller options:

https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/cmd/gardener-extension-provider-local/app/app.go#L152-L156
https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/cmd/gardener-extension-provider-local/app/app.go#L186
https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/cmd/gardener-extension-provider-local/app/app.go#L201-L203
https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/cmd/gardener-extension-provider-local/app/app.go#L245
https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/cmd/gardener-extension-provider-local/app/options.go#L60

- Modify the extension controller charts so that the `--heartbeat-namespace`, `--heartbeat-renew-interval-seconds` and RBAC are set properly:

https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/charts/gardener/provider-local/extension/templates/deployment.yaml#L60-L61
https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/charts/gardener/provider-local/extension/values.yaml#L42-L43
https://github.com/gardener/gardener/blob/e57e63d6e3165e2b788f16cd641cb23abe9c40c9/charts/gardener/provider-local/extension/templates/rbac.yaml#L49-L74

---

**Comment by rfranzke** [comment]
/close
all related tasks have been completed
