### ISSUE TITLE
Open Prometheus ingress or Grafana Explore feature to shoot owners

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4800]
**How to categorize this issue?**

/area monitoring
/kind enhancement

**What would you like to be added**:

Let's do one (or both) of the following:
- allow shoot owners to access the prometheus ingress of their shoot clusters
- enable the `Explore` feature in the user-facing Grafana instance (ref https://github.com/gardener/gardener/pull/4140)

**Why is this needed**:

Endusers want to analyze the performance data of their clusters more freely.
Currently they are restricted to using the provided dashboards in the user-facing Grafana instance. They are currently not able to use arbitrary queries against prometheus (and loki).
Enabling endusers to debug and analyze their clusters in more detail, will relieve operators from helping them out because of current monitoring restrictions on their side.

**Comment by timebertt** [comment]
@wyb1 As you have already spent some thoughts on this back in the days, can you elaborate what options we have with which pros/cons?
cc @vlerenc @istvanballok

**Comment by wyb1** [comment]
Most of the cons were related to these 2 points:

1) End users can see the internal workings of the control plane
2) There is (currently) no contract between the monitoring and endusers

Point 1. is not necessarily negative since it means that endusers can help themselves if they know what they are looking for and considering that it will (hopefully) reduce operational load, it is more like a positive now.

Regarding point 2. any changes to the monitoring will affect the end users as well and we will have to figure out what to do when we deprecate metrics or change behaviors in the monitoring stack.

Overall though I think adding this feature will lead to a net positive. I would start with your suggestion of enabling the explore feature for end users. If we do that endusers should be able to create/edit dashboards as well, so we might as well give them access to the operator dashboards, too. This also means we can remove the users grafana, unless it still has a purpose for the logging (/cc @vlvasilev ).

**Comment by timebertt** [comment]
cc @Kristian-ZH as you pointed out some concerns in https://github.com/gardener/gardener/pull/4140#issuecomment-851445420

**Comment by Kristian-ZH** [comment]
In the past we had a discussion and decided to not expose everything to the end users. Instead of that we took an approach to whitelist the components we want to expose.
This decision was taken because we were not sure if the components are enough secure (logging critical data).
Also such logs are valuable for the Operators, not for the Users (I think).
/cc @vlvasilev
