### ISSUE TITLE
Allow excluding `ManagedResource`s from reconciliation

### ISSUE THREAD

**Issue by briantopping** [gardener/gardener#4806]
**How to categorize this issue?**
/area control-plane
/kind enhancement
/priority normal

**What would you like to be added**:
Have resource manager check if an annotation is on a resource before replacing it.

**Why is this needed**:
When a resource needs to be hand-patched by an operator to keep the system running, resource manager keeps overwriting it. gardener/gardener-resource-manager#100 would help so the origin could be found, but there are situations where even that takes too long. Allowing the operator to annotate the generated resource not to be overwritten would be helpful.

Understandably, this may be a feature and not a bug. In that case, maybe there is some kind of unique value for the annotation key could be required. For security-conscious environments, that value would be stored in Vault. 

Feel free to close this as will not fix, it was just a random idea. Cheers!

**Comment by rfranzke** [comment]
cc @dguendisch @ScheererJ 
IIUC, we recently had a case where such solution (allowing operators to annotate a ManagedResource to prevent GRM from reconciling it) would be helpful, correct?

**Comment by ScheererJ** [comment]
@rfranzke yes, I remember a few cases where this would have helped a lot.

**Comment by dguendisch** [comment]
+1000 correct, yes, absolutely :)
Even more worse, since the GRM is responsible for the projected volume tokens, scaling down GRM temporarily (to manually modify GRM observed resources) also will block i.e. gardener managed pods in kube-system from being created
```
E0114 13:09:17.437153       1 daemon_controller.go:320] kube-system/calico-node failed with : Internal error occurred: failed calling webhook "projected-token-mount.resources.gardener.cloud": Post "https://gardener-resource-manager.shoot--core--d123:443/webhooks/mount-projected-service-account-token?timeout=10s": context deadline exceeded
I0114 13:09:17.437224       1 event.go:291] "Event occurred" object="kube-system/calico-node" kind="DaemonSet" apiVersion="apps/v1" type="Warning" reason="FailedCreate" message="Error creating: Internal error occurred: failed calling webhook \"projected-token-mount.resources.gardener.cloud\": Post \"https://gardener-resource-manager.shoot--core--d123:443/webhooks/mount-projected-service-account-token?timeout=10s\": context deadline exceeded"
```

**Comment by rfranzke** [comment]
OK, thanks for clarifying :) Then we probably want to look into this somewhen.

/area dev-productivity

**Comment by timebertt** [comment]
> Even more worse, since the GRM is responsible for the projected volume tokens, scaling down GRM temporarily

Hmm, wouldn't it be enough to make sure, grm respects the respective `*max-concurrent-workers` flags so that operators can "scale down" the MR controller?
I think, it's not respected because of some missing plumbing. So that should be way easier to fix/implement and maintain than a "lock annotation".

Would this be enough for the cases that you have in mind @dguendisch @ScheererJ?

**Comment by dguendisch** [comment]
> Would this be enough for the cases that you have in mind @dguendisch @ScheererJ?

One thing is to be able to "scale down" MR handling at all. In the past this was possible by scaling down GRM, so setting some startup flag would do equally well.

However the feature of "selectively" disabling certain MRs or even better like described in this ticket on the affected actual resource (like a daemonset) would be super handy because this is the usual task: recognizing that something coming from MRs does not fit (be it too low resource limits, be it unfitting log levels, be it whatever) and wanting to therefore manually adapt the affected resource for some time.
Doing it on the affected resource has of course another consequence: the shoot owner can do it herself (which is obviously a pro and a con at the same time, but I'd consider it an advantage in particular for outage situations...).

**Comment by timebertt** [comment]
Ok, thanks for your thoughts. 

> Doing it on the affected resource has of course another consequence: the shoot owner can do it herself

I'm also a bit torn on this, so I can't form a clear opinion ATM. This should definitely considered more, when we start working on this topic.

For now, I opened https://github.com/gardener/gardener/issues/5281 about the bug I mentioned. This should be a long-hanging fruit which we can focus on first.

**Comment by rfranzke** [comment]
I think we should just allow excluding an entire `ManagedResource` from reconciliation (via annotation in the `Seed`) and not particular resources. This should be good enough for such "corner cases".

**Comment by rfranzke** [comment]
/title Allow excluding `ManagedResource`s from reconciliation
