### ISSUE TITLE
Resource Manager does not respect Chart namespace applied the same way Helm does

### ISSUE THREAD

**Issue by deitch** [gardener/gardener#4828]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority 3

**What happened**:

Applying a helm chart that expects to receive the equivalent of `helm install --namespace` does not get namespace applied, nor does it have a mechanism for doing so.

**What you expected to happen**:

Pass a namespace

**How to reproduce it (as minimally and precisely as possible)**:

Install a chart that expects a namespace to be applied at CLI, it will just get the `default`.

** Additional Information **

For lower helm-specific context, see [this issue](https://github.com/helm/helm/issues/10231)

When running `helm install chart`, I can run `helm install --namespace foo chart`. This means that:

* Any manifests that are not namespaced (e.g. `ClusterRole`) are unaffected
* Any manifests that have an explicit namespace in them are unaffected
* Any manifests that _are_ namespaced but do _not_ have an explicit namespace will be applied in that namespace

What helm does, is the equivalent of:

1. Render the chart
2. Apply the chart with the client-go version of `kubectl apply -n foo manifests`

Gardener's resource manager does the first part correctly (mainly because it copies the bit of helm code that does it). It then, however, just passes the rendered chart (i.e. manifests) as is.

The problem is that because charts _can_ expect users to pass `--namespace` when applying, some inevitably do (rook-ceph being the prime example that brought this up).

We could request that upstream charts be changed, but it is not correct to call those "wrong" if they are relying upon an explicit helm API.

Proposal: we extend the resource manager functions that apply charts (I am not sure if this goes in resource manager or in [ChartApplier](https://pkg.go.dev/github.com/gardener/gardener@v1.33.0/pkg/client/kubernetes#ChartApplier)) to be able to receive a namespace and apply it as the equivalent of `kubectl apply -n <namespace>`.

cc @stoyanr who was involved in the discussion and @rfranzke who should be involved in the discussion

**Comment by stoyanr** [comment]
As I already pointed out in https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/136#issuecomment-941018133, I am not sure that the proposed improvement brings enough value for the complexity involved. So far this was not an issue for any charts we or somebody else had to use, and from our perspective it's easily mitigated by adding a single namespace field to a resource that should probably be there anyway (since `helm` is ambiguous of its treatment of namespaces as can also be seen from helm/helm#10231). Being able to override the namespace when applying a chart does not make using `.Release.Namespace` correctly in the chart obsolete from my perspective.

As for whether and how this could be done in GRM or `ChartApplier`, in fact the choice is between GRM and `ChartRenderer`. In the scenario that you are interested in, charts are first rendered by [ChartRenderer](https://pkg.go.dev/github.com/gardener/gardener@v1.33.0/pkg/chartrenderer#Interface) that in turn uses Helm libraries under the hood. It then passes the contents of the rendered charts to GRM via `ManagedResource` resources that are applied by GRM later. So the namespace could be introduced either by the `ChartRenderer`, or by GRM. 

Both options would involve non-trivial effort, because:
* The Helm libraries `ChartRenderer` return the manifests as `[]byte` and there is no option to set the namespace as suggested.  In order to set the namespace, these manifests would have to be properly unmarshalled to Kubernetes resources, the namespace set (only where missing and only for namespaced resources), and then marshalled back to `[]byte`. The `ChartRenderer` is used in a number of places and so one should be careful to preserve backward compatibility (e.g. via an additional parameter to `Render`). 
* GRM currently has no notion of namespaces in managed resources at all. If a namespace is missing for a namespaced resource, it will always set it to `default`. To set the namespace in GRM, one would need to add the namespace as an optional field to  the `ManagedResource` spec, and ensure that it's set and propagated correctly.

**Comment by deitch** [comment]
> Being able to override the namespace when applying a chart does not make using .Release.Namespace correctly in the chart obsolete from my perspective.

I agree with you. If I were designing helm, I probably would have said, from the beginning, "we will not use `kubectl apply -n <ns>` anywhere. If you use `helm install --namespace foo`, we will just set that for `.Release.Namespace`; if you don't template it, you don't get it."

I did not design helm, however; people much smarter than me did, and this is what there is. It _does_ apply it using the `kubectl -n <ns>` (well, apply it in the client-go libraries [here](https://github.com/helm/helm/blob/932d2a98a2a01c069aaefb25b12c1ece1f1879d5/pkg/action/install.go#L275)), and so charts _can_ rely on it. I might have had the (bad) luck of stumbling across the first case messed up by it in rook-ceph, but rook-ceph is pretty popular, and it is highly unlikely to be the last.

We are agreeing on how this _should_ work, but it doesn't work the way we think it _should_, so don't we want to match the way charts will be expected to be applied? Given the existing helm context, that seems to me to be the right thing to do.

> As for whether and how this could be done in ...
> 
> Both options would involve non-trivial effort, because:

You are making a good practical argument. I only can contribute so much to this discussion, because my knowledge of this part is quite small compared to yours.

My limited opinion here is that we shouldn't mess with the returned `[]byte` values, as you point out. It is very messy and almost guaranteed to be a source of headaches and errors. We should do what helm does, and have a namespace available when applied, essentially what `helm install` itself does. I agree, this is non-trivial - we would need to have an option to add a namespace when applying a managed resource, and get it right, and not break existing things - but it is less risky than the first option.
