### ISSUE TITLE
Avoid querying all extension admission webhooks

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#4932]
**How to categorize this issue?**

/area high-availability
/area robustness
/kind enhancement

**What would you like to be added**:
Would be great if gardener had a mechanism to avoid having to query all admission webhooks on e.g. shoot creation.
Today on a given installation we have e.g. a bunch of them:
```
gardener-extension-admission-alicloud
gardener-extension-admission-aws
gardener-extension-admission-azure
gardener-extension-admission-gcp
gardener-extension-admission-openstack
gardener-extension-validator-vsphere
```

Now if we create a shoot e.g. for AWS, also the non-AWS webhooks are called, and if one of them is not ready (e.g. the vpshere one), then the whole admission fails and shoots cannot be created.

@rfranzke suggested that such thing could be implemented by defining some labels on a shoot by another/new admission webhook, that would allow the cloudprovider specific webhooks to filter correspondingly for shoots they are responsible for and thus ignore all other shoots.

**Why is this needed**:
Limit the blast radius of cloudprovider specific or extension specific failures.

**Comment by rfranzke** [comment]
@shafeeqes can this issue be closed now?

**Comment by shafeeqes** [comment]
All the extensions which currently have admission webhooks have this ObjectSelector now. If we introduce admission webhooks in other extensions in the future, probably they can just add the objectSelector since gardener/gardener part is already handled. I'd say we can close this issue.
FYI, This change is not yet adapted in the landscape setup, since there are releases pending for most of the extensions. I have opened the PR, but it's in draft state.

**Comment by rfranzke** [comment]
OK, thanks. Then everything related to the open source work seems to be done.
/close

**Comment by shafeeqes** [comment]
For future reference:
Currenly we don't have webhooks for DNS specific validation in the extensions. But when we introduce it in the future, we should have a seperate webhook. Because if we use the objectSelector for the DNS labels in the resources, since the requirements from `matchLabels` are added ([ref](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements)), and gcp shoots can use `aws-route53` for dns, we cannot set the requirements in the current validation webhook.

**Comment by shafeeqes** [comment]
Add objectSelector in `admission-cilium` : https://github.com/gardener/gardener-extension-networking-cilium/pull/115
