### ISSUE TITLE
Expected Capacity of machine should be able to be passed down to worker resource

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/gardener#4948]
**How to categorize this issue?**

/area autoscaling
/area usability
/kind enhancement
/kind api-change
/kind discussion

**What would you like to be added**:
* add a `expectedNodeAttributes` field to the `core.gardener.cloud/v1beta1.Machine`
* add `expectedNodeAttributes` field to the `extensions.gardener.cloud/v1alpha1.WorkerPool` which can be updated by gardenlet while creating worker resource
* add validation logic for the fields

the field is 
```
type ExpectedNodeAttributes struct {
	CPU *int 
	GPU *int 
	Memory *resource.Quantity
}
```
**Why is this needed**:
To enable machine resource information to be passed down from cloudprofile to worker resource, and finally to machineclass

**Comment by himanshu-kun** [comment]
cc @rfranzke @AxiomSamarth 
I want to discuss 
* if the name `expectedNodeAttributes` is ok
* the types of CPU,GPU and particularly Memory is fine , or any other suggestions
* any other thoughts ,improvement tips or queries

**Comment by AxiomSamarth** [comment]
Linked Umbrella issue - https://github.com/gardener/autoscaler/issues/27

**Comment by AxiomSamarth** [comment]
> cc @rfranzke @AxiomSamarth I want to discuss
> 
> * if the name `expectedNodeAttributes` is ok
@himanshu-kun 

The name `ExpectedNodeAttribute` looks good to me. I would prefer the same as the name would be consistent across custom resources (MachineClass uses the same name)

> * the types of CPU,GPU and particularly Memory is fine , or any other suggestions

Regarding the Types, I think integer should be good for CPU & GPU. I do not see any fractional values in the machine catalogue for AWS/Azure. I will look for further comments by other senior colleagues.

> * any other thoughts ,improvement tips or queries

So far so good. Once you hear from Rafael, you can open a draft PR.

**Comment by rfranzke** [comment]
> if the name expectedNodeAttributes is ok

Personally, I find `expectedNodeAttribute` highly confusing when reading it. In your description you write "end user to provide the resources cluster autoscaler should consider when scaling a worker pool from zero". I don't see how `expectedNodeAttribute` fits here. Finding precise, short names is hard and I don't have a better proposal now, but maybe you can reiterate on that.

> the types of CPU,GPU and particularly Memory is fine , or any other suggestions

Why not use `resource.Quantity` for all of them, similar to how it's done in Kubernetes core APIs and also in our `CloudProfile` resource (https://github.com/gardener/gardener/blob/29ffac5ed724458803b7748800e9de6f07c84f0a/pkg/apis/core/v1beta1/types_cloudprofile.go#L140-L145)?

**Comment by AxiomSamarth** [comment]
@rfranzke Hey Rafael, 

Thanks. Regarding the data type `resource.Quantity`, yes, this is thought through. You are correct. This shall be implemented using `resource.Quantity` but somewhere in new future.

Why?

Currently, the machine catalogue (like [here](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go)) which CA uses has these values as integer types and even the [node template](https://github.com/gardener/autoscaler/blob/2bf7dbe0a9dfe0a49f6c31186d17927cd0e3df26/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L120-L125) uses the same. Also, [while building the node from the node template](https://github.com/gardener/autoscaler/blob/2bf7dbe0a9dfe0a49f6c31186d17927cd0e3df26/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L766-L769), these `int` types are ultimately type casted to `resource.Quantity`.

With the changes coming via PR linked to this issue, indeed, the scope of usage of machine catalogue will be nullified in Gardener context. However, we are looking forward to retain the usage of node template generation using machine catalogue for next couple of releases to offer backward compatibility (especially for those who are using MCM/CA independent of Gardener).

**Comment by himanshu-kun** [comment]
Hi @rfranzke 
Thanks for valuable inputs. 
We'll try to come up with a more meaningful name other than `expectedNodeAttributes`
The second point abt using `resource.Quantity` now seem valid to us. Earlier we were skeptical to make the changes as that would have required changes in the CA level as well. But after discussion among ourselves we have decided to make the following changes

1. Change `expectedNodeAttributes` to a more meaningful name
2. Use `resource.Quantity` for CPU, GPU as well in gardener `core` API
3. The changes in CA include
     - change the `InstanceType` struct to use `resource.Quantity` for CPU,GPU, MemoryMb fields in [mcm_manager.go](https://github.com/gardener/autoscaler/blob/2bf7dbe0a9dfe0a49f6c31186d17927cd0e3df26/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L120-L125) and [aws catalogues](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go) and [azure catalogues](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go)
     - adapt these in [buildNodeFromTemplate()](https://github.com/gardener/autoscaler/blob/2bf7dbe0a9dfe0a49f6c31186d17927cd0e3df26/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L766-L769) method and [getMachineDeploymentNodeTemplate](https://github.com/gardener/autoscaler/blob/2bf7dbe0a9dfe0a49f6c31186d17927cd0e3df26/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L609) method
     - make changes in the machineClass API [here](https://github.com/gardener/machine-controller-manager/blob/77ebf4db974011eb30b03370eeed7e37576e3331/pkg/apis/machine/v1alpha1/machineclass_types.go#L74-L98)

cc @vlerenc @ashwani2k

**Comment by rfranzke** [comment]
Thanks!

**Comment by danielfoehrKn** [comment]
Do I get this right, that these hardcoded resource values are only required for ScaleMP where the amount of memory not necessarily matches the instance type? 

While having read the attached generic scale from zero approaches [and this comment](https://github.com/gardener/autoscaler/issues/27#issuecomment-910201951), I am still not quite sure why this has to be hardcoded in the Shoot resource.

The main argument if I get it right, is that at runtime the amount of available memory can change and not necessarily matches the instance type.
Node resources are advertised by the kubelet on the `Node` resource via the `Capacity`. Could that be used to advertise the capacity on the `MachineClass` ?

**Comment by AxiomSamarth** [comment]
Hey @danielfoehrKn You are correct with respect to the ScaleMP use case. This is one of the use cases which, this scale from zero story is addressing. The primary use case, this is trying to solve is to make Cluster Autoscaler scale up the worker pool from zero (when there are 0 nodes in the worker pool)

>Node resources are advertised by the kubelet on the Node resource via the Capacity. Could that be used to advertise the capacity on the MachineClass ?

I doubt, if we can achieve this for 'scale from zero scenario' because there will be no nodes for the `kubelet` to refer the `Capacity` from. Am I right?

**Comment by danielfoehrKn** [comment]
> I doubt, if we can achieve this for 'scale from zero scenario' because there will be no nodes for the kubelet to refer the Capacity from. Am I right?

Correct, but this could be reconciled by a controller in the MCM which has access to the Shoot API server in the Seed. The capacity could then be regularly written to the MachineClass.

**Comment by himanshu-kun** [comment]
> Correct, but this could be reconciled by a controller in the MCM which has access to the Shoot API server in the Seed. The capacity could then be regularly written to the MachineClass.

The problem which ScaleMP colleagues were facing is that scale-from-one works for them perfectly but not scale-from-zero.
The solution you are proposing solves the aspect where the machineclass can be updated with the resources of the node. 
But the problem will be that we don't have the node (or any similar node) already present to read the resources from, and MCM also creates the machine/node once Cluster Autoscaler instructs it to do so. 
Cluster Autoscaler will not instruct until it can form a nodeTemplate ( for which it needs node resources).
So the only way to break this is when some third party(Gardenlet and extension providers) updates the machineClass with the resources, so that CA can form nodeTemplate. The only way third party can get to know the resources during runtime is when its explicitly mentioned by the customer somewhere and since only customer facing API is shoot API we made changes there.

**Comment by rfranzke** [comment]
@timebertt proposed to rather not expose this `expectedNodeAttributes` field in the `Shoot` API but only in the `extensions.gardener.cloud/v1alpha1.Worker` resource. This way, only scale-from-zero will be supported.
In order to support the ScaleMP scenario we could extend the `providerConfig` of the SuSE CHost extension (as initially proposed in https://github.com/gardener/autoscaler/issues/27#issuecomment-910258051). If overridden node attribute configuration is provided here, the SuSE CHost extension could inject them via a mutating webhook into the `MachineClass`.
The rationale behind this proposal is that "overwriting node attributes" is highly specific to the ScaleMP scenario only, right? There is no other reasonable use case, or? If so, it should not be part of the `Shoot` API, probably. Obviously, this is a bit more to implement, however, perhaps the cleaner solution.

**Comment by timebertt** [comment]
Side-question: is there actually a need to support scale-from-zero for the ScaleMP scenario? I have the feeling, that we are overdoing it because of an edge case (?). I feel like, it would probably be acceptable to simply only support scale-from-one for ScaleMP, because it is anyways not widely used (not at all?)?
I might be wrong, so I'm asking to clarify this :)

**Comment by ashwani2k** [comment]
> Side-question: is there actually a need to support scale-from-zero for the ScaleMP scenario? I have the feeling, that we are overdoing it because of an edge case (?). I feel like, it would probably be acceptable to simply only support scale-from-one for ScaleMP, because it is anyways not widely used (not at all?)? I might be wrong, so I'm asking to clarify this :)

I would like to pitch in here as I was involved in some of the initial discussions around the requirement.
For worker pools with XXL type machines, scale to zero is very important to save costs.
If I understand correctly, the biggest value preposition of ScaleMP is to expand instance memory of the provisioned XXL type machines to get even more out of them. So not able to support scale from zero will be counter intuitive to keep the XXL machines running if they consume scaleMP but supported otherwise.
Also for `mutli-az` deployments where scale from zero becomes more important (costs perspective), currently to achieve scaling across `AZs` we have the limitation to keep the `Min` for workers to be equal to `no. of AZs` configured for providers where Scale From Zero  is not supported.  So not supporting or only supporting `Scale From 1` will only add to costs.
Given the costs savings involved and the usage, I believe we should support the feature here although its not a commonly asked one. 

> @timebertt proposed to rather not expose this `expectedNodeAttributes` field in the `Shoot` API but only in the `extensions.gardener.cloud/v1alpha1.Worker` resource. This way, only scale-from-zero will be supported. In order to support the ScaleMP scenario we could extend the `providerConfig` of the SuSE CHost extension (as initially proposed in [gardener/autoscaler#27 (comment)](https://github.com/gardener/autoscaler/issues/27#issuecomment-910258051)). If overridden node attribute configuration is provided here, the SuSE CHost extension could inject them via a mutating webhook into the `MachineClass`. The rationale behind this proposal is that "overwriting node attributes" is highly specific to the ScaleMP scenario only, right? There is no other reasonable use case, or? If so, it should not be part of the `Shoot` API, probably. Obviously, this is a bit more to implement, however, perhaps the cleaner solution.

Coming to the approach -- Just from the original intent we wanted to solve the 3 problems laid out in the original intent in #27 through a single approach and hence the idea to have them as part of shoot spec. But as owners of the  `Shoot` spec if you recommend that a better way of achieving the same would be via enhancing the `Worker` spec and for scaleMP use-case via the  `providerConfig` of the os-extension,  then I believe we should explore these and adapt the implementation.  
We can manage the additional effort and expectation with the stakeholder if the final solution is a lot cleaner. 

Hope it was of some help. 

Also while we refine this PR from the inputs in this thread, is the name `AutoscalarNodeTemplate` agreed upon or is the search still on :)

**Comment by danielfoehrKn** [comment]
> AutoscalerNodeTemplate

For me, that sounds good :)

**Comment by vlerenc** [comment]
@timebertt As far as I understand and @ashwani2k also confirmed, scale-from/to-zero is a cost saving topic for certain big players. These are the same big players that also require ScaleMP to get even more out of their already expensive machines.

@AxiomSamarth In regards to `expectedNodeAttributes`, I believe I expressed also doubts about that field name in one of our syncs, but I don't mind too much. My proposal was `capacity` in https://github.com/gardener/autoscaler/issues/27#issuecomment-910230136, but I see `nodeTemplate` above which sounds nice. So, here you have it (another opinion). ;-) However, see below...

@AxiomSamarth @rfranzke @timebertt As the capacity actually depends on the OS, I also second https://github.com/gardener/gardener/issues/4948#issuecomment-964234966 -> https://github.com/gardener/autoscaler/issues/27#issuecomment-910258051 as the more natural fit. The general scale-from/to-zero issue is solved, because we take the capacity from the cloud profile in general and the specific ScaleMP issue is solved, because the OS extension then "expands" (intercepts/overwrites) the capacity, which is what the extension actually quite literally does (poetic fit). ;-)

**Comment by timebertt** [comment]
> @timebertt As far as I understand and @ashwani2k also confirmed, scale-from/to-zero is a cost saving topic for certain big players. These are the same big players that also require ScaleMP to get even more out of their already expensive machines.

I'm still wondering whether these big players will actually scale their worker pools with these expensive machines to zero. Because I would expect that for development / evaluation use cases, where you might want to scale to zero, they surely wouldn't use these expensive machines and rather default machine types, which would already support scale-to/from-zero out of the box.

**Comment by timebertt** [comment]
/reopen
PRs are reverted with https://github.com/gardener/gardener/pull/5113

**Comment by himanshu-kun** [comment]
Hi Colleagues,
Earlier we had come to conclusion that user will be providing their desired capacity in [`image provider config`](https://github.com/gardener/gardener/blob/131fadc0875b7f35ceb7cc3b116bf1023b7304d0/pkg/apis/core/v1beta1/types_shoot.go#L1160) like [this](https://github.com/gardener/autoscaler/issues/27#issuecomment-910258051) and we'll be implementing a mutating webhook in `gardener-extension-suse-chost` to mutate the machineClass and update `nodeTemplate` field to cater`scaleMP memoryOne` useCase(where runtime capacity is different from what's mentioned in cloudProfile), which will be used by Hana.

However, after discussion with @vpnachev and @dkistner we figured that in the coming future there might be other OS which enhances resources on runtime and to handle that we would have to introduce mutating webhook in every OS extension, and also update some interfaces for webhooks in g/g. Also there is this concern as to why OS extension should deal with machineClasses ? 
A solution we concluded with would be to introduce `nodeTemplate` field in [`providerConfig`](https://github.com/gardener/gardener/blob/131fadc0875b7f35ceb7cc3b116bf1023b7304d0/pkg/apis/core/v1beta1/types_shoot.go#L1077-L1079) of the `core.gardener.cloud/v1beta1.Worker` structure. The advantages of this solution will be 
* OS extensions won't have to deal with machineClasses
* worker controller in the extensions is the one to fill nodeTemplate in machineClasses and would take a look at providerConfig at that time for any user provided values
* no extra changes required in g/g
* would be quicker to implement

I would like to hear comments from @rfranzke and @timebertt on the same , and if it is feasible to make this change.
It would be great if we could conclude with a plan before colleagues go on Christmas vacation

cc @ashwani2k @vlerenc @AxiomSamarth

**Comment by sunir1** [comment]
As discussed and reviewed with @AxiomSamarth , his suggested approach looks to be suitable to our requirement.

The needed functionality is something we asked for back in August, and and delay is blocking us from improving TCO in HANA-Cloud, where already hundreds of instances are being used on daily (>100 are with over 1TB of memory).

**Comment by himanshu-kun** [comment]
Update:
We have got private approval regarding the new approach , and will proceed working on it. Since we are planning to enable feature in AWS first , we will be working on the changes in `gardener-extension-aws` . Please refer to [this](https://github.com/gardener/gardener-extension-provider-aws/pull/461) PR for progress.
