### ISSUE TITLE
Using the `unmanaged` DNS provider does not work

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4995]
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
When creating a shoot with the `unmanaged` DNS provider (setting `.spec.dns.providers[0].type=unmanaged`) it fails with:

```
Error from server (Forbidden): error when creating "dev/local/shoot.yaml": shoots.core.gardener.cloud "my-shoot" is forbidden: 2 errors occurred:
	* given Shoot uses non-registered dns type: spec.dns.providers[0].type ("unmanaged")
	* given Shoot uses non-registered extension type: spec.dns.providers[0].type ("unmanaged")
```

**What you expected to happen**:
Shoot creation should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
Do we still need this functionality? It obviously seems to be unused. Should we consider dropping it?

cc @timuthy 

**Environment**:

- Gardener version: `master`

**Comment by timuthy** [comment]
> Do we still need this functionality? It obviously seems to be unused. Should we consider dropping it?

I was about to remove the functionality entirely from the code since this particular use case hasn't worked for ~10 months (see https://github.com/gardener/gardener/commit/322ba4a7e31783036566c8b409f97fc5a92bd744). However, `unmanaged` providers can also be used for default and internal domains and we simply don't know if this feature is used or not. At least I'm reluctant to remove this feature w/o any deprecation period and migration path. #5241 fixes the problem for now.

**Comment by rfranzke** [comment]
OK, thanks @timuthy. Shall we then close this ticket for now? It was created under the assumption that everything related to `unmanaged` providers does not work. I assume that we don't want to spend the effort of deprecating and migrating existing systems with `unmanaged` providers?

**Comment by timuthy** [comment]
I would also suggest to close this issue. We can still tackle the removal in the future if there are strong arguments to do so.

**Comment by rfranzke** [comment]
OK, then let's merge your PR and close this issue with it. Thanks!
