### ISSUE TITLE
cluster-autoscaler cannot count migrated PVs and cannot scale up on `exceed max volume count`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5064]
**How to categorize this issue?**

/area quality auto-scaling
/kind bug

**What happened**:
cluster-autoscaler cannot count migrated PVs -> cannot scale up on `exceed max volume count`. Pod(s) hangs forever in Pending state.

**What you expected to happen**:
cluster-autoscaler to properly count migrated PVs and to scale up appropriately on scheduling failures with reason `exceed max volume count`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster with K8s that does not have CSI enabled (for example AWS cluster with K8s 1.17)
   For machine type select a one that allows 25 volume attachments - for example `m5.large`
   Autoscaler should be also enabled for this cluster. An example worker spec:

   ```yaml
    workers:
      - cri:
          name: containerd
        name: worker-nq600
        machine:
          type: m5.large
          image:
            name: gardenlinux
            version: 318.8.0
        maximum: 2
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: gp2
          size: 50Gi
        zones:
          - eu-west-1c
        systemComponents:
          allow: true
   ```

   Make sure that you have a single Node. Its allocatable volume attachments should be 25.
   ```
   $ k get csinode

   spec:
     drivers:
     - allocatable:
         count: 25
       name: ebs.csi.aws.com
   ```

2. Create dummy StatefulSet and scale to 20 replicas

   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: nginx
     labels:
       app: nginx
   spec:
     ports:
     - port: 80
       name: web
     clusterIP: None
     selector:
       app: nginx
   ---
   apiVersion: apps/v1
   kind: StatefulSet
   metadata:
     name: web
   spec:
     selector:
       matchLabels:
         app: nginx # has to match .spec.template.metadata.labels
     serviceName: "nginx"
     replicas: 3 # by default is 1
     template:
       metadata:
         labels:
           app: nginx # has to match .spec.selector.matchLabels
       spec:
         terminationGracePeriodSeconds: 10
         containers:
         - name: nginx
           image: k8s.gcr.io/nginx-slim:0.8
           ports:
           - containerPort: 80
             name: web
           volumeMounts:
           - name: www
             mountPath: /usr/share/nginx/html
     volumeClaimTemplates:
     - metadata:
         name: www
       spec:
         accessModes: [ "ReadWriteOnce" ]
         resources:
           requests:
             storage: 1Gi
   ```

   ```
   $ k scale sts web --replicas=20
   ```

This will create 20 Pods and PVs (note that PV are created with the internal volume driver).

3. Update to K8s version with CSI enabled (for example AWS cluster with K8s 1.18)

   After completing this spec you should have 20 "migrated" PVs (PVs that are provisioned with the in-tree volume plugin).

4. Scale the StatefulSet to 26 replicas
   ```
   $ k scale sts web --replicas=26
   ```

4. Make sure that the 26th replica (Pod `web-25`) fails to be scheduled (as expected) but **cluster-autoscaler never triggers a scale up**

   ```
   Events:
   Type     Reason            Age   From               Message
   ----     ------            ----  ----               -------
   Warning  FailedScheduling  54m   default-scheduler  0/1 nodes are available: 1 node(s) exceed max volume count.
   Warning  FailedScheduling  54m   default-scheduler  0/1 nodes are available: 1 node(s) exceed max volume count.
   ```

   (If you perform this steps to reproduce on a cluster without any migrated PVs, the cluster-autorscaler then is able to trigger the expected scale up)

   Logs of cluster-autoscaler:
   ```
   I1124 14:44:02.817569       1 csi.go:178] Persistent volume had no name for claim default/www-web-25
   I1124 14:44:02.817584       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817592       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817599       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817606       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817612       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817615       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817629       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817634       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817641       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817644       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817649       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817652       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817659       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817662       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817668       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817671       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817678       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817685       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817691       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817694       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817700       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817705       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817713       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817721       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817729       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817732       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817738       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817741       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817751       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817759       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817766       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817769       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817774       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817778       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817787       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817791       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817797       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817800       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817806       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
   I1124 14:44:02.817809       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
   I1124 14:44:02.817818       1 scheduler_binder.go:241] FindPodVolumes for pod "default/web-25", node "ip-10-250-28-64.eu-west-1.compute.internal"
   I1124 14:44:02.817842       1 scheduler_binder.go:819] No matching volumes for Pod "default/web-25", PVC "default/www-web-25" on node "ip-10-250-28-64.eu-west-1.compute.internal"
   I1124 14:44:02.817852       1 scheduler_binder.go:883] Provisioning for 1 claims of pod "default/web-25" that has no matching volumes on node "ip-10-250-28-64.eu-west-1.compute.internal" ...
   I1124 14:44:02.817868       1 filter_out_schedulable.go:118] Pod default.web-25 marked as unschedulable can be scheduled on node ip-10-250-28-64.eu-west-1.compute.internal (based on hinting). Ignoring in scale up.
   I1124 14:44:02.817878       1 filter_out_schedulable.go:132] Filtered out 1 pods using hints
   I1124 14:44:02.817884       1 filter_out_schedulable.go:170] 0 pods were kept as unschedulable based on caching
   I1124 14:44:02.817888       1 filter_out_schedulable.go:171] 1 pods marked as unschedulable can be scheduled.
   I1124 14:44:02.817894       1 filter_out_schedulable.go:79] Schedulable pods present
   I1124 14:44:02.817913       1 static_autoscaler.go:402] No unschedulable pods
   I1124 14:44:02.817929       1 static_autoscaler.go:449] Calculating unneeded nodes
   ```

**Anything else we need to know?**:
From what I managed to track in the autoscaler repository, the autoscaler creates a new scheduler framework and "simulates" whether the Pod is really unschedulable (most probably using default scheduling config). This was something new for me.

```
I1124 14:44:02.817868       1 filter_out_schedulable.go:118] Pod default.web-25 marked as unschedulable can be scheduled on node ip-10-250-28-64.eu-west-1.compute.internal (based on hinting). Ignoring in scale up.
```
The above log entry makes it clear that the Pod is unschedulable according to the kube-scheduler (exceed max volume count) but the same Pod is schedulable according to the cluster-autoscaler. The differences comes from the `NodeVolumeLimits` filter in the scheduler - kube-scheduler obviously has the required CS migration feature gates set and can correctly count migrated volumes. cluster-autoscaler current does not have any such config, hence it cannot count migrated volumes:
```
I1124 14:44:02.817806       1 csi.go:205] CSI Migration of plugin kubernetes.io/aws-ebs is not enabled
I1124 14:44:02.817809       1 csi.go:158] Could not find a CSI driver name or volume handle, not counting volume
```

I believe this is exactly the issue we hit when we enabled SeedKubeScheduler feature gate on our landscapes.

**Environment**:

- Gardener version: v1.36.0
- Kubernetes version (use `kubectl version`): v1.17 and v1.18 (see steps to reproduce)
- Cloud provider or hardware configuration:
- Others:

**Comment by AxiomSamarth** [comment]
@ialidzhikov I think there is a similar issue on upstream autoscaler. 

- [Link to issue](https://github.com/kubernetes/autoscaler/issues/2806)
- [Also this](https://github.com/kubernetes/kubernetes/issues/93186)

I will some time around this to understand the reason and to find a solution if any tomorrow. In the meantime, these links can be of some help to you.

**Comment by ialidzhikov** [comment]
> @ialidzhikov I think there is a similar issue on upstream autoscaler.
> 
> * [Link to issue](https://github.com/kubernetes/autoscaler/issues/2806)
> * [Also this](https://github.com/kubernetes/kubernetes/issues/93186)
> 
> I will some time around this to understand the reason and to find a solution if any tomorrow. In the meantime, these links can be of some help to you.

I am not super convinced that these are the same issue. We are not applying any custom max volume limit or any custom scheduling config (is this even possible/supported?). I think the default volume limit and the default scheduling config are used.

PS. If it is really not possible to apply a custom scheduling config to the cluster-autoscaler, then this sounds like yet another blocker issue for #4741.

**Comment by AxiomSamarth** [comment]
Yes, AFAIK, custom scheduling configurations are not possible in CA. It runs the default ones. Also, it does not interact with the actual scheduler binary running in the cluster, instead imports some of the scheduling codes and runs it within CA simply to simulate pod schedulability. So, there are high chances that the behaviour of CA & Scheduler may vary.

**Comment by himanshu-kun** [comment]
> I think the default volume limit and the default scheduling config are used.

@ialidzhikov  I think the default scheduling config is not used because
* gardener CA is inline with upstream CA v1.20 which uses scheduler v1.20
* the `CSIMigrationAWS` feature gate is not enabled by defualt in scheduler v1.20 as per [this doc](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=1.14-,CSIMigrationAWS,1.17,-CSIMigrationAzureDisk) but you have enabled it.
 
Because of this the CA scheduling algo hits [this code](https://github.com/kubernetes/kubernetes/blob/39c76ba2edeadb84a115cc3fbd9204a2177f1c28/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L194-L198).

Doesn't look like we can enable/disable feature gates in CA scheduler algo as per [this](https://github.com/kubernetes/autoscaler/issues/2806#issuecomment-611058840) comment.

**Comment by AxiomSamarth** [comment]
Any fresh inferences or conclusions arrived at wrt this issue?

**Comment by vlerenc** [comment]
> If it is really not possible to apply a custom scheduling config to the cluster-autoscaler, then this sounds like yet another blocker issue for #4741.

@ialidzhikov I wouldn't say blocker, but it's generally bad. Reasoning:
- When we speak about #1455 (I would probably rather drop the current custom scheduler code behind #4617 and map #4741 to #1455 if we anyway offer that for end users), we will offer it as alpha feature anyway for certain "big players" and they can test their scenarios specifically before going (or not going) for this feature.
- I wholeheartedly agree that the primitive way how CA deals with the entire subject matter (own simulation of scheduler logic that always trails behind instead of finding some common ground/making the core kube-scheduler scheduling logic  reusable and using it in CA) is very bad, but we actually "only" want to switch to bin-packing in #1455 and that isn't making things worse, I believe (the "bug" is, but not the difference in this single scheduling "flag"), because:
  - If the pod can be scheduled to a node that is highly utilised but still has capacity, CA is not invoked and everything runs smoothly.
  - If the pod cannot be scheduled at all, the CA **should** see that error and the simulation **should** find that a new node is required and create it so that the pod can be scheduled. But as you wrote, it doesn't and that seems to be a "bug" rather than the problem of the improper simulation.

All in all, I would be even OK to go on with #1455 and put a fat disclaimer to that alpha feature: Doesn't work properly on clusters with migrated volumes (this issue) and may cause kubelet issues (cgroup setup issue).

But, I would rather want to find a way to resolve this and the cgroups issue first, of course.

So, that "bug" and our seeds are certainly blockers for #4741 (not necessarily for #1455), but the poor simulation in general (without that "bug") is probably not a blocker, but as bad as it was also before (years ago I was shocked that CA has implemented a simulation of their own - it was always awful that the community went down this troubling path, but probably scheduling was much simpler back then when the first version of CA was short-sightedly released).

**Comment by vlerenc** [comment]
@himanshu-kun @AxiomSamarth How can we help to make this "bug" disappear and go on with the bin-packing feature that will probably safe all users tons of money and help reduce the ecological footprint the default spread scheduling has?

Yes, I got that it's not really a proper bug (from @himanshu-kun analysis in https://github.com/gardener/gardener/issues/5064#issuecomment-979424468), because it's primarily a "misalignment" between what the scheduler sees/does (as @ialidzhikov reported) and the CA that doesn't have these insights, but we have a fork. Can we make a tweak (we already have a bunch of patches that we have to back-port when we upgrade to new upstream versions) in the case of Gardener that works for all our clusters (old and new versions)?

**Comment by ialidzhikov** [comment]
- For this particular issue I created https://github.com/kubernetes/autoscaler/issues/4517. The issue was discussed yesterday in the SIG Autoscaling meeting. I will give a try to follow-up on this issue and check what needs to be done.
- While we talk about volume limits and scaling on volume limits, there is also https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1139 - volume limits maintained by aws-ebs-csi-driver for a lot of nitro instance types is wrong.
- For the concern raised in https://github.com/gardener/gardener/issues/5064#issuecomment-978062759 (the cluster-autoscaler scheduling config vs the kube-scheduler scheduling config) I created https://github.com/kubernetes/autoscaler/issues/4518. The reply from a cluster-autoscaler maintainer was that the cluster-autoscaler runs only kube-scheduler Filters. In theory, if we only have custom config for the Scoring, and use the default Filters, this should not affect us. But I haven't played with it yet.

**Comment by ialidzhikov** [comment]
Wrt to the 1st issue from https://github.com/gardener/gardener/issues/5064#issuecomment-993657306, folks from the upstream community asked me to try out with latest cluster-autoscaler (that vendors K8s v1.23.0) because some of the CSI feature gates are enabled by default with K8s v1.23.0. How I am supposed to do this when our forked cluster-autoscaler vendors K8s v1.18? @AxiomSamarth @himanshu-kun do plan anytime soon to update the cluster-autoscaler fork (https://github.com/gardener/autoscaler/issues/91, https://github.com/gardener/autoscaler/issues/89)?

**Comment by AxiomSamarth** [comment]
Could you try these steps out locally on our Gardener fork (`machine-controller-manager-provider` branch) and rebase with latest upstream `master`? Steps are [here](https://github.com/gardener/autoscaler/blob/935bf3362d640b3b186748855c078b52db4c01f3/cluster-autoscaler/FAQ.md#how-do-i-get-the-latest-changes-from-master-onto-the-fork-of-autoscaler-on-gardener) & these steps are yet to be merged in the FAQ of the repo via [this PR](https://github.com/gardener/autoscaler/pull/102)

Currently, we are not planning on upgrading it to latest because there could be multiple version jump. This will have to be done as a careful exercise as the CA rebasing is a bit tricky.

**Comment by ialidzhikov** [comment]
> Could you try these steps out locally on our Gardener fork (`machine-controller-manager-provider` branch) and rebase with latest upstream `master`? Steps are [here](https://github.com/gardener/autoscaler/blob/935bf3362d640b3b186748855c078b52db4c01f3/cluster-autoscaler/FAQ.md#how-do-i-get-the-latest-changes-from-master-onto-the-fork-of-autoscaler-on-gardener) & these steps are yet to be merged in the FAQ of the repo via [this PR](https://github.com/gardener/autoscaler/pull/102)
> 
> Currently, we are not planning on upgrading it to latest because there could be multiple version jump. This will have to be done as a careful exercise as the CA rebasing is a bit tricky.

That's **disappointing**.
1. **What is the update/sync strategy for out forked CA?** Because the current strategy from your reply seems to be "we don't want to do it right now because it is painful".
2. **What is the versioning policy and compatibility promises of our forked CA?** Why we don't maintain a version for each and every K8s release? The upstream CA does this (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases). Why our forked CA does not follow the same approach?
With this issue we see that we depend actually on the K8s version that is vendored by CA because of the kube-scheduler feature gates that have different values for each and every release. As a "happy" consumer of our forked CA **I would like to use a concrete CA version per K8s version (for example CA version v1.22 only for K8s 1.22)**.
I don't see any continuous effort invested in this fork wrt to updating it and rebasing it to the upstream. Obviously it is easy to fork and "make the things work" but do we think in longterm what is impact of having such fork and maintaining it?


And @vlerenc above suggesting for yet another hack in our a fork:
> Can we make a tweak (we already have a bunch of patches that we have to back-port when we upgrade to new upstream versions) in the case of Gardener that works for all our clusters (old and new versions)?

Sorry, that's too much and this is not how I imagine the things to work. Your approach seems to be "fork the thing", "hack it in ugly way if needed" and "don't invest any effort about rebasing/syncing the fork". Ideally we should be investing into getting rid of this fork..

> Currently, we are not planning on upgrading it to latest because there could be multiple version jump. 

Can you explain me what is the plan forward with this CA fork?

**Comment by AxiomSamarth** [comment]
>What is the update/sync strategy for out forked CA? Because the current strategy from your reply seems to be "we don't want to do it right now because it is painful".

It is painful, I agree. But, I beg to differ with you with respect to why we do not want to do it right now. It is not because it is painful, but because there is one important release around **scale to zero** which is awaited immediately. When we started working on CA a couple of months back and when we did, the first exercise we did was to rebase with the upstream to a version (or to a commit-hash to be more precise) where things weren't breaking [see here](https://github.com/gardener/autoscaler/commit/4ab68fb75f50dc46217924d20d75ceaf94db3f99) and before this, it was done in December 2020 by colleagues before [see here](https://github.com/gardener/autoscaler/commit/54adeac45e5d7d8289d29879486a14482979fa5d). So, there is indeed a debt.

>Can you explain me what is the plan forward with this CA fork?

- _**Current plan would be to cut a release with scale to zero feature & then rebase the fork with latest upstream (version by version)**_.
- We have a process already to keep the fork up to date which is not documented yet. We plan to pick it up as next step.
- Also we shall work on introducing a release matrix as you suggested (just like it is in upstream). Thank you for this!

**Comment by vlerenc** [comment]
> why we do not want to do it right now

Sure @AxiomSamarth, the general statement/recommendation always is to finish topics before picking up new ones. So, let's get scale-to/from-zero done first before tackling something new.

> Your approach seems to be "fork the thing", "hack it in ugly way if needed" and "don't invest any effort about rebasing/syncing the fork". Ideally we should be investing into getting rid of this fork..

@ialidzhikov Please don't rush with your statements. Often people have reasons.

**Comment by ialidzhikov** [comment]
> * _**Current plan would be to cut a release with scale to zero feature & then rebase the fork with latest upstream (version by version)**_.

I created the following issue (https://github.com/gardener/autoscaler/issues/107) with my expectations/proposal.

**Comment by ialidzhikov** [comment]
https://github.com/kubernetes/autoscaler/pull/4539 was merged, looking forward to gardener/autoscaler#107.

**Comment by ialidzhikov** [comment]
I now verified once again (this time with the above-linked changes in the provider extensions and the new cluster-autoscaler images) that this issue gets resolved (scale-up happens when the volume limit is reached for the Node).

**Comment by ialidzhikov** [comment]
We can close this issue now, all above-linked PRs are merged.

/close
