### ISSUE TITLE
`keep-after-project-deletion` annotation is wrongly added to the Project Namespace

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5192]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
`namespace.gardener.cloud/keep-after-project-deletion: "true"` is wrongly added to the Project namespace on Project creation that requests a new Namespace.

**What you expected to happen**:
`namespace.gardener.cloud/keep-after-project-deletion: "true"` to be not added to the Project Namespace.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Project that requests a new Namespace (make sure that the project `garden-foo` does not exist)

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: foo
spec:
  owner:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  members:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: alice.doe@example.com
    role: admin
  namespace: garden-foo
```

2. Make sure that the `namespace.gardener.cloud/keep-after-project-deletion: "true"` annotation is wrongly added to the newly created Namespace.

```
$ k get ns garden-foo -o jsonpath="{.metadata.annotations}"
{"namespace.gardener.cloud/keep-after-project-deletion":"true","namespace.gardener.cloud/project":"2be8076c-68d0-4a83-a1aa-d414a83168b8"}
```

3. Make sure the Project deletion does not delete the namespace and it "leaks"

```
$ ./hack/usage/delete project foo

$ k get project foo
Error from server (NotFound): projects.core.gardener.cloud "foo" not found

$ k get ns garden-foo
NAME         STATUS   AGE
garden-foo   Active   9m14s
```

4. Create Project `foo` once again

5. Make sure that it is Failed state because of the previously "leaked" Namespace (that now does not have the project labels):

```
$ k describe project foo

Events:
  Type     Reason                    Age                From                         Message
  ----     ------                    ----               ----                         -------
  Warning  NamespaceReconcileFailed  3s (x13 over 24s)  gardener-controller-manager  namespace cannot be used as it needs the project labels map[string]string{"gardener.cloud/role":"project", "project.gardener.cloud/name":"foo"}
```

**Anything else we need to know?**:
I was not able to reproduce the issue against a Gardener landscape. But it is always reproducible locally.

**Environment**:

- Gardener version: v1.38.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
The issue seems to be same as 2nd point mention in this comment https://github.com/gardener/gardener/issues/5295#issuecomment-1017415479.

**Comment by BeckerMax** [comment]
Looking into this with @acumino we investigated this bug. It looks like parallel reconcilations can cause a race condition which leads to the annotation being wrongfully added to the namespace. Timeline of the race condition:

- project gets created and AddEvent is triggered, reconcilation starts 
- The project is patched multiple times in the reconcilation flow. First to add [finalizers](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L46) then to update the [status](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L62). Each of those patches trigger an update event which causes another reconcilation.
- The second reconcilation (triggered by adding the finalizer) has a newObject that contains the added finalizer and an `ObservedGeneration` of `0`. 
- The second reconcilation will do a GET request [here](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control.go#L99) now at this point in time there can be two situations:
  - The first reconcilation already patched the `ObservedGeneration` [here](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L146) and therefore the second reconcilation will update its project object to also have `ObservedGeneration` set to `1`.
  - The first reconcilation did not yet patch the `ObservedGeneration` and the second reconcilation will continue its run with `ObservedGeneration` set to `0`. Then it will reach this [check](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L208)  `if project.Status.ObservedGeneration == 0` and will add the annotation wrongfully.

**Comment by rfranzke** [comment]
@BeckerMax @acumino Thanks a lot for this analysis! When I read it for the first time, I had the feeling you assumed that there can be two parallel reconciliations for the same `Project`. However, the queue ensures that there is only at most one reconciliation for the same object at any given point in time. Anyways, it doesn't matter much.

In short, I think the problem is: Due to the fact that we set `.status.observedGeneration=.metadata.generation` only at the [very end](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L146) of the reconciliation - more particularly only after we have [reconciled the `Namespace`](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L71-L77) - any error occurring [in this section](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L78-L142) will lead to the problem reported in this issue (if it's the initial `Project` creation since only then `.status.observedGeneration=0`).

This makes me wondering why we only update `.status.observedGeneration` so late. Shouldn't/can't we do this very early in the reconciliation, e.g. somewhere [here](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L62-L64)? This is at least what we do in other controllers (e.g., in gardenlet's `Shoot` controller).

**Comment by acumino** [comment]
I investigated more in this issue. Here are the findings:
> However, the queue ensures that there is only at most one reconciliation for the same object at any given point in time. Anyways, it doesn't matter much.

Yes, That's true. But,
- The project is patched multiple times in the reconciliation flow. First to add [finalizers](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L46) then to update the [status](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L62). Each of those patches triggers an `update event` which causes another reconciliation.
- These update events add the `project` in the [queue](https://github.com/gardener/gardener/blob/179cf336ce5cfaa8dc3b0ef08ea1aba87ee0765c/pkg/controllermanager/controller/project/project_control.go#L41).
- According to the `queue` add logic, it always adds `object` to the `dirty set` and will add to the queue if `object` is not in the `processing set`. Please see [here.](https://github.com/kubernetes/client-go/blob/7f0455096073f978a0f4b832c7ab10a0ed5a66b9/util/workqueue/queue.go#L119-L139)
- So now we have a `project with old status` which is in the `dirty set` and also in the `processing set`.
- When the `project` is removed from the `processing set` then the `project with old status` which is in the `dirty set` will be added to the queue. Please see [here](https://github.com/kubernetes/client-go/blob/7f0455096073f978a0f4b832c7ab10a0ed5a66b9/util/workqueue/queue.go#L71-L85). 
- This is the reason for the above issue.

Please point out if I have taken something wrong into consideration.

Here is one such example, we can see `foo` is in both `dirty set` and `processing set`.

<img width="1792" alt="Screenshot 2022-01-29 at 5 48 35 PM" src="https://user-images.githubusercontent.com/28653770/151681587-c4719a76-4008-4177-bc08-0a13feb31cc5.png">

**Comment by acumino** [comment]
Looking into this with @rfranzke and @BeckerMax we had the following findings - 

Scenario 1: When the first reconciliation is able to complete successfully but the second reconciliation reads the object from the non-updated cache.
- As described in https://github.com/gardener/gardener/issues/5192#issuecomment-1025011615 the cache issue can occur even though we are fetching the object in the next reconciliation [here](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L53-L58).
- @rfranzke pointed out that reconciliation [here](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control.go#L115) should use `gardenClient.APIReader()` instead of `gardenClient.Client()` which was changed in #4111.

Scenario 2: The first reconciliation fails for some reason after the [namespace creation](https://github.com/gardener/gardener/blob/818052a3ff3b741d5fe223517d8720fcdd7e9bc4/pkg/controllermanager/controller/project/project_control_reconcile.go#L71) and the `.status.observedGeneration` is not updated.
- In this case, the second reconciliation will always add `keep-after-project-deletion`  annotation wrongly to the Project Namespace.

- For this case, there were two decisions: 
  - Remove dependency of  adding annotation `keep-after-project-deletion annotation` based on `.status.observedGeneration`.
  - Introduce a new annotation that signifies that `namespace` was created by the `gardener`.
