### ISSUE TITLE
Harmonize Worker Names

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#52]
By @rfranzke: @AndreasBurger propsed to harmonize the worker names as follows:

`shoot-${shoot_name}-${worker_name}-${worker_az}-${worker_count}`

The length of `${shoot_name}` is restricted by 10 characters.
The length of `${worker_name}` is restricted by 15 characters.
The length of `${worker_az}` is restricted by ~ 25 characters.
The length of `${worker_count}` is restricted by 4 characters.

In sum, we'll get a length of maximum 63 characters (whereas the `${worker_az}` is usually much shorter).

Does that sound reasonable to everybody?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [d070668](https://github.com/d070668)**
_Tuesday Nov 28, 2017 at 15:53 GMT_

----

Sounds fine to me. For Azure, however, there is no useful availability-zone name. Therefore I'd suggest 
```
shoot-${shoot_name}-${worker_name}-${worker_count}
```
for the Azure case.

**Comment by vlerenc** [comment]
@rfranzke, @dkistner, @AndreasBurger What's the status of this ticket? Still something to do? Proposal still valid? Source is not accessible publicly. Length restriction does not apply anymore.

**Comment by rfranzke** [comment]
With the machine-controller-manager we will get harmony regarding the VM/instance names.
The scheme will look like as follows:

`shoot-<project>-<shoot-name>-<worker-name>-z<zone-nr>`, so for example `shoot-myproject-cluster1-cpu-worker-z1`. For clouds where no availability zones exist (at the moment only Azure) the zone number is simply omitted.

However, for AWS Shoots we still need to use the VM's internal DNS name for the name of the resulting nodes (because the AWS cloud provider expects it like that).

Thus, let's close the ticket.

**Comment by vlerenc** [comment]
Thanks for the update!
