### ISSUE TITLE
Drop `PodSecurityPolicy` usage / move to `PodSecurity`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5250]
**How to categorize this issue?**

/area open-source
/kind enhancement

**What would you like to be added**:
Drop usage of `PodSecurityPolicy`s and potentially move to `PodSecurity`.
Read more here: [PodSecurityPolicy Deprecation: Past, Present, and Future](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/)

Steps:
- [x] Add an option to disable the `kube-apiserver` admission plugins in the ShootSpec. > #6403 
- [x] Adapt mutating fields handled by PSPs in gardener and extensions components in the `PodSpec` so that we can drop all the gardener deployed PSPs when the user disables the `PodSecurityPolicy` admission plugin.
     - [x] #6409 
       - Release: [`v1.53.0`](https://github.com/gardener/gardener/releases/tag/v1.53.0)
     - [x] https://github.com/gardener/gardener-extension-shoot-dns-service/pull/153
       - Release:  [`v1.24.0`](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.24.0)
     - [x] https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/30
       - Release: [`0.7.0`](https://github.com/gardener/gardener-extension-shoot-networking-filter/releases/tag/v0.7.0) 
     - [x] https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/23
       - Release:  [`v0.5.0`](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/releases/tag/v0.5.0)
     - [x] https://github.com/gardener/external-dns-management/pull/273
       - Release:  [`v0.13.1`](https://github.com/gardener/external-dns-management/releases/tag/v0.13.1) 
     - [x] https://github.com/gardener/gardener-extension-networking-calico/pull/203
       - Release:  [`v1.26.0`](https://github.com/gardener/gardener-extension-networking-calico/releases/tag/v1.26.0)
     - [x] https://github.com/gardener/gardener-extension-networking-cilium/pull/120
       - Release:  [`v1.17.0`](https://github.com/gardener/gardener-extension-networking-cilium/releases/tag/v1.17.0)
     - [x] https://github.com/gardener/gardener-extension-provider-alicloud/pull/523
       - Release: [`v1.40.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.40.0) 
     - [x] https://github.com/gardener/gardener-extension-provider-aws/pull/587
       - Release: [`v1.38.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.38.0)
     - [x] https://github.com/gardener/gardener-extension-provider-azure/pull/558
       - Release: [`v1.30.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.30.0)
       - [x] https://github.com/gardener/gardener-extension-provider-azure/pull/575/commits/d5bd49de85eb9625914dd56274e3ab883aa99161
       - Release: [`v1.31.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.31.0)
     - [x] https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/232/commits/ae6915750c764c6987c23f2d018594e64f34bfb0
       - Release: [`v2.5.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.5.0) 
     - [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/482
       -  Release: [`v1.25.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.25.0) 
     - [x] https://github.com/gardener/gardener-extension-provider-openstack/pull/485
       - Release: [`v1.29.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.29.0) 
     - [x] https://github.com/gardener/gardener-extension-provider-vsphere/pull/295
       - Release: [`v0.19.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.19.0)
     - [x] https://github.com/gardener/gardener-extension-runtime-gvisor/pull/56/
       - Release:  [`v0.6.0`](https://github.com/gardener/gardener-extension-runtime-gvisor/releases/tag/v0.6.0)
- [x]  Add handling for enforcing `PodSecurityPolicy` admission plugin is disabled in the ShootSpec, if users want to upgrade their clusters to k8s `v1.25` . Add documentation to follow the migration steps mentioned [here](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/) and cleanup the PSPs deployed by them, because otherwise in `v1.25` there won't be any API serving the `PodSecurityPolicy` and therefore the resources can't be cleaned up. > https://github.com/gardener/gardener/pull/6431
- [x]  If user has set a default config for `PodSecurity` plugin in the Shoot spec for this plugin, add `kube-system` to exempted namespaces. > https://github.com/gardener/gardener/pull/6549
- [x] Add a validation to deny setting `.spec.kubernetes.allowPrivilegedContainers` for Shoot clusters with kubernetes version `>=v1.25`.With `PodSecurityPolicy` plugin not present, this field doesn't have any relevance. > https://github.com/gardener/gardener/pull/6570
- [x] Handle `pod-security.admission.config.k8s.io/v1` for clusters >= 1.25 > https://github.com/gardener/gardener/pull/6668/
- [x] Remove `PodSecurityPolicy` from [requiredAdmissionPlugins](https://github.com/gardener/gardener/blob/0b7503d366f32432a6aa0d3be6fac9eb4daabb1b/pkg/apis/core/validation/shoot.go#L757) list and add a User facing warning for considering migration in `v1.23`+ clusters. > https://github.com/gardener/gardener/pull/6700

**Why is this needed**:
`PodSecurityPolicy`s are deprecated and will be removed in v1.25. With v1.23, a new feature called `PodSecurity` was promoted to beta ([ref](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#podsecurity-graduates-to-beta)).

**Comment by shafeeqes** [comment]
I looked into this issue.I will try to summarize what I understood:

1. Pod Security Admission is controlled by labels on namespaces. eg: pod-security.kubernetes.io/`MODE`: `LEVEL`
There are 3 modes, 

- enforce : Policy violations will cause the pod to be rejected.
- audit       : Policy violations will trigger the addition of an audit annotation to the event recorded in the audit log, but are otherwise allowed.
- warn        : Policy violations will trigger a user-facing warning, but are otherwise allowed.

and 3 levels: 

- Privileged : Unrestricted policy
- Baseline : Allows the default (minimally specified) Pod configuration.
- Restricted : Heavily restricted policy.

2. It is Purely validating , So we have to take care of the current mutating  and mutating&validating fields.  Also introduce validating webhooks for the fields which are not part of the new PodSecurity , but we still want to handle. The whole mapping is given [here](https://kubernetes.io/docs/reference/access-authn-authz/psp-to-pod-security-standards/),

In short, The fields which we have to take care in our case are: 

- `.spec.allowedHostPaths`
- `.spec.supplementalGroups` 
- `.spec.fsGroup`
- `.spec.seLinux`
- `.spec.runAsUser`
- `.spec.requiredDropCapabilities`
- `.spec.seLinux`
- `.spec.runAsUser`
- `.spec.allowPrivilegeEscalation` 

 3. So the suggested migration method, is to create a new PSP without these fields, (and handling everything else by our own admission webhooks), and then give RBAC to use this PSP, and once all the pods are migrated, we have to delete the old PSP. (detailed steps are [here](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/))
 4. Then we update the namespaces with the desired levels and modes. and for new namespaces, there is default setting as well: https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller and for exemptions: https://kubernetes.io/docs/concepts/security/pod-security-admission/#exemptions
 5. So currently doing a dryrun of the baseline policy on a seed, gives these warning, which means, we have to give these namespaces privileged permissons/exempt them
 ```bash
kubectl label --dry-run=server --overwrite ns --all pod-security.kubernetes.io/enforce=baseline
namespace/default labeled
namespace/extension-dns-external-99c7f labeled
namespace/extension-networking-calico-njsht labeled
namespace/extension-os-gardenlinux-9h7lj labeled
Warning: existing pods in namespace "extension-provider-aws-4kwh2" violate the new PodSecurity enforce level "baseline:latest"
Warning: mtu-customizer-2qlwd (and 5 other pods): non-default capabilities, host namespaces
namespace/extension-provider-aws-4kwh2 labeled
Warning: existing pods in namespace "garden" violate the new PodSecurity enforce level "baseline:latest"
Warning: fluent-bit-946g8 (and 5 other pods): hostPath volumes
namespace/garden labeled
namespace/istio-ingress labeled
namespace/istio-system labeled
namespace/kube-node-lease labeled
namespace/kube-public labeled
Warning: existing pods in namespace "kube-system" violate the new PodSecurity enforce level "baseline:latest"
Warning: apiserver-proxy-jpxzz (and 5 other pods): non-default capabilities, host namespaces, hostPort
Warning: calico-kube-controllers-6f444cdf45-prhdq: privileged
Warning: calico-node-76xrz (and 11 other pods): host namespaces, hostPath volumes, hostPort, privileged
Warning: calico-typha-deploy-7c7455f5c7-lzf2k: host namespaces, hostPort
Warning: egress-filter-applier-55lwd (and 5 other pods): non-default capabilities, host namespaces
Warning: kube-proxy-worker-tj5yb-v1.23.6-2mhjp (and 5 other pods): non-default capabilities, host namespaces, hostPath volumes, hostPort, privileged
Warning: network-problem-detector-host-9bjvg (and 11 other pods): host namespaces, hostPath volumes, hostPort
Warning: network-problem-detector-pod-8w9v7 (and 5 other pods): hostPath volumes
Warning: node-problem-detector-5k44s (and 5 other pods): hostPath volumes, privileged
Warning: vpn-shoot-578d5dcd9b-kp584: non-default capabilities, privileged
namespace/kube-system labeled
Warning: existing pods in namespace "shoot--i545724dev--i545724-1" violate the new PodSecurity enforce level "baseline:latest"
Warning: etcd-events-0 (and 1 other pod): non-default capabilities
Warning: kube-apiserver-864475f96-ns8qd: hostPath volumes
Warning: loki-0 (and 1 other pod): non-default capabilities, privileged
namespace/shoot--i545724dev--i545724-1 labeled
```
6. And we have to rollout the new PSPs and webhooks as mentioned, in one release and then handle the logic after no pods are using the old ones. And we have to do this for only for clusters >= v1.22

**Comment by shafeeqes** [comment]
Summarizing the meeting on "Migration to PodSecurity" on 12/07/22,
The next steps on this issue would be:

1. - For clusters with k8s `v1.23+`,  Adapt components to use `gardener.privileged` PSP instead of dedicated PSPs. 
2. Adapt extensions as well to use `gardener.privileged` PSP For clusters with k8s `v1.23+`
3. Add an option to disable the `kube-apiserver` admission plugins in the ShootSpec. 
4. Add handling for enforcing `PodSecurityPolicy` admission plugin is disabled in the ShootSpec, if users want to upgrade their clusters to k8s `v1.25` . Add documentation to follow the migration steps mentioned [here](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/) and cleanup the PSPs deployed by them, because otherwise in `v1.25` there won't be any API serving the `PodSecurityPolicy` and therefore the resources can't be cleaned up.
5. If `PodSecurityPolicy` plugin is disabled in ShootSpec, clean up `gardener.privileged` PSP as well.
6. For new clusters starting from v1.25, if `spec.kubernetes.allowPrivilegedContainers` is set to false in shoot yaml, we apply the restricted level for all the namespaces by default.
 If `spec.kubernetes.allowPrivilegedContainers` is set to true, then all the namespaces would have privileged level by default (currently if this field is set to true, `gardener.privileged` psp is used which have all the permissions).
 Resources deployed by gardener will be exempted in all cases.

Update: The progress is now tracked in the issue description itself and has modified steps.

**Comment by rfranzke** [comment]
With @ary1992 we looked the description above and were a bit confused about the following points:

1. The step
   >  Disable `PodSecurityPolicy` admission controller for these clusters after migration.

   is mentioned before the step
   > For safe migration of shoot clusters for end users, we will introduce a field [...]

   However, it should be connected with each other, right? Only when the end-user confirms that the PSP migration was done from his side (by setting this `disablePSP=true`) then we should disable the `PodSecurityPolicy` admission plugin in the `kube-apiserver` and delete all `PodSecurityPolicy` API objects that we created.

2. Instead of introducing the new `disablePSP` field, can we re-use https://github.com/gardener/gardener/blob/9044fe3cd5c7c59871bc4de9aca914686f0dc4d3/pkg/apis/core/v1beta1/types_shoot.go#L636-L641 and extend it with the option to disable admission plugins? Right now, this API only allows to enable admission plugins and/or provide configuration for them, but we don't support disabling admission plugins yet. This way, it would be (a) cleaner (a field `disablePSP` is quite "ugly" in the spec) and (b) has the advantage that this feature can also be used by end-users for other use-cases.

3. Instead of doing this:
   >  The gardener managed namespaces should have privileged level by default.

   Can we simply exempt the `gardener-resource-manager` (by username, ref https://kubernetes.io/docs/concepts/security/pod-security-admission/#exemptions) instead of exemption the whole namespace? This way, end-users could still decide to make `kube-system` restricted if they prefer without breaking us.

**Comment by shafeeqes** [comment]
> 1. The step
>    > Disable `PodSecurityPolicy` admission controller for these clusters after migration.
>    
>    
>    is mentioned before the step
>    > For safe migration of shoot clusters for end users, we will introduce a field [...]
>    
>    
>    However, it should be connected with each other, right? Only when the end-user confirms that the PSP migration was done from his side (by setting this `disablePSP=true`) then we should disable the `PodSecurityPolicy` admission plugin in the `kube-apiserver` and delete all `PodSecurityPolicy` API objects that we created.

Sorry for the confusion, I just meant it as steps, that's why I said "for these clusters after migration."

> 2\. nstead of introducing the new `disablePSP` field, can we re-use https://github.com/gardener/gardener/blob/9044fe3cd5c7c59871bc4de9aca914686f0dc4d3/pkg/apis/core/v1beta1/types_shoot.go#L636-L641
>      and extend it with the option to disable admission plugins? Right now, this API only allows to enable admission plugins and/or provide configuration for them, but we don't support disabling admission plugins yet. This way, it would be (a) cleaner (a field `disablePSP` is quite "ugly" in the spec) and (b) has the advantage that this feature can also be used by end-users for other use-cases.

Good suggestion. Thanks.

How about a `Disabled` field?
```
// AdmissionPlugin contains information about a specific admission plugin and its corresponding configuration.
type AdmissionPlugin struct {
	// Name is the name of the plugin.
	Name string
	// Disabled describes whether this plugin should be disabled in the kube-apiserver
	Disabled *bool
	// Config is the configuration of the plugin.
	Config *runtime.RawExtension
}
```

> 3\. Instead of doing this:
>     > The gardener managed namespaces should have privileged level by default.
>     
>     
>     Can we simply exempt the `gardener-resource-manager` (by username, ref https://kubernetes.io/docs/concepts/security/pod-security-admission/#exemptions) instead of exemption the whole namespace? This way, end-users could still decide to make `kube-system` restricted if they prefer without breaking us.

Sure.

Will update the issue comment soon.

**Comment by shafeeqes** [comment]
> * Instead of introducing the new `disablePSP` field, can we re-use https://github.com/gardener/gardener/blob/9044fe3cd5c7c59871bc4de9aca914686f0dc4d3/pkg/apis/core/v1beta1/types_shoot.go#L636-L641
>    and extend it with the option to disable admission plugins? Right now, this API only allows to enable admission plugins and/or provide configuration for them, but we don't support disabling admission plugins yet. This way, it would be (a) cleaner (a field `disablePSP` is quite "ugly" in the spec) and (b) has the advantage that this feature can also be used by end-users for other use-cases.
> *

How about a `Disabled` field?
```
// AdmissionPlugin contains information about a specific admission plugin and its corresponding configuration.
type AdmissionPlugin struct {
	// Name is the name of the plugin.
	Name string
	// Disabled describes whether this plugin should be disabled in the kube-apiserver
	Disabled *bool
	// Config is the configuration of the plugin.
	Config *runtime.RawExtension
}
```

**Comment by rfranzke** [comment]
Thanks!

> How about a `Disabled` field?

Sounds reasonable, I think we already have this for globally enabled extensions as well, so it "fits": https://github.com/gardener/gardener/blob/51c46e2c89ae65bdf6f56c95f271d05faca0b6ed/pkg/apis/core/v1beta1/types_shoot.go#L434-L436

**Comment by shafeeqes** [comment]
/close
All tasks are completed.
