### ISSUE TITLE
Shoot creation fails with `no matches for kind "Deployment" in version "apps/v1"`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5285]
**How to categorize this issue?**

/area ops-productivity quality
/kind bug
/priority 2

**What happened**:
After the rollout of v1.38 we regularly see on a daily basis Shoot creation/deletion errors that fail with:
```
[task \"Deploying managed resources for system components and optional addons\" failed: retry failed with context deadline exceeded, last error: error rendering \"shoot-core\" chart: no matches for kind \"Node\" in version \"v1\" task \"Deploying CoreDNS system component\" failed: retry failed with context deadline exceeded, last error: no matches for kind \"Deployment\" in version \"apps/v1\"]
```

```
{"log":"{\"flow\":\"Shoot cluster reconciliation\",\"level\":\"info\",\"msg\":\"Succeeded\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"task\":\"Waiting until operating system configurations for worker nodes have been reconciled\",\"ts\":\"2022-01-18T06:09:08.604Z\"}\n"}	
{"log":"{\"level\":\"error\",\"msg\":\"Could not initialize Shoot client for garbage collection of shoot garden-foo/bar: error creating new ClientSet for key \"garden-foo/bar\": Secret \"gardener-internal\" not found\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:09:33.006Z\"}\n"}	
{"log":"{\"level\":\"error\",\"msg\":\"Could not initialize Shoot client for constraints check: error creating new ClientSet for key \"garden-foo/bar\": Secret \"gardener-internal\" not found\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:09:33.006Z\"}\n"}	
{"log":"{\"level\":\"error\",\"msg\":\"Could not initialize Shoot client for health check: error creating new ClientSet for key \"garden-foo/bar\": Secret \"gardener-internal\" not found\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:09:33.006Z\"}\n"}	

{"log":"{\"level\":\"error\",\"msg\":\"Error during shoot garbage collection: no matches for kind \"Pod\" in version \"v1\"\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:10:33.295Z\"}\n"}	
{"log":"{\"error\":\"observed generation outdated (0/1)\",\"level\":\"error\",\"msg\":\"Worker shoot--foo--bar/bar did not get ready yet\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:10:36.685Z\"}\n"}	
{"log":"{\"error\":\"retry failed with context deadline exceeded, last error: error rendering \"shoot-core\" chart: no matches for kind \"Node\" in version \"v1\"\",\"flow\":\"Shoot cluster reconciliation\",\"level\":\"error\",\"msg\":\"Error\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"task\":\"Deploying managed resources for system components and optional addons\",\"ts\":\"2022-01-18T06:10:41.549Z\"}\n"}	
{"log":"{\"error\":\"retry failed with context deadline exceeded, last error: no matches for kind \"Deployment\" in version \"apps/v1\"\",\"flow\":\"Shoot cluster reconciliation\",\"level\":\"error\",\"msg\":\"Error\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"task\":\"Deploying CoreDNS system component\",\"ts\":\"2022-01-18T06:10:41.549Z\"}\n"}	

{"log":"{\"flow\":\"Shoot cluster reconciliation\",\"level\":\"info\",\"msg\":\"Succeeded\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"task\":\"Waiting until shoot worker nodes have been reconciled\",\"ts\":\"2022-01-18T06:12:16.701Z\"}\n"}	
{"log":"{\"flow\":\"Shoot cluster reconciliation\",\"level\":\"info\",\"msg\":\"Finished\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:12:16.701Z\"}\n"}	
{"log":"{\"level\":\"error\",\"msg\":\"Failed to reconcile Shoot cluster \"bar\": flow \"Shoot cluster reconciliation\" encountered task errors: [task \"Deploying managed resources for system components and optional addons\" failed: retry failed with context deadline exceeded, last error: error rendering \"shoot-core\" chart: no matches for kind \"Node\" in version \"v1\" task \"Deploying CoreDNS system component\" failed: retry failed with context deadline exceeded, last error: no matches for kind \"Deployment\" in version \"apps/v1\"]\",\"operation\":\"reconcile\",\"shoot\":\"garden-foo/bar\",\"ts\":\"2022-01-18T06:12:16.740Z\"}\n"}
```

**What you expected to happen**:
Shoot creation/deletion to succeed as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Not clear for now.

**Anything else we need to know?**:
It seems to be possible to mitigate this issue by restarting gardenlet Pod.

**Environment**:

- Gardener version: v1.38.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
cc @timebertt - Did we change anything related to the REST mapper? 👀

**Comment by timuthy** [comment]
We also see messages for other kinds, so it leads more and more to REST mapper or discovery. 
```
task "Cleaning up webhooks" failed: 2 errors occurred:
	* no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"
	* no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"
```

**Comment by rfranzke** [comment]
Together with @timebertt we shortly looked into this and thought that it might be related to #5012. With this PR, the [`gardeneraccess` component](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/gardeneraccess/access.go) was introduced which first creates shoot access secrets for gardenlet and second a `ManagedResource` containing a `ClusterRoleBinding` for providing `cluster-admin` privileges to gardenlet.

Also, we saw quite some "special handling" for `Forbidden` errors in the discovery client used by the REST mapper (https://github.com/kubernetes/client-go/blob/664b1a6c8ce9c92ce65bef3f9833b402449c98d2/discovery/discovery_client.go#L158-L186). Such errors are ignored and an empty resource list is returned (https://github.com/kubernetes/client-go/blob/664b1a6c8ce9c92ce65bef3f9833b402449c98d2/discovery/discovery_client.go#L178).

We suspected that the reported issue might result out of a race condition: When gardenlet already uses the token in the shoot access secret while the `ClusterRoleBinding` for associating privileges to the token was not yet created then `Forbidden` errors should be returned by the API server.

I tried reproducing this by commenting out the creation of the `ManagedResource` and later creating the `ClusterRoleBinding` manually. However, I was not successful, i.e., I have not encountered `no match` but only `forbidden` errors.

Above theory also anyways contradicts to how we configure the custom rate limiter used for the REST mapper (https://github.com/gardener/gardener/blob/c8f7398c1a1e0223cd892a3471f91e714dbfde5f/pkg/client/kubernetes/runtime_client.go#L77-L81). Actually, it should rediscover the API each `5s` if there are `no match` errors.

The observations described in this issue by @ialidzhikov and @timuthy indicate that the observed `no match` errors persist longer than `5s`.
Especially during [shoot deletion when webhooks are cleaned up](https://github.com/gardener/gardener/issues/5285#issuecomment-1015271586), the occurrence of the suspected race condition seems to be unlikely since the `ClusterRoleBinding` should already exist before the shoot client is created, i.e., `forbidden` errors are not expected during shoot deletion.

@timuthy @ialidzhikov Have you observed such `forbidden` errors anywhere in the logs or did you only see `no match` errors?

I'm not sure how to proceed, potentially @timebertt could have a look since he has more knowledge about the REST mapping internals.

**Comment by ialidzhikov** [comment]
> @timuthy @ialidzhikov Have you observed such forbidden errors anywhere in the logs or did you only see no match errors?

Nope, I don't see forbidden errors in the gardenlet logs.

> Above theory also anyways contradicts to how we configure the custom rate limiter used for the REST mapper (https://github.com/gardener/gardener/blob/c8f7398c1a1e0223cd892a3471f91e714dbfde5f/pkg/client/kubernetes/runtime_client.go#L77-L81). Actually, it should rediscover the API each `5s` if there are `no match` errors.

That's very interesting finding actually. For 1 of the occurrences I was able to fetch the available api resources with `k api-resources` and verify that all core api resources are available. Looks like in theory this rediscovery thing should work but in practice for some reason it does not.

**Comment by timebertt** [comment]
I won't have much time left to look into this issue today because of other tasks that came up, so I will do it tomorrow, if nobody else finds time for it earlier than me.

**Comment by timebertt** [comment]
It seems, I don't have enough information/time for now to debug this issue further. 
We should take another at it, when the problem reoccurs.

**Comment by rfranzke** [comment]
I have just seen this again, however, there is not much useful in the `gardenlet` logs.
In this case, the `Shoot` got created at `2022-02-02T11:25:29Z`, an the first occurrence of the "no match" log is at `2022-02-02T11:29:32.457Z`:

```
...
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Deploying metrics-server system component","ts":"2022-02-02T11:29:10.845Z"}
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Deploying shoot network plugin","ts":"2022-02-02T11:29:10.846Z"}
{"error":"observed generation outdated (0/1)","level":"error","msg":"Network shoot--foo--bar/bar did not get ready yet","operation":"reconcile","shoot":"garden-foo/bar","ts":"2022-02-02T11:29:10.846Z"}
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Deploying vpn-shoot system component","ts":"2022-02-02T11:29:10.859Z"}
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Reconcile node-local-dns system component","ts":"2022-02-02T11:29:10.866Z"}
{"level":"info","msg":"Skipping sync of Shoot bar's Network extension state with name bar and purpose <nil>: state already up to date","ts":"2022-02-02T11:29:10.886Z"}
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Waiting until extension resources are ready","ts":"2022-02-02T11:29:15.527Z"}
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Waiting until shoot network plugin has been reconciled","ts":"2022-02-02T11:29:15.847Z"}
{"flow":"Shoot cluster reconciliation","level":"info","msg":"Succeeded","operation":"reconcile","shoot":"garden-foo/bar","task":"Configuring shoot worker pools","ts":"2022-02-02T11:29:15.969Z"}
{"level":"info","msg":"Skipping sync of Shoot bar's Worker extension state with name bar and purpose <nil>: state already up to date","ts":"2022-02-02T11:29:16.007Z"}
{"error":"observed generation outdated (0/1)","level":"error","msg":"Worker shoot--foo--bar/bar did not get ready yet","operation":"reconcile","shoot":"garden-foo/bar","ts":"2022-02-02T11:29:20.970Z"}
{"error":"observed generation outdated (0/1)","level":"error","msg":"Worker shoot--foo--bar/bar did not get ready yet","operation":"reconcile","shoot":"garden-foo/bar","ts":"2022-02-02T11:29:25.970Z"}
{"error":"observed generation outdated (0/1)","level":"error","msg":"Worker shoot--foo--bar/bar did not get ready yet","operation":"reconcile","shoot":"garden-foo/bar","ts":"2022-02-02T11:29:30.971Z"}

{"level":"error","msg":"Error during shoot garbage collection: no matches for kind \"Pod\" in version \"v1\"","shoot":"garden-foo/bar","ts":"2022-02-02T11:29:32.457Z"}

{"error":"observed generation outdated (0/1)","level":"error","msg":"Worker shoot--foo--bar/bar did not get ready yet","operation":"reconcile","shoot":"garden-foo/bar","ts":"2022-02-02T11:29:35.972Z"}

{"error":"retry failed with context deadline exceeded, last error: no matches for kind \"Deployment\" in version \"apps/v1\"","flow":"Shoot cluster reconciliation","level":"error","msg":"Error","operation":"reconcile","shoot":"garden-foo/bar","task":"Deploying CoreDNS system component","ts":"2022-02-02T11:29:40.742Z"}

{"error":"retry failed with context deadline exceeded, last error: error rendering \"shoot-core\" chart: no matches for kind \"Node\" in version \"v1\"","flow":"Shoot cluster reconciliation","level":"error","msg":"Error","operation":"reconcile","shoot":"garden-foo/bar","task":"Deploying managed resources for system components and optional addons","ts":"2022-02-02T11:29:40.742Z"}
```

**Comment by plkokanov** [comment]
Saw this issue again, this time with `Leases`:
```
task "Waiting until kube-controller-manager is active" failed: retry failed with context deadline exceeded, last error: could not check whether controller kube-controller-manager is active: no matches for kind "Lease" in version "coordination.k8s.io/v1"
```

I'll update this comment with more logs once I've gathered them.

**Comment by MartinWeindel** [comment]
~~Not clear if it is a useful information: The issue was seen on three clusters on canary all with Kubernetes v1.22.4. After some hours the issue self-resolved.~~
I think self-resolving is related to Gardenlet restart.

**Comment by BeckerMax** [comment]
synced with @rfranzke and he is going to take over for now.
/unassign

**Comment by rfranzke** [comment]
The issue seems to not be related to potential `Forbidden` errors (ref https://github.com/gardener/gardener/issues/5285#issuecomment-1015518384) given that discovering the API is allowed for all authenticated users by default.

**Comment by rfranzke** [comment]
Together with @timebertt, we were able to reproduce the problem locally with the following modifications:

```diff
diff --git a/example/provider-local/shoot.yaml b/example/provider-local/shoot.yaml
index ec7827175..520ea35b2 100644
--- a/example/provider-local/shoot.yaml
+++ b/example/provider-local/shoot.yaml
@@ -25,4 +25,6 @@ spec:
       maxSurge: 1
       maxUnavailable: 0
   kubernetes:
+    kubeAPIServer:
+      enableAnonymousAuthentication: true
     version: 1.23.1
diff --git a/pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go b/pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go
index 484f6eff3..f5c082091 100644
--- a/pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go
+++ b/pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go
@@ -70,6 +70,8 @@ type seedInfo struct {

 // CalculateClientSetHash calculates a SHA256 hash of the kubeconfig in the 'gardener' secret in the Shoot's Seed namespace.
 func (f *ShootClientSetFactory) CalculateClientSetHash(ctx context.Context, k clientmap.ClientSetKey) (string, error) {
+       return "", nil
+
        key, ok := k.(ShootClientSetKey)
        if !ok {
                return "", fmt.Errorf("unsupported ClientSetKey: expected %T got %T", ShootClientSetKey{}, k)
diff --git a/pkg/operation/operation.go b/pkg/operation/operation.go
index 2a204935c..c78a3ac9b 100644
--- a/pkg/operation/operation.go
+++ b/pkg/operation/operation.go
@@ -18,6 +18,7 @@ import (
        "context"
        "fmt"
        "strings"
+       "time"

        gardencorev1alpha1 "github.com/gardener/gardener/pkg/apis/core/v1alpha1"
        gardencorev1alpha1helper "github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper"
@@ -335,6 +336,7 @@ func (o *Operation) InitializeSeedClients(ctx context.Context) error {
 // a Kubernetes client as well as a Chart renderer for the Shoot cluster will be initialized and attached to
 // the already existing Operation object.
 func (o *Operation) InitializeShootClients(ctx context.Context) error {
+       time.Sleep(10 * time.Second)
        return o.initShootClients(ctx, false)
 }
```

Additionally, while creating the `Shoot` (with enabled anonymous authentication) we had to scale down `gardener-resource-manager` to `0` replicas shortly after it got deployed, and scale it up again after ~`30s` or so. This was to prevent it from populating the token for the `gardener-internal` secret used by gardenlet for communicating with the shoot cluster. As a result, we ended up with failing reconciliations due to "no match" errors.

This is what happens:

When creating a client for the shoot, this code is executed:

https://github.com/gardener/gardener/blob/f5b355e3abb9da4ec07dd6c21fd0a342de327a74/pkg/client/kubernetes/clientmap/internal/generic_clientmap.go#L154-L164

This code is racy since both functions in the `ShootClientMap` implementation read the `gardener-internal` secret with the cached seed client: https://github.com/gardener/gardener/blob/f5b355e3abb9da4ec07dd6c21fd0a342de327a74/pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go#L71-L108

After #5012, the `gardener-internal` secret is created with an "empty" kubeconfig (no `AuthInfos` at all) and `gardener-resource-manager`'s `TokenRequestor` controller is expected to eventually populate the token. The race condition happens when `NewClientSet` returns the secret with the empty kubeconfig while `CalculateClientSetHash` returns the secret with the kubeconfig containing the populated token. In such case, the empty kubeconfig is stored in the `ClientMap` and any subsequent [`GetClient`](https://github.com/gardener/gardener/blob/f5b355e3abb9da4ec07dd6c21fd0a342de327a74/pkg/operation/operation.go#L369-L372) calls do not refresh the kubeconfig already stored in the client map (because the hash is still the same) until the token gets renewed after ~`12h` or the gardenlet is restarted (since this resets the `ClientMap`).

Note that the problem only occurs for clusters with enabled anonymous authentication. The reason is that for such clusters it is possible to access the `/version` endpoint without any authentication. However, accessing the `/api{s}` endpoints is not possible. This explains why https://github.com/gardener/gardener/blob/f5b355e3abb9da4ec07dd6c21fd0a342de327a74/pkg/client/kubernetes/client.go#L344-L346 succeeds and with it the creation of the clientset. 
As suggested in https://github.com/gardener/gardener/issues/5285#issuecomment-1015518384, there is some "strange" handling in the discovery client when `Forbidden` errors occur (https://github.com/kubernetes/client-go/blob/664b1a6c8ce9c92ce65bef3f9833b402449c98d2/discovery/discovery_client.go#L158-L186). For clusters with enabled anonymous authentication, querying the `/api{s}` endpoints leads to `403 Forbidden` errors.

For clusters without anonymous authentication the issue does not occur since accessing the `/version` endpoint is not possible, hence the creation of the clientset fails and the "broken client" is never persisted in the `ClientMap`.
