### ISSUE TITLE
Shoots registered as Seeds do not get Seed conditions updated

### ISSUE THREAD

**Issue by BeckerMax** [gardener/gardener#5295]
**How to categorize this issue?**

/kind bug

**What happened**:
Shoots registered as Seeds sometimes do not get Seed conditions updated. 
This results in the Seed resource to have a mismatch in conditions with the corresponding Shoot resource leading to Shoots falsely reporting as healthy or non-healthy. The dashboard relies on the conditions in the Shoot and therefore will display healthiness potentially wrongly.

**What you expected to happen**:
Conditions to be coherent between Seed and Shoot resource for managed Seeds

**How to reproduce it (as minimally and precisely as possible)**:
Unclear - seems like it only sometimes happens and self heals after days.

**Anything else we need to know?**:
Most likely introduced with https://github.com/gardener/gardener/pull/5013

For the scheduling decision the Seed resource is used which in our case has the bootstrap condition set correctly. Therefore, this bug is not influencing scheduling decisions.

**Comment by timebertt** [comment]
@BeckerMax and I looked into this problem and we recognized two problems in the shoot condition controller, that can lead to the described behavior under certain circumstances:
1. `filterSeedForShootConditions` doesn't evaluate to `true` for `Add` events. This is relevant for situations, where the `Seed` reflector looses the watch connection and has to do a full relist. In this case, the informer emits `Add` events for all objects in the cache and the controller would need to enqueue them again, because it might have missed relevant `Update` events. As the predicate doesn't evaluate to `true`, the condition might change during a timeframe where the watch connection is broken and has to be reestablished, the controller will not update the shoot conditions until the seed conditions change again. Note: if the shoot reflector would be similarly effected, it would also emit `Add` events, which would enqueue them. Hence, the described situation can only become a real problem if the seed informer breaks but the shoot informer doesn't.
2. If the seed condition is changed multiple times in (quick) succession, it might happen, that the shoot cache doesn't contain the status update from the first reconciliation run in the next run and hence calculate a wrong diff on the client-side (based on a stale shoot object) and hence only copy the `last{Update,Transition}Time` fields in the condition, leaving the status, reason and message untouched. This happens, if `updateShootConditions` is called with a stale `shoot` param, here: https://github.com/gardener/gardener/blob/65655ff2ebdb00f8c678b15c9f018ec2a19a137c/pkg/controllermanager/controller/shoot/shoot_conditions_control.go#L137-L141
The following snippet demonstrates the wrongly calculated diff based on a stale shoot object:

<details>
<pre>
func main() {
	condition := gardencorev1beta1.Condition{
		Type:               gardencorev1beta1.SeedBootstrapped,
		Status:             gardencorev1beta1.ConditionTrue,
		Reason:             "BootstrappingSucceeded",
		LastUpdateTime:     metav1.NewTime(time.Date(2022, 1, 1, 0, 0, 0, 0, time.Local)),
		LastTransitionTime: metav1.NewTime(time.Date(2022, 1, 1, 0, 0, 0, 0, time.Local)),
	}

	shoot := &gardencorev1beta1.Shoot{
		Status: gardencorev1beta1.ShootStatus{
			Conditions: []gardencorev1beta1.Condition{*condition.DeepCopy()},
		},
	}

	condition.LastUpdateTime = metav1.Now()
	condition.LastTransitionTime = metav1.Now()
	conditions := []gardencorev1beta1.Condition{condition}

	patch := client.StrategicMergeFrom(shoot.DeepCopy())
	shoot.Status.Conditions = conditions
	jsonBytes, _ := patch.Data(shoot)
	fmt.Println(string(jsonBytes))

   // result does only contain LastUpdateTime and TransitionTime, missing status and reason: {"status":{"$setElementOrder/conditions":[{"type":"Bootstrapped"}],"conditions":[{"lastTransitionTime":"2022-01-20T10:20:59Z","lastUpdateTime":"2022-01-20T10:20:59Z","type":"Bootstrapped"}]}}
}
</pre>
</details>

The second one is likely the problem as we saw cases where the `lastUpdateTime` and `lastTransitionTime` matched between Shoot and Seed conditions but the `status` and `reason` differed. We were able to correlate the timing with an overload situation on gardener-apiserver (high request rate, severe CPU throttling). This could explain, that the controller-manager's watch connection for shoots was either broken or lagging behind severely to cause the second problem due to a stale cache read. In addition, we saw that the Seed condition flipped in a time range of about 1-2 minutes during the overload situation of the apiserver.

The problem should be resolvable by a restart of gardener-controller-manager.

**Comment by timuthy** [comment]
Thanks for the detailed description @timebertt.

 > The problem should be resolvable by a restart of gardener-controller-manager.

Is there any further mitigation planned? How about additional periodic re-syncs (see [comment](https://github.com/gardener/gardener/pull/5013#discussion_r751971488))?

**Comment by BeckerMax** [comment]
For problem number 2. we discussed switching the update strategy from `Patch` with `strategicMergePatch` to `Update` when [updating the shoot conditions](https://github.com/gardener/gardener/blob/6159c839ded65dc64ab9bc8f742ee9117efc7642/pkg/controllermanager/controller/shoot/shoot_conditions_control.go#L140). This ensures that the shoot object in the cache is up-to-date otherwise it will be retried.
I will open a respective PR.

**Comment by timebertt** [comment]
For problem 1, I would additionally make sure that the predicates evaluate to true for add events in any case (e.g. because of restarts or reflector relists).



> How about additional periodic re-syncs (see [comment](https://github.com/gardener/gardener/pull/5013#discussion_r751971488))?

I would not add manual periodic resyncs as already discussed in the referenced PR comment. Instead we should make sure, that the predicate evaluates to true for the cache periodic resync, i.e. for update events with unchanged `resourceVersion`s (currently not the case for `filterSeedForShootConditions` and the shoot informer has no event handler for `update` registered).
That will make sure, that the controller is triggered for each periodic resync.
This resync period could then be lowered, if we want to have such fallback mechanisms more frequently.

**Comment by timebertt** [comment]
I dug a bit deeper into the cache resync topic, so here is some additional information for documentation purposes:
- cache resyncs don't involve an API call (they only process all object's in the store on the client-side and `Sync` events to the cache's internal queue, see [reflector.go](https://github.com/kubernetes/client-go/blob/a4e27104a2f8f5d3965f1520f74a190eba1ad221/tools/cache/reflector.go#L380-L386) and [delta_fifo.go](https://github.com/kubernetes/client-go/blob/a4e27104a2f8f5d3965f1520f74a190eba1ad221/tools/cache/delta_fifo.go#L643-L661))
- these `Sync` events emit `Update` events to the event handlers registered on the informers, see [shared_informer.go](https://github.com/kubernetes/client-go/blob/a4e27104a2f8f5d3965f1520f74a190eba1ad221/tools/cache/shared_informer.go#L541-L555)
- such resync `Update` events have the same `resourceVersion` on `newObj` and `oldObj`
- kubernetes controllers sometimes filter out such resync events for "owned objects" (e.g. ReplicaSets in the Deployment controller, see [deployment_controller.go](https://github.com/kubernetes/kubernetes/blob/45b6af6b71db0c5c61596add8b3f2c67dd071727/pkg/controller/deployment/deployment_controller.go#L259-L263). Interestingly, they enqueue pretty much all updates to the "controlled objects", see [deployment_controller.go](https://github.com/kubernetes/kubernetes/blob/45b6af6b71db0c5c61596add8b3f2c67dd071727/pkg/controller/deployment/deployment_controller.go#L173-L178). However, their controllers are much more lightweight than ours
- kube-controller-manager has no manual periodic sync periods like some of our controllers and instead rely on the cache's resync events
- kube-controller-manager's default cache resync periodic is `12h`, see [defaults.go](https://github.com/kubernetes/kubernetes/blob/45b6af6b71db0c5c61596add8b3f2c67dd071727/staging/src/k8s.io/controller-manager/config/v1alpha1/defaults.go#L31-L33)
- controller-runtime defaults the cache resync period to `10h`, see [cache.go](https://github.com/kubernetes-sigs/controller-runtime/blob/7ba3e559790c5e3543002a0d9670b4cef3ccf743/pkg/cache/cache.go#L133)
- the cache resync period in our controller-runtime caches is `6h`, see [runtime_client.go](https://github.com/gardener/gardener/blob/8a9c88866ec5fce59b5acf57d4227eeeb73669d7/pkg/client/kubernetes/runtime_client.go#L36)
- You cannot influence the individual informer's resync period on controller-runtime caches. The resync period is a cache-global setting and applies to all informers created by the cache.
