### ISSUE TITLE
Scrapping logs from shoot kube-system pods.

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardener#5439]
**How to categorize this issue?**

/area logging
/kind enhancement

**What would you like to be added**:
It would be good to add the logs from the shoot `kube-system` pods.
As there is already a node `systemd` scraping configuration this could be achieved easily by adding additional job in the  `promtail` [configuration](https://github.com/gardener/gardener/blob/3c6404d23e2fb583a991c0b9247a3f23c9523d93/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config.go#L107).
1. The easiest way is to use [File Target Discovery](https://grafana.com/docs/loki/latest/clients/promtail/scraping/#file-target-discovery). It is very similar to the [fluent-bit tail plugin](https://github.com/gardener/gardener/blob/3c6404d23e2fb583a991c0b9247a3f23c9523d93/charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl#L23) which we already use in the Seed logging stack. We get the same meta information, the `pod_name`, `namespace_name`, `container_name` and the `cointainer_id`. Also, we get the `nodename`. In this forked repo [branch](https://github.com/vlvasilev/gardener/tree/scrape-shoot-kube-system-logs) I have a working version that does not need any extra configuration.
Pros:
- A connection to the kube API server is not required. all of the logs in the `kube-system` are scraped and sent to Loki.
Cons:
- As we have seen a lot of the users are deploying in the `kube-system`. We don't have a convenient way to differentiate them. If start to filter those user logs with regex we have to wait for a new release each time we add a new component in the shoot system.

2. The second way is to use [Kubernetes Discovery](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#kubernetes_sd_config). Here we can get vast metadata like the annotation, the labels and etc.
Pros:
- A lot of metadata so a new release is not required whenever a new component is added.
- The user's logs are not collected.
Cons:
- A connection to the Kube API server is required, which may increase the network traffic cost.

**Why is this needed**:
To speed up issues investigation using the Grafana

**Comment by vlvasilev** [comment]
/cc @dguendisch @timebertt @rfranzke @istvanballok
I will need advice on how to proceed with this feature.

**Comment by rfranzke** [comment]
I would vote for option 2, mainly motivated by this fact you outlined:

> As we have seen a lot of the users are deploying in the `kube-system`. We don't have a convenient way to differentiate them.

As a con for option 2 you mention

> A connection to the Kube API server is required, which may increase the network traffic cost.

Do we have some numbers to compare, i.e., how "worse" is it? My gut feeling is that the network traffic costs for streaming logs for ALL pods in `kube-system` is (in sum) significantly higher given that many folks deploy workload into this namespace (which is perfectly fine).

Otherwise, the required connection to KAPI is not a problem since (a) if the `Node` cannot join the cluster then we already get the kubelet logs and no other logs are typically relevant/exist at all, and (b) if the connection to KAPI breaks then also kubelet has a problem and all this is typically not related to anything system components do.
