### ISSUE TITLE
Rework error code detection

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5444]
**How to categorize this issue?**

/area ops-productivity quality
/kind technical-debt

## Problem / Motivation

Gardener uses a set of [error codes](https://github.com/gardener/gardener/blob/d7c9001613b659ac29d5308e28eac6a172c82857/docs/usage/shoot_status.md#error-codes) to mark reconciliation problems or failed health checks as user issues in several categories (e.g. invalid provider credentials).

Currently, there is a set of regexes, that are used to detect these error codes from plain strings: https://github.com/gardener/gardener/blob/d7c9001613b659ac29d5308e28eac6a172c82857/pkg/apis/core/v1beta1/helper/errors.go#L54-L64

Gardenlet runs any errors of the shoot flow tasks against these regexes for detecting error codes https://github.com/gardener/gardener/blob/d7c9001613b659ac29d5308e28eac6a172c82857/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L630

Similarly, extensions run any errors through these regexes as well https://github.com/gardener/gardener/blob/b4175fd224983e96a31367e5aa06aae68a10c0ef/extensions/pkg/controller/status.go#L141

These error code mappings have been augmented again and again over time in order to minimize distraction by user-caused issues for operators. However, we now face problems with the general approach:

- changes in the central error code mapping in this repository lead to regression in extensions: https://github.com/gardener/gardener-extension-provider-aws/pull/481
- some problems are wrongly classified as user issues because of too generalized error code detection: https://github.com/gardener/gardener/issues/5440, https://github.com/gardener/gardener/issues/4139
- the current set of regexes is hard to maintain: unclear which error strings are required by which provider, which are still needed, etc.

## Proposal

Instead of having a centralized set of regexes to detect error codes that is used everywhere, we should map errors to error codes as close to the actual error as possible:

- extensions should maintain their own set of mappings specific to the infrastructure
- extensions should preferably use the concrete errors returned by provider SDKs and similar to map to error codes instead of blindly applying regexes to plain strings (might not be applicable where components sit in between, e.g. terraformer, machine-controller-manager)
- extensions should populate the `status.lastError.codes` list accordingly
- gardenlet should not apply the current set of regexes to all errors from shoot flow tasks
- gardenlet should only pick up the `status.lastError.codes` list from extension objects
- gardenlet should maintain an own error code mapping for flow tasks that can reveal user issues (e.g. configuration problems) and only apply this mapping to these tasks

## Steps

- [x] deprecate the current error code mapping and start phasing out their usage (#5625)
- [x] introduce new gardenlet-specific error code mapping and apply it to relevant tasks: https://github.com/gardener/gardener/pull/6677
- [x] stop applying current error code mapping in gardenlet to all shoot flow errors: https://github.com/gardener/gardener/pull/6677
- [x] apply current error code mapping only to tasks that deal with extension objects (for backwards-compatibility): https://github.com/gardener/gardener/pull/6677
- [x] introduce new provider-specific error code mappings in extensions
  - provider-alicloud: https://github.com/gardener/gardener-extension-provider-alicloud/pull/552, released with [v1.44.0](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.44.0)
  - provider-aws: https://github.com/gardener/gardener-extension-provider-aws/pull/650, released with [v1.42.0](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.42.0)
  - provider-azure: https://github.com/gardener/gardener-extension-provider-azure/pull/605, released with [v1.34.0](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.34.0)
  - provider-gcp: https://github.com/gardener/gardener-extension-provider-gcp/pull/534, released with [v1.28.0](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.28.0)
  - provider-openstack: https://github.com/gardener/gardener-extension-provider-openstack/pull/534, released with [v1.32.0](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.32.0)
  - shoot-dns-service: https://github.com/gardener/gardener-extension-shoot-dns-service/pull/190 , released with [v1.30.0](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.30.0)
- [x] drop the current error code mapping and stop applying it, after all extensions in this org have been released with provider-specific error code mappings: https://github.com/gardener/gardener/pull/7641

**Comment by timuthy** [comment]
I really like the approach 👍 

>  introduce new provider-specific error code mappings in extensions

> introduce new gardenlet-specific error code mapping and apply it to relevant tasks

Does it make sense to populate a list of well-known error codes in `gardener/gardener` which are supposed to be re-used by extensions and they only use new or provider specific codes for very specific use-cases? Otherwise we're going to have a variety of codes with the same meaning.

**Comment by timebertt** [comment]
Thanks for your feedback :)
Got your concern. Can you give an example of such a well-known error code, that would apply everywhere?

**Comment by timuthy** [comment]
My impression is that many if not all codes that we have today are very generic, match nearly all providers and cover many use-cases.
In general, I wonder why a GCP extension should for instance return `ERR_INFRA_RATE_LIMITS_EXCEEDED` while an Azure extension returns `ERR_AZURE_RATE_LIMIT_EXHAUSTED`. Only additional and very provider specific codes seem beneficial.

**Comment by timebertt** [comment]
Oh, there must be a misunderstanding.
I was not proposing to add provider-specific error codes. The error codes should stay independent from providers and should be defined centrally by gardener (as it is today).
I was proposing to maintain only a mapping of provider SDK errors, error messages regexes or similar things to these well-known error codes in our extensions. I.e., the extensions should figure out by themselves, using provider-specific knowledge, what error codes are appropriate, instead of relying on generic and centrally maintained regexes.

**Comment by vlerenc** [comment]
@timebertt That sounds like a great improvement (pushing down the matching into the component that knows best how to do that).

I am just wondering, instead of defining the errors codes all centrally in Gardener, wouldn't it be even better (next step?), if also the extensions could define, contribute, and report up "their own sets of error codes"? Much like what @timuthy was thinking at first, but with his concern mitigated. What I am trying to say:

- Even the plain error codes break the extension concept somewhat (error codes cannot be "contributed" by an extension), so they will remain centrally managed for all in Gardener itself
- Components will either "smear" their error codes into Gardener or not contribute any new error codes because it's too far away (which is what we realistically see/have today, i.e. just a few very generic error codes)
- Extensions can still agree on their set of common error codes (to mitigate @timuthy 's concern), because between Gardener and a concrete extension is the "category/group of extensions" overseen by "Gardener's SIG Extensions", e.g.:
  - IaaS extensions
  - OS extensions
  - Networking extensions
  - Container runtime extensions
  - Others such as DNS/certificate extensions

In principle, Gardener doesn't really care about errors generated by extensions, but it needs to pass them on, so that the end users understand what's going on. That, beside code maintenance, is the thing we actually want to improve (as well), right? We can define the categories in Gardener (much like the 1/2/3/4/5xx HTTP status codes), but give the extensions more control/ownership, given that they handle that wisely, e.g. we should definitely avoid too many needless differences in error codes (@timuthy 's concern) as this breaks the abstraction (homogeneous clusters), but when it comes to IaaS details, there are differences that also Gardener cannot hide and never tried to hide (instance types, network topology, IaaS resources in general), but the error messages are often too/very generic for end users, wouldn't you agree?

**Comment by timebertt** [comment]
I'm open for thinking about your proposal. 
But for the sake of progress, I would vote for focusing on the problem at hand first, which includes: removing technical debt, lowering maintenance burden, lowering potential for wrongful categorization, increasing release velocity for extensions, etc.

Once we have completed this story and moved out the mapping as such, we can still think about allowing arbitrary error codes.

> [..] the error messages are often too/very generic for end users, wouldn't you agree?

I would agree, that the error messages shown for error codes in the dashboard are too generic. However, note that error codes as such don't hide the actual error message added by gardener or extensions from the shoot status itself.
So, there are means to make these more meaningful without allowing arbitrary error codes (which would be another plain text field).

**Comment by vlerenc** [comment]
> But for the sake of progress, I would vote for focusing on the problem at hand first, which includes: removing technical debt, lowering maintenance burden, lowering potential for wrongful categorization, increasing release velocity for extensions, etc.

Sure, :+1:

> I would agree, that the error messages shown for error codes in the dashboard are too generic. However, note that error codes as such don't hide the actual error message added by gardener or extensions from the shoot status itself.
So, there are means to make these more meaningful without allowing arbitrary error codes (which would be another plain text field).

Sure, but that's not really nice and creates the same problem we have also for our end users. Imagine there would be only 100/200/300/400/500 as HTTP status codes and we would all parse the HTTP status message... ;-)

**Comment by shafeeqes** [comment]
/unassign for now
I will take a look after https://github.com/gardener/gardener/issues/5250 and https://github.com/gardener/gardener/issues/6567.
Please feel free to take over if anyone likes to work on it in the meanwhile.

**Comment by acumino** [comment]
/assign 
for gardener changes.
