### ISSUE TITLE
Request to make monitoring alert email configuration editable

### ISSUE THREAD

**Issue by qfframb** [gardener/gardener#5475]
**How to categorize this issue?**
/area Monitoring
/kind enhancement

**What would you like to be added**:
Request to make monitoring alert email configuration editable

**Why is this needed**:
Currently, the 'send_resolved' in alert email_configuration is set to default value 'false'  due to hardcoded https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/monitoring.go#L312-L318.
We hope an issue solved alert email would send out when issue solved, so request to make this configuration editable.

**Comment by timebertt** [comment]
cc @wyb1 @istvanballok

**Comment by wyb1** [comment]
Hi @qfframb 

making the email configuration editable is a reasonable request, but is not something that we would work on at this time. If you provide the change we will be happy to review it. 

I assume the problem is that alerts fire -> you look into them but they are already resolved. What I think would be more valuable is looking into which alerts get resolved quickly and change the alerting so that this doesn't happen. Sending the resolved email will only treat the symptom (not looking into an alert that probably shouldn't have fired). Let us know if this is the case and which alert/alerts are causing the problem.

As another alternative we can set the `send_resolved` value to `true`. However, this would double the volume of emails for the existing users which is why we are reluctant to do this.

**Comment by qfframb** [comment]
Hi @wyb1,

Thanks for the explanation, I will close this issue.
