### ISSUE TITLE
Nginx Ingress Controller misses projected volume

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#5530]
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
The Nginx Ingress Controller pod crash looped because it cannot connect to the Kube-Apiserver:

```
F0307 12:43:19.843203       7 main.go:299] Error while initiating a connection to the Kubernetes API server. This could mean the cluster is misconfigured (e.g. it has invalid API server certificates or Service Accounts configuration). Reason: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
Refer to the troubleshooting guide for more information: https://kubernetes.github.io/ingress-nginx/troubleshooting/
```

**What you expected to happen**:
The Nginx Ingress Controller to work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new shoot with Nginx Ingress Addon enabled. This is a race, so the issue does not happen every time.

**Anything else we need to know?**:
The Nginx Ingress Controller pod misses the required projected volume to be able to connect to the Kube-Apiserver.

- Creation timestamps:
  - Nginx Pod: creationTimestamp: `"2022-03-07T04:17:12Z"`
  - MutatingWebhookConfiguration: creationTimestamp: `"2022-03-07T04:16:44Z"`

After deleting the pod, the new Nginx Controller pod receives the necessary updates from the webhook:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/40451181/157041005-4f7e45b7-ef62-4e15-9aaa-dcd97089b66a.png">

**Environment**:

- Gardener version: `v1.41.1`

**Comment by rfranzke** [comment]
I looked at an occurrence of this and it seems to be a race condition (as expected). Here is the list of the relevant created resources and their `creationTimestamps`:

- `06:03:53Z` `MutatingWebhookConfiguration/gardener-resource-manager-shoot` --> This one contains the `projectedTokenMount` webhook with the following `namespaceSelector`:

  ```yaml
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: In
      values:
      - kube-system
      - kubernetes-dashboard
  ```
- `06:04:22Z` `Deployment/addons-nginx-ingress-controller`
- `06:04:22Z` `ReplicaSet/addons-nginx-ingress-controller-c85c55b6b`
- `06:04:22Z` `ServiceAccount/addons-nginx-ingress`
- `06:04:23Z` `Pod/addons-nginx-ingress-controller-c85c55b6b-g8k9r` --> This one does not have any volumes at all, i.e., the `projectedTokenMount` webhook did not act.

The logs of the three `gardener-resource-manager` instances contain:

```
2022-03-10 06:04:10 {"log":"Registering webhook","path":"/webhooks/mount-projected-service-account-token","severity":"INFO","source":"controller-runtime.webhook"}
2022-03-10 06:04:04 {"log":"Registering webhook","path":"/webhooks/mount-projected-service-account-token","severity":"INFO","source":"controller-runtime.webhook"}
2022-03-10 06:03:53 {"log":"Registering webhook","path":"/webhooks/mount-projected-service-account-token","severity":"INFO","source":"controller-runtime.webhook"}
```

Hence, at the time of the `Pod` creation the webhook was registered in the system and all instances were available. However, I cannot find any log message for the created pod in the `projectedTokenMount` handler logs.
This can only mean that the webhook server was not contacted at all (if it was and was not available then the `Pod` creation must have failed due to the `failurePolicy: Fail` in the webhook config).

The only reason for the webhook not being called is that the `namespaceSelector` did not trigger, i.e., the `kube-system` namespace was not yet labeled. And indeed, the shoot reconciliation flow reveals the racy behaviour:

https://github.com/gardener/gardener/blob/afb63a9c60cba19cc9536fcf7cedde2c1d070168/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L410-L414

This is the task that is supposed to label the `Namespace`. Its respective `ManagedResource` is deployed in parallel to the `ManagedResource` containing the system component and addons resources (like `Deployment/addons-nginx-ingress`):

https://github.com/gardener/gardener/blob/afb63a9c60cba19cc9536fcf7cedde2c1d070168/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L468-L472

Since it is not clear which `ManagedResource` gets reconciled first, it may happen that the `addons-nginx-ingress` pods get created before the `kube-system` `Namespace` got labeled. Consequently, the webhook is not contacted and no voluems get injected into the `PodSpec`.

**Comment by timebertt** [comment]
Nice investigation!

Probably, it would have helped if we had metrics for resource-manager (e.g. about webhook invocations).
I opened https://github.com/gardener/gardener/issues/5547 to track this.
