### ISSUE TITLE
CPU and memory limits are not reconciled back when they are removed manually

### ISSUE THREAD

**Issue by voelzmo** [gardener/gardener#5611]
**How to categorize this issue?**

/area auto-scaling
/area control-plane
/kind bug

**What happened**:
We used an OPA policy to remove CPU and memory limits on Deployments in a Shoot namespace on a Seed. This worked as expected, limits got removed on e.g. the `kube-apiserver` Deployment, the Deployment got rolled and all Pods and Containers got updated as expected. 
Afterwards, we tried to bring the limits back by ensuring the OPA policy isn't applied anymore (we removed the marker labels on the Shoot namespace) and reconciled the Shoot. Limits were brought back in the `kube-apiserver` Deployment, but not on all containers – the `kube-apiserver` container did *not* get any limits assigned.

**What you expected to happen**:
The `kube-apiserver` also gets limits reconciled, similar to the other containers in the Deployment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This seems to happen [because we're using HVPA to manage the `kube-apiserver` container](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/kubeapiserver/hvpa.go#L63-L72), [which leads to `resources` being managed by HVPA only during Deployment reconciliation](https://github.com/gardener/gardener/blob/1a4065005208a81a4b2d331db72133df29f84411/pkg/operation/botanist/kubeapiserver.go#L399-L406)

**Comment by timebertt** [comment]
I have given this some thought many times already and I came up with the following rule of thumb about what objects webhooks should mutate for which use cases:

I would generally recommend to do all pod-specific/runtime-related mutations on pods themselves instead of mutating higher-level controllers, e.g.:
- resource requests/limits
- scheduling constraints
- injecting sidecars

Only workload-related mutations should be applied to higher-level controllers, e.g.:
- manipulating command-line flags
- adding additional application config

This has the advantage, that when you change webhooks to apply different runtime-related settings (or stop applying them) it will take effect on the next pod creation. This minimizes unnecessary disturbance by rollouts and doesn't need to wait for the next update to the higher-level controller (e.g. by gardenlet).
If runtime-related settings differ between multiple pods, it's generally not an issue. However, following the above pattern ensures that workload-related settings are consistently applied across replicas.

**Comment by voelzmo** [comment]
> I would generally recommend to do all pod-specific/runtime-related mutations on pods themselves instead of mutating higher-level controllers

This is also my opinion, especially when there is already an existing mechanism operating on pod level. Unfortunately, it is already like it is: HVPA operates on pod-owner level while VPA operates on pod level.
