### ISSUE TITLE
Consider disabling etcd-main downscaling for Shoots with `.spec.purpose=infrastructure`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5622]
**How to categorize this issue?**

/area control-plane auto-scaling
/kind enhancement

**What would you like to be added**:
Currently, when the HVPA feature gate is enabled we disable etcd-main downscaling for Shoots with `.spec.purpose=production` - ref https://github.com/gardener/gardener/blob/v1.42.3/docs/concepts/etcd.md#autoscaling. For all other clusters lower advertised requests/limits are only applied during the Shoot's maintenance time window

If disabling scale down entirely for Shoots with production purpose brings a higher quality of service for the Shoot cluster itself, then we should also consider doing the same for Shoots with `.spec.purpose=infrastructure`.

**Why is this needed**:
See above.

**Comment by ialidzhikov** [comment]
> If disabling scale down entirely for Shoots with production purpose brings a higher quality of service for the Shoot cluster itself, then we should also consider doing the same for Shoots with .spec.purpose=infrastructure.

@gardener/etcd-druid-maintainers @gardener/hvpa-controller-maintainers (+ @voelzmo @stoyanr ) can you provide feedback whether we should disable etcd-main scale down entirely for Shoots with `.spec.purpose=infrastructure` (our ManagedSeed clusters)? Thanks in advance!

**Comment by voelzmo** [comment]
I'm no expert in the area of etcd operations, but if it helps to reduce downtimes for our `production` systems, it seems reasonable to also do this for our `infrastructure` systems. I'm wondering if there are any unwanted side-effects, e.g. are we sure how many etcd's are currently tagged as `infrastructure` and are these the ones we don't want to be scaled down?
/cc @timuthy

**Comment by vlerenc** [comment]
`infrastructure` is used by (and allowed only for) Gardener for its seeds, i.e. this only impacts ETCDs in the soils.

In general, it's odd that we treat infrastructure clusters not "at least as critical" as production clusters. They are even more critical, so should include all production cluster measures. Due to the nature of this field (no list, i.e. only one value possible), we may have other deltas? In any case, it sounds very reasonable to help our infrastructure clusters here and when clustered/multi-node ETCD lands, we can delete this "special behaviour" again.
