### ISSUE TITLE
Discussion of extending monitoring in PRs #5561 and #5639

### ISSUE THREAD

**Issue by dergeberl** [gardener/gardener#5650]
**How to categorize this issue?**
/area monitoring
/kind discussion

Hi @rfranzke @ialidzhikov

I open this issue to have one place for the discussion for 2 PRs #5561 and #5639

My thoughts for this 2 PRs:

## optional external blackbox exporter for probing shoots outside gardener #5561

> To be honest, I have some mixed feelings about additions like this one or also #5639. While I appreciate the contributions, it seems that the solutions are very specific and tailored to a specific use-case. Shouldn't such customizations better be put into an extension?

_Originally posted by @rfranzke in https://github.com/gardener/gardener/pull/5561#pullrequestreview-919837503_

I think this one can be done with a extension because this feature do not require any change directly in the helm chart.

## Add additionalAllowedMetrics for prometheus and additionalArgs for node-exporter #5639

>+1. I think in the past we recommended end users to deploy their own node-exporter if they need customizations - ref https://github.com/gardener/gardener/pull/5396#pullrequestreview-874473369 (@wyb1 correct me if I am wrong).
I agree that it is getting too much to allow configuring similar things in the gardenlet component config. I could image that this easily explodes if we start allowing configurations for each and every chart gardenlet is deploying.

_Originally posted by @ialidzhikov in https://github.com/gardener/gardener/pull/5639#pullrequestreview-920037437_

For this PR I see it different. Of course if an end user needs more metrics they can deploy their own node-exporter. But we developed this feature to have more metrics on operation side. In our case this was for `diskstats` and currently we are working on metrics for `oomkills` witch both needs additionalAllowedMetrics (and more node-exporter collectors). Unfortunately deploying for each cluster an additional node-exporter means a lot more resources, so this isn`t really an option. 

Overall I think the complete monitoring topic could be done in an extension. So also the configuration is not inside of the gardenlet. But to move all monitoring stuff in a dedicated extension require much more work, and we cant provide/develop this feature right now.

cc: @einfachnuralex @nschad

**Comment by rfranzke** [comment]
@dergeberl I don't think the team has the bandwidth to discuss the topics to their full extents right now, very sorry about that.

I think both changes could be done as part of extensions. For the second one (#5639), your extension can register a webhook for the shoot clusters and then modify the `node-exporter` daemon set as needed. This is already common practice and done at various places, e.g. https://github.com/gardener/gardener/tree/master/pkg/provider-local/webhook/shoot or https://github.com/gardener/gardener-extension-provider-aws/tree/master/pkg/webhook/shoot. There is also a doc about it: https://github.com/gardener/gardener/blob/master/docs/extensions/shoot-webhooks.md

> Overall I think the complete monitoring topic could be done in an extension. So also the configuration is not inside of the gardenlet. But to move all monitoring stuff in a dedicated extension require much more work, and we cant provide/develop this feature right now.

Definitely, we would like to achieve the same (also for logging by the way, see #3553), but for similar reasons we aren't able to pursue these topics for now.

Would it be okay for your purposes to put your customizations into an extension so that you are not blocked and we don't build new technical debt until we have the time to solve these problems cleanly?

**Comment by dergeberl** [comment]
@rfranzke I got you and the idea but I think it is not practicable for the prometheus config in my opinion. In this case we have to parse the prometheus config and update the keep list for the metrics. I think this will be possible but not practicable to implement this with a webhook. I totally get your point and we don`t want produce more technical debts, we can maintain this feature for now in our fork. So we are fine to close this PRs if you like.

**Comment by rfranzke** [comment]
I see, understood and agreed. Yeah, maybe that's a good option for now (sorry for the inconveniences). I truly hope that we can sort this out and implement cleanly in the future.
