### ISSUE TITLE
Switch back to upstream VPA CRD (with strict validation)

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5658]
/area auto-scaling
/kind enhancement

**What would you like to be added**:
With https://github.com/gardener/gardener/pull/4675 we relaxed the VPA CRD to allow unknown fields in order to unblock users who applied "broken" VPA objects before. See https://github.com/gardener/gardener/pull/4675 for more details.

**Why is this needed**:
We should switch back to the upstream VPA CRD again (maybe with a feature gate in case we still have users that apply "broken" VPA objects (?)) to have the schema validation in-place (hence, to forbid "broken" VPA objects to be created).

**Comment by timebertt** [comment]
@andrerun are there any updates on this issue?

**Comment by voelzmo** [comment]
@timebertt We were blocked on a few internal issues, but these have been resolved. I think we're going to fix this soon!

**Comment by andrerun** [comment]
Documenting discussion on a side channel:
Today I confirmed that an update was recently made to bring existing clusters to conformance. As next steps, I will validate said conformance to the v1 schema, and then I’ll switch to it. Unless we consider it urgent, it will take a couple of weeks due to competing priorities.
