### ISSUE TITLE
DNS intermittent delay

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#57]
By @swapnilgm: It seems like there is issue with kube-DNS. It sometimes takes time to setup DNS entry for services. 

Issue was first found with deployment of etcd backing shoot clusters.  Etcd while bootstrapping, tries to find peers in cluster using peer urls. We setup headless service for this peer URL's. But since sometimes, DNS resolution takes extra time, etcd runs through timeout and fails on bootstrap. 

While digging up I found this isn't etcd specific issue, and can occur with other deployments in future. There are already existing related issues on kubernetes porjects, as listed below,
https://github.com/kubernetes/kubernetes/issues/56903
https://github.com/kubernetes/kubernetes/issues/45976

**Comment by vlerenc** [comment]
The original problem is no longer existing/pressing, because we stopped using the etcd operator and switched to statefulsets. Overall it's anyhow hard to analyse and fix the issue, since kube-dns is a Kubernetes component. We also haven't seen it in other problem scenarios. If you do not agree @swapnilgm, please reopen.
