### ISSUE TITLE
Shoots get reconciled even if seed system components are unhealthy or not up-to-date

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5850]
**How to categorize this issue?**

/area robustness ops-productivity
/kind enhancement

**What would you like to be added**:
We lack information about the health status of seed system components. This was already reported in #5154 and should be addressed with https://github.com/gardener/gardener/pull/5274.
When this PR is merged, the shoot controller in `gardenlet` will not start reconciling shoots when the newly introduced `SystemComponentsHealthy` condition on the `Seed` reports `False`.

However, when a seed system component is updated then `gardenlet` would not wait for the update to finish. This can be particularly problematic when a system component needs to have a specific version to work with the reconciliation of `gardenlet` (see example below).

This can easily be reproduced by creating a `Seed` on `master` branch, then stopping `gardenlet` and applying the following patch before restarting it:

```diff
diff --git a/pkg/operation/botanist/component/etcd/bootstrap.go b/pkg/operation/botanist/component/etcd/bootstrap.go
index d9f2d98e6..5582f7160 100644
--- a/pkg/operation/botanist/component/etcd/bootstrap.go
+++ b/pkg/operation/botanist/component/etcd/bootstrap.go
@@ -318,7 +318,7 @@ func (b *bootstrapper) Deploy(ctx context.Context) error {
 }

 func getDruidDeployCommands(gardenletConf *config.GardenletConfiguration) []string {
-	command := []string{"" + "/bin/etcd-druid"}
+	command := []string{"" + "/bin/foobar"}
 	command = append(command, "--enable-leader-election=true")
 	command = append(command, "--ignore-operation-annotation=false")
 	command = append(command, "--disable-etcd-serviceaccount-automount=true")

```

The `ManagedResource/garden/etcd-druid`'s `.status.conditions` always report `ResourcesHealthy=true`:

```
$ kubectl -n garden get mr etcd-druid -o yaml  | grep ResourcesHealthy -B3
  - lastTransitionTime: "2022-04-22T13:06:03Z"
    lastUpdateTime: "2022-04-22T13:06:03Z"
    message: All resources are healthy.
    reason: ResourcesHealthy
    status: "True"
    type: ResourcesHealthy
```

even though the update of the `etcd-druid` failed:

```
$ kubectl -n garden get pod -l gardener.cloud/role=etcd-druid
NAME                          READY   STATUS              RESTARTS   AGE
etcd-druid-5b4d64f97f-gtwnc   1/1     Running             0          17m
etcd-druid-696f9f6785-jwvvb   0/1     RunContainerError   2          21s
```

Shoots would now be able to get reconciled.

**Why is this needed**:
The `gardener/gardener@v1.44` version contains a new `etcd-druid` version (seed system component) as well as adapted reconciliation logic in `gardenlet` related to the `Etcd` resource.
During the rollout of `gardener/gardener@v1.44` we have seen shoot clusters whose `Etcd`s were reconciled by the old `etcd-druid` because the newly created `etcd-druid` pod had not yet taken over. This led to issues since the old `etcd-druid` version is not compatible with the adapted logic in `gardenlet` related to construction of `Etcd` resource. Eventually, manual intervention was required.

**Comment by rfranzke** [comment]
FYI @dguendisch

**Comment by timebertt** [comment]
Idea is to 
- [x] (@kris94) Merge https://github.com/gardener/gardener/pull/5274
- [x] (@timebertt) introduce a new condition `Progressing` (or `RolloutProgressing`) on `ManagedResources` that is set to `True` if resources included in the `ManagedResource` (e.g. a `Deployment`) are not fully rolled out yet: https://github.com/gardener/gardener/pull/5904
  - condition is set to `Unknown` after applying all resources
  - health controller checks for progressing resources (taking into account outdated `observedGeneration`) and sets condition to `False`, if all resources are fully rolled out
- [x] (@plkokanov) seed reconciler always sets `Healthy` condition introduced by https://github.com/gardener/gardener/pull/5274 to `Progressing` on each reconciliation: https://github.com/gardener/gardener/pull/5995
- [x] (@ialidzhikov) ensure that new `Progressing` condition in `ManagedResource` status checks that there are no old `Pod`s anymore which are still terminating, similar to https://github.com/gardener/gardener/pull/5968/commits/35e3f6a6032482ea502b76fd26692f3b261564db#diff-96cccc01c29f594d0845a57556abf22d242fa5d4abf1a8ffc9a4355b710dc124R136-R144
  - In the GQF meeting we decided to do not implement this feature for now as it will come with a certain cost. The concern is that if we add similar handling GRM will have to list Pods for every Deployment it manages (or have a watch all Pods in the cluster) which will lead to additional load on apiserver side (or increased memory usage on GRM side due to the watch). For most of the cases it should not be a mission critical failure if a request hits the `Terminating` replica. I also created a feature request to K8s to track such information in the Deployment status if possible - ref https://github.com/kubernetes/kubernetes/issues/110171.
- [x] (@plkokanov) seed care reconciler only sets `Healthy` condition to `True` if there are no `ManagedResources` with `Progressing={True,Unknown}`. This will make the shoot controller wait for the seed to be fully rolled out before starting shoot reconciliations and thereby resolve the described issue: https://github.com/gardener/gardener/pull/6028

The new condition can also be used for shoot components managed by resource-manager later on.

**Comment by timebertt** [comment]
/unassign
The first step toward resolving this issue is done with https://github.com/gardener/gardener/pull/5904. 
Once both https://github.com/gardener/gardener/pull/5904 and https://github.com/gardener/gardener/pull/5274 have been merged, this can be continued (by anyone who is free then).

**Comment by plkokanov** [comment]
For the last part:
> seed care reconciler only sets Healthy condition to True if there are no ManagedResources with Progressing={True,Unknown}. This will make the shoot controller wait for the seed to be fully rolled out before starting shoot reconciliations and thereby resolve the described issue.

We could simply change the following function in https://github.com/gardener/gardener/blob/master/pkg/operation/care/checker.go
```diff
diff --git a/pkg/operation/care/checker.go b/pkg/operation/care/checker.go
index 7e1ac0292..00223b844 100644
--- a/pkg/operation/care/checker.go
+++ b/pkg/operation/care/checker.go
@@ -234,26 +234,27 @@ func (b *HealthChecker) CheckManagedResource(condition gardencorev1beta1.Conditi
                return &c
        }
 
-       toProcess := map[gardencorev1beta1.ConditionType]struct{}{
-               resourcesv1alpha1.ResourcesApplied: {},
-               resourcesv1alpha1.ResourcesHealthy: {},
+       typeToExpectedStatus := map[gardencorev1beta1.ConditionType]gardencorev1beta1.ConditionStatus{
+               resourcesv1alpha1.ResourcesApplied:     gardencorev1beta1.ConditionTrue,
+               resourcesv1alpha1.ResourcesHealthy:     gardencorev1beta1.ConditionTrue,
+               resourcesv1alpha1.ResourcesProgressing: gardencorev1beta1.ConditionFalse,
        }
 
        for _, cond := range mr.Status.Conditions {
-               _, ok := toProcess[cond.Type]
+               expectedStatus, ok := typeToExpectedStatus[cond.Type]
                if !ok {
                        continue
                }
-               if cond.Status == gardencorev1beta1.ConditionFalse {
+               if cond.Status != expectedStatus {
                        c := b.FailedCondition(condition, cond.Reason, cond.Message)
                        return &c
                }
-               delete(toProcess, cond.Type)
+               delete(typeToExpectedStatus, cond.Type)
        }
 
-       if len(toProcess) > 0 {
+       if len(typeToExpectedStatus) > 0 {
                var missing []string
-               for cond := range toProcess {
+               for cond := range typeToExpectedStatus {
                        missing = append(missing, string(cond))
                }
                c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceMissingConditionError, fmt.Sprintf("ManagedResource %s is missing the following condition(s), %v", mr.Name, missing))
```

I have not tested it completely but this will probably be better than adding a similar check only in https://github.com/gardener/gardener/blob/master/pkg/operation/care/seed_health.go and it would also resolve
> The new condition can also be used for shoot components managed by resource-manager later on.

@timebertt @ialidzhikov @rfranzke wdyt?

**Comment by rfranzke** [comment]
This will also consider the `Progressing` condition for `ManagedResource`s associated with `Shoot`s. Is this safe at this stage, or better, do we really want this/care about it?

**Comment by rfranzke** [comment]
All related tasks have been completed. Thanks everybody for your contributions!
/close
