### ISSUE TITLE
Handle scaling of KCM/MCM as part of generic `Worker` actuator reconciliation

### ISSUE THREAD

**Issue by unmarshall** [gardener/gardener#5878]
**How to categorize this issue?**
/area control-plane
/area robustness
/kind enhancement

**What would you like to be added**:
See [DWD/Issue#45](https://github.com/gardener/dependency-watchdog/issues/45)

It is possible that prober scales down KCM/MCM/CA partially or fully before the reconciler reacts to a Request and then attempts to cancel the probe because the cluster has been marked for hibernation. This will cause the hibernation to be stuck as it requires KCM/MCM to be up and running.

It was argued that DWD should not scale up `KCM/MCM` if they have been previously scaled down by DWD probe due to external probe failures for the following reasons:
1. Break the single actor principle and thus causing more than one actors to concurrently execute conflicting actions w.r.t scaling Up/Down KCM/MCM for a shoot cluster.
2. Prevent DWD from having direct dependencies to MCM APIs which will be required to figure out if the shoot machines have been brought down successfully.
3. Reduce the complexity in DWD and instead keep the responsibility to ensure that the hibernation succeeds to the actor which already overlooks the entire hibernation process for a shoot cluster.

It was proposed by @rfranzke and @ialidzhikov to make changes to https://github.com/gardener/gardener/blob/80c9a619e3d5e68f6fb5a4fcdb016004c34fbc64/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L58-L63 to additional scale up KCM/MCM if they are down for a shoot cluster for which hibernation has been enabled and is stuck.

**Why is this needed**:
See [DWD/Issue#45](https://github.com/gardener/dependency-watchdog/issues/45)

**Comment by vlerenc** [comment]
If understand it right, this sounds much better/safer, so basically:
- Hibernation was implemented with the wrong assumptions and should no longer assume everything is up/running and should first bring everything up/to the expected state (even if there are networking issues and `kubelet`s cannot update their status, that's irrelevant during hibernation) and then commence with the hibernation flow
- Since the desired cluster state is `hibernated`, DWD will not take repeated/conflicting action anymore if a cluster is in this state

Considering that hibernation was implemented before DWD (I believe), the "outdated assumptions" issue strikes again. The more complex software becomes, the more likely it becomes that past assumptions no longer hold true in an evolving system, I guess.

**Comment by unmarshall** [comment]
Correction:
In [actuator_reconcile.go](https://github.com/gardener/gardener/blob/80c9a619e3d5e68f6fb5a4fcdb016004c34fbc64/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go) only MCM and CA are scaled up/down. KCM is not handled in this reconciler.

**Comment by unmarshall** [comment]
cc @rishabh-11
