### ISSUE TITLE
Always update timestamp annotation on `Infrastructure` reconciliation

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5914]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
Today, the timestamp annotation is only updated when the reconcile operation annotation is added to the `Infrastructure`: https://github.com/gardener/gardener/blob/f74b427915216972c2595d4271db0520e01b9522/pkg/operation/botanist/component/extensions/infrastructure/infrastructure.go#L136-L139

I think we should always update it (similar to what we do [here](https://github.com/gardener/gardener/blob/63a4bd7f9fa2b6e18265b7a04c4984316235f0c4/pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go#L189-L192)). 

The same issue seems to apply for `DNSRecord` resources: https://github.com/gardener/gardener/blob/63a4bd7f9fa2b6e18265b7a04c4984316235f0c4/pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go#L147-L150

**Why is this needed**:
The `Infrastructure` deployment task is only executed in the shoot maintenance time window. However, in case the credentials have expired and the `Shoot` transitioned to `Failed`, and now the users retries the operation, the extension won't try reconciling the `Infrastructure` again since there is no `UPDATE` event (because the timestamp annotation is not updated).

**Comment by acumino** [comment]
> now the users retries the operation

@rfranzke What does user retries means. Does it mean the user annotates the shoot with retry operation? 

>  the extension won't try reconciling the Infrastructure

If we annotate a shoot with retry, the infra also gets the reconcile annotation and it gets reconciled. I am not sure what I am missing here.

**Comment by rfranzke** [comment]
@voelzmo Can you potentially add some details what was happening in your scenario and maybe even some more conrete steps for reproduction?

**Comment by ary1992** [comment]
For reproducing the issue I have done the following steps :
 - Created a shoot with valid AWS credentials. The infrastructure resource got deployed with timestamp annotation and shoot was in healthy state.
 - Made the change to `shoot-operator-aws` secret in `garden-dev` namespace with invalid credentials.
 - The shoot didn't reconciled to failed state as the infrastructure reconciles only during the maintenance window.
 - Annotate the shoot with `gardener.cloud/operation=maintain`. It resulted in `infrastructure` resource to be in `Error` state and shoot to be in `Failed` state.
 - On annotating the shoot with `retry` operation , the infrastructure resource also got reconciled  and timestamp annotation got updated as the shoot had `shoot.gardener.cloud/tasks: deployInfrastructure` added during maintenance operation.
 
 Only after removing the `shoot.gardener.cloud/tasks: deployInfrastructure` annotation , the infrastructure resource didn't reconciled.
 My confusion is in which scenario we will have the shoot in Failed state without the `shoot.gardener.cloud/tasks: deployInfrastructure` annotation . I am not able to reproduce the mentioned scenario (without manually deleting the `shoot.gardener.cloud/tasks: deployInfrastructure` annotation).

 @voelzmo maybe you can clarify a bit more on reproducing the issue.

**Comment by voelzmo** [comment]
> The same issue seems to apply for DNSRecord resources

Can confirm that the same cluster no longer has an `infrastructure` problem, but now has a `DNSRecord` problem.

> maybe you can clarify a bit more on reproducing the issue.

Here is what I did (caveat: this is how I remember it, no guarantee that this is 100% correct):
* I'm using the IaaS based local-setup and had a Shoot from a few weeks ago. I hibernated it back then, because I didn't need it for a while
* When I needed it again, I started the local setup, waited for reconciliation to finish with the hibernated Shoot once, then switched to `hibernation.enabled: false` and tried to reconcile
* Saw problems with the credentials (just like always when you get back to your dev setup after a while) and updated creds for internal/default DNS domain and GCP provider
* re-tried a gazillion times to reconcile, but didn't succeed
* got one step further when Rafael added the timestamp to the infrastructure, now seeing issues with `DNSRecords`
