### ISSUE TITLE
Cleanup CloudProfile `docker` migration

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#6375]
**How to categorize this issue?**

/kind cleanup technical-debt

**What would you like to be added**:

The `CloudProfile` controller has temporary migration coding, that adds `docker` to all `.spec.machineImages[].versions[].cri` configurations (introduced by https://github.com/gardener/gardener/pull/4500):
https://github.com/gardener/gardener/blob/115733caad7e60110fbd379ad85b526fd151825e/pkg/controllermanager/controller/cloudprofile/reconciler.go#L120-L129

https://github.com/gardener/gardener/pull/6360 (fca8a723870d31b2c9b9b107ddea56cac162d865) tried to clean this up. However, this is not so easy and requires more cleanup as mentioned in https://github.com/gardener/gardener/pull/6360#discussion_r926405269.

We need to:

- validate that `.spec.machineImages[].versions[].cri` is not empty (as proposed in https://github.com/gardener/gardener/pull/4501), as other controllers can't deal with that (e.g. [shoot maintenance controller](https://github.com/gardener/gardener/blob/a18f88131245415ee4d7d08d808b4e3284aed332/pkg/controllermanager/controller/shoot/shoot_maintenance_control.go#L445-L450))
- validate that `.spec.machineImages[].versions[].cri` contains `docker`, as long as gardener requires machine images to have the `docker` daemon installed (as long as https://github.com/gardener/gardener/issues/4673 is not resolved)
- default an empty `.spec.machineImages[].versions[].cri` to a list containing only `docker` (this was the implicit default, so it should be defaulted properly during API defaulting now rather than during reconciliation)
- drop the migration code from the `CloudProfile` controller

**Why is this needed**:

Cleanup the left-overs and unfinished work from https://github.com/gardener/gardener/issues/4110.

**Comment by timebertt** [comment]
cc @voelzmo @BeckerMax

**Comment by voelzmo** [comment]
Do we need to tackle this now instead of doing #4673 first, such that we can simply remove that code? Is there a benefit in touching this, knowing that it is going to be removed as soon as we _can_ produce docker-less OS images?

Also: I think while it is true that we cannot produce docker-less images right now, it is a different story if we advertise the option to use `docker` as a container runtime with a certain operating system version. Removing this option in e.g. a certain GardenLinux version would be a perfectly fine product decision, imho, even if the docker daemon is still installed on the OS.

**Comment by timebertt** [comment]
Well, I do not see any movement or pull on https://github.com/gardener/gardener/issues/4673. AFAIK nobody is working on it.
However, we should get rid of this technical debt.
