### ISSUE TITLE
Shoots are created without access credentials

### ISSUE THREAD

**Issue by IliyanVidenov** [gardener/gardener#643]
We are experiencing some issues when we try to create a shoot. It is successfully created (ControlPlaneHealty condition is set to true) but without access credentials both missing in the gardener dashboard and seed secrets. After reconciliation, the credentials appear.

**Comment by rfranzke** [comment]
Can you elaborate a little more? I didn't get the actual problem.

**Comment by adracus** [comment]
The condition `ControlPlaneHealthy` is not the indicator for the credentials being present. The only time when you can assume that the credentials are there is after a _successful complete reconciliation_ (i.e. roughly translates to `Shoot.status.LastOperation.Progress == 100 && Shoot.status.LastOperation.State == Succeeded`)

**Comment by vpnachev** [comment]
The issue is that the access credentials are synced too late to the Garden cluster, in the best case on the second reconciliation of the shoot cluster.

The scenario is like this:
1. A shoot called `my-shoot` was already successfully created and was working fine
2. The shoot called `my-shoot` is scheduled for deletion
3. A few minutes later the GCM reported that it is successfully deleted
4. But the access credentials( `ssh-keypair` and `kubeconfig` secrets) are not deleted from the Garden cluster
5. A new shoot was created, also called `my-shoot`
6. During the creation of the new shoot cluster, the access credentials for the previous one are deleted from the Garden cluster
7. The GCM report that the new Shoot is created(100%), but the access credentials are missing in the Garden cluster
8. On the next reconciliation of the Shoot, the access credentials are synced and are finally presented in the Garden cluster and in the Gardener Dashboard.

I will look deeper into this issue.

**Comment by vpnachev** [comment]
It turns that the `garbagecollector` controller was not enabled for the KCM in the kubernetes cluster extended by the Gardener. So, when a shoot cluster is deleted, the `deletionTimestamp` of the secrets containing the access credentials is set, but there is no controller to finalize the deletion of these secrets within reasonable time. 

Thanks to @rfranzke who proposed what could be wrong and I just had to validate it.

I think that this issue could be closed now.
