### ISSUE TITLE
[Flaky Test] ExposureClass Controller Integration Test Suite

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#6496]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
- ExposureClass Controller Integration Test Suite.[It] should add the finalizer and not release it on deletion since there is still referencing shoot

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6480/pull-gardener-integration/1559427070918922240
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6431/pull-gardener-integration/1559413958002085888

Any many other occurenaces.

**Reason for failure**:

**Anything else we need to know**:

**Comment by acumino** [comment]
/assign @ary1992
Can you please follow-up on this issue?

**Comment by timebertt** [comment]
The test failures are similar to https://github.com/gardener/gardener/issues/6486#issuecomment-1214835354.
I will take a look.
/unassign @ary1992 
/assign

**Comment by timebertt** [comment]
/reopen
This was not fixed with https://github.com/gardener/gardener/pull/6527/commits/cb5a46f1acb58aabab36aafe86051ea804fa7df8

This is obviously not enough:
https://github.com/gardener/gardener/blob/c44dddf1439a0cbde65c7e9a8b54708b55656129/test/integration/controllermanager/exposureclass/exposureclass_test.go#L106-L113
The `ExposureClass` might be cleaned up until the shoot is created.
(Or gardener-apiserver's cache could be outdated...)

We should create the shoot first, disable whatever admission plugin denies referencing a non-existing ExposureClass and then wait for the manager's cache to observe the Shoot.
Then we can create the ExposureClass.
This should be bulletproof then 😄
