### ISSUE TITLE
control plane migration does not respect seedSelector in cloud profile

### ISSUE THREAD

**Issue by RaphaelVogel** [gardener/gardener#6654]
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
Control plane migration does not respect `seedSelector.matchLabels` defined in cloud profile. Control plane migration to a destination seed which does not have the corresponding label should not work.
**What you expected to happen**:
When a control plane is migrated it should be checked, if the destination seed has the required label which is defined in the cloud profile. If this is not the case, no migration should be executed 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
So far, the `seedSelector` in the `CloudProfile` is not used by any validation (independent of control plane migration) but only by the `gardener-scheduler`.

**Comment by ialidzhikov** [comment]
As @rfranzke shared in https://github.com/gardener/gardener/issues/6654#issuecomment-1241942300 the CloudProfile's `.spec.seedSelector` is currently only used by the gardener-scheduler. I think it is possible (and was possible before) to create Shoots on Seed that does not match CloudProfiles `.spec.seedSelector`. Hence, the semantic of this `.spec.seedSelector` field currently is  "checked during scheduling, not checked for manual seed assignment (Shoot creation or CP migration)". Do I get it right that we now want to change the semantics of this field and check that CloudProfiles `.spec.seedSelector` matches the Seed for manual seed assignment (Shoot creation or CP migration)? Said with other words, the CloudProfiles `.spec.seedSelector` will be be always checked and enforced. I am asking such question because I don't know what was the semantic/idea when this field was initially introduced. 
Having in mind that we use this field to differentiate between the different openstack instances/landscapes, I assume we want to enforce this field as suggested in this issue, right?

**Comment by rfranzke** [comment]
It probably makes sense to enforce it, yes @ialidzhikov. If the `CloudProfile` references a `Shoot` with a specific `seedSelector` then most probably only those seeds are eligible for running the shoot's control plane. If it's `nil` then there is no such constraint and any seed could be used (even cross-provider).
