### ISSUE TITLE
[Flaky Test] Pod Scheduler Name Webhook Handler

### ISSUE THREAD

**Issue by shafeeqes** [gardener/gardener#6709]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [0.011 seconds]
Pod Scheduler Name Webhook Handler
/home/prow/go/src/github.com/gardener/gardener/test/integration/seedadmissioncontroller/podschedulername/podschedulername_test.go:27
  [It] should set .spec.schedulerName
  /home/prow/go/src/github.com/gardener/gardener/test/integration/seedadmissioncontroller/podschedulername/podschedulername_test.go:66
  Begin Captured GinkgoWriter Output >>
    STEP: deleting test pod 09/20/22 09:08:27.088
  << End Captured GinkgoWriter Output
  Expected
      <string>: default-scheduler
  to equal
      <string>: gardener-shoot-controlplane-scheduler
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/seedadmissioncontroller/podschedulername/podschedulername_test.go:[69](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6698/pull-gardener-integration/1572150280986824704#1:build-log.txt%3A69)
------------------------------
```
**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6698/pull-gardener-integration/1572150280986824704

**Reason for failure**:
See above.

**Anything else we need to know**:

**Comment by rfranzke** [comment]
This seems to be similar to #6671

**Comment by timebertt** [comment]
I think the problem here is, that we are only a single `CREATE pod` call right after creating the webhook.
If the API server's webhook admission plugin has not observed the webhook object yet, the webhook might not get called.

Here you can see how the `{Mutating,Validating}Webhook` admission plugin makes use of informers for retrieving the webhooks to call during a given API call:
- https://github.com/kubernetes/kubernetes/blob/5556d3336b986dcd7ec7de85f731425be91273b4/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook.go
- https://github.com/kubernetes/kubernetes/blob/5556d3336b986dcd7ec7de85f731425be91273b4/staging/src/k8s.io/apiserver/pkg/admission/configuration/mutating_webhook_manager.go

That’s why it’s not guaranteed that a webhook is called immediately after being created. It’s eventually consistent. :slightly_smiling_face: 


Hence, I propose to use `Eventually` to create the pod and observe that the mutating gets applied "eventually".

**Comment by ialidzhikov** [comment]
@rfranzke @timebertt If I am not wrong currently there is no way to run a webhook env test against existing cluster, right?
The webhook's is created/updated with localhost url:
```yaml
  clientConfig:
    url: https://127.0.0.1:53599//webhooks/default-pod-scheduler-name/gardener-shoot-controlplane-scheduler
```

and kube-apiservers (`make kind-up` or `make local-garden-up`) fail to call the webhook with:
```
E1007 09:19:07.571606       1 dispatcher.go:184] failed calling webhook "kube-scheduler.scheduling.gardener.cloud": failed to call webhook: Post "https://127.0.0.1:53599/webhooks/default-pod-scheduler-name/gardener-shoot-controlplane-scheduler?timeout=2s": dial tcp 127.0.0.1:53599: connect: connection refused
```

Or, I am missing something?

**Comment by ialidzhikov** [comment]
Anyways I managed to run the stress tool for the the webhook tests by not using existing cluster.

**Comment by ialidzhikov** [comment]
@rfranzke @timebertt the reason for this flake is rather that in the BeforeSuite we are missing a wait until the webhook is started. Example from other webhook envtest:

https://github.com/gardener/gardener/blob/2c5074415de457e9609f51850e62991c3cdb4f0d/test/integration/resourcemanager/seccompprofile/seccompprofile_suite_test.go#L127-L131
