### ISSUE TITLE
[Flaky Test] ControllerInstallation Controller tests

### ISSUE THREAD

**Issue by shafeeqes** [gardener/gardener#6786]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [6.690 seconds]
ControllerInstallation controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:37
  responsible
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:128
    [It] should create a namespace and deploy the chart
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:141
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6750/pull-gardener-integration/1579353349046669312

**Reason for failure**:
```
  Expected
      <string>: "...ls:
            controllerinstallation-controller-test: "628249e0"
            provider.extensions.gardener.cloud..."
  to equal                                                            |
      <string>: "...ls:
            controllerinstallation-controller-test: 628249e0
            provider.extensions.gardener.cloud/p..."
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:164
```
**Anything else we need to know**:

**Comment by rfranzke** [comment]
Two more:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6784/pull-gardener-integration/1579753120127258624
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-integration/1579544044596367360

**Comment by rfranzke** [comment]
Another one:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6808/pull-gardener-integration/1579827971126988800

**Comment by rfranzke** [comment]
Looking at all the failures, the problem seems to occur when the `testRunID` is interpreted as number: https://github.com/gardener/gardener/blob/d3bda6cf471143652fc24036e8f497d373cb250c/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go#L109

In this case, https://github.com/gardener/gardener/blob/d3bda6cf471143652fc24036e8f497d373cb250c/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go#L175 must be quoted (but we don't).

In above failures, the `testRunID` values were the following (which supports the hypothesis):

- `628249e0`
- `00653735`
- `54407633`
- `964645e9`

I was also able to reproduce it locally with a `41608e10` as `testRunID`.
