### ISSUE TITLE
Requirements for failureTolerance "node" are not checked on Shoot creation/update

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#6827]
**How to categorize this issue?**

/area high-availability
/kind bug

**What happened**:
It is possible to create shoots with `failureTolerance` type `node` even when there are no seeds with this feature enabled.

_Shoot creation:_
New shoots with failure tolerance type node can be scheduled anywhere, even on seeds having HA disabled. 

_Shoot update:_
Failure tolerance of type node can be activated on shoots which are scheduled on a seed having HA disabled. 

In both cases the shoots run in a non HA setup. **This is not visible for the user**. You can just see it by checking etcd pods in control-plane.
For failure tolerance type zone on the other hand, there is a check which prevents updating the shoot (update case) or at least making them unschedulable (create case).

**What you expected to happen**:
It should not be possible to create/update shoots with failure tolerance type node if there are no suitable seeds.

**How to reproduce it (as minimally and precisely as possible)**:
Create or update shoots in a landscape without any HA seeds with this config:
```
...
spec:
  controlPlane:
    highAvailability:
      failureTolerance:
        type: node
...
```

**Anything else we need to know?**:
I found two places where the availability of `failureTolerance` type `node` on the seed is not checked
- gardener-admission-controller: [ref](https://github.com/gardener/gardener/blob/3c02b2b99184f6789306965256e940a2da71d052/plugin/pkg/shoot/validator/admission.go#L360)
- gardener-scheduler: [ref](https://github.com/gardener/gardener/blob/3c02b2b99184f6789306965256e940a2da71d052/pkg/scheduler/controller/shoot/reconciler.go#L222)

This list might not be complete.

**Environment**:

- Gardener version: v1.57.0

**Comment by timuthy** [comment]
As discussed with @oliver-goetz, this issues mixes up two scenarios when stating "[...] no seeds with this feature enabled":

1. The `HAControlPlane` feature gate is not enabled by `gardenlet` -> This will result in shoot clusters having non-HA control-planes even though it's desired by `spec` or `metadata.annotations`. I only see potential protection for this problem by adding the feature gate also to `gardener-apiserver`, so that users can't create HA shoot clusters when disabled.

2. The seed does not configure `spec.highAvailability.failureTolerance.type: node` but a `node` HA shoot is scheduled onto it -> This will result in a `node` tolerance shoot control-plane on a seed which doesn't have the same tolerance level for its seed system components. https://github.com/gardener/gardener/pull/6833 addresses this gap which is actually an incompatible change but should still be acceptable, considering the `alpha` status of the feature.

cc @unmarshall
