### ISSUE TITLE
Node's Pods count in the `Node/Worker Pool Overview` dashboard is wrong

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6892]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
![Screenshot 2022-10-25 at 8 57 16](https://user-images.githubusercontent.com/9372594/197694007-9b0f9390-fc52-4d39-b940-b61b13a34f1c.png)

The dashboard shows 9 Pods for `ip-10-242-1-133.eu-central-1.compute.internal` and 11 Pods for `ip-10-242-1-136.eu-central-1.compute.internal`.
But in reality:
```
$ k get po -A --field-selector=spec.nodeName=ip-10-242-1-133.eu-central-1.compute.internal --no-headers | wc -l
67
$ k get po -A --field-selector=spec.nodeName=ip-10-242-1-136.eu-central-1.compute.internal --no-headers | wc -l
180
```

**What you expected to happen**:
`Node/Worker Pool Overview` dashboard to show the correct number of Pods per Node.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.58.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by acumino** [comment]
For shoot, we only collect metrics for `kube-system` namespace https://github.com/gardener/gardener/blob/b53d99f3edadcfa6d1fb66510debbf5777a92209/pkg/operation/botanist/component/kubestatemetrics/resources.go#L218. That's why no. of pods shown in grafana is wrong as it is the count of pods in `kube-system` namespace only.
