### ISSUE TITLE
Use wildcard certificate to expose `kube-apiserver`s of `Shoot` with trusted certificate

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7233]
**How to categorize this issue?**

/area networking usability
/kind enhancement

**What would you like to be added**:
Operators can already provide a wildcard certificate for the seed cluster's ingress domain which is used to expose the observability components with a trusted certificate. This functionality is undocumented.

The `gardenlet`'s `Shoot` controller copies the wildcard certificate secret into the shoot namespaces: https://github.com/gardener/gardener/blob/759c2641dab95cba6653924e3462aeec2e1fe56d/pkg/operation/botanist/secrets.go#L309-L335
When constructing the `Ingress` resources for the observability components, this secret is used in `spec.tls[].secretName`: https://github.com/gardener/gardener/blob/759c2641dab95cba6653924e3462aeec2e1fe56d/pkg/operation/botanist/monitoring.go#L164-L180
https://github.com/gardener/gardener/blob/759c2641dab95cba6653924e3462aeec2e1fe56d/charts/seed-monitoring/charts/alertmanager/templates/ingress.yaml#L17-L21

Let's enhance `gardenlet` to also create an `Ingress` resource for the `kube-apiserver` of shoots with a subdomain of the seed's ingress domain (similar like it's done for the observability components). Use this wildcard certificate secret to expose it. In order for this to work, `kube-apiserver` must be additionally configured with `--tls-sni-cert-key`.
From https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/:

> A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. The domain patterns also allow IP addresses, but IPs should only be used if the apiserver has visibility to the IP address requested by a client. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com".

**Why is this needed**:
The https://github.com/gardener/terminal-controller-manager could benefit from it since it currently sets this up manually.

**Comment by rfranzke** [comment]
~~⚠️ Let's finish https://github.com/gardener/gardener/issues/7232 first before we work on this one.~~

**Comment by timebertt** [comment]
TBH, I still don't like this request to use a "commonly trusted" certificate for the API server.
Not from a security point of view and not from a kubernetes point of view.
In my opinion, any component wishing to establish trust with any shoot API server should first obtain the corresponding CA bundle from a trusted origin (e.g. the garden cluster). It should then verify the presented server certificate with the CA bundle.
I would consider this protocol for establishing trust even more secure than blindly trusting anybody with a "commonly trusted" server certificate because you establish that this is indeed the authority you want to connect to.

That being said...

> Let's enhance `gardenlet` to also create an `Ingress` resource for the `kube-apiserver` of shoots with a subdomain of the seed's ingress domain

I'm concerned about adding an additional path for accessing API servers next to the common path via the istio ingress gateway.
Adding a new path means mechanisms like ACL need to protect all paths to be effective, which is error-prone and hence increases the security risk.
This probably doesn't affect any mechanisms in g/g. However, I'm afraid such an architectural decision might be troublesome in the long run.

Because of this, I vote for making a distinction between the wildcard certificate used for `Ingress` objects (observability endpoints) and the wildcard certificate for the API server ingress.
Operators could potentially use the same certificate. But it should be possible to use the currently existing ingresses without the side-effect of enabling the additional API server ingress.

If this feature is purely optional, I'm fine with having it in the codebase.

**Comment by rfranzke** [comment]
The feature is optional, just like it is today for the observability ingresses. If you don't provide a wildcard certificate secret as operator then nothing will happen. Also, my understanding is that istio-ingressgateway (and thus, the same "path") will be reused once we have tackled #7232. It's just another endpoint with a trusted certificate instead of the self-signed one.

**Comment by timebertt** [comment]
> The feature is optional, just like it is today for the observability ingresses. If you don't provide a wildcard certificate secret as operator then nothing will happen

Great, that's good news!

> Also, my understanding is that istio-ingressgateway (and thus, the same "path") will be reused once we have tackled #7232. It's just another endpoint with a trusted certificate instead of the self-signed one.

I'm not sure if this is the case. I assume there will be different envoy filter chains, etc. for the existing API server access and the `Ingress` resources. But I'm not very deep into the topic.
Maybe it makes sense to rely on istio's built-in resources instead of the `Ingress` API to benefit from the same feature set and most importantly consistency.

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/7518 is the first step. What is missing is the integration into `gardenlet`s `shoot` controller (concretely, the instrumentation of the `kubeapiserver` package via the botanist) as described above.

If anybody is interested to implement the second part, feel free to pick it up :)
