### ISSUE TITLE
provider-local: Cannot delete Seed

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7237]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
I am following https://github.com/gardener/gardener/blob/master/docs/development/getting_started_locally.md.

I need to delete my `local` Seed and create a new one with updated spec (not allowed to change immutable fields).

Hence, I deleted my seed.
```
% k delete seed local
```

The deletion fails with:
```yaml
  - lastTransitionTime: "2022-12-19T13:42:39Z"
    lastUpdateTime: "2022-12-19T13:44:39Z"
    message: "Failed to delete Seed Cluster (1 error occurred:\n\t* task \"Destroy
      dependency-watchdog-probe\" failed: error while waiting for all resources to
      be deleted: retry failed with context deadline exceeded, last error: resource
      garden/dependency-watchdog-probe still exists:\nCould not clean all old resources:
      1 error occurred: deletion of old resource \"apps/v1/Deployment/garden/dependency-watchdog-probe\"
      is still pending\n\n)."
    reason: DebootstrapFailed
    status: "False"
    type: Bootstrapped
```

`kube-controller-manager` cannot remove finalizer `foregroundDeletion` from the `dependency-watchdog-probe` Deployment.

KCM logs:
```
% k -n kube-system logs kube-controller-manager-gardener-local-control-plane | grep --text dependency-watchdog-probe

E1219 13:46:23.348686       1 garbagecollector.go:374] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"apps/v1", Kind:"Deployment", Name:"dependency-watchdog-probe", UID:"54392e49-619d-41af-b859-1ba932a46eb4", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:"garden"}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, deletingDependents:true, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:true, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference(nil)}: admission webhook "dnsconfig.local.extensions.gardener.cloud" denied the request: Service "coredns" not found
E1219 13:51:50.706630       1 garbagecollector.go:374] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"apps/v1", Kind:"Deployment", Name:"dependency-watchdog-probe", UID:"54392e49-619d-41af-b859-1ba932a46eb4", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:"garden"}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, deletingDependents:true, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:true, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference(nil)}: admission webhook "dnsconfig.local.extensions.gardener.cloud" denied the request: Service "coredns" not found
```

**What you expected to happen**:
The Seed deletion to work.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: 44c7c5613ed79a618900a5bfacd3d812224fb3e1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by Kostov6** [comment]
The issue stems from the fact that the ControllerInstallation of a seed and its deployment of `coredns` in `gardener-extension-provider-local-coredns` namespace gets deleted earlier than the `dependency-watchdog-probe`.  The removal of the finallizer of `dependency-watchdog-probe` triggers the dnsconfig webhook and the webhook returns an error because it can not get the `coredns` object in `gardener-extension-provider-local-coredns` ([code](https://github.com/gardener/gardener/blob/master/pkg/provider-local/webhook/dnsconfig/mutator.go#L76)) thus denying the removal of the finallizer. Currently the absence of `coredns` acts as a blocker for any changes that a pod, deployment or statefulset may receive. My proposal is that if `coredns` is not present to not return an error and instead to pass the change (without `coredns` the function `injectDNSConfig` can not be executed and the main purpose of the webhook is to run this function):
```
if err := m.client.Get(ctx, client.ObjectKey{Namespace: "gardener-extension-provider-local-coredns", Name: "coredns"}, service); err != nil {
	if apierrors.IsNotFound(err) {
		return nil
	}
	return err
}
```
I dont see a reason for the absence of `coredns` to discard any changes that these objects may receive. 
If someone has a better suggestion feel free to make a proposal.
@rfranzke @timebertt

**Comment by rfranzke** [comment]
When `coredns` in `gardener-extension-provider-local-coredns` gets deleted, doesn't the extension itself (serving the webhook) get deleted as well? They are part of the same Helm chart/`ControllerInstallation`. If so, then the real problem is that the `MutatingWebhookConfiguration` remains in the system while the server is already gone?

**Comment by ialidzhikov** [comment]
> They are part of the same Helm chart/`ControllerInstallation`.

Are they? @Kostov6 found that it is rather a Seed webhook that is created by provider-local. See https://github.com/gardener/gardener/blob/2f34cb1422985253aa47eb761bb759d6ae4823e3/extensions/pkg/webhook/registration.go#L152-L191

I now see that provider extensions actually have ownerReference to the extension namespace:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  # unrelated fields are omitted
  name: gardener-extension-provider-aws
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: false
    controller: true
    kind: Namespace
    name: extension-provider-aws-dmdjz
    uid: 0f063708-8242-11e9-b96a-ea6eec396f2b
```

while the provider-local webhook does not have such ownerReference:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2023-02-21T15:13:03Z"
  generation: 1
  labels:
    remediation.webhook.shoot.gardener.cloud/exclude: "true"
  name: gardener-extension-provider-local
  resourceVersion: "39465"
  uid: 9cd478d8-844c-42d7-9186-f6ae04d7b3e6
```

**Comment by rfranzke** [comment]
I don't fully get your reply @ialidzhikov, but yes, my suspicion in https://github.com/gardener/gardener/issues/7237#issuecomment-1437263256 was also that the not-deleted/still-existing webhook is the problem for this. Are confirming this here? Do you know why the owner reference is missing?

**Comment by ialidzhikov** [comment]
> I don't fully get your reply @ialidzhikov, but yes, my suspicion in https://github.com/gardener/gardener/issues/7237#issuecomment-1437263256 was also that the not-deleted/still-existing webhook is the problem for this. Are confirming this here?

Yes, the issue is caused by the not-deleted/still-existing webhook. In https://github.com/gardener/gardener/issues/7237#issuecomment-1437263256 I tried to explain that the webhook is rather created by provider-local on start-up and that the webhook manifest is not part of the Helm chart/ControllerInstallation. And that for the deletion of such Seed webhooks, we use the `ownerReferences` approach where the owner is the extension Namespace in the Seed.

**Comment by rfranzke** [comment]
OK, thanks!

> I tried to explain that the webhook is rather created by provider-local on start-up and that the webhook manifest is not part of the Helm chart/ControllerInstallation.

How does this work for `provider-aws`? My understanding is that it works the same way, i.e. it creates (via extensions library) the webhook on start-up and it is not a template of its Helm chart.

**Comment by Kostov6** [comment]
Here the `ownerReference` to the namespace is missing because the namespace value comes from the `--webhook-config-namespace` command option. In the `start-extension-provider-local` script this option seems to intentionally be left missing. I came to this conclusion because of this:

https://github.com/gardener/gardener/blob/afe07938c905c47cef81565ebafc1c203dc96978/extensions/pkg/webhook/cmd/options.go#L277-L282

It seems it is expected for local dev this option to be not set and thus no `ownerReference` gets created that takes care of deleting the webhook. I tested with local deployment setup and there `--webhook-config-namespace` is set thus `ownerReference` is set, webhook gets deleted and seed gets deleted successfully

Do you know if my assumptions are correct and `--webhook-config-namespace` is intentionally not set in `start-extension-provider-local`?

**Comment by Kostov6** [comment]
I assume `--webhook-config-namespace` is not set intentionally as probably another thing fails it if is set. As shared in https://github.com/gardener/gardener/issues/7237#issuecomment-1440248730, there is a special logic that expects `c.Server.Namespace` to be empty string. If we specify now `--webhook-config-namespace`, we will break this special handling. Do you have more details about this special handling?

**Comment by rfranzke** [comment]
Just to get the full picture: Other provider extensions (like AWS) have the same problem, correct?
