### ISSUE TITLE
gardener-scheduler: Seed assignment can be quite inappropriate for Azure Shoots

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7383]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
The limitation is already listed in https://github.com/gardener/gardener/blob/v1.62.1/docs/concepts/scheduler.md#current-limitation--future-plans:
> - Azure has unfortunately a geographically non-hierarchical naming pattern and does not start with the continent. This is the reason why we will exchange the implementation of the `MinimalDistance` strategy with a more suitable one in the future.

Currently, a Shoot created with region `switzerlandnorth` gets assigned to a Seed running in region `australiaeast` while there are many Seeds in more appropriate regions: `westeurope`, `northeurope`.

**Why is this needed**:
To have better Seed selection by the gardener-scheduler which ensures that the Shoot data plane is closer to the Shoot control plane.

**Comment by dguendisch** [comment]
In the last two days we realized that:
- we cannot happily serve customers that want to deploy into shoots in aws `ca-central-1` (where we have no specific seed there, but plenty of capacity in `us-east-1` which would be latency-wise close to optimal) because the scheduler cannot relate `ca` to `us`, hence `ca` shoots will be scheduled anywhere in the world
- we have a lot of mismatched shoot/seed regions specifically for azure regions where we don't have dedicated seeds (as mentioned in the initial description, there is no relation of any region in azure because of the missing hierarchy in azure region names)

For better capacity planning (as a seed operator) and for better latency experiences (as a shoot customer) it would be highly welcomed to have the scheduler actually "understand" region distances or latencies.

In a quick chat we brainstormed ideas of defining distances/latencies (maybe defining once is already enough, as they probably rarely change) either via some cloud provider specific distance or latency table (effectively something like e.g. https://www.cloudping.co/grid for aws) or via some canonical mapping of cloud provider specific regions (e.g. azure `switzerlandnorth` being some region in a canonically named **west europe** region) and then some cloudprovider agnostic distance/latency table. Such a latency table could be an additional input to the shoot scheduler to determine the order/preference of seed candidates (after having filtered out non-applicable seeds).

**Comment by rfranzke** [comment]
/assign @timuthy @rfranzke 

Together with @vlerenc we discussed that we will introduce optional configurability to `gardener-scheduler` such that it can better map which (ordered) regions are the best to choose for a specific other region. This way, human operators have the freedom to decide the order based on their chosen criteria (e.g., latency, geographical location).

Concretely, human operators can create `ConfigMap`s with a well-known label which is then dynamically read by `gardener-scheduler` and used to take the decision:

```yaml
apiVersion: v1
kind: ConfigMap
data:
  eu-central-1: |
    eu-west-1: 23
    eu-south-1: 31
    ca-central-1: 231
```

We also discussed other (apparently more "lightweight") alternatives (e.g., defining continent and orientation per region in the `CloudProfile`), but eventually came back to above proposal in all cases.

**Comment by dguendisch** [comment]
- the example cm would indicate that for a shoot with `.spec.region: eu-central-1`, ONLY the 3 named regions would be valid seed candidate regions?
- the numbers would indicate the priority before e.g. trying to balance seeds?
- the human operator mentioned is a gardener operator or a shoot operator?

**Comment by rfranzke** [comment]
> * the example cm would indicate that for a shoot with `.spec.region: eu-central-1`, ONLY the 3 named regions would be valid seed candidate regions?

Nope, we will fallback to the current Levenshtein logic when we don't find both regions in the mapping.

> * the numbers would indicate the priority before e.g. trying to balance seeds?

Yes, the numbers basically define the ordering. Whether this is latency, geo distance or something else is up to the human operator. In the end, we find choose the seeds with the lowest number and, in a follow-up step (like now), choose the seed with the lowest usage.
Hence, it's just about improving the "distance" logic which fails for some cases with Levenshtein.

> * the human operator mentioned is a gardener operator or a shoot operator?

A Gardener operator 😄 The `ConfigMap`s will reside in the `garden` namespace of the virtual cluster.

**Comment by dguendisch** [comment]
Thanks!
On the use case of shoot operators wanting to ensure that the control plane resides in the same or similar region as the workers: should we consider this here or stick to the currently existing option of labeling seeds with some region information and then let the shoot operator express restrictions via the `seedSelector` field?

**Comment by rfranzke** [comment]
We discussed this as well and think that this is a different concern not related to this issue. Indeed, adding labels to `Seed`s and using `seedSelector` in `Shoot`s would be the preferred solution to tackle such requirements. Do you agree?

**Comment by dguendisch** [comment]
Yes I agree, rethinking on it, the labels and selectors are a trivial but powerful mean to this. It allows gardener operators to label seed regions multiple times with e.g. a different granularity, e.g. with `region/cloudprovider: eu-central-1`, `region/country: germany`, `region/continent: eu` and shoot operators can decide based on their "data-residency" requirements which label to select.

**Comment by rfranzke** [comment]
Exactly :) Operators should just avoid adding something like a `kubernetes.io/metadata.name` label to `Seed`s unless they want to allow seed pinning (typically they don't).
