### ISSUE TITLE
`VPN Seed (CPU| Memory) Usage` panels don't show data

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7402]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
For a ManagedSeed cluster:
![Screenshot 2023-01-27 at 17 10 36](https://user-images.githubusercontent.com/9372594/215119768-8846b7c8-8cbf-40e7-aa8c-f40e9aa7e393.png)

As shown in the above screenshot, the `VPN Seed (CPU| Memory) Usage` panels don't show data.
One of the queries behind the panels is `rate(container_cpu_usage_seconds_total{pod=~"kube-apiserver-.*|prometheus-.*", container="vpn-seed"}[$__rate_interval])`.
There is no such container called vpn-seed in the kube-apiserver Pod (kube-apiserver, apiserver-proxy-pod-mutator) or in the prometheus Pod.

**What you expected to happen**:
The panels to show data for non-HA and HA control planes.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.62.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by Sallyan** [comment]
The `VPN` dashboard has another issue of panel `VPN Shoot CPU Usage`. 
It only shows the request not show the `Actual` and `Limits`
<img width="1424" alt="Screenshot 2023-05-03 at 13 40 51" src="https://user-images.githubusercontent.com/50126000/235839844-56fcd1b0-43b0-48c5-9ee8-373dfd247b37.png">


Panel `VPN Shoot CPU Usage` has the query of `Actual` and `Limits`
<img width="1082" alt="Screenshot 2023-05-03 at 13 44 33" src="https://user-images.githubusercontent.com/50126000/235840290-62370f05-178b-4f4e-999f-696267667ef0.png">

**Comment by Sallyan** [comment]
In Panel `VPN Shoot CPU Usage`, query of `Actual` doesn't show data because of the `Min step` is too low. 
The prometheus data-source `Scrape interval ` is `1m`
```
data:
  prometheus.yaml: |

    global:
      evaluation_interval: 1m
      scrape_interval: 1m
```
`$__rate_interval` is always at least four times the value of the Scrape interval. The value of $__rate_interval is defined as max($__interval + Scrape interval, 4 * Scrape interval), where Scrape interval is the “Min step” setting (also known as query*interval, a setting per PromQL query) if any is set. Otherwise, Grafana uses the Prometheus data source’s “Scrape interval” setting.

The Min step setting defines the lower bounds on the interval between data points. If `Min step` set to `10s`, it will not cover sample to calculate the rate. Removing the `Min step`, the dashboard would show data. 
<img width="1078" alt="Screenshot 2023-05-03 at 16 27 32" src="https://user-images.githubusercontent.com/50126000/235866654-4c9fe5a5-1435-42d0-a2ab-83cf25f0bfd4.png">

**Comment by Sallyan** [comment]
For `VPN Shoot CPU Usage` - Limits, it doesn't have data as vpn-shoot pod doesn't set cpu limits.

**Comment by Sallyan** [comment]
For `VPN Seed CPU|Memory Usage`, the pod name is `vpn-seed-server-.*` and container name should be `vpn-seed-server`
<img width="1012" alt="Screenshot 2023-05-04 at 14 10 39" src="https://user-images.githubusercontent.com/50126000/236124541-6f08e829-af0c-42c1-a0dd-ab9dfac6ea80.png">
