### ISSUE TITLE
☂️ Upgrade observability apps in Gardener 

### ISSUE THREAD

**Issue by nickytd** [gardener/gardener#7585]
/area logging
/area monitoring
/kind enhancement

Update older Grafana and Loki applications to the updated alternatives Plutono and Vali

# Motivation

Currently we use old Apache-2 licensed versions of Loki and Grafana and we would like to move towards Plutono and Vali forks. Plutono (fork of Grafana) -> https://github.com/credativ/plutono/releases/tag/v7.5.19 Vali (fork of Loki) -> https://github.com/credativ/vali/releases/tag/v2.2.3 Both forks feature an updated golang (1.19) fixing numerous public CVEs.

## Migration strategy for seed/shoots Logs
The proposed change includes updating current helm charts, runtime deployments, log shippers configurations, documentation and a migration strategy particularly for the current loki stateful sets.

Here is a list of viable options for the migration strategy of the stateful sets.

### Option I
In this option we
- introduce new Vali stateful sets with new PVs.
- preserve old Loki stateful sets with old Loki PVs to allow searches in a case of troubleshooting scenarios
- scale down Loki stateful set to avoid resource consumption on current production landscapes

Pros:
- Allows operators and users to still access the old logs in case of an emergency.
- Preserves current resource consumption

Cons:
- Require manual steps from the operators to increase the replica counts on Lokis if they want access to the old indexed logs.

### Option II
In this option we
- introduce new Vali stateful sets with new PVs.
- delete completely the existing Loki stateful sets

Pros:
- Preserves current resource consumption
- Simplest possible scenario

Cons:
- Older logs in Loki are not available

### Option III
In this option we
- introduce new Vali stateful sets with new PVs.
- copy Loki indices from old PVs to the new ones.

Pros:
- Older logs are still available in the new Vali instances
Cons:
- Copy operations just takes too much time with corresponding downtime. In addition this options puts pressure on the log shippers.

### Option IV
In this option we
- delete loki but preserve it's PVs
  - set `reclaimPolicy`  to `Retain`
  - clean up `claimRef`
- Introduce Vali and claim now `available` Loki PVs

The best option is **Option IV**

Option IV was initially though to be non valid but was proven by @istvanballok and @rickardsjp 

## Migration plan
The entire transition setup requires 4 consecutive Gardener releases

![observability-migration](https://user-images.githubusercontent.com/3019431/224321493-57767e12-5f19-4e18-a085-60ddcd77543a.png)

### Gardener release 1.X
(gardener/gardener)
1. Decouple `fluent-bits` from the targets backend by introducing a dedicated `logging.<shoot-namespace>` service https://github.com/gardener/gardener/pull/7623

### Gardener release 1.X+1
(gardener/gardener)
1. Switch `fluent-bits` to target `logging.<shoot-namespace>`
https://github.com/gardener/gardener/pull/7731

At this stage we will have all `fluent-bits` using an unified  `logging` service.

### Gardener release 1.X+2 
(gardener/logging)
1. Adjust fluent-bit output plugin https://github.com/gardener/logging/pull/186
`v0.53.0-dev` tag is the current testing build of (1) aka 

> ```yaml
> - name: fluent-bit-plugin-installer
>     repository: eu.gcr.io/gardener-project/gardener/fluent-bit-to-vali
>     tag: "v0.53.0-dev"
> ```

(2) needs to reference the images from (1) in the charts/images.yaml

(gardener/gardener)
2. Migrate `loki` and `grafana` references in g/g  https://github.com/gardener/gardener/pull/7318

At this stage `gardener/dashboard` still shows Grafana URLs to accommodate the case where we can have both shoots in migrated and non-migrated state. Since `fluent-bits` sends logs to a unified `logging.<shoot-namespace>` service it can ships logs to both migrated and non-migrated clusters. 

### Gardener release 1.X+3
(gardener/dashboards)
1. Adjust `grafana`  URLs in `gardener/dashboard` https://github.com/gardener/dashboard/pull/1409

**Comment by vpnachev** [comment]
I also vote for **Option I**.

Something that should be considered during the implementation is that the `fluent-bit` is managed per seed and usually changes are immediately rolled out while shoot reconciliation might run in the maintenance time window of the respective shoot, so for the period between gardenlet update and shoot reconciliation (usually up to 24 hours) fluent bit should be capable to handle the migration and ingest the logs in the existing backend. 

One idea is:
1. In gardener version `1.X` fluent bit keeps ingesting the logs in service `loki.<shoot-namespace>`. 
2. During shoot reconciliation
   1. Vali is deployed 
   1. The `loki` service is reconfigured to point to the Vali pods 
   1. A new service `vali` is created that also points to the Vali pods
4. In gardener version `1.X+1` 
   1. Fluent bit is reconfigured to ingest the logs in the service `vali.<shoot-namespace>`
   1. The loki service is deleted.

To avoid binding to logging backend solutions, the new service name might be `logging` instead of `vali` and the next time the logging backend is changed, just the pod selector in the service needs to be changed during the shoot reconciliation.

Alternatively, the fluent-bit plugin can be enhanced to check itself if the shoot is migrated to vali or not.

**Comment by nickytd** [comment]
Plan is updated to reflect the proposal by @istvanballok and @rickardsjp with `loki PVs` preservation.
