### ISSUE TITLE
gardenlet can occasionally leak ShootStates

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7784]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
In our landscapes we see leaked ShootStates resources without any associated Shoot.
With had a short look with @plkokanov and @rfranzke and noticed the following gap/flaw:
In the Shoot deletion flow, the ShootState is being deleted after the deletion of the Shoot namespace in the Seed. https://github.com/gardener/gardener/blob/ad6bbae73a100376ff6332e469633ba67554686d/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L637-L641

But we also have the following early exit in the beginning of the Shoot deletion flow - if the Shoot namespace in the Seed does not exist, then we early exit:
https://github.com/gardener/gardener/blob/ad6bbae73a100376ff6332e469633ba67554686d/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L81-L85
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/gardenlet/controller/shoot/shoot/reconciler.go#L872-L882

**What you expected to happen**:
No ShootState to be leaked.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot
2. Put a finalizer on the Infrastructure
3. Delete the Shoot
4. Stop gardenlet
5. Purge the Shoot namespace in the Seed
6. Start gardenlet
7. Make sure that the deletion succeeds but the ShootState leaks

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.68.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
Probably, `ShootStates` should be deleted by gardener-controller-manager. 
It should watch both `Shoot` and `ShootStates` and if it finds a `ShootState` with a missing `Shoot` or observed a `Shoot` deletion it should clean up the `ShootState`.

**Comment by plkokanov** [comment]
Yesterday we paired with @rfranzke on this issue. We basically removed the early exit that happens if the control plane namespace is deleted and made it so that the steps which depend on the namespace existing do not happen if it is already deleted. This way we can avoid similar problems that happen with the `ShootState` now to happen with other resources in the future. I still need to test the approach and can open a PR with the changes.

**Comment by plkokanov** [comment]
I noticed that another thing will be fixed by avoiding the early exit. With the early exit if the control plane namespace does not exist, there is a chance for this code to not get executed if the flow errored right after the namespace was deleted:
https://github.com/gardener/gardener/blob/74439fb075785b7c1c02a4e5d9843d95a3bca774/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L654-L658
