### ISSUE TITLE
[API] Improve worker pool sizing for zones

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#8142]
**How to categorize this issue?**

/area usability
/area high-availability
/kind enhancement
/kind api-change

**What would you like to be added**:
The Shoot API should be extended to allow worker pool configuration values which are considered **per zone**. 

_Proposal_:

```
spec:
  providers:
    workers:
    - name: pool-1
       zones:
       - a
       - b
       - c
       zoneConfiguration: # <-- new structure that allows to specify per zone values
         minimum: 20
         maximum: 100
         maxSurge: 5
         maxUnavailable: 0
```

Provider extensions are supposed to create `MachineDeployment`s for each zone and take the values as is, as opposed to today, where  `minimum`, `maximum`, `maxSurge` and `maxUnavailable` are fairly distributed over zones (see https://github.com/gardener/gardener/pull/8125).

_Introduction of API change_:

ℹ️ We may deliver this (enforced) change in the scope of the support for a new Kubernetes version, e.g. `1.28`. 

_Existing shoots:_
1. If shoot doesn't use `zones`, nothing will change. Setting `zoneConfiguration` will be denied.
2. If `zones` configuration of worker pools remain unchanged, nothing will change. (This is especially important for Gardener's maintenance controller which can still forcefully upgrade clusters w/o resizing the workers. Also users who properly sized their pools are not affected by any incompatible change.)
3. If a new zone is added to `zones`, setting `zoneConfiguration` AND unsetting `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable` will be required. (This will tell users to reconsider the pool size when adding new zone(s).)
4. Users can configure `zoneConfiguration` anytime (proactively) but must unset `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable`.

_New Shoots:_
1. If shoot doesn't use `zones`, nothing will change. Setting `zoneConfiguration` will be denied.
2. If shoot uses one or multiple `zones`, then setting `zoneConfiguration` is required. Configurig `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable` will be denied.
3. Users can configure `zoneConfiguration` anytime (proactively) but must unset `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable`.

**Why is this needed**:
Users are confused and surprised by Gardener's handling of `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable`.
The situation can become quite serious if these values are configured without knowing that they are divided by the number of zones of the affected worker pool.
For instance, the worker pool size can suddenly become too small when a new zone is added or some `MachineDeployment`s can even be created with `maxSurge: 0` which means a 1:1 machine replacement (see https://github.com/gardener/machine-controller-manager/issues/798).

**Comment by ScheererJ** [comment]
@timuthy Why do we want to prevent usage of `zoneConfiguration` for new clusters without `zones`? Would it not be more consistent to enforce usage of `zoneConfiguration` (and consequently deny usage of the old attributes) for all new clusters so that at least new clusters all have the same configuration?
While allowing zone-less clusters to use the old approach might seem like an improvement with regards to compatibility, i.e. not getting personal feedback from your stakeholders ;-) , I feel that it enforcing the change for zonal cluster just reduces the amount of affected clusters, but still might cause unhappy stakeholders.

**Comment by timuthy** [comment]
> While allowing zone-less clusters to use the old approach might seem like an improvement with regards to compatibility

Compatibility wasn't the primary motivation for the approach in question. I rather have the impression that it's inconsistent to configure values for zones where there are no zones at all.

**Comment by ScheererJ** [comment]
> Compatibility wasn't the primary motivation for the approach in question. I rather have the impression that it's inconsistent to configure values for zones where there are no zones at all.

I would argue that all clusters with nodes have at least one zone ;-) .

From my perspective, your approach will lead to both APIs for specifying max/min/... being used forever as long as there are clusters specifying no zones. The other approach would lead to only one API being used for new clusters and old clusters eventually moving to the new approach when worker groups are changed. While it does not guarantee eventual removal of the old API it seems to move faster in that direction. However, this might come at the price of forcing change on cluster owners.

**Comment by timuthy** [comment]
> The other approach would lead to only one API being used for new clusters and old clusters eventually moving to the new approach when worker groups are changed.

Totally agree, that would in general be much nicer 👍 

> I would argue that all clusters with nodes have at least one zone ;-) .

Can't really agree with that one. An availability zone is a specific concept that your provider and region needs to support, see Azure for instance where not all regions offer zones ([ref](https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies)). Gardener explicitly allows non-Zone use-cases and also API-wise everything that is zone related, is optional (see [example](https://github.com/gardener/gardener/blob/be26caebee05992186cce49f1f2778959ef2168f/example/90-shoot.yaml#L129)).

We can think of a better naming for `zoneConfiguration` that would fit both cases, though.

**Comment by vlerenc** [comment]
Thanks for inviting me @timuthy. As you know from https://github.com/gardener/machine-controller-manager/issues/798#issuecomment-1463559061, I am very much in favour in per-zone settings and suggested something like `minMachinesPerZone`, `maxMachinesPerZone`, `maxSurgeMachinesPerZone`, `maxUnavailableMachinesPerZone` to resolve the ambiguity. Your proposal is different and another option. There are a few more like putting the sums under the zones or introducing a boolean that distinguishes between global and per-zone.

```yaml
workers:
  maximumPerZone: 5
  minimumPerZone: 3
  maxSurgePerZone: 1
  maxUnavailablePerZone: 0
  ...
```

```yaml
workers:
  zoneConfiguration:
    minimum: 20
    maximum: 100
    maxSurge: 5
    maxUnavailable: 0
  ...
```

```yaml
workers:
  zoneConfiguration:
    - zone: europe-west1-a
      maximum: 5
      minimum: 3
      maxSurge: 1
      maxUnavailable: 0
    - zone: europe-west1-b
      ...
```

```yaml
workers:
  configurationPerZone: true
  ...
```

Personally, I would love to drop the old way - ideally without any left-overs. In that sense `zoneConfiguration` would become a relict eventually, but the last option wouldn't. It may be less clear/more painful though to go with such a boolean (last option) whose default is switched with `1.28` out of the sudden, though. 🤔

**Comment by timuthy** [comment]
> Your proposal is different and another option.

I've actually never considered it much different to `minMachinesPerZone`, `maxMachinesPerZone`, ... 🤔 The only difference is that it places these fields underneath a new struct `zoneConfiguration`.

> In that sense zoneConfiguration would become a relict eventually, but the last option wouldn't. 

Why would it become a relict, can you explain? As mentioned in https://github.com/gardener/gardener/issues/8142#issuecomment-1602678520, we can also think of a different name to cover providers (or regions) with and providers without zones (avoid mentioning anything with 'zone' in new struct), e.g.

```
workers:
  capacity: <-- This will become the new way to configure the worker pool.
    minimum: 20
    maximum: 100
    maxSurge: 5
    maxUnavailable: 0
```

> It may be less clear/more painful though to go with such a boolean (last option) whose default is switched with 1.28 out of the sudden, though.

+1
I'm also not in favor of the boolean approach.

**Comment by vlerenc** [comment]
> Why would it become a relict

@timuthy Well, would we have had this per-zone thinking in mind right from the beginning, we would not have introduced an intermediate level (`zoneConfiguration` or `capacity` or anything else). In that sense, what we do here is to work around/patch this old decision. When we are through, some things are configured right below workers (e.g. OS, disk, etc.) while some other things like the sums will be configured below `zoneConfiguration` (or `capacity` or anything else).

Then let's find a good name that wraps these 4 numbers (sums).

However, I am definitely with @ScheererJ on his viewpoint:

> I would argue that all clusters with nodes have at least one zone ;-) .

Whether or not the provider calls it "zone", the machines need to run somewhere, in a DC (=often called „zone“), on physical hardware.

Also, if we omit the little word "zone" that probably most people will have no trouble understanding, we drop one other main advantage of this field: Give people more (unambiguous) clarity on how the numbers are interpreted.



So, from the discussion, I understood, there is a middle ground. @timuthy You are in favour of the intermediate level and you are OK to make it the new norm for all clusters (contrary to the initial description) and not only the new norm for zone-based clusters, which would be more favourable for @ScheererJ and me (I’d also prefer only one way). For me, to even less see that as a relict later, it would help to find a name that includes the "category" of these 4 numbers (which "justifies" them being on an intermediate level) and the word "zone" (because that is very helpful to understand what happens with these numbers).

So, how about `capacityPerZone` or something similar?

The adapted description would therefore become:

_Existing shoots:_
1. If shoot doesn't use `zones`, nothing will change. ~~Setting `capacityPerZone` will be denied.~~ If `capacityPerZone` is not set, the “old way” remains supported.
2. If `zones` configuration of worker pools remain unchanged, nothing will change. (This is especially important for Gardener's maintenance controller which can still forcefully upgrade clusters w/o resizing the workers. Also, users who properly sized their pools are not affected by any incompatible change.)
3. If a new zone is added to `zones`, setting `capacityPerZone` AND unsetting `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable` will be required. (This will tell users to reconsider the pool size when adding new zone(s).)
4. Users can configure `capacityPerZone` anytime (proactively) but must unset `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable`.

_New Shoots:_
~~1. If shoot doesn't use `zones`, nothing will change. Setting `capacityPerZone` will be denied.~~
2. ~~If shoot uses one or multiple `zones`, then~~ Setting `capacityPerZone` is required. Configurig `workers[].minimum`, `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable` will be denied.
~~3. Users can configure `capacityPerZone` anytime (proactively) but must unset `workers[].minimum`, 
 `workers[].maximum`, `workers[].maxSurge` and `workers[].maxUnavailable`.~~

**Comment by unmarshall** [comment]
> **I would argue that all clusters with nodes have at least one zone ;-) .**
> Whether or not the provider calls it "zone", the machines need to run somewhere, in a DC (=often called „zone“), on physical hardware.

This is a valid argument. A zone is an isolated set of one or more data-centers where resources are provisioned. Almost all provides also provide fault tolerance within the same as well (az - via AvailabilitySet/VMSS and aws - spread placement groups/cluster placement groups). Now if you have more than 1 zone then your quality of service (availability) only gets enhanced. However a concept of single zone is still valid which comes with a different high-availability guarantees.

>So, how about capacityPerZone or something similar?

This still only offers a single configuration that gets applied to all zones. Having per-zone configuration is quite flexible and allows for consumers to down-scale some zones and upscale other zones. They would probably do this due to capacity constraints in one zone which prevents from launching further VMs of a given type.

If no zone configuration is chosen then you can use the existing logic of equitable distribute of VMs across all zones specified and also mutate the shoot to reflect this distribution and make it explicit by creating 3 zone-configurations. This not only makes the distribution explicit but also gives a handle to the consumer to change it if they wish to at a later point in time.

**Comment by vlerenc** [comment]
> This still only offers a single configuration that gets applied to all zones.

Yes, that would be the improvement that was sought (no magic divisions and remainders anymore), but I see that you would like to go beyond, which is more in line with proposal no. 3 up there (or similar):

```
workers:
  zoneConfiguration:
    - zone: europe-west1-a
      maximum: 5
      minimum: 3
      maxSurge: 1
      maxUnavailable: 0
    - zone: europe-west1-b
      ...
```

That was not yet in scope (until now).

> Having per-zone configuration is quite flexible and allows for consumers to down-scale some zones and upscale other zones. They would probably do this due to capacity constraints in one zone which prevents from launching further VMs of a given type.

That's a valid point for people that like to take it into their own hands/do not rely or are not as happy with the expander approach. Would you say, our stakeholders would welcome that over the expanders? I also ask, because you know what will happen to MCM/CA (where you will improve/change things).

After all, what people probably would prefer is not to duplicate the information per zone and let Gardener/MCM/CA be "smart" (fast and autonomous) about this (capacity issues, etc.). Only if we cannot satisfy them, we have no other option than to open that up, but it raises the bar (also in comparison to what the hyperscalers offer) and make things more complex, because they are configurable (flexibility has its good and bad sides).

Let's also invite Dieter into the discussion as many discuss with him/the landscape stability team as well. Any additional thoughts from your perspective @dguendisch?

**Comment by timuthy** [comment]
> After all, what people probably would prefer is not to duplicate the information per zone and let Gardener/MCM/CA be "smart" (fast and autonomous) about this (capacity issues, etc.). Only if we cannot satisfy them, we have no other option than to open that up, but it raises the bar (also in comparison to what the hyperscalers offer) and make things more complex, because they are configurable (flexibility has its good and bad sides).

+1
Also consider that a per zone configuration, as mentioned by @unmarshall, should similarly be possible by creating multiple worker pools with only one zone?! The configuration will become more complex (for sure) but still the option exists and would satisfy the small amount of users who want to configure/control their worker groups like this.

I generally like the summary from @vlerenc and at the moment would vote for the proposal in https://github.com/gardener/gardener/issues/8142#issuecomment-1607512159.

**Comment by vlerenc** [comment]
FYI: The MCM team discussed another option that would give more advanced configurability options to better serve the needs of the customers, especially those with resource capacity issues in particular zones. They'd like to give it some more thought (effort, complexity) for some days more.

**Comment by vlerenc** [comment]
Here @unmarshall proposal, based on another proposal by @himanshu-kun:

``` yaml
workers:
  zoneConfigurations:
    - zone: [europe-west1-a, europe-west1-b]
      maximum: 5
      minimum: 3
      maxSurge: 1
      maxUnavailable: 0
      machineTypes: [machine-type-1] # optional extension
    - zone: [europe-west1-c]
      maximum: 5
      minimum: 3
      maxSurge: 1
      maxUnavailable: 0
```

**Comment by timuthy** [comment]
I don't know if the design in https://github.com/gardener/gardener/issues/8142#issuecomment-1611194438 is complete or if something is missing.

We might be confronted with the following issues:

1. Today `workers` is a slice of `worker` objects. It won't be possible to add `zoneConfigurations` directly to `workers`.
2. If `zoneConfigurations` is intended like shown in the comment, then it won't be possible to configure these values per worker group and lacks the use-case where shoots have multiple worker groups with the same machine type in the same zone(s).
3. If `zoneConfigurations` became part of the `worker` struct, we shouldn't offer `machineTypes` since a worker pool can only handle one machine type.

**Comment by unmarshall** [comment]
> Today workers is a slice of worker objects. It won't be possible to add zoneConfigurations directly to workers

What we (Vedran with the MCM team where this proposal was made) was a different representation for only `zonalConfiguration`. You are right that it is not complete and its incorrectly placed under workers.
The complete proposal is as follows:
```yaml
spec:
  providers:
    workers:
    - name: pool-1
        zoneConfigurations:
        - zones: [europe-west1-a, europe-west1-b]
           maximum: 5
           minimum: 3
           maxSurge: 1
           maxUnavailable: 0
        - zones: [europe-west1-c]
           maximum: 10
           minimum: 2
           maxSurge: 2
           maxUnavailable: 1
```
**Advantages:**

- Provides a capability for zone specific configuration
- No duplication of zones. If all zones have the same max, min, maxSurge and maxUnavailable then you just need to have a single entry under zoneConfigurations array with zones initialised with all zones.
- You can even offer a simplified view for setting these configurations via the dashboard. If the customers choose to not set different configurations per zone, simple options can be provided allowing the customer to choose - if same configuration should be applied to all zones or one configuration should be distributed across all zones (current default). They can optionally add additional zone specific configurations if they choose to (which the power users would probably opt for).

**Additional points:**
* For all new shoots we can go with this configuration format.
* For existing shoots existing `workers[].minimum, workers[].maximum, workers[].maxSurge and workers[].maxUnavailable` can be transformed into corresponding `zoneConfiguration` using equitable distribution logic (that is the default).

**Machine Type(s)**
Coming to your last point. 
>we shouldn't offer machineTypes since a worker pool can only handle one machine type.

Yes that is true today. We are only limited by the cluster-autoscaler as of today. CA does not support a node group with more than one machine type. A pool with 3 zones will create 3 machine-deployments which will correspond to 3 node groups (in CA). A straight-forward mapping like this means that you can already have 1 machine-type per node-group which translates back to have 1 machine-type per zone. Therefore this is quite possible.

Coming to a question of supporting multiple machine types per zone - this would be a bit tricky (can be technically done though) but we need to see if this adds value and compare it against the cluster-autoscaler's expander facility. Therefore for now i would keep that out. 

> NOTE: In the discussion with Vedran this was an idea which was briefly discussed because he had mentioned quite a while back that Ali cloud provides consumers to provide more than one machine type and it was quite easy to consume. Having dedicated zonal configurations only opens the door at a later point of time to consider these things as possibilities.

**Comment by vlerenc** [comment]
/blocked

Let's wait for the discussion in https://github.com/gardener/gardener/pull/8593.

Also, after some discussion, it seems that per-zone configuration is not necessarily ideal: in case a zone is down and the workload doesn't mind (e.g. no preventive topology spread constraints, etc.), CA may try to stack up a broken zone until it goes into back-off or might even never stack up the other zones if the total maximum has been reached. So, the approach can be too rigid, even if the workload would be flexible.

**Comment by timuthy** [comment]
> CA may try to stack up a broken zone until it goes into back-off or might even never stack up the other zones if the total maximum has been reached. So, the approach can be too rigid, even if the workload would be flexible.

Can you make an example? I don't get the point what would be the difference between `regional` and `zonal` values in case of an zone outage and the behavior of CA.

**Comment by vlerenc** [comment]
In a sample size of 6568 clusters, I see:
- pools in total: 22407 (342%)
- pools with no scale: 3926 (18%)
- pools with scale: 18481 (82%)
- pools with scale from zero: 11507 (51%)
- pools with scale from warm: 1153 (5%)
- pools with percentage surge=12671 (57%)
- pools with inadequate surge=2970 (13%)
- pools with allowed unavailable=96 (0%)
- pools with inadequate unavailable=65 (0%)

This shows a few things:
- People make good use of multiple worker pools and also the auto-scaling feature (more than half use percentages even), with about half scaling from zero, so we hit a nerv here.
- Only few people use `minimum` for warming up worker pools before the cluster creation finishes. Those who do, run the risk of overpaying/running underutilized machines, if load drops. Headroom, if that's the intent, is best provided with excess capacity pods like we do (minimum number of machines gives little to no guarantees with varying load).
- Almost nobody uses `maxUnavailable` (looking deeper, those who do, set it to 1 and never anything else), so that's of little use to our users.
- At least 13% of people set `maxSurge` (and most who use `maxUnavailable`) probably wrong (more than 0, but less than the number of zones, i.e. mostly 1). The dark figure may be a lot higher, though.

**Comment by vlerenc** [comment]
> So, it appears to me as if maximum is better left regional and only maxSurge and maxUnavailable make much more sense to be looked at in a zonal way.

After pondering on the subject matter again, I think my statement in regards to maxSurge and maxUnavailable is suboptimal:
- The user doesn't really care too much where `maxSurge` is added (which zone) as long as her quota is met, which is regional, not zonal. We care, but only because we technically mapped a zone to a machine deployment. If not/we would be free, `maxSurge` should probably remain regional, but be enforced across all machine deployments for a worker pool (or we find a way in the future to handle machine deployments completely different). So, from API PoV, making a zonal setting out of it feels wrong. Both, because of the way how quotas are set and what the user actually wants.
- `maxUnavailable` is something that I would rather kill, but we probably have it because that's what Kubernetes deployments and other cloud providers have. It is probably true, that this setting (only this) is best interpreted per zone, but almost nobody used it in the above sample and I have a hard time seeing why I ever would (it's safer to go with surge).

Hence, I am wondering whether we are asking the wrong question and the right question should rather be:
`maxSurge` and `maxUnavailable` are relevant only during worker pool upgrades, so let them be regional (and apply them fully to all machine deployments, i.e. without division by the number of zones), but run the worker pool upgrades zone by zone. WDYT?

That would be much more in line with the thinking of our users/make more sense and be safer:
- we wouldn't, by chance, drain nodes in multiple zones that run pods with co-dependencies that would block the roll-out
- it would be more predictable/less chaotic and give users much better means to pause a roll-out should they see something go haywire in one zone

**Comment by oliver-goetz** [comment]
I prefer true regional properties for `maximum`, `minimum`, `maxSurge`, `maxUnavailable`.
At the moment worker groups with 3 zones are the same as 3 worker groups with one zone which are sharing the same settings. This might work most of the time, but introduces a strange behavior in edge cases, because it is not transparent for the user that we simply divide all values by the number of zones.
Some "strange" behaviors I noticed are:
- The `maximum` of a worker cannot be exhausted when one zone is lacking of machines with the given machine type (about the same thing @vlerenc described before)
- When nodes are unevenly balanced between the zones, rolling the nodes can be slower than expected because `maxSurge` cannot be exhausted

Running worker pool upgrades zone by zone as @vlerenc suggested might help mitigate my last issue when everything runs smoothly. However, there is still a price 😅 One node which is stuck in drain could block the rollout of the entire worker group, because it could not proceed with the next zone. If there are Pods with high termination grace periods spread across three zones, this could triple the time for rolling the worker group.

We cannot pause rollouts atm., couldn't we?

**Comment by vlerenc** [comment]
@oliver-goetz Yes, this has disadvantages. Another that @unmarshall brought up is that a zone may be out of resources - that would also block things. Just saying, you are both right. That being said, also services like [GKE do just that](https://cloud.google.com/kubernetes-engine/docs/concepts/node-pool-upgrade-strategies), they run zone by zone and don't care. I am not saying, it's OK to lower our service qualities, but it would make it simpler and less chaotic/more predictable (it has also advantages).

@oliver-goetz Yes, [we have `pause`](https://github.com/gardener/machine-controller-manager/blob/master/docs/FAQ.md#How-to-pause-the-ongoing-rolling-update-of-the-machinedeployment), just not exposed to end-users, but we discussed making that available to end users (not sure what the status is on that, though).

**Comment by timuthy** [comment]
> @oliver-goetz Yes, this has disadvantages. Another that @unmarshall brought up is that a zone may be out of resources - that would also block things. Just saying, you are both right. That being said, also services like [GKE do just that](https://cloud.google.com/kubernetes-engine/docs/concepts/node-pool-upgrade-strategies), they run zone by zone and don't care.

Isn't that something we could optimize, .e.g. the error would be detected, the rollout in that zone paused and the next zone is picked for rolling update?
This would probably mean to make `MachineDeployment`s multi-zone aware and MCM optimizes the rollout for whatever cases we see.

**Comment by vlerenc** [comment]
> Isn't that something we could optimize, .e.g. the error would be detected, the rollout in that zone paused and the next zone is picked for rolling update?

Just a comment: I don't think GKE deals with it this way. Wrong what I understand, they strictly go zone by zone.

To your question, what would "detection" mean here? If a PDB is violated, is that already a reason to jump to the next zone? Probably not. Yet, if it happens, we do not know how long it will take. Or if we get an error that a machine type is out of stock. Who says, it will fail another time or that it will work in another zone.

It's probably really hard to make that decision.

Even if, what happens with what is currently in-flight? Or can we leverage that? If every node that is in-flight is considered blocked, we go to the next zone, but then we mix again or what are we doing with the blocked nodes?

I am not sure I can see all cases, so I would think, it's either what we have today (separate, parallel rolling updates) or the GKE model (strictly zone by zone). Not sure... :-/
