### ISSUE TITLE
Guard against illegal cloud profile modifications

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#82]
As discussed in #14 @rfranzke noted that we should prohibit illegal cloud profile modifications, e.g. dropping a Kubernetes version or machine type while a shoot cluster still uses it. So let's write a small admission controller that prevents that in general (droppings/modifications) or that prevents that only from happening if there are clusters still using it (otherwise allows it).

**Comment by rfranzke** [comment]
As @mandelsoft suggested (and that's how it's implemented right now; similar to what we (@vlerenc) discussed about yesterday): Instead of preventing the CloudProfile from removing values in the constraints which are still in use by any Shoot, we should rather adapt the existing ShootValidator admission plugin. With this commit the following behaviour is implemented: When a field `X` in a Shoot manifest is changed to value `Y`, the operation will only succeed if `Y` is part of the referenced CloudProfile. For existing Shoots whose field `X` has another value that is not part of the CloudProfile, updating other fields different than `X` does not prevent the request from succeeding (like it was before). This allows us to remove old entries from the CloudProfiles (so that no new Shoots can use old values).
