### ISSUE TITLE
`BackupBucket` is not reconciled, when `ManagedSeed` is annotated with `gardener.cloud/operation=reconcile`

### ISSUE THREAD

**Issue by hendrikKahl** [gardener/gardener#8256]
**How to categorize this issue?**

/area backup
/kind bug

**What happened**:
As part of a credentials rotation exercise, I updated the `secret`, which holds the credentials used by a `backupbucket` in the garden. The `backupbucket` belongs to a `managedseed`, which I subsequently reconciled using the annotation ` gardener.cloud/operation=reconcile`. 

The operation was performed and the annotation removed. However the `secret` on the actual `seed` was not updated. 

Only when I annotate the `backupbucket` with ` gardener.cloud/operation=reconcile`, the data is replicated properly.

**What you expected to happen**:
When I update the `backupbucket` secret in the garden and reconcile the `managedseed`, I would expect the credentials to be updated on the `seed` as well.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a managedseed with dedicated credentials for the backupbucket 
- change the credentials in the secret
- reconcile the managedSeed
- check the respective secret on the seed (garden namespace)

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.74.1
- Kubernetes version (use `kubectl version`):  v1.24.14

**Comment by shafeeqes** [comment]
The solution is not very straightforward; the `ManagedSeed` reconciliation reconciles the seed secrets and deploys the gardenlet, but doesn't trigger the reconciliation of the seed itself (Unless gardenlet is updated in which case it restarts and starts the reconciliation). 
- In case of restart, the `BackupBucket`s are also reconciled, but those reconciliations are spread across random durations within 24h. We could add the operation annotation for the `BackupBucket` here and trigger an immediate reconciliation, https://github.com/gardener/gardener/blob/9643ea5fa3b8207f1722f014489b54a08521a773/pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go#L726
which will also only work if the seed itself is reconciled.
- We cannot annotate the `BackupBucket` during the `ManagedSeed` reconciliation flow because the parent gardenlet doesn't have the permissions to patch the `BackupBucket` of the child seed.
- We cannot watch for the referred secrets and reconcile the corresponding BackupBuckets because the gardenlet cannot list all the secrets in the garden namespace but only the ones which are related to that seed.

**Comment by rfranzke** [comment]
@shafeeqes Can the parent `gardenlet` annotate the `Seed` related to the `ManagedSeed`? If so, we could make the child `gardenlet` reconcile its `BackupBucket` as part of the `Seed` reconciliation when there is a special annotation requesting for it?

**Comment by shafeeqes** [comment]
> Can the parent gardenlet annotate the Seed related to the ManagedSeed?

No, that's also not allowed.

**Comment by rfranzke** [comment]
Well, then I guess we don't have much handle here other than asking the operator (@hendrikKahl) to also add the `reconcile` operation annotation to the `BackupBucket`. WDYT?

**Comment by hendrikKahl** [comment]
Fine with me. Thanks for checking ❤️ 
/close

**Comment by timuthy** [comment]
@shafeeqes out of curiosit, would it help if we had the `resourceVersion` of the backup secret in the `seedConfig`?

**Comment by timuthy** [comment]
IMHO, this is not a nice user experience and even an undocumented procedure.

> We cannot watch for the referred secrets and reconcile the corresponding BackupBuckets because the gardenlet cannot list all the secrets in the garden namespace but only the ones which are related to that seed.

We could if we synced the secret to the `seed-*` namespace like already done for other resources.

**Comment by shafeeqes** [comment]
/reopen
https://github.com/gardener/gardener/issues/8256#issuecomment-1653550559 seems achievable.
