### ISSUE TITLE
Zone pinning not working for volumes in `Immediate` binding mode

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#8563]
**How to categorize this issue?**

/area cost
/area performance
/area high-availability
/kind bug

**What happened**:
Gardener adds `nodeAffinity` terms to control-plane pods (aka zone pinning, [ref](https://github.com/gardener/gardener/blob/master/docs/development/high-availability.md)).

The current implementation doesn't work well if there is a storage class with `volumeBindingMode: Immediate` ([ref](https://github.com/gardener/gardener-extension-provider-aws/pull/597)). Volumes are created in a random zone, the pods' `nodeAffinities` are disregarded -> zone pinning breaks.

**How to reproduce it (as minimally and precisely as possible)**:
Create shoot clusters on seeds with a `default` storage class with `volumeBindingMode: Immediate`.

**Environment**:

- Gardener version: v1.80.0

**Comment by rfranzke** [comment]
We discussed this today in a call, and one idea was to enhance validation in `etcd-druid`'s `Etcd` controller to ensure the referenced `StorageClass` (or the default `StorageClass`, if none is provided explicitly) uses the `WaitForFirstConsumer` binding mode. This would make the `Etcd` reconciliation fail and prevent volumes from getting created in random zones.
We cannot validate this in the `gardenlet'`s `Seed` controller since most provider extensions inject the storage class name during creation of the `Etcd` resource, so `gardenlet` cannot know it upfront.

**Comment by timuthy** [comment]
@gardener/etcd-druid-maintainers WDYT?

**Comment by unmarshall** [comment]
I agree that we should have the validation to check if the referenced `StorageClass` uses `WaitForFirstConsumer`. I checked the azure cluster that i have created on dev and noticed that it already uses `WaitForFirstConsumer`
```
gardener.cloud-fast    kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   363d
```
We also have an open issue [druid#409](https://github.com/gardener/etcd-druid/issues/409) in druid raised by @timuthy and we have planned to work on it as well. We can include this validation as part of [druid#409](https://github.com/gardener/etcd-druid/issues/409).

**Comment by timuthy** [comment]
Thanks for the feedback @unmarshall. If you already have a separate issue where process is tracked, I suggest to close this one.
/close
