### ISSUE TITLE
Possibility of `etcd-backup` secret to get deleted during shoot creation

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#8675]
**How to categorize this issue?**

/area backup
/kind bug

**What happened**:
It seems during shoot creation that it is possible for the `etcd-backup` secret to get deleted by an expiring `BackupEntry` created from prior shoot deletion . This makes the cluster to get stuck on the `Deploying main and events etcd` task

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Add `deletionGracePeriodHours: 24` in `charts/gardener/gardenlet/values.yaml`
``` yaml
  controllers:
    backupBucket:
      concurrentSyncs: 20
    backupEntry:
      concurrentSyncs: 20
      deletionGracePeriodHours: 24
```
2. In local setup add a fake task delay `time.Sleep(15 * time.Second)` on first line of `DeployEtcd `
https://github.com/gardener/gardener/blob/694b88c048001eee0572f310001b8ebf82a0436d/pkg/operation/botanist/etcd.go#L98-L99
3. Create and delete a cluster for a `core.gardener.cloud/v1beta1.BackupEntry` to remain
4. In a different window run `watch k -n shoot--local--local get secret etcd-backup`
5. On another terminal edit the `BackupEntry` from step 3 with `backupentry.core.gardener.cloud/force-deletion: "true"` but don's save the change yet
7. Create a cluster
8. When `etcd-backup` appears on the terminal save the change from step 5 (run `:wq` in vim). This will simulate an expiration of the `BackupEntry`
9. After max 1 sec `etcd-backup` will dissapear
10. Shoot creation will get stuck on this line
https://github.com/gardener/gardener/blob/694b88c048001eee0572f310001b8ebf82a0436d/pkg/operation/botanist/etcd.go#L102-L104

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by Kostov6** [comment]
Thinking about this issue is there a reason for the deletion of `extensions.gardener.cloud/v1alpha1.BackupEntry` to delete `etcd-backup` secret? Because a gardenlet with `deletionGracePeriodHours` config won't delete immediately `core.gardener.cloud/v1beta1.BackupEntry` -> won't delete `extensions.gardener.cloud/v1alpha1.BackupEntry` -> won't delete `etcd-backup`. But `etcd-backup` gets deleted anyways, so there is a second mechanism of it's deletion beside the deleion of `extensions.gardener.cloud/v1alpha1.BackupEntry`

**Comment by plkokanov** [comment]
A long time ago we modified the logic in `extensions.gardener.cloud/v1alpha1.BackupEntry` so that the `etcd-backup` secret is always deleted in: https://github.com/gardener/gardener/pull/4894
During the restore phase of control plane migration there are two `extensions.gardener.cloud/v1alpha1.BackupEntry`s which get deployed - one with prefix `source-` which is used to create a `source-etcd-backup` secret and one without a prefix used to create the `etcd-backup` secret.
The `source-etcd-backup` secret contains the access secret for backup bucket of the source seed and the `etcd-backup` secret contains the access secret for the backup bucket of the destination seed. These secrets are used by `EtcdCopyBackupsTask` which performs a copy of etcd data from the source bucket to the destination bucket.
After the copy is performed we have to get rid of the `source-etcd-backup` secret for security reasons. This is why that secret is deleted when the corresponding source `extensions.gardener.cloud/v1alpha1.BackupEntry` is deleted.

Because we didn't want to make the handling of these secrets "special" only for the case when the `extensions.gardener.cloud/v1alpha1.BackupEntry` contains the `source-` prefix we decided to delete the secrets in all cases. Changing this would be the least complex fix.

**Comment by ialidzhikov** [comment]
Some possible approaches that we discussed today:
1. There is the suggestion to delete secret only if has the `source-` prefix and to leave the etcd-backup - ref https://github.com/gardener/gardener/issues/8675#issuecomment-1776971768. We all agreed that it is hacky approach that was avoided back then.
2. We could change to name of the etcd-backup Secret to include the BackupEntry name/UID. We need to check how to make this backwards-compatible.
3. We could maintain annotation (or ownerReference) on the etcd-backup Secret about which BackupEntry is its owner. Respectively, on BackupEntry deletion, it would delete the etcd-backup Secret if it is the Secret owner.

Maybe 3. would be the easiest option to implement.
@rfranzke @shafeeqes WDYT?

---

Just for the record, we wouldn't observe this issue if we reconcile the extension.BackupEntry every time the core.BackupEntry is reconciled. See https://github.com/gardener/gardener/blob/cf2e024732cfb42e341be78f261c5102b9a7edbc/pkg/gardenlet/controller/backupentry/reconciler.go#L228-L231.
Currently, if the extension.BackupEntry is in Succeeded state, we won't trigger its reconciliation.

**Comment by shafeeqes** [comment]
> Just for the record, we wouldn't observe this issue if we reconcile the extension.BackupEntry every time the core.BackupEntry is reconciled.

Yeah, this was intentional not to reconcile the extension backupentry and cause unnecessary cloud API calls.

> Maybe 3. would be the easiest option to implement.

In this case, the secret will get deleted right after the backupEntry gets the `deletionTimestamp`, right? I am asking since we have a deletion grace period for the backupentry.

**Comment by ialidzhikov** [comment]
> In this case, the secret will get deleted right after the backupEntry gets the `deletionTimestamp`, right? I am asking since we have a deletion grace period for the backupentry.

The proposal is not to change when the `etcd-backup` Secret gets deleted. The proposal is to add an annotation to the `etcd-backup` Secret that denotes which BackupEntry is the owner of the Secret. Then the BackupEntry deletion logic has to be adapted to delete the `etcd-backup` Secret only it is the owner of the Secret. In this way we will prevent a BackupEntry scheduled for deletion from the Shoot in the past to delete the `etcd-backup` Secret of the already new Shoot (with the same name).
