### ISSUE TITLE
Leaked ManagedResource `extension-controlplane-shoot-webhooks` might prevent shoot deletion

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#8688]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
It is possible between gardenlet's tasks `Waiting until shoot control plane has been destroyed` and `Waiting until shoot managed resources have been deleted` in shoot deletion flow an extension's  `webhook-certificate` to create `extension-controlplane-shoot-webhooks` MR
https://github.com/gardener/gardener/blob/00365d6c0fa6fb9053dec6f1e2fa489c53ef53cc/extensions/pkg/webhook/certificates/reconciler.go#L196-L198
This will prevent shoot deletion

**How to reproduce it (as minimally and precisely as possible)**:
1. Manually crash `waitUntilControlPlaneDeleted `
``` golang
		waitUntilControlPlaneDeleted = g.Add(flow.Task{
			Name: "Waiting until shoot control plane has been destroyed",
			Fn: flow.TaskFn(func(ctx context.Context) error {
				time.Sleep(5 * time.Second)
				return fmt.Errorf("Fake error")
				//return botanist.Shoot.Components.Extensions.ControlPlane.WaitCleanup(ctx)
			}).SkipIf(o.Shoot.IsWorkerless),
			Dependencies: flow.NewTaskIDs(destroyControlPlane),
		})
```
2. Comment this line
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/extensions/pkg/webhook/shoot/webhook.go#L115
``` golang 
	log.Info("Continuing as in local setup there is no expected netpol")
	//return nil
```
3. Create and delete a local shoot
4. Watch for `extension-controlplane-shoot-webhooks` MR

Task `Destroying shoot control plane` will delete  `extension-controlplane-shoot-webhooks` MR
Because `webhook-certificate` runs every 5 minutes it will eventually create `extension-controlplane-shoot-webhooks`

This demonstrates how an extension can create `extension-controlplane-shoot-webhooks` between a tight time period when it is expected to not exist

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by Kostov6** [comment]
Would adding the following logic be sufficient to solve the issue?
`webhook-certificate` would deploy `extension-controlplane-shoot-webhooks` in a given namespace only if a controlplane object is present in the given namespace?

**Comment by plkokanov** [comment]
Hmm, isn't the  `extension-controlplane-shoot-webhooks` only edited by this reconciler if it already exists:
https://github.com/gardener/gardener/blob/f8ab20df60635d783ccac3d103f89e04490fca0c/extensions/pkg/webhook/shoot/webhook.go#L103-L110
This function should return nil if the mr was deleted or not created yet.

This code was changed 3 weeks ago in https://github.com/gardener/gardener/pull/8540 Can you still reproduce it from the master branch? The links that you posted are from older commits: https://github.com/gardener/gardener/commit/00365d6c0fa6fb9053dec6f1e2fa489c53ef53cc (from September 6th) and https://github.com/gardener/gardener/commit/5abed1bfedd6f2188e5dcec9af161d1b5c286236 (from March 3rd) respectively.

**Comment by plkokanov** [comment]
I think what @Kostov6 means is that:
1.  the `webhook-certificate` reconciler can get to here: https://github.com/gardener/gardener/blob/f8ab20df60635d783ccac3d103f89e04490fca0c/extensions/pkg/webhook/shoot/webhook.go#L105 while CP is being deleted, but MR still exists so the `Get` call will actually return the MR
2. The CP finishes the deletion and the MR is removed.
3. The function from 1 continues its execution and eventually gets to here https://github.com/gardener/gardener/blob/f8ab20df60635d783ccac3d103f89e04490fca0c/extensions/pkg/webhook/shoot/webhook.go#L71 
which recreates the MR

There should be a very slim chance of that happening though. 

I'm not sure if preventing the `webhook-certificate` reconciler from doing its job while the shoot has a deletion time stamp won't cause other issues (it probably will if the deletion runs for a longer time due to earlier errors).

Additionally, I don't think that simply checking the `ControlPlane`'s deletion timestamp is too good as well, since this code seems can potentially be used to uppdate other MRs for other webhooks/extensions. For instance, this reconciler is used by the gardener-operator, although due to all the `ifs` this exact functionality is not called.

**Comment by timuthy** [comment]
Thanks for the explanation @plkokanov.

IIUC, the issue is that the `webhook-certificate` reconciler handles (recreates) the entire MR whereas it should only patch out the CA it created/rotated. So, we might want to tackle the problem in the reconciler to only mutate the CA portion of the webhook.

**Comment by Kostov6** [comment]
This issue certainly proves that the if statement below is reachable I propose to handle it as follows:
In `extensions/pkg/webhook/shoot/webhook.go@ReconcileWebhookConfig`:
```go 
conrolplaneList := &extensionsv1alpha1.ControlPlaneList{}
if err := c.List(ctx, conrolplaneList, client.InNamespace(shootNamespace)); err != nil {
	return err
}

if cluster.Shoot.DeletionTimestamp != nil && len(conrolplaneList.Items) == 0 {
	// if we create the MR at this point 
        // a) cluster is guaranteed to get stuck in deletion
        // b) MR gets created after "Waiting until shoot managed resources have been deleted" step
        // Therefore now it is this reconcilers job to delete any unhandled MR and not create new one
	if err := managedresources.Delete(ctx, c, shootNamespace, managedResourceName, false); client.IgnoreNotFound(err) != nil {
		return err
	}
	return nil
}
if err := managedresources.Create(ctx, c, shootNamespace, managedResourceName, nil, false, "", data, nil, nil, nil); err != nil {
	return fmt.Errorf("could not create or update managed resource '%s/%s' containing shoot webhooks: %w", shootNamespace, managedResourceName, err)
}
```
What do you think about this solution? I've tested it manually locally and it does seem to work.
