### ISSUE TITLE
`etcd-druid` scraping job does not work

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#8831]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
`PrometheusCantScrape` alert is active because the `etcd-druid` job fails:

<img width="1366" alt="image" src="https://github.com/gardener/gardener/assets/40451181/c634e5f3-9d7d-4ee0-82e3-bcde7e727abe">

**What you expected to happen**:
The scraping job to work and the alert not being active.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot and check Prometheus frontend.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.84
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by istvanballok** [comment]
The control plane Prometheus federates the etcd-druid metrics from the "cache" Prometheus in the garden namespace. The cache Prometheus scrapes the shared etcd-druid component that runs in the garden namespace. The shared etcd-druid component takes care of all the etcd-s for all the shoots in the given seed.

Etcd-druid exposes metrics related to etcd compaction if the `--enable-backup-compaction` is set to true. Otherwise, it does not expose any relevant (allow listed) metrics if the backup compaction is not active.

The generic [PrometheusCantScrape](https://github.com/gardener/gardener/blob/2edac3255e8e27f8c3239da1e18b3d7e02258443/pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/rules/prometheus.rules.yaml#L6) alert checks if the given scrape (in our case the federation) worked (this works if the "cache" Prometheus is running) and at least a few metrics were received. If the backup compaction feature is not enabled, and hence no metrics are exposed and received, this alert will fire for the etcd-druid job.

We could prevent this by either acknowledging that we do not expect any etcd-druid metrics under some conditions (if the backup compaction is not enabled) and then we can "opt out" from the generic PrometheusCantScrape alert by filtering out the etcd-druid job (`up{   job!="etcd-druid"   }`) or preferably, by making sure that the etcd-druid exposes some valuable metrics even in that case.

I assume that the new `--enable-backup-compaction` feature is going to be turned on for all the landscapes eventually, which will "mitigate" this issue. In the meanwhile this alert will keep firing for all the shoots on landscapes where this feature is not yet turned on hence another mitigation is needed.

Exposing new and valuable metrics by the etcd-druid about the shoot control plane etcd-s unconditionally or opting out of the generic alert could be options to prevent these alerts. Opting out is probably easier (a g/g PR #8988 that adds the filter above) but might hide real issues in the future that the generic alert could have caught. Exposing new metrics might be more involved (come up with a meaningful metric, PR and release for etcd-druid, etc.). So, I'd suggest to opt out from the PrometheusCantScrape alert for the etcd-druid job for now.

cc @abdasgupta
