### ISSUE TITLE
Request thousands of KUBECONFIG at same time

### ISSUE THREAD

**Issue by chengshifan** [gardener/gardener#8975]
According to the description [here](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsadminkubeconfig-subresource), dynamical KUBECONFIG could be generated via 
```
expiration := 10 * time.Minute
expirationSeconds := int64(expiration.Seconds())
adminKubeconfigRequest := &authenticationv1alpha1.AdminKubeconfigRequest{
  Spec: authenticationv1alpha1.AdminKubeconfigRequestSpec{
    ExpirationSeconds: &expirationSeconds,
  },
}
err := client.SubResource("adminkubeconfig").Create(ctx, shoot, adminKubeconfigRequest)
if err != nil {
  return err
}
config = adminKubeconfigRequest.Status.Kubeconfig
```

My question is that is there any rate limit here ? Assume that we have thousands of clusters need to rotate kubeconfig at a same time, is gardener able to suffer that workload in a short time ? We don't expect any error caused by having so many creating request. Just confirm if gardener could suffer the workload.

Thanks in advance.

**Comment by rfranzke** [comment]
I don't think we can provide a reasonable answer since this depends on many aspects related to the respective Gardener installation, for example configuration of [API priority and fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/), the number of `gardener-apiserver` replicas, their resource requirements, the configured auto-scaling, etc.

Generally, the generation of an admin kubeconfig is somewhat CPU-intensive since it generates a client certificate, so doing this a lot of times in parallel will definitely increase the CPU consumption of the API server pods. However, with the "right tuning" of the Gardener system, all this should certainly be possible.

I'm closing this issue since I don't think there is anything concrete to follow-up with. Feel free to join our [Slack channel](https://kubernetes.slack.com/archives/CB57N0BFG) as well for further questions :)
/close
