### ISSUE TITLE
Support RBAC-based cluster access for extensions

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#8980]
**How to categorize this issue?**

/area security usability
/kind enhancement

**What would you like to be added**:
https://github.com/gardener/gardener/issues/8001 enabled access to the `virtual-garden` cluster for extensions with almost the same permissions of Gardenlet.
Some extensions deploy further components into seed clusters that need access to the `virtual-garden` cluster, as well. For them it's desirable to use a dedicated service account token as well as customizable permissions because the ones provided for the extension are either too restrictive or too open.

Implementation proposal / approach:
1. Operators apply a `ClusterRole` in the `virtual-garden` cluster with permissions the extension's components need
2. Extensions create additional `RequestToken` secrets for components
3. Extensions create a `ClusterRoleBinding` referring to the `ClusterRole` in [1.] and the service account resulted from `[2.]`
4. The `ClusterRoleBinding` creation is protected by the `SeedRestriction` admission plugin to prevent any privilege escalation

**Comment by rfranzke** [comment]
I looked into the proposal above, but I don't think it will work this way:

- In https://github.com/gardener/gardener/blob/master/docs/deployment/gardenlet_api_access.md#seedauthorizer-authorization-webhook-enablement, we recommend to put `Webhook` after `RBAC` for the `--authorization-mode` flag.
- With this, [step 3](https://github.com/gardener/gardener/issues/8980#issue-2048982693) will fail because the `RBAC` plugin might already deny the request:
  ```
  error: failed to create clusterrolebinding: clusterrolebindings.rbac.authorization.k8s.io "extension" is forbidden: user "system:serviceaccount:seed-local:extension-provider-local-8rp72" (groups=["system:serviceaccounts" "system:serviceaccounts:seed-local" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
  {APIGroups:["authorization.k8s.io"], Resources:["subjectaccessreviews"], Verbs:["create"]}
  ```

I would like to propose another implementation:

- Step 1 remains the same - a human operator creates a `ClusterRole` with the needed additional permissions, and they label it with `extensions.gardener.cloud/bindable-by=<extension-name>`, e.g. `extensions.gardener.cloud/bindable-by=provider-local`
- A new controller part of `gardener-controller-manager` watches `ClusterRole`s and all `ServiceAccount`s in seed namespaces which are prefixed with `extension-<extension-name>`, e.g., `extension-provider-local`.
- This controller maintains a `ClusterRoleBinding` for the respective `ClusterRole` that binds it to all `ServiceAccount`s in the seed namespace with the name prefix.
- With this, the permissions are clearly bound by a human operator, and there's no additional work for extensions in the seed clusters (except for maybe creating dedicated garden access secrets (i.e., dedicated `ServiceAccount`s)).

**Comment by timuthy** [comment]
> A new controller part of gardener-controller-manager watches ClusterRoles and all ServiceAccounts in seed namespaces which are prefixed with extension-<extension-name>, e.g., extension-provider-local.

To be sure, `extension-provider-local` is still the prefix here, i.e. the actual `ServiceAccount`s name can be something like `extension-provider-local-component-foo`, right?

**Comment by rfranzke** [comment]
Right @timuthy

**Comment by rfranzke** [comment]
After the discussions in https://github.com/gardener/gardener/pull/9066#discussion_r1464566008 and https://github.com/gardener/gardener/pull/9066#discussion_r1464598490, we agreed with @timuthy on a slightly changed proposal:

- Instead of putting `authorization.extensions.gardener.cloud/bind-to=<extension-name>` into the annotations of the `ClusterRole` (which filters by name prefixes of `SerivceAccount`s), it should rather be label selector for `ServiceAccount`s, e.g. `authorization.extensions.gardener.cloud/serviceaccount-selector={"foo":"bar"}`.
- This requires to extend the `tokenrequestor` controller to allow providing custom labels for the `ServiceAccount`s it creates.
- `gardenlet` will put a label `controllerregistration-name=<name>` to the `ServiceAccount`s it creates by default for extensions.
- This way, humans can either use `controllerregistration-name=<name>` in the `authorization.extensions.gardener.cloud/serviceaccount-selector` annotation for the `ClusterRole` to extend the permissions of the "default" extension service account, or they choose a different label selector for a custom label they use for a dedicated `ServiceAccount` (to not inherit all "standard" permissions but only apply those of the `ClusterRole`).
