### ISSUE TITLE
Unexpected error during PUT: spec.seedName cannot be changed by patching the shoot

### ISSUE THREAD

**Issue by cbarbian-sap** [gardener/gardener#9186]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
Gardener API server rejects idempotent PUT shoot requests with error
```
Error from server (Forbidden): error when replacing "/tmp/shoot.yaml": shoots.core.gardener.cloud "<redacted>" is forbidden: spec.seedName cannot be changed by patching the shoot, please use the shoots/binding subresource
```

**What you expected to happen**:

This should of course work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot (e.g. `kubectl create`).
2. Do a put (e.g. `kubectl replace`) using the same descriptor used for creation.

**Anything else we need to know?**:

Nothing

**Environment**:

- Gardener version: 1.73.0
- Kubernetes version (use `kubectl version`): irrelevant (1.27.6, 1.28.4 in our case)
- Cloud provider or hardware configuration: AWS
- Others: nothing

**Comment by plkokanov** [comment]
@cbarbian-sap If I understand you correctly here's what happened:
1. You created a shoot from a `*.yaml` file. Usually these files do not specify a `.spec.seedName` as this is left to be assigned by the `gardener-scheduler`
2. After you created the shoot, the `gardener-scheduler` actually assigned your shoot to a seed and thus changed the `spec.seedName` 
3. You then tried to call `kubectl replace` with the original file, which in turn tries to reset the `.spec.seedName` back to nil which is not an allowed operation - changes to `.spec.seedName` are only allowed via the `shoots/binding` subresource. 

If I'm correct in the assumption above, what I see here as a possible improvement is to perhaps slightly enrich the error and display what the "new" and "old" `.spec.seedNames` are so that users do not assume that there are no changes,
