### ISSUE TITLE
Issue with Scaling down the nodes

### ISSUE THREAD

**Issue by ghost** [gardener/gardener#92]
Using Gardener, I have created a cluster on AWS with 5 worker groups with auto scaling limits set minimum as 5 and maximum as 10.
**Observation1:**  I expect gardener to create a 25 Node Cluster but it created 20 node cluster(no errors from my AWS console regarding the quota limits).
**Observation2:** Using kubectl, I have deleted 19 nodes out of 20 and the nodes got deleted successfully. So when I execute kubectl get nodes -- shows only one node.
But surprisingly when I look in to AWS EC2 console I still see that 20 Instances are still running. Shouldn't it delete all the un-needed VM's?
**Observation3:** I need to cut down my AWS costs, so I have deleted all the un-needed 19 VM's from the EC2 console manually. But due to the auto scaling groups AWS again spawned up 20 more VM's. But surprisingly, when I now execute kubectl get nodes-- gives me 20 nodes back again.
Could someone explain this behavior which is pretty odd.

**Comment by rfranzke** [comment]
Hi @K7king,

regarding observ. 1: I have checked that all five auto scaling groups were created successfully on AWS and have been configured with the correct desired/minimum/maximum counts. Therefore, I'm very unsure what we/Gardener can do further about the situation? It has fulfilled the "contract" with AWS by successfully creating the resources there. I suggest to contact AWS and ask what's wrong with the one auto scaling group that does not produce any VMs. 

Regarding observ. 2: You cannot delete VMs by executing `kubectl delete node`, that won't work. The current Gardener is not (at least not gracefully) able to scale down, however, the latest `master` version will support that as well as hibernating clusters completely or even updating them. Once deployed, the proper way to scale down would be to modify the `autoScalerMin`/`autoScalerMax` configuration in the Shoot manifest.

Regarding observ. 3: This behaviour is caused by the AWS auto scaling group - if you only delete the created VMs without changing the desired/minimum/maximum settings in the auto scaling group configuration itself, AWS will always replace terminated VMs with new ones (to have always as many VMs as the `desired` flag tells). To scale down manually, simply change this configuration on the auto scaling group. However, as said above, with the latest Gardener you should only do that by adapting the Shoot resource. You won't be able to manually modify infrastructure resources at it will reconcile its desired state every 10 minutes, discarding your manual changes.

It would be great and very interesting if you could get back to us regarding observ. 1. Let's keep the ticket open therefore.

Best regards, Rafael
