### ISSUE TITLE
Allow `ShootResourceReservation` to be configurable per seed

### ISSUE THREAD

**Issue by adenitiu** [gardener/gardener#9965]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:
Provide an option to allow `ShootResourceReservation` to be configurable per seed and which also allows to change the value of the `useGKEFormula` field from [false to true.](https://github.com/gardener/gardener/blob/master/example/20-admissionconfig.yaml#L26)

**Why is this needed**:
We want to rollout this admissionplugin `ShootResourceReservation` of the `gardener-apiserver` individually, per seed

**Comment by rfranzke** [comment]
cc @MichaelEischer

**Comment by MichaelEischer** [comment]
It's currently already possible to overwrite kubeReserved per shoot. `useGKEFormula` has only an effect only newly created shoots when kubeReserved is not set; existing shoots are not affected by `useGKEFormula`. That is, you can enable `useGKEFormula` and let it inject resource reservations for new shoots that have no `kubeReserved` configuration. To create shoots with the static defaults, just add the following snippet in the shoot configuration:

```
spec:
  kubernetes:
    kubelet:
      kubeReserved:
        cpu: 80m
        memory: 1Gi
        pid: 20k
```

Would that work for you?

**Comment by adenitiu** [comment]
Right... we are already doing this for existing shoots, i.e. setting the static `kubeReserved` values. My understanding was that by enabling `useGKEFormula` on existing shoots a re-calculation of the resource reservations will take place based on the different machines used in the shoot.

**Comment by timuthy** [comment]
@MichaelEischer 

> It's currently already possible to overwrite kubeReserved per shoot. useGKEFormula has only an effect only newly created shoots when kubeReserved is not set; existing shoots are not affected by useGKEFormula. 

That might be true for long lived shoots. However, there are service which create (mid and short-lived) shoots en masse and such a config change can have surprising side effects. @adenitiu will discuss further with the team about potential risks and if a partial roll out would still be required.

**Comment by voelzmo** [comment]
I'm summarizing my current understanding after looking at the implementation to get a better understanding how new/existing Shoots are impacted after setting `useGKEFormula: true`:
* The webhook acts on Shoot `CREATE` and `UPDATE` requests: https://github.com/gardener/gardener/blob/f3c4176d734cf6a9cc2a6acf352ea5a2973c4d59/plugin/pkg/shoot/resourcereservation/admission.go#L65
* When `useGKEFormula: false` is used:
  * If an existing Shoot does not have values set in `.spec.kubernetes.kubelet.kubeReserved`, it will get set by this webhook to the default static configuration (`80m CPU, 1Gi RAM, 20k PID`) on the next `UPDATE` requests to this Shoot. This could e.g. be a different spec update or waking up from hibernation.
  * If an existing Shoot does have values set, they are not touched
  * the webhook doesn't care if the Shoot spec defines `kubeReserved` on individual worker pools – the global values are injected anyways based on the above logic
* When `useGKEFormula: true` is used:
  * the global setting for `.spec.kubernetes.kubelet.kubeReserved` is determined in the same way like above
  * AND `kubeReserved` is set for each worker pool according to the GKE formula, if there is nothing in the Shoot spec for this worker pool yet

Additional notes
* Due to [the defaulting logic existing before the introduction of the webhook](https://github.com/gardener/gardener/pull/9449/files#diff-7a31395cc11cbafe095cb36d5140c6653b82e4e21fbc8becefdd204965976a9c), all existing Shoots do have some value defined in `.spec.kubernetes.kubelet.kubeReserved`: either the global default or a custom value, so nothing happens to existing Shoots when `useGKEFormula: false`
* Once `useGKEFormula: true` is set, all Shoots which don't have `kubeReserved` defined on their worker pools will get this setting on the next `UPDATE` request
* If `kubernetes.kubelet` is defined on a worker pool level, [this object takes precedence](https://github.com/gardener/gardener/blob/f3c4176d734cf6a9cc2a6acf352ea5a2973c4d59/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L692-L697) over the global configuration object at `.spec.kubernetes.kubelet`  – this was already true before the webhook was introduced
  * However, this also means that once we start setting `useGKEFormula: true`, any of the other settings done in https://gardener.cloud/docs/gardener/api-reference/core/#kubeletconfig at the global level _will no longer be applied to the nodes_ – or did I misinterpret the code? This was kind of hard to test with an actual Shoot for me, sorry. 

So I don't agree with the summary, that nothing will happen to existing Shoots and this will only have impact for new Shoots. Did I miss something, @MichaelEischer?

To understand what happens after the worker pool specific `kubeReserved` settings have been updated in the Shoot spec, we need to consider the feature gate `NewWorkerPoolHash`.

* if `NewWorkerPoolHash: false`
  * `kubeReserved` is not part of the worker pool hash calculation, the worker pool name doesn't change, no nodes are rolled, the kubelet configuration is updated in-place and Pods are potentially evicted if they no longer fit on a Node after `kubeReserved` has been changed
* if `NewWorkerPoolHash: true`
  * `kubeReserved` (and all other kubelet configuration) is part of the worker pool hash, therefore the worker pool name changes and nodes are rolled

**Comment by voelzmo** [comment]
Update: created https://github.com/gardener/gardener/issues/10470 to follow up on issues with the global kubelet configuration.
